### ISSUE TITLE
｢custom_phrase.txt｣里加入｢#｣

### ISSUE THREAD

**Issue by nutnutwin** [rime/home#1002]
custom_phrase.txt 里加入

+[Tab] jh [Tab] 100
后, 可以用jh输入｢+｣

#[Tab] jh [Tab] 100
后, 无法用jh输入｢#｣

请问这是什么限制吗? 比如｢#｣表示注解? 

谢谢

**Comment by lotem** [comment]
參考 https://github.com/rime/home/issues/144

**Comment by nutnutwin** [comment]
> 參考 #144

搞定了, 谢谢!
