### ISSUE TITLE
小狼毫能不实现在A（英文模式）英文提示？

### ISSUE THREAD

**Issue by fudilove** [rime/home#1009]
我们一般讲的词库，都是“中”字模式下的，中文提示。
中模式下，也可以提示英文提示，但总感觉有点不爽。

但切换到A状态下后，就只能打单个英文字母了。

我想问切换到A后，能提示单词或常句子就好了。
比如我打en，就出现english……

**Comment by LEOYoon-Tsaw** [comment]
做一个英文方案，切換方案
