### ISSUE TITLE
修改 *.custom.yaml 文件并部署后 *.yaml 文件会自动被修改

### ISSUE THREAD

**Issue by Mayrixon** [rime/home#103]
installation.yaml 文件如下：
distribution_code_name: Squirrel
distribution_name: "鼠鬚管"
distribution_version: 0.9.26.1
install_time: "Sat Aug 13 18:18:47 2016"
installation_id: "79e23ae2-154f-4b41-b188-7e752a11921b"
rime_version: 1.2.9

系统版本为 macOS Sierra version 10.12 PB4 (16A284a)

**Comment by lotem** [comment]
目前是這樣設計的。

**Comment by osfans** [comment]
直接调用select_schema之后，需要自己写user.yaml？
F4好像就没有问题。

**Comment by lotem** [comment]
樓上的回覆串錯門了吧？看不太懂。
---
關於這一行爲的詳細解釋：
https://github.com/rime/home/wiki/CustomizationGuide#%E5%AE%9A%E8%A3%BD%E6%8C%87%E5%8D%97

**Comment by osfans** [comment]
就是順便問一下，通過函數select_schema切換方案時，是否應該在user.yaml中記錄previously_selected_schema和schema_access_time。
通過F4切換方案時會記錄的。

**Comment by lotem** [comment]
喔，想不想影響方案選單的順序呢？

**Comment by osfans** [comment]
要影響吧，就想要跟F4選方案的行爲一樣。有什麼情況不需要影響嗎？

**Comment by osfans** [comment]
`select_schema`時要不要默認調到這一段https://github.com/rime/librime/blob/develop/src/gear/schema_list_translator.cc#L31
```c
user_config->SetString("var/previously_selected_schema", keyword_);
user_config->SetInt("var/schema_access_time/" + keyword_, time(NULL));
```

現在同文、pime-rime、fcitx-rime都有做方案列表菜單，看樣子都需要這一段
