### ISSUE TITLE
Showing candidates inline in preedit

### ISSUE THREAD

**Issue by xsrvmy** [rime/home#1030]
When using rime-fcitx5 on some wayland compositors, the candidate box does not appear, which makes methods such as pinyin unusable. Is it possible to show the candidates as part of the preedit string (the underlined text that appears in the textbox) so that the list of candidates will always be visible even if the system does not support showing the candidate box itself?

**Comment by ChihSee-Hsie** [comment]
Maybe you can alter the key
    "style/preedit_type": composition
to
    "style/preedit_type": preview
which can be patched in the configuration file weasel.custom.yaml.

**Comment by Python-37** [comment]
Nay, `weasel.custom.yaml` cannot take effect on Linux.

**Comment by lotem** [comment]
It's a front end feature. Better consult the developer of fcitx5-rime (not invented here).
