### ISSUE TITLE
table_translator无法按照词频排序所有候选词吗？

### ISSUE THREAD

**Issue by THMonster** [rime/home#1033]
正在做一个音形码的码表，发现无论如何设置`dict.yaml`中的`sort`属性，候选词都只有在完全重码时才会按词频/码表顺序去排序，否则是按字母顺序排列，比如：
当我输入a时，我希望所有以a开头的候选字/词以码表中或词频的顺序去排列，但我现在得到的却是按字母顺序的排列，如：
`a b c ab ac ad aba abc`
我找了几个现成的形码码表，像wubi86，也是如此按照字母顺序排列。但我试了几个拼音的码表，却没有这个问题，能够正常按照词频排序。
请问怎样才能解决这个问题？

**Comment by LEOYoon-Tsaw** [comment]
改程序啦

**Comment by THMonster** [comment]
> 改程序啦

我不太懂，您的意思是指这是有意为之？能请教一下为什么要让除拼音以外的码表只能够按照字母顺序排列候选词吗？

**Comment by Ace-Who** [comment]
只有完全匹配输入码的候选才能按照设定排序。补全候选不是完全匹配输入码。

**Comment by Ace-Who** [comment]
拼音的设计用法包括缩略拼写，音节有限，只有数百，所以 `script_translator` 适应这种设计。而 `table_translator` 适应码表输入方案，编码数以十万计，缩略变化太多，所以不是标配，有需求可以修改码表或配置拼写运算。

**Comment by THMonster** [comment]
> 拼音的设计用法包括缩略拼写，音节有限，只有数百，所以 `script_translator` 适应这种设计。而 `table_translator` 适应码表输入方案，编码数以十万计，缩略变化太多，所以不是标配，有需求可以修改码表或配置拼写运算。

我还是无法理解，既然您说“码表输入方案，编码数以十万计”，那为何还要以字母顺序排列他们呢？如果做一件事情困难，那么就不去做他，这是自然的状态。对应到这件事情上，不应该是编码太多，所以我们不去排序（让他保持码表中的顺序）。

**Comment by LEOYoon-Tsaw** [comment]
你可以改邏輯嘛，可能也就百來行代碼，先試試

**Comment by Ace-Who** [comment]
我的看法不代表开发者：数据结构使然。按字母顺序检索的计算量是很低的，只需要从 a 到 z 依次查询，能够采用懒惰算法，只需生成当前分页所及的几个至十几个候选；按权重排列，则权重数字不可枚举，不能采用懒惰算法，每次增删输入码都要生成成千上万的全部候选，并进行排序计算，最后才能按结果呈现，性能不可接受。

**Comment by tianhe117** [comment]
您好，想问一下，最后怎么解决这个问题的呢，也想实现按照字频排序的功能

**Comment by THMonster** [comment]
> 您好，想问一下，最后怎么解决这个问题的呢，也想实现按照字频排序的功能

我的解决方法是：能用fcitx就用fcitx，没得用就忍。

**Comment by lotem** [comment]
是的。`dict.yaml`中的`sort`選項控制 **重碼字** 的排序。

而編碼前綴匹配的候選字，嚴格地說並不是當前輸入碼的候選，這裏就沒有做特定的排序。
可觀察到的順序是由詞典的數據結構決定的。詞典按照類似編碼的字母順序做索引是爲了快速根據輸入碼定位相關的候選數據。如果要對所有前綴相同的候選字按照權重排列，輸入一個碼元時，相當於要檢索整個詞典1/N的內容並做排序，這要花費大量時間或者以空間換時間，預先對所有可能的輸入碼做索引。

**Comment by lotem** [comment]
> 对应到这件事情上，不应该是编码太多，所以我们不去排序（让他保持码表中的顺序）吗？

不對詞典做任何索引的結果是每次輸入都要遍歷整個詞典的數據才能找到編碼匹配項。

**Comment by tianhe117** [comment]
> 

那是否会考虑增加一个控制开关，部署方案的时候可以预先索引候选词的权重排序呢

**Comment by tianhe117** [comment]
> 是的。`dict.yaml`中的`sort`選項控制 **重碼字** 的排序。
> 
> 而編碼前綴匹配的候選字，嚴格地說並不是當前輸入碼的候選，這裏就沒有做特定的排序。 可觀察到的順序是由詞典的數據結構決定的。詞典按照類似編碼的字母順序做索引是爲了快速根據輸入碼定位相關的候選數據。如果要對所有前綴相同的候選字按照權重排列，輸入一個碼元時，相當於要檢索整個詞典1/N的內容並做排序，這要花費大量時間或者以空間換時間，預先對所有可能的輸入碼做索引。

那是否会考虑增加一个控制开关，部署方案的时候可以预先索引候选词的权重排序呢

**Comment by lotem** [comment]
> 部署方案的时候可以预先索引候选词的权重排序呢

那用家會輸入權重查詞嗎？

**Comment by MagePine** [comment]
> > 部署方案的时候可以预先索引候选词的权重排序呢
> 
> 那用家會輸入權重查詞嗎？
我折腾过的Rime形码词库大多带有合理的权重，但带来输入体验的提升不大。再常用的词，也需要4码，所以大多数时候候选栏前几页是生僻字。这种现象出现在绝大多数形码输入法里：百度搜狗触宝等等。目前只有多多输入法能在输入一码的时候就在候选中列出常用词。作者应该是用到权重排序而非为常用词设置二简或三简，具体实现方法不得而知。
