### ISSUE TITLE
求助如何配置地球拼音作反查码表？

### ISSUE THREAD

**Issue by ziloeng** [rime/home#104]
现在问题是在于反查不能识别声调符号，应该跟“recognizer/patterns/reverse_lookup"到配置有关。

`
reverse_lookup: "`[a-z/<>]*;?$" # 这样是正常可以反查并识别/<>三个声调。

reverse_lookup: "`[a-z/<>-\\]*;?$" # 加上-和\就会卡死。
`

卡死就是无响应，提示关闭程序。
要手动删除用户文件夹下的xxx.prism.bin，xxx.schema.yaml，更改user.yaml的previously_selected_schema到另一输入方案，再切换输入法重新部署才可正常使用。

试过这几种也不行  `-  \-  \x2D  \\  \x5C`
求解决方法

我的schema.yaml文件中反查相关配置：
schema:
  dependencies:
    - terra_pinyin

reverse_lookup:
  dictionary: terra_pinyin
  prism: terra_pinyin
  prefix: "`"
  suffix: "'"
  tips: 〔拼音〕
  preedit_format:
    - xform/([nl])v/$1ü/
    - xform/([nl])ue/$1üe/
    - xform/([jqxy])v/$1u/

recognizer:
  import_preset: default
  patterns:
    punct: "^/([0-9]0?|[a-z]+)$"
    reverse_lookup: "`[a-z]*;?$"

**Comment by lotem** [comment]
有兩處錯誤：

`"[a-z/<>-\\]*;?$"` 這個 YAML 字符串的內容爲 `[a-z/<>-\]*;?$` ；
正則表達式 `[\]]` 可匹配字符 `]`，方括號裏的 `]` 需要轉義；方括號裏的 `\` 也需要轉義。

正則表達式 `[x-y]` 表示匹配內碼範圍在 x 和 y 之間的任一個字符，其中的 `-` 表示這是一個範圍。如果要匹配的字符包括 `-`，則應緊接着開始的 `[` 。 

你想寫的可能是 `'[-a-z/<>\\]*;?$'`

**Comment by ziloeng** [comment]
谢谢，发现 `\\` 放后面接着`]` 编译没错误但不能运行，``[-\\a-z/<>]*;?$`这样才行
