### ISSUE TITLE
mac下詞庫部署失敗！求教，有償也沒問題！

### ISSUE THREAD

**Issue by xk05** [rime/home#1048]
m1 mac部署失敗，已經難受死了，搞了一晚上沒搞好。按照教程安裝的詞庫部署還是輸入不出來。
rt看看
<img width="1305" alt="截圖 2022-04-16 21 13 27" src="https://user-images.githubusercontent.com/100983005/163676435-bb3a6f3f-2d65-43e3-9b82-f243060d34d7.png">
！

**Comment by lotem** [comment]
你需要把问题说清楚。失败的具体表现，错误信息等。按照什么教程，对配置做了哪些修改。修改的目的是什么。

从图上看，问题不大，输入法应该能工作。
如果搞不好，把用户文件夹清空在重新部署，就能恢复出厂设置。

**Comment by lotem** [comment]
如果不清楚怎么自定义，建议先用默认配置或者高手做好的全套配置。

**Comment by xk05** [comment]
> 你需要把问题说清楚。失败的具体表现，错误信息等。按照什么教程，对配置做了哪些修改。修改的目的是什么。
> 
> 从图上看，问题不大，输入法应该能工作。 如果搞不好，把用户文件夹清空在重新部署，就能恢复出厂设置。

你好，感谢回复，我主要想部署【明月拼音】方案的词库，创建了luna_pinyin.extended.dict.yaml和luna_pinyin.sougou.dict.yaml（词库文件），并在extended.dict.yaml文件下import输入了sougou（如图），单是部署后词库依旧不生效，请教原因。

**Comment by lotem** [comment]
明月拼音用的詞庫是 `luna_pinyin.dict.yaml`，配置爲 `translator: { dictionary: luna_pinyin }`
你創建的 `luna_pinyin.extended.dict.yaml` 又在哪裏用到了呢？

**Comment by lotem** [comment]
信息不足。不再跟進了。
