### ISSUE TITLE
rime 无法在另一个账户上工作

### ISSUE THREAD

**Issue by Acfboy** [rime/home#1049]
### 现在表现
在我现在使用的管理员账户里，rime 可以正常工作，但当我切换到另一个普通账户里的时候，虽然输入法列表中会显示中州韻，但却没有办法输入。

### 预期表现
在所有账户下都可以正常输入汉字。

### 重现步骤
新建一个普通账户。

### 系统环境
Manjaro Linux, KDE  Plasma 5.24.4, Fcitx 5

**Comment by lotem** [comment]
怎麼安裝的，輸入方案安裝到哪裏？
輸入方案做全局安裝，一般是在 `/usr/share/rime-data/`，就可以多用戶共用。
另外 fcitx5-rime 是fcitx5團隊開發的，你可以去諮詢他們。

**Comment by Acfboy** [comment]
> 怎麼安裝的，輸入方案安裝到哪裏？ 輸入方案做全局安裝，一般是在 `/usr/share/rime-data/`，就可以多用戶共用。 另外 fcitx5-rime 是fcitx5團隊開發的，你可以去諮詢他們。

rime 是系统自带的。
我看了 `/usr/share/rime-data/` 目录，几个 `luna_pinyin` 开头的 yaml 文件确实在下面。

看上去似乎确实是输入方案的问题，谢谢您的回复，我会尝试在另一个账户下检查输入方案。

**Comment by lotem** [comment]
如果共享數據目錄只有YAML而沒有.bin文件，新帳號第一次用可能要等一小會兒。
