### ISSUE TITLE
鼠须管会自动切换到繁体

### ISSUE THREAD

**Issue by BiosSun** [rime/home#105]
使用鼠须管时，会自动切换为繁体；即便设置回简体，切换几次窗口后，依然还会自动变回繁体，请问这是什么原因导致的？

之前没有这个情况，是在今天突然出现的。

鼠须管版本：0.9.26.2
系统版本：Mac OS X 10.11.6

**Comment by lotem** [comment]
我並未觀察到。請排除以下情況：

1. 輸入法在每個應用（窗口）中保持一份狀態，在一個打開的應用中通過方案選單切換簡繁體，不改變已打開的其他應用中的輸入法狀態；只會影響後續打開的應用（窗口）。
1. 用快捷鍵 `Control+Shift+4` 切換，只作用於當前輸入法會話期間，不會保存狀態。

**Comment by mhohai** [comment]
Ubuntu 用户来电，表示rime没有问题。。。

**Comment by BiosSun** [comment]
我在 luna_pinyin.schema.yaml 文件中的 Switches[name:simplification] 下添加了一个 reset: 1 就好了。

![image](https://cloud.githubusercontent.com/assets/2755933/17802646/12c906c4-6624-11e6-9ddb-b679ee48072f.png)

**Comment by msongz** [comment]
我也是这个情况，谢谢你的方法 @BiosSun 
但是状态无法保留，例如我从简体切换到繁体
用了reset 1，那么切换输入法就会回到简体
并不能回到我最后使用的简or繁的状态

**Comment by jettdavid23** [comment]
@msongz 可以試試把簡繁體的轉換單獨做成一份`schema`方案配置，這樣切換後就不會變了，但我現在的問題是怎麼設置快捷鍵來快速切換方案。 🤔

**Comment by StellaMeow** [comment]
我也遇到了同样的情况，之前用的好好的突然有天开始经常自动切换到繁体
