### ISSUE TITLE
鼠须管所在层级

### ISSUE THREAD

**Issue by zhu123759** [rime/home#1050]
MacOS系统
在使用某些截图软件时（如iShot），无法显示中文内容的候选项，向截图软件方反馈了一下，说可能的原因是鼠须管所在图层不是最顶层，是否可以通过配置的方式修改输入法所在层级，谢谢。

ps:在某些截图软件中工作正常

**Comment by LEOYoon-Tsaw** [comment]
是頂層了，技術上是屏保層。什麼垃圾軟件，肯定不是鼠鬚管層級的問題

**Comment by zhu123759** [comment]
是在截图过程中想要在图片上添加中文标注，效果是输入拼音有下划线效果，但是无法出现候选项，只能默认选择未知的第一项（因为没有显示），先和截图软件那边反馈了一下说有可能是层级的问题，具体原因我也不清楚

**Comment by lotem** [comment]
這麼說是被截圖軟件蓋住了。

**Comment by zhu123759** [comment]
那还是层级问题吗？是应该截图软件那边给解决吗？还是说输入法里面有参数可以自己调整调整

**Comment by lotem** [comment]
沒有辦法調整。

截圖軟件的編輯界面不需要很高層級吧。既然要在上面輸入文字，那就得低於輸入法的界面。

**Comment by zhu123759** [comment]
那就是说截图软件把自身的层级设置的太高了是吗？

**Comment by LEOYoon-Tsaw** [comment]
用command+control+shift+3/4

**Comment by zhu123759** [comment]
好的，谢谢，我试试

**Comment by lotem** [comment]
> 那就是说截图软件把自身的层级设置的太高了是吗？

沒用過。不瞭解。
