### ISSUE TITLE
Ubuntu + Pycharm双屏状态下, 若编辑器在右侧屏, 打字提示框会显示在左屏

### ISSUE THREAD

**Issue by yulinxx** [rime/home#1053]
双屏状态下, 若编辑器在右侧屏, 打字的时候会显示在左屏

未做双屏适配?

**Comment by LEOYoon-Tsaw** [comment]
Linux下的前端應該不在本項目裡

**Comment by yulinxx** [comment]
不好意思 这是Pycharm的问题, 因为Pycharm是Java写的, 只要是Java写的输入控件,均存在此问题
