### ISSUE TITLE
没有注音的多音字，表现不一致

### ISSUE THREAD

**Issue by iDvel** [rime/home#1060]
比如在 `xxx.dict.yaml` 中写了没有注音的词句：
```
漫漫长夜
罪恶都市
孟山都
```
用 `man man chang|zhang ye` 都可以打出「漫漫长夜」；
用 `zui e du|dou shi` 都可以打出「罪恶都市」。

但是用 `meng shan du` 就打不出「孟山都」，只能用 `dou` 才行。

**Comment by LEOYoon-Tsaw** [comment]
q肯定是在某個地方注了音唄，仔細找找

**Comment by iDvel** [comment]
@LEOYoon-Tsaw 
没有在别的地方注音，删除个人词库再重新部署也这样。你那里可以打出来吗？
<img width="606" alt="image" src="https://user-images.githubusercontent.com/14658234/166973934-345c385d-ef11-4710-8458-2d35b56e4a2e.png">

**Comment by LEOYoon-Tsaw** [comment]
也有可能是都 dou的詞頻是0%，即不參與自動組詞

**Comment by iDvel** [comment]
@LEOYoon-Tsaw 
谢谢大佬，好像真是这个问题。
我用的词频是：
```yaml
都	dou	48783880
都	du	332701
```
把 dou 的词频改成 10 后，就可以用 du 打出来了。

我又试了调整「长」的词频分别为：
```
长	zhang	99999999
长	chang	1
```
很多无注音的，原来都能打出来的词汇，现在用 chang 就打不出来了。

请问这个词频的设定，最高为多少比较合适呢？或是有多大比例的差距会导致这样的问题呢？

**Comment by iDvel** [comment]
知道怎么回事了。
[當含有多音字的詞組缺少編碼字段時，自動註音程序會利用權重百分比高於 5% 的讀音進行組合、生成全部可能的註音](https://github.com/rime/home/wiki/RimeWithSchemata#%E7%A2%BC%E8%A1%A8%E8%88%87%E8%A9%9E%E5%85%B8)  
  

```
# 打不出来：
长	zhang	100
长	chang	5

# 这样就可以了：
长	zhang	100
长	chang	6
```
需要自动注音的多音字，百分比高于 5% 就可以了。
