### ISSUE TITLE
有繁體的筆劃輸入法嗎？

### ISSUE THREAD

**Issue by c933103** [rime/home#1064]
現在 https://github.com/rime/rime-stroke 雖然碼表有繁體字，但那碼表對於繁簡統合了的Unicode字元，例如所有含有草花頭部件的漢字，依然是採用簡體中文的筆順，對於繁體中文使用者構成困惑。
另一方面，預設的筆劃輸人按鍵，用h,s,p,n,z來代表橫、豎、撇、捺、折，分散到鍵盤各處，不利連續輸入，而且所選的字母為相關漢字名稱的普通話漢語拼音首字母，對於不熟悉普通話，或者不熟悉漢語拼音方案的中文使用者而言，相關碼位難以記憶，因此希望能夠改善。

**Comment by LEOYoon-Tsaw** [comment]
第二個問題簡單，在speller/algebra下做個mapping即可

**Comment by lotem** [comment]
笔顺没有简繁体之分，统一的规则可以应对所有简繁汉字。

**Comment by c933103** [comment]
> 笔顺没有简繁体之分，统一的规则可以应对所有简繁汉字。

由於Unicode把繁簡體不同寫法的字形合成同一個碼位，同一個字在繁體系統和簡體系統顯示的寫法可以不同，因此筆順也有差別。

**Comment by lotem** [comment]
樓主所述的可能不是簡繁之分，而是不同地區的筆順規範。
例如草頭三筆還是四筆，書法上兩種寫法都有的，不同的標準制定者會選取一種書寫方式定爲規範。例如中國大陸中文專業繁體字草頭也一律是以三筆爲準；日文中的漢字包含很大一部分傳承字，然而無論是否日文簡化字，草字頭都是三筆。

不能因爲系統字體不同，就當作不同的字看待。書法中的變體更多，舉個不恰當的例子，走之底點幾點、折幾折、甚至筆畫之間連不連，是不是都要用不同內碼區分、當作不同的漢字呢？如果正楷的些許不同寫法都要分，那麼更要爲隸書要造一大批「⾋」形的字了。而圍繞同屬一字的界定原則，Unicode已經給出了解答。

rime-stroke 的數據源顯然是按照「新字形」編碼。決不能在同一碼表中混合「新字形」和「舊字形」的筆畫編碼。少量兼收多種筆順的字，限於同一字形有多種通行的書寫習慣。

**Comment by c933103** [comment]
> 樓主所述的可能不是簡繁之分，而是不同地區的筆順規範。
> 例如草頭三筆還是四筆，書法上兩種寫法都有的，不同的標準制定者會選取一種書寫方式定爲規範。例如中國大陸中文專業繁體字草頭也一律是以三筆爲準；日文中的漢字包含很大一部分傳承字，然而無論是否日文簡化字，草字頭都是三筆。
> 
> 不能因爲系統字體不同，就當作不同的字看待。書法中的變體更多，舉個不恰當的例子，走之底點幾點、折幾折、甚至筆畫之間連不連，是不是都要用不同內碼區分、當作不同的漢字呢？如果正楷的些許不同寫法都要分，那麼更要爲篆書、隸書要造一大批「⾋」形的字了。而圍繞同屬一字的界定原則，Unicode已經給出了解答。
> 
> rime-stroke 的數據源顯然是按照「新字形」編碼。決不能在同一碼表中混合「新字形」和「舊字形」的筆畫編碼，會使出字混亂、使用不便。少量兼收多種筆順的字，限於同一字形有多種通行的書寫習慣。

我不是說想要把不同的字形的編碼全部合併到同一碼表內，但輸入法內應該要有能讓使用者按照個人慣用習慣來進行選擇的餘地。
至於說Unicode決定合併什麼字而不合併什麼字，很明顯那些決定之中有許多因歷史原因殘留的妥協和不完善且不一致的地方，很難說是如何區分的最終解答。

**Comment by lotem** [comment]
有的。
Rime作爲輸入法軟件的主要特色之一是通過「[Rime輸入方案](https://github.com/rime/home/wiki/RimeWithSchemata)」實現高度的自定義。
如果有合適的碼表資源，使用者可以快速創作出符合輸入習慣的輸入方案，比方說起名叫 `good_stroke`。
rime-stroke 就是如上所述的一個輸入方案。顯然他收錄的字採用所見的筆順，只是因爲其[數據源](https://github.com/rime/rime-stroke/blob/master/AUTHORS)提供的原始數據如此。雖然不一定適用，但是您可以把它當作一份理想筆畫輸入法的參考實現。
事實上Rime不針對任何特定的編碼方式，而是根據各種輸入法的特點提供音碼、形碼兩套通用邏輯，搭配用家的碼表即可定製出個性化的輸入法。
