### ISSUE TITLE
输入法没有主动学习用户输入习惯的功能吗

### ISSUE THREAD

**Issue by kwbrb** [rime/home#1072]
没有这个功能再多的词库也是废物输入法吧

**Comment by LEOYoon-Tsaw** [comment]
有啊

**Comment by Ace-Who** [comment]
快卸载吧。

**Comment by kwbrb** [comment]
早就卸载了



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2022年5月27日(周五) 凌晨2:11
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [rime/home] 输入法没有主动学习用户输入习惯的功能吗 (Issue #1072)




 
快卸载吧。
