### ISSUE TITLE
请问我可以在切换到英文输入法的时候出现智能补充么？

### ISSUE THREAD

**Issue by PencilMing** [rime/home#1073]
![telegram-cloud-photo-size-5-6086733257556209819-y](https://user-images.githubusercontent.com/82462283/170418058-e4dcf906-73bd-48d4-80e5-e830c96d7aef.jpg)
我现在这个模式是把这个手动改为true的，才会有在中文模式的英文补全。但是我希望这个模式出现在朙月拼音输入法切换成英文输入的时候自动补充，这可以实现么。我现在切换英文就是完全没有像中文这样的菜单。。。就和系统美国输入法一样完全没有提示。

**Comment by PencilMing** [comment]
![telegram-cloud-photo-size-5-6086733257556209817-y](https://user-images.githubusercontent.com/82462283/170418127-28134750-6fe9-4f91-a4ec-576e555f5d72.jpg)
这种情况下可以混合输入英文和中文

**Comment by lotem** [comment]
那你得在中文、英文两个输入方案之间切换。
`ascii_mode` 顾名思义是输入ASCII字符的模式。不是「英文模式」。

**Comment by PencilMing** [comment]
> 那你得在中文、英文两个输入方案之间切换。 `ascii_mode` 顾名思义是输入ASCII字符的模式。不是「英文模式」。

那我可以通过快捷键切换么。我在设置里好像没有看到相关的设置。

**Comment by PencilMing** [comment]
那我怎么才能在英文输入法里享受这个自动补充呢🤔。。。

**Comment by lotem** [comment]
> > 那你得在中文、英文两个输入方案之间切换。 `ascii_mode` 顾名思义是输入ASCII字符的模式。不是「英文模式」。
> 
> 那我可以通过快捷键切换么。我在设置里好像没有看到相关的设置。

默认设有 `Control+Shift+1` 在最近使用的两个输入方案之间切换。

**Comment by lotem** [comment]
> 那我怎么才能在英文输入法里享受这个自动补充呢🤔。。。

如题主贴图演示的，使用 `table_translator` 输入前缀时匹配单词。
