### ISSUE TITLE
“湧”这个字无法打出来，为什么呢如何才能打出来，谢谢

### ISSUE THREAD

**Issue by longester** [rime/home#1076]
“湧”这个字无法打出来，为什么呢如何才能打出来，谢谢

**Comment by LEOYoon-Tsaw** [comment]
<img width="143" alt="Screen Shot 2022-05-30 at 22 59 44" src="https://user-images.githubusercontent.com/4469383/171084182-d9f70472-e711-4601-adeb-af2a1d05fd36.png">
就用明月拼音啊

**Comment by shinzoqchiuq** [comment]
「湧」是「涌」的繁体，你关掉繁转简应该就能打出来了。

**Comment by longester** [comment]
请问如何关闭简繁转换啊

**Comment by shinzoqchiuq** [comment]
明月拼音的话，按 `F4` 或者 `Ctrl` + `` ` `` 选择繁体。

**Comment by longester** [comment]
果然可以打出來了謝謝，如何讓在簡體下也能夠輸出呢，謝謝

**Comment by Mjzsl123-github** [comment]
解决了关闭issue啊
