### ISSUE TITLE
倡議 繁, 簡 外的第三種選擇

### ISSUE THREAD

**Issue by kentsin** [rime/home#1084]
這位許諾先生已做了部份工作

https://zhuanlan.zhihu.com/p/141486006

現在港澳地區常常遇到 "幹炒" 之類的困擾, 原因是委托內地印刷廠印刷品因簡化字轉換成繁體而出現

除了 opencc 改進外, 我倡議在打字時就在輸入法做一個預備轉換成繁體(簡體) 的目標 : 除了繁, 簡外, 增加這樣以簡字為主, 避開一些字, 以便轉換後至少不會出一些极端的狀況

這樣的工作當然不易, 要借助网絡上眾人一起來做

**Comment by LEOYoon-Tsaw** [comment]
OpenCC支持多地的用字標準

**Comment by lotem** [comment]
從軟件的角度沒什麼障礙。
無論定製輸入法詞典中的用字，還是定製OpenCC轉換詞典實現一套新的用字標準，抑或將二者結合，都已有現成的解決方案。
OpenCC已經內置多種漢字轉換標準：
https://github.com/BYVoid/OpenCC#%E9%A0%90%E8%A8%AD%E9%85%8D%E7%BD%AE%E6%96%87%E4%BB%B6

用家根據對文字的需要和理解，收集整理數據即可。依我的理解，這些工作不需要輸入法軟件開發者的配合與協助。

**Comment by kentsin** [comment]
推廣和集合力量
    On Thursday, June 16, 2022, 10:48:23 PM GMT+8, 居戎氏 ***@***.***> wrote:  
 
 


從軟件的角度沒什麼障礙。
無論定製輸入法詞典中的用字，還是定製OpenCC轉換詞典實現一套新的用字標準，抑或將二者結合，都已有現成的解決方案。
OpenCC已經內置多種漢字轉換標準：
https://github.com/BYVoid/OpenCC#%E9%A0%90%E8%A8%AD%E9%85%8D%E7%BD%AE%E6%96%87%E4%BB%B6

用家根據對文字的需要和理解，收集整理數據即可。依我的理解，這些工作不需要輸入法軟件開發者的配合與協助。
