### ISSUE TITLE
使用倉頡五代如何避免打出速成詞組

### ISSUE THREAD

**Issue by hongfanmeng** [rime/home#1086]
在我使用倉頡五代輸入 "人戈日口金" 時候選字中會出現 "什麼問題" ，如何避免這種詞組出現

**Comment by lotem** [comment]
原裝的詞典(cangjie5.dict.yaml)配置爲使用詞組。
詞組不是速成碼，是根據快趣規則編碼的。詳見另一則[討論](https://github.com/rime/home/discussions/1082#discussioncomment-2926795)。

要只打單字，需要修改輸入方案和詞典。

在詞典(cangjie5.dict.yaml)中設置不導入預設詞組
```yaml
use_preset_vocabulary: false
```

在輸入方案(cangjie5.schema.yaml)中設置不啓用自動組詞
```yaml
translator:
  enable_encoder: false
```

**Comment by hongfanmeng** [comment]
好的，成功了，謝謝
我原本只把 enable_encoder 改成了 false 沒想到要把 use_preset_vocabulary 這項也改掉
