### ISSUE TITLE
字典、方案的名稱前綴不限制字符

### ISSUE THREAD

**Issue by DaengGWokFook** [rime/home#109]
目前只能用西文、符號等基本字符命名。製作方言方案的地名用西文表達很模糊，希望能支持漢字。

**Comment by ipcjs** [comment]
编码问题很麻烦的吧，这样的需求优先级太低

**Comment by osfans** [comment]
文件名还是schema_id？

**Comment by ipcjs** [comment]
文件名和schema_id不是要相同吗？

**Comment by DaengGWokFook** [comment]
舉例：
jyutping.dict.yaml
jyutping,schema.yaml
前綴改爲
粵拼.dict.yaml
粵拼.schema.yaml

**Comment by lotem** [comment]
我建議只在方案裏的 `name:` 字段用漢字。這個才是用戶可見的名字。

方案標識屬於代碼範疇，用拉丁字母、數字、下劃線命名（而且最好以字母開頭、只使用小寫字母），是一種約定。這樣命名可以方便在各種平臺打包發佈、保證相關的腳本和工具對文件名做正確處理。

即使改名能調試通過，也請不要這樣做。因爲無法保證跨平臺兼容性。
