### ISSUE TITLE
使用双拼输入法，只输入声母的时候侯选框有时候会消失

### ISSUE THREAD

**Issue by dingangui** [rime/home#1094]
当输入的字母组合不能构成一个拼音组合时，侯选框就会消失，当我输入“比如输入这段话的时候”，当我依次按下”biruuuru“，输入到”b“和”bir“时，侯选框都消失不见，补充后续单词构成正常的拼音组合又会重新出现，这个还挺影响使用的，请问该如何解决呢？

https://user-images.githubusercontent.com/30258241/178259873-626b7ae2-f417-4711-ad3a-bf75706a3dc8.mov

**Comment by DreamAfar** [comment]
你的方案,估计有问题,小鹤双拼是可以输入一个以上编码时,出候选的

检查你的方案是不是用了中英文混合编码的词典？,还有拼运规则. 我知道的这个会造成类似你这样的问题

![image](https://user-images.githubusercontent.com/69999980/179341060-d7a374e2-d89e-453d-8036-64a2ef7f2f97.png) ![image](https://user-images.githubusercontent.com/69999980/179341073-f8c6c513-3697-46d9-bb56-e9c3bc619403.png)

**Comment by lotem** [comment]
不用原裝的方案就不要報錯了。
