### ISSUE TITLE
cangjie5關閉碼表輸入法連打設定無效

### ISSUE THREAD

**Issue by lkamhk** [rime/home#1096]
在用戶文件資料夾下自建的 cangjie5.custom.yaml 文件中根據教學:

patch:
  translator/enable_sentence: false

設定無效,但其它設定有效, 例如 "menu/page_size": 9
但在程序文件夾中的 cangjie5.schema.yaml 中設定有效

本人win10 小狼亳版本:
![image](https://user-images.githubusercontent.com/20964665/178520730-5d410ea1-14c6-46ad-ba69-42311b519f2c.png)

**Comment by lkamhk** [comment]
@lotem 是bug阿 我重複試了很多次 都是同樣情況

**Comment by lotem** [comment]
該补丁文件有其他错误。你可以把文件内容精简为原题描述中的相关代码验证其是否有效。

**Comment by lkamhk** [comment]
> 該补丁文件有其他错误。你可以把文件内容精简为原题描述中的相关代码验证其是否有效。



> 該补丁文件有其他错误。你可以把文件内容精简为原题描述中的相关代码验证其是否有效。

謝回答,已測試的確是其他問題
