### ISSUE TITLE
单个编码在按下 Enter 键后有些情况下无法上屏，反而直接执行回车键命令，Ibus rime 中文输入

### ISSUE THREAD

**Issue by smokesuen** [rime/home#1098]
版本是 Ibus-rime。

举例：在 Chrome 地址栏中键入单个编码，随后按下 Enter 键，结果非但不上屏，还对文本框执行了回车命令。如下图：
![Peek 2022-07-18 17-35](https://user-images.githubusercontent.com/56160731/179485178-c04a90f0-35c3-4bd7-9eab-496a1250afde.gif)

但在另一些情况下，又可以上屏单个编码，如下图（Google 网页搜索控件中）：
![Peek 2022-07-18 17-36](https://user-images.githubusercontent.com/56160731/179485356-7e6aeda3-9c01-42d8-9120-24d17d695f07.gif)

两个及以上编码都还是可以直接上屏的。

我尝试换回到安装默认方案，这个情况也是一样出现的，不明白是哪里出现了问题，恳请大家帮助。

**Comment by lotem** [comment]
Chrome有這個毛病。鼠鬚管的做法是在Chrome裏強制使用inline風格。

**Comment by smokesuen** [comment]
### 解决

换用 fcitx5-rime。
