### ISSUE TITLE
一鍵切換指定方案

### ISSUE THREAD

**Issue by DaengGWokFook** [rime/home#110]
目前安卓同文輸入法辦到了，不知小狼毫會不會增加此功能？

**Comment by osfans** [comment]
這個接口是有的，select_schema，但是不知能不能通用。通用的話，同文也改成這種做法。

**Comment by osfans** [comment]
好像可以，你試試。

https://github.com/rime/brise/blob/master/default.yaml#L127
https://github.com/rime/brise/blob/master/default.yaml#L132

**Comment by lotem** [comment]
正解。在 `select:` 代碼中引用方案標識（schema_id）。
