### ISSUE TITLE
鼠须管，在mac os下， qt creator IDE中输入不了

### ISSUE THREAD

**Issue by nocanstillbb** [rime/home#1108]
应该说只能输入a，  也删除不了字符，  除非option+delete才能删除。
试了百度输入法是正常的，  
windows下的小狼毫  在 qt creator里也能正常输入。

录了个像太大了，传不上来

**Comment by LEOYoon-Tsaw** [comment]
#911

**Comment by nocanstillbb** [comment]
已确认， 在qt creator低版本 （使用qt 5构建），可以用鼠须管正常工作，可以卸载百度输入法了。
