### ISSUE TITLE
退出rime后，字符上屏问题

### ISSUE THREAD

**Issue by chqy24** [rime/home#111]
现在的情况是，有时候打了很长的字符，然后发现输入状态不对，退出rime时，会自动上屏对应的汉字。请问如何配置可以在退出rime的时候，自动上屏英文字符？

**Comment by ipcjs** [comment]
我一般按ESC取消输入，不会有字符上屏，你是按什么键？

**Comment by chqy24** [comment]
我是用Caps Lock切换到系统输入法，然后就上屏了中文字符，不知道有没有配置项可以在切换出去的时候上屏英文字符。

**Comment by ipcjs** [comment]
试了下打字的过程中切换输入法确实会这样。。
不知道能不能改这个行为。
不过，打字的过程中按shift切换到rime的英文输入模式，这时的上屏行为是可以改的。

**Comment by osfans** [comment]
試試這裏：
https://github.com/rime/brise/blob/master/default.yaml#L153

**Comment by chqy24** [comment]
osfans
我把Caps Lock键映射为别的键值了，只用来切换输入法，所以这个配置是不行的。
不知道切换输入法时上屏的行为是由rime还是系统控制的。

**Comment by osfans** [comment]
各前臺應該可以控制：離開輸入法時，要清空還是上屏。

**Comment by chqy24** [comment]
osfans
不好意思，没有理解到“前台”的意思，是指系统配置吗？

**Comment by osfans** [comment]
是指小狼毫、ibus、pime、同文這些前端輸入法，行爲並不完全相同。rime是內核，是共用的。

**Comment by chqy24** [comment]
这样子，那我用的是鼠须管，请问下哪里有文档可以查看吗？

**Comment by ipcjs** [comment]
怎么关闭了。。。。
问题解决了吗？怎么解决的？

**Comment by xdidi3r** [comment]
我倒想知道怎么解决这个问题呀！

**Comment by chqy24** [comment]
哦，我改了一点源码，有兴趣的可以查看我fork的repo，只适用mac os。
[https://github.com/chqy24/squirrel](https://github.com/chqy24/squirrel)

**Comment by lotem** [comment]
同 https://github.com/rime/squirrel/issues/146

**Comment by mhohai** [comment]
我总结下，如果输入的不要了`ESC`，如果需要对应的字母，直接`Enter`。
补充，我的Ubuntu系统，没有这个问题。

**Comment by xdidi3r** [comment]
@mhohai 你这个是没有退出rime的前提，现在讨论的问题是在切换了输入法的情况下，而不是输入法内切换。

**Comment by mhohai** [comment]
@xdidi3r 我切换输入法没有这个问题。

**Comment by WesleyBlancoYuan** [comment]
https://github.com/rime/home/issues/133

这个issue已经给出了解决方案：

> 我用shift切换中英文，设置成commit_code就行了。
> ```
> ascii_composer/switch_key:
>      Shift_L: commit_code
>      Shift_R: commit_code
> ```
```

**Comment by alswl** [comment]
@WesleyBlancoYuan 不是 shift 切换上屏，而是切换输入法上屏。

**Comment by hailite** [comment]
Same concern +1

**Comment by Hustoking** [comment]
> 
不是在 rime 内切换中英文，而是从 rime 切换到系统输入法时会上屏首选项而不是字符，因为我只用 rime 输入中文，在输入英文的时候用的时系统自带的默认输入法。

**Comment by fifv** [comment]
我遇到了同樣的問題，切換成其他輸入法時想要上屏英文
使用的是`fcitx5-rime`，系統爲Arch/Hyprland

找到的解決辦法：
1. 打開配置工具 `fcitx5-configtool`
2. 選擇 `Addons`
3. 找到 `Input Method` 下的 `Rime`，點擊齒輪
4. 把`Action when switching input method` 改爲`Commit raw input`
