### ISSUE TITLE
字体fallback问题

### ISSUE THREAD

**Issue by Mjzsl123-github** [rime/home#1112]
如图，扩展G汉字显示成方框
![image](https://user-images.githubusercontent.com/110514823/184057486-c522dde0-ae30-4e5a-8854-66e3306b4797.png)
据说Squirrel可以设置fallback顺序，然而我用Weasel
这样打生僻字很不方便诶
![image](https://user-images.githubusercontent.com/110514823/184057843-6a89ca04-c9ae-4f15-b97d-f334fc716ed4.png)  
![image](https://user-images.githubusercontent.com/110514823/184057859-1e15802f-c803-4a68-9ef4-1c99e59ceac9.png)

**Comment by LEOYoon-Tsaw** [comment]
某非官方版小狼毫可以指定字體fallback

**Comment by Mjzsl123-github** [comment]
有““某非官方版小狼毫可以指定字體fallback”说明能实现
话说，rime几年没更新了
