### ISSUE TITLE
【文档】wiki文档格式错误

### ISSUE THREAD

**Issue by LawssssCat** [rime/home#1125]
wiki文档格式错误：
markdown代码块末尾缺少结束符 `` ``` ``，导致后面格式混乱

文档url：<https://github.com/rime/home/wiki/RimeWithSchemata#%E4%B8%80%E7%A0%B4%E7%A9%BA%E4%B8%AD%E5%87%BA%E9%9E%98>

**Comment by lotem** [comment]
已修正。谢谢。
