### ISSUE TITLE
关于“𨈖”（U+28216）

### ISSUE THREAD

**Issue by Mjzsl123-github** [rime/home#1126]
![image](https://user-images.githubusercontent.com/110514823/186586817-805ba645-ec46-48d5-9b34-adf83d42f281.png)
![image](https://user-images.githubusercontent.com/110514823/186586865-1e5b9c53-1d6b-4ae3-86be-058277a5c04b.png)
“din”这个读音哪来的？

**Comment by Mjzsl123-github** [comment]
“忹”（U+5FF9），读音为kuang2或wang3，没有nin读音
真正有nin读音的是“𢗖”（U+225D6）

**Comment by Mjzsl123-github** [comment]
䚾的读音是ren2非nin

**Comment by LEOYoon-Tsaw** [comment]
> ![image](https://user-images.githubusercontent.com/110514823/186586817-805ba645-ec46-48d5-9b34-adf83d42f281.png)
> 
> ![image](https://user-images.githubusercontent.com/110514823/186586865-1e5b9c53-1d6b-4ae3-86be-058277a5c04b.png)
> 
> “din”这个读音哪来的？

當禁切唄，雖然現任是不應案普通話直接切的，但當禁（m尾）也不可能切出振（n尾），當禁在切韻以後的音系裡都是不合法的音，強行存古的話可以認為是章母侵韻去聲，枕（之任切）
但這些奇怪的切語既然怎麼看怎麼不對，大可當作不存在，猜來猜去意義不大

**Comment by Mjzsl123-github** [comment]
好的
不过希望修正“忹”
