### ISSUE TITLE
win10 安装小狼毫后，开始菜单不能打开

### ISSUE THREAD

**Issue by eallion** [rime/home#113]
win10 安装小狼毫后，开始菜单不能打开

**Comment by ipcjs** [comment]
开issue前请先搜索下，这是已知问题。
小狼豪不支持Win10。

**Comment by Kahaani** [comment]
在 Win10 上建议把「小狼毫（TSF）」删去，只留下「小狼豪（desktop only）」。

**Comment by littleq0903** [comment]
#25
