### ISSUE TITLE
疑问：关于comment中的 太极/陰陽魚符号 “☯️”

### ISSUE THREAD

**Issue by LawssssCat** [rime/home#1133]
![Snipaste_2022-09-03_10-05-14](https://user-images.githubusercontent.com/18041500/188251842-4f374e7f-b4f1-49ef-961f-924610b37674.png)

情况：
关于这个太极符号 ☯️ 的结果

我查遍了wiki的资料，只找到<https://github.com/rime/home/wiki/UserGuide#%E5%80%89%E9%A0%A1>里面说了 这个结果是“已知字碼自動組合而成的結果”

但用起来的效果是：只反显我输入的英文编码且大小写会变，因此这个结果从来没有用到过，但又总是占据结果第一位（有时又不显示）非常碍眼且影响打字

问题：
1. 请问如何配置才能使这个太极符号 ☯️ 的结果有用？
2. 或者怎么屏蔽这个结果？或者不然他显示在第一页？

---

我的配置：<https://github.com/LawssssCat/rime-userdata-backup>

**Comment by lotem** [comment]
原裝方案沒有這條結果。應該是詞典裏定義了兩個字，分別是`guan`和`F`。

**Comment by LawssssCat** [comment]
> 原裝方案沒有這條結果。應該是詞典裏定義了兩個字，分別是`guan`和`F`。

我对比了我以前的配置，发现把 `translator/enable_sentence` 设置成 `false` 就屏蔽了 "☯️"

但是关于这个 `enable_sentence` 配置，我看这里说是“开启自动造句” <https://github.com/LEOYoon-Tsaw/Rime_collections/blob/master/Rime_description.md#%E4%B8%89translator>
这个功能可以怎么看到他起作用？除了一开始说的会反显一些不想要的英文编码外

**Comment by lotem** [comment]
主題圖就是該選項在起作用。用詞典裏的假字造了一個假詞組。

**Comment by LawssssCat** [comment]
“自动造句” 意思是下面两个句子可能自动合并在一起显示吗？
```yml
春花秋月	chun hua qiu yue
独上西楼	du shang xi lou
```
![Snipaste_2022-09-04_01-51-55](https://user-images.githubusercontent.com/18041500/188282587-76fb5969-4294-40a7-a430-07f800ae8a2d.png)

但为什么这个结果没有"☯️"comment，且我把 `translator/enable_sentence` 设置成 false 后，依然有这个结果显示？（没有把这个结果输出到编辑器，因此应该没有用户记忆）
