### ISSUE TITLE
windows上 installation.yaml 会自动变回默认设置，无法保存

### ISSUE THREAD

**Issue by sunrisewestern** [rime/home#1140]
distribution_code_name: Weasel
distribution_name: "小狼毫"
distribution_version: 0.14.3
rime_version: 1.5.3
installation_id: "HomePC"
sync_dir: "C:\Users\RimeSync"

installation.yaml 设置sync目录后 deploy， installation.yaml 会自动变回默认设置，无法同步设置

**Comment by jack911jie** [comment]
后来怎么解决的？我也是遇到了这个问题。

**Comment by sunrisewestern** [comment]
@jack911jie  sync_dir 后面路径只能用单引号。。

**Comment by jack911jie** [comment]
真的耶。。。感谢。。那个id也用单引号才行。好误导人啊。。。

**Comment by plutotree** [comment]
这个不支持双引号，的确是一个坑，而且日志是正常的，看不出问题，只是最后没有生成文件
