### ISSUE TITLE
同步词库：同步 custom_phrase.txt 问题

### ISSUE THREAD

**Issue by fingerknight** [rime/home#1149]
Hi

我在同一台电脑上转了两个 rime： 一个是系统使用的 rime ，一个是 emacs-rime。二者都用的小鹤双拼，配置几乎相同（不同是因为如果把系统配置直接挪到 emac-rime 下会导致 emacs-rime 无法正常使用，需要微调），二者都在用 sycn，install.yaml 里面填了不同的 Id 和相同的同步路径（前者为系统的 rime，后者为 emacs-rime ）。

![image](https://user-images.githubusercontent.com/56252828/193727650-18f4da08-725a-4188-be3b-e4f50728f6e3.png)

![image](https://user-images.githubusercontent.com/56252828/193727718-40c198e6-8d06-4ce5-afd5-f05ca09579cf.png)

两边进行同步后，都在同步目录下生成了子目录：

![image](https://user-images.githubusercontent.com/56252828/193727336-251f6a3d-632a-4210-afa8-355d216a7f2d.png)

我在用 emacs-rime 的时候，手动在 custom_phrase.txt 下添加了新的条目：

![image](https://user-images.githubusercontent.com/56252828/193727408-74c5c99f-264a-4364-b18b-f36a5eaebb1b.png)

但是两边都使用同步之后，系统的 rime 在同步目录下的 custom_phrase.txt 并没有添加：

![image](https://user-images.githubusercontent.com/56252828/193727557-a2769b29-6902-48a7-995b-20f613a3776f.png)

所以我想问一下，用 rime 的 sync 是否会同步 custom_txt.phrase ？ 如果会，是我的哪个地方配置不对，还是它把词库存到其他地方？如果不会，那要如何同步这二者之间的自定义词库呢？

任何建议都万分感谢！

**Comment by iDvel** [comment]
那个「同步」功能除了同步，对其他 YAML 和 TXT 文件只是做一个**单向备份**而已。
你修改「同步目录」下的 TXT 文件不会产生任何作用，你需要修改「配置目录」的那个。

**Comment by fingerknight** [comment]
明白，谢谢！
