### ISSUE TITLE
[advice] How about use a same path for ibus/fcitx/fcitx5

### ISSUE THREAD

**Issue by Freed-Wu** [rime/home#1163]
According to <https://wiki.archlinux.org/title/Rime_(%E7%AE%80%E4%BD%93%E4%B8%AD%E6%96%87)#%E9%85%8D%E7%BD%AE>,

For ibus/fcitx/fcitx5, the config file is

- ~/.config/ibus/rime/default.custom.yaml
- ~/.config/fcitx/rime/default.custom.yaml
- ~/.local/share/fcitx5/rime/default.custom.yaml

Why not use a same global path like `~/.config/rime/default.custom.yaml`? It can
be more convenient for user switch input method and backup their config file.

Thanks.

**Comment by mokapsing** [comment]
As a Linux user, you should know how to create a symbolic link to a file. if you don't know, you can google "ln Linux"

**Comment by Freed-Wu** [comment]
I know `coreutils`. But I think if all rime (ibus/fcitx/fcitx5) use same config, why not provide a unified path to store the setting?

**Comment by Freed-Wu** [comment]
I have taken a look:

```c
  RIME_STRUCT(RimeTraits, rime_traits);
  traits.user_data_dir = "XXX";
```

`traits.user_data_dir` doesn't have a default value. It just be NULL. Different rime distributions set their default value. Let upstream (rime) to decide a default value is not appropriate because librime is just a library, should not provide any too more designation.
