### ISSUE TITLE
鼠鬚管如何在秘╱袐之外，添加祕？

### ISSUE THREAD

**Issue by mgeorgetw** [rime/home#1170]
我想用luna_pinyin_tw輸入「[示字旁的祕](https://www.moedict.tw/%E7%A5%95)」，這是臺灣教育部收錄的用法，某些情況我只能用這個字。

不過選字欄中只找得到「禾字旁的秘」和「衣字旁的袐」，後者雖然肉眼難分辨，卻沒有收錄在臺灣教育部的辭典中。

我試過用「[導入其他來源的碼表](https://github.com/rime/home/wiki/UserGuide#%E5%B0%8E%E5%85%A5%E5%85%B6%E4%BB%96%E4%BE%86%E6%BA%90%E7%9A%84%E7%A2%BC%E8%A1%A8)」介紹的方法，至少添加常用的兩個詞條：

```
神祕	shen mi	100
便祕	bian bi	100
```

可是依然沒有出現在選字框中。

原因是不是源碼表中沒有收錄「示字旁的祕」？如果是的話，按照「[導入其他來源的碼表](https://github.com/rime/home/wiki/UserGuide#%E5%B0%8E%E5%85%A5%E5%85%B6%E4%BB%96%E4%BE%86%E6%BA%90%E7%9A%84%E7%A2%BC%E8%A1%A8)」的說法，我可以：

1. 用OpenCC完成碼表的繁、簡轉換。
2. 凡是編碼爲源碼表中未出現過的形式，如通過「拼寫運算」實現的簡拼、異拼，又如編碼中的拼寫錯誤，都將導致該條記錄成爲用戶詞典中的無效數據，因爲無法通過正常的輸入檢索到。

就第一點，我已經在schema裡定義了OpenCC，但在這裡無助我輸入「示字旁的祕」：
```
simplifier:
  opencc_config: t2tw.json
  option_name: zh_tw
```

就第二點，我在[#825](https://github.com/rime/home/issues/825)看到類似的問題，討論串中提到小狼毫的解法，但我該怎麼用鼠鬚管解呢？

**Comment by oniondelta** [comment]
鼠鬚管解法和小狼毫完全相同
https://github.com/rime/home/issues/825 已說明了大致問題，且說明解法很多種，但不要同時使用！

### 字詞庫解法：

1. opencc 為字詞濾鏡轉換，先關掉避免干擾
以下「#」遮屏
```
  - name: zh_tw
    reset: 1

simplifier:
  opencc_config: t2tw.json
  option_name: zh_tw
```
3. 在 luna_pinyin.dict.yaml 內加詞條，重新部署
4. 如果不行，修改八股文（附加詞頻用）
方法：
複製該檔 https://github.com/rime/rime-essay/blob/master/essay.txt
丟進 Rime 資料夾（用戶設定）
然後打開 essay.txt 查詢你修改的詞彙是否在裡面，調大詞頻，重新部署
ps：essay.txt 該檔鼠鬚管中已有，以上方法，只是覆蓋引用

### opencc 解法：

1. 字詞庫都不要動

2. 修改 t2tw.json 相關檔案（以下），並丟入opencc 資料夾中，說明有點繁複，懶得說 XD 會改其實很快 XD
ps：TWVariants.ocd2 可置換為 TWVariants.txt，txt 比較方便修改，ocd2 即時轉換速度較快
https://github.com/BYVoid/OpenCC/blob/master/data/config/t2tw.json
https://github.com/BYVoid/OpenCC/blob/master/data/dictionary/TWVariants.txt

4. 在 schema 裡定義新修改好的 opencc


![截圖 2022-11-15 20 59 13](https://user-images.githubusercontent.com/54584047/201930065-948ba40d-e61d-44ee-998a-430f40f8786e.png)

**Comment by mgeorgetw** [comment]
沒有在GitHub上看到您的回覆，不知怎麼回事。

原來是OpenCC干擾了我的詞條。沒錯，兩種方法都有效，我後來選了第二種，也保留異體字偶爾會用到。

感謝！

onion ***@***.***> 於 2022年11月15日 週二 晚上9:29寫道：
