### ISSUE TITLE
win11 小狼毫如何关闭状态栏右下角图标？

### ISSUE THREAD

**Issue by chenxia25** [rime/home#1171]
如何关闭状态栏右下角“中/A”图标？

已经尝试过在 `weasel.custom.yaml` 中添加 `"style/display_tray_icon": false`，没有用。重启也没用。

版本 1.5.3。

**Comment by fxliang** [comment]
如您想要的是关闭语言栏的图标，没有办法的。微软拼音也是类似的情况。
