### ISSUE TITLE
fcitx5 中 Switcher 快捷键除 Control 之外全部无效

### ISSUE THREAD

**Issue by zimtsui** [rime/home#1175]
在 `~/.local/share/fcitx5/rime` 中设置 switcher hotkeys:

- Control+任意小写字母，有效
- Control+Shift+任意小写字母，无效
- Shift+任意小写字母，无效
- Alt+任意小写字母，无效

甚至连默认设置 `/usr/share/rime-data/default.yaml` 中的 `Control+Shift+grave` 都无效。

版本
fcitx5 5.0.19
fcitx5-rime 5.0.14-1
Plasma 5.26.3
Plasma Framework 5.98.0

**Comment by pzzxqj** [comment]
摸索出方法，留下供后来者参考。用Shfit键修饰的快捷键，要用按住Shift键产生的符号。比如`Control+Shift+2`要写成`Control+Shift+at`，即@符号。

**Comment by pzzxqj** [comment]
键对应的名称https://github.com/LEOYoon-Tsaw/Rime_collections/blob/master/Rime_description.md#%E5%85%AB%E5%85%B6%E5%AE%83
