### ISSUE TITLE
求问ibus-rime/fcitx-rime简入繁出实现方式

### ISSUE THREAD

**Issue by nemo-nullius** [rime/home#118]
我之前在windows上安装小狼毫，并在weasel-0.9.30\data\opencc\文件夹下自行添加simp_to_trad_characters.ocd、simp_to_trad_phrases.ocd、zhs2zht.ini（并修改路径），通过在shema.yaml文件中调用`opencc_config: zhs2zht.ini`，在windows上已实现简入繁出。

可现在ubuntu 14.04上安装fcitx-rime与ibus-rime后，再如windows中的方法在/usr/share/rime-data中拷入这三个文件，无论使用fcitx-rime或ibus-rime，都无济于事。不知ubuntu中的rime能通过调用opencc词库实现简入繁出吗？有什么方法呢？是不是我路径没找对呢？

谢谢！

**Comment by lotem** [comment]
查了一下，Trusty 打包的是「新版」libopencc1，配置文件的格式與 opencc 0.4.x 有所不同。
