### ISSUE TITLE
如何恢复同步

### ISSUE THREAD

**Issue by jiuhuche120** [rime/home#1194]
当我点击同步用户数据的情况下，仅将我当前的用户数据同步到云数据，无法从云数据同步到我当前的配置

**Comment by keminu** [comment]
同问，如何恢复呢？

**Comment by hellomsg** [comment]
这里的"同步"是否只是"备份"的意思?

**Comment by lotem** [comment]
> 这里的"同步"是否只是"备份"的意思?

不是。详见
https://github.com/rime/home/wiki/UserGuide#%E5%90%8C%E6%AD%A5%E7%94%A8%E6%88%B6%E8%B3%87%E6%96%99
