### ISSUE TITLE
建議添加自動上屏功能

### ISSUE THREAD

**Issue by jakwings** [rime/home#12]
最近試用了一下 Mac 提供的可裝載鍵盤佈局功能，用來實現世界語字母的 X 組合公式。實際上就是要設計一個有限狀態自動機，達到終止條件即自動上屏（而不是達到最大長度）。公式如下：

```
c + x/X = ĉ, C + x/X = Ĉ
g + x/X = ĝ, G + x/X = Ĝ
h + x/X = ĥ, H + x/X = Ĥ
j + x/X = ĵ, J + x/X = Ĵ
s + x/X = ŝ, S + x/X = Ŝ
u + x/X = ŭ, U + x/X = Ŭ
```

另外尚有輔助公式：

```
c + <Tab> = c, C + <Tab> = C
g + <Tab> = g, G + <Tab> = G
h + <Tab> = h, H + <Tab> = H
j + <Tab> = j, J + <Tab> = J
s + <Tab> = s, S + <Tab> = S
u + <Tab> = u, U + <Tab> = U
```

終止條件還包括找不到對應終止符，[另有一套規則](https://github.com/jakwings/mac-keyboard-Esperanto/blob/master/Esperanto.bundle/Contents/Resources/Esperanto.keylayout#L1162-L1198)。（可視作將已有字符上屏）

自動上屏還有一個好處：假如當前應用爲 Terminal，用如上拉丁文方案，基本功能都不受影響（除了左右 Shift 那類問題）。

那個世界語的插件在此，源碼都有詳盡注釋：<https://jakwings.github.io/mac-keyboard-Esperanto/>

**Comment by lotem** [comment]
用 Rime 输入方案实现吧。可以用正则表达式定义上屏条件。不过写世界语的话，空格要作为一般的符号键来处理，这也有选项控制。

**Comment by jakwings** [comment]
`speller/max_code_length` 和 `speller/auto_select_pattern` 似乎對 `engine/translator/echo_translator` 提供的候選不起作用，非要碼表中已有輸入碼才能自動上屏，所以我用了點難看的花招。

空格還是沒搞定，我想要的效果是，即使編碼框有內容也直接將空格也一並輸出直接上屏。

輸入方案及碼表：<https://gist.github.com/jakwings/834ce4da5c482b59ef79>

**Comment by lotem** [comment]
的確，自動上屏只針對 table_translator。
echo_translator 的作用是把輸入碼當作一個額外的候選，會一直緩存輸入碼。
我感覺只須把所有字母（包括以兩鍵組合輸出的字母）加入詞典並開啓自動上屏、關閉造句，就能達到依字母上屏的效果。

要取消空格在 composing 狀態兼作功能鍵的用法，得設置 `punctuator/use_space: true`
https://github.com/LEOYoon-Tsaw/Rime_collections/blob/master/Rime_description.md

**Comment by jakwings** [comment]
那篇說明我看了好幾遍了，各種亂試，根本弄不明白，最多也只是讓空格留在輸入框，不能直接上屏。不知道有沒有簡單的示例，依次打 `a<空格>b`（不用按回車）出 `a b`，a 和空格同時出，b 最後？

其實我還想加入 `<Option> + i + <字母>` 等重音符號組合的，不過剛試了也不行。Orz 我還是用系統自帶功能吧。RIME 好像比較適合語句流，用於那些不定長而又無重碼還要自動上屏的方案就吃力很多，`fluid_editor` 和 `express_editor` 都有不少限制。

謝了，我先折騰到這吧。再下去應該要直接研究源碼了，囧。
