### ISSUE TITLE
"钻" 简体中文打不出

### ISSUE THREAD

**Issue by asepsisWu** [rime/home#120]

**Comment by ipcjs** [comment]
你拼音打对了？
![screenclip](https://cloud.githubusercontent.com/assets/4396864/20414287/aa9fc692-ad6c-11e6-85b2-52676790850d.png)

**Comment by asepsisWu** [comment]
![zhuanshi](https://cloud.githubusercontent.com/assets/4438057/20414739/fc9de652-ad6e-11e6-9cbb-13b317afb017.png)
![zhuan](https://cloud.githubusercontent.com/assets/4438057/20414754/236bf486-ad6f-11e6-8a34-a00b184e9f4c.png)
拼音没打错。
windowsXP的小狼毫 和centos7的rime都不可以。是不是我的设置有问题？

**Comment by ipcjs** [comment]
@asepsisWu 正确的拼音貌似是`zuan`。。。我开了模糊拼音，打`zhuan`也可以打得出来。
[brise](https://github.com/rime/brise)里的拼音没有问题，自己看下自己的词典是不是有问题吧。

**Comment by asepsisWu** [comment]
多谢@ipcjs
