### ISSUE TITLE
输入法能否根据候选项长度自动变换水平模式和竖直模式？

### ISSUE THREAD

**Issue by jkhnfk** [rime/home#1213]
### Discussed in https://github.com/rime/home/discussions/1212

<div type='discussions-op-text'>

<sup>Originally posted by **jkhnfk** February 15, 2023</sup>
在平时输入过程中有许多时候需要输入较长的内容，如地址、身份证号、税号、以及一些较长的专业术语。
一旦这些内容同时出现在好几个修选项中时，如果此时是水平模式，候选框就会无比地长，观察和选择都比较困难。
能否增加输入法根据候选项的长度，在判断候选项长度比较长时，自动转为竖直模式，待输入完成后又自动转为水平模式？
</div>

**Comment by LEOYoon-Tsaw** [comment]
可以，你可以試試，（macOS上，windows我不知道）應該不會太難。

**Comment by LEOYoon-Tsaw** [comment]
請勿重複發帖
