### ISSUE TITLE
應該如何打開.ocd檔案？

### ISSUE THREAD

**Issue by HIRATEYURINA46** [rime/home#1223]
作業系統：Windows 11

我希望編輯「程序文件夾」下「opencc」資料夾內的一些 .ocd 檔案，於是下載了OCAD 2018 Mapping Solution試圖打開這些檔案。但OCAD最終也未能打開這些檔案。

若有人知道如何打開並編輯這些 .ocd 檔案，還請不吝賜教，本人在此感激不盡。

**Comment by LEOYoon-Tsaw** [comment]
用opencc_dict轉換成txt

**Comment by HIRATEYURINA46** [comment]
> 用opencc_dict轉換成txt

我下載了最新版本的預編譯 `OpenCC` 之後，將欲轉換之檔案放置在程式 `opencc_dict.exe` 所在目錄下，然後在該目錄下打開 `Windows PowerShell`  並輸入命令 `.\opencc_dict -i 檔案名.ocd -o 檔案名.txt -f ocd -t text`  ，該命令運行後沒有報錯，但無論如何也找不到轉換出來的檔案。

請問這是甚麼情況，有何解決辦法呢？

**Comment by HIRATEYURINA46** [comment]
最新測試結果：預編譯版本的 `OpenCC` 自帶的 `ocd2` 檔案可以被正常轉換，但 `RIME` 自帶的 `ocd` 檔案則無法被成功轉換。

**Comment by LEOYoon-Tsaw** [comment]
哦，windows的小狼毫幾百年沒更新了，librime早就換了新的OpenCC，可以用新的librime替換一下
