### ISSUE TITLE
添加了 zhwiki 词库后，部署会闪退

### ISSUE THREAD

**Issue by PinkD** [rime/home#1231]
问题描述：

在添加了 [zhwiki](https://github.com/felixonmars/fcitx5-pinyin-zhwiki) 词库后，重新部署，从任务管理器观察到部署的进程占用了接近 2G 内存，然后闪退， `%TEMP%` 目录下的日志文件中无任何相关的日志输出

一些猜测和疑问：

- 发现小狼毫的程序是 32 位的，猜测是不是内存撞到瓶颈了
- 是否会提供 64 位的小狼毫程序
- 词库构建的算法是否有优化的空间，一共几十 M 的词库构建时占用超过 2G 内存感觉还是比较令人疑惑的(没详细了解过构建的算法，这里仅仅是提出疑惑)

版本信息：

- os: win10
- weasel: 0.14.3

**Comment by cptang** [comment]
确实词库部署有时候会部署失败

**Comment by PinkD** [comment]
@eagleoflqj 可以关联一下哪个 pr 或者 commit 解决了该问题吗？

**Comment by ksqsf** [comment]
[librime 1.9.0](https://github.com/rime/librime/blob/master/CHANGELOG.md#190-2023-09-16) 引入了性能优化。目前小狼毫尚未发布搭载 1.9.0 的正式版，可用 [nightly](https://github.com/rime/weasel/releases/tag/latest) 版测试。

**Comment by fxliang** [comment]
rime/weasel#1121 引入64/32位共用安装包，自动根据当前系统版本释放文件，另外针对32位系统还加入了大地址支持，考虑到目前主流的windows 8.1以上的系统大多都是64位，目前这个内存限制已基本不大。如果您系统是8.1以上，可以用nightly的构建产物即可。

> @eagleoflqj 可以关联一下哪个 pr 或者 commit 解决了该问题吗？
