### ISSUE TITLE
【功能请求】形码不定码长自动切分思路

### ISSUE THREAD

**Issue by yueduz** [rime/home#124]
#【功能请求】形码不定码长自动切分思路
按我使用的方案来看，rime是优先切分出单字的，如果真是这样，其实思路很简单，只要优先切出能匹配词库的词就好了。
像图片上的‘不要’和‘不是我’词库里是有的，但是编码和我手动切分的不一样。
图片链接，请复制打开
[http://od5dg4nzk.bkt.clouddn.com/2016-12-24%2008-58-01.png](url)

**Comment by lotem** [comment]
你想要的效果可以類比輸入拼音「hahan」得出「很愛很愛你」，輸入「dan」得出「戴安娜」，輸入「zhe」得出「這會兒」。
然而規則是優先匹配詞典裏的內容。
由程序切分組詞屬於「猜測」，因此其優先級不及在詞典裏寫明的。
要想優先出詞，可以在詞典裏給這個詞編碼。

**Comment by yueduz** [comment]
怎么个猜法？那可以让猜测的优先吗？

**Comment by yueduz** [comment]
因为码长是不固定的，要为所有打法编码有点难度

**Comment by lotem** [comment]
我不太懂你的編碼。
你既然說「‘不要’和‘不是我’词库里是有的，但是编码和我手动切分的不一样」，等於是說，你告訴輸入法「不要」這個詞的編碼是 ab，現在卻要求打 cd 能出來（你沒告訴輸入法他怎麼知道呢），而且優先於詞典裏編碼爲 cd 的詞。我看這個詞典是有點兒問題的。

**Comment by yueduz** [comment]
不要的全码是wwan，但是w是‘不’的一级简码，’a‘是要的一级简码

**Comment by yueduz** [comment]
schema.yaml文件
--------------------------------------------------------------------------------
`custom_phrase:
  db_class: stabledb
  dictionary: ""
  enable_completion: false
  enable_sentence: false
  initial_quality: 0
  user_dict: custom_phrase
customization: 2533496964
engine:
  filters:
    - simplifier
    - uniquifier
  processors:
    - ascii_composer
    - recognizer
    - key_binder
    - speller
    - punctuator
    - selector
    - navigator
    - express_editor
  segmentors:
    - ascii_segmentor
    - matcher

    - abc_segmentor
    - punct_segmentor
    - fallback_segmentor
  translators:
    - punct_translator
    - script_translator
    - reverse_lookup_translator
    - "table_translator@custom_phrase"

key_binder:
  import_preset: default
menu:
  page_size: 5

reverse_lookup:
  dictionary: pinyin_simp
  prefix: "`"
  suffix: "'"
  tips: 〔拼音〕
  preedit_format:
    - xform/([nl])v/$1ü/
    - xform/([nl])ue/$1üe/
    - xform/([jqxy])v/$1u/
punctuator:
  import_preset: symbols
recognizer:
  import_preset: default
  patterns:
    punct: "^/([0-9]0?|[a-z]+)$"
    reverse_lookup: "`[a-z]*'?$"
schema:
  author:
    - "谢振斌"
  dependencies:
    - pinyin_simp
  description: |
    山人全息码
    sunman.uueasy.com

  name: "山人"
  schema_id: sunman
  version: 0.9.01
simplifier:
  option_name: sunman_simp
  tips: all
speller:
  algebra:
    - "fuzz/^(\\w)(\\w).+$/$1$2/"
    - "fuzz/^(\\w)(\\w)(\\w).+$/$1$2$3/"
    - "fuzz/^(\\w)(\\w)(\\w)(\\w).+$/$1$2$3$4/"
  alphabet: zyxwvutsrqponmlkjihgfedcba
  delimiter: " '"

switches:
  - name: ascii_mode
    reset: 0
    states: ["中文", "西文"]
  - name: full_shape
    states: ["半角", "全角"]
  - name: ascii_punct
    states: ["。，", "．，"]
  - name: sunman_simp
    states: ["漢字", "汉字"]
translator:
  dictionary: sunman.extended
  enable_user_dict: false
  prism: sunman
  strict_spelling: true`
=================================================
部分码表：
-------------------------------------------------------
`䳭	zzki
书	zzs	28
卪	zzsd
丩	zzsv
卩	zzsv
堲	zzt	1
堲	zztu
乜	zzv
㐨	zzvv
の	zzz	4
の	zzzz	2

#词

〇〇		658
〇一		488
〇七		493
〇三		437
〇九		616
〇二		471
〇五		470
〇八		573
〇六		505
〇四		485
㐖毒		0`
------------------------------------------------------------------

我看了我方案，词组都没有编码，好像也没有定义词组规则。我是从网上找的方案，我也是太懂方案配置

**Comment by lotem** [comment]
山人我並不會用，聽打山人的同學說過是每字兩碼地打詞組和整句。既然是下載的方案，那就請相信作者吧，他的設置應該就是正確用法。
如果有「一級簡碼」這概念，那從策略上更不可能像簡拼那樣一字一碼地自動造詞並作爲首選，否則詞典裏的詞全部得靠後站。

**Comment by lotem** [comment]
且不論方案的設計是否能支持你提出的組詞策略，
我就告訴你一點，電腦程序是嚴謹而明確的。
不管你心裏怎麼想，你要實現這個簡碼，卻告訴他說該詞的編碼是另一個，那是不行的。
我舉一個例子。拼音詞典將「空調」編碼爲「kōng tiáo」，但是「空」還有一個編碼「kòng」，「調」也還有一個編碼「diào」。既然詞典給定了詞組的編碼，輸入法要是再發明出「kōng diào」等誤讀，那詞典的意義何在？果真有多種讀法的詞，比如「便宜 pián yi / biàn yí」，則須分別註明。這是詞典的功能和用法。必須對個別方案作出明確定義，才能驅動通用的輸入法程序。
