### ISSUE TITLE
能否通过修改代码的方式来实现以下内容？

### ISSUE THREAD

**Issue by Pcodcsja** [rime/home#1245]
![image](https://user-images.githubusercontent.com/66547114/227769286-7424de74-953b-4034-82a5-226bbffb533b.png)

能否通过修改代码的方式来实现上图所示方式？

**Comment by Pcodcsja** [comment]
> 你是要分为 3 行的候选面板？ 还是只是不同按键选词？

分为三行的候选面板，界面和上图一样，然后可以通过空格和 1 2 3 4 来选词
能通过修改代码的方式实现吗？请大佬解答，感谢！

**Comment by LEOYoon-Tsaw** [comment]
修改代碼可以實現**任意**功能

**Comment by pdog18** [comment]
> > 你是要分为 3 行的候选面板？ 还是只是不同按键选词？
> 
> 分为三行的候选面板，界面和上图一样，然后可以通过空格和 1 2 3 4 来选词 能通过修改代码的方式实现吗？请大佬解答，感谢！

通过 yaml 配置实现不了，修改源码可以实现

**Comment by Pcodcsja** [comment]
> > > 你是要分为 3 行的候选面板？ 还是只是不同按键选词？
> > 
> > 分为三行的候选面板，界面和上图一样，然后可以通过空格和 1 2 3 4 来选词 能通过修改代码的方式实现吗？请大佬解答，感谢！
> 
> 通过 yaml 配置实现不了，修改源码可以实现

感谢大佬解答，但是修改源代码对我来说有点太困难了😂

**Comment by pdog18** [comment]
> > > > 你是要分为 3 行的候选面板？ 还是只是不同按键选词？
> > > 
> > > 
> > > 分为三行的候选面板，界面和上图一样，然后可以通过空格和 1 2 3 4 来选词 能通过修改代码的方式实现吗？请大佬解答，感谢！
> > 
> > 
> > 通过 yaml 配置实现不了，修改源码可以实现
> 
> 感谢大佬解答，但是修改源代码对我来说有点太困难了😂

可以将 issue close 掉了
