### ISSUE TITLE
有个问题困扰我很久，希望能自定义候选短句数（不是候选词数）

### ISSUE THREAD

**Issue by Buggist** [rime/home#1246]
很多时候在输入法内敲出很长一句话，候选词页面前面有很多页都是些不正确的候选短句，而我知道我真正想输入的短句并不在词库内，我只是想不要弹出那么多候选短句，赶快让我开始选择我需要的那个字。而过多的候选短句浪费了我大量时间。
--------
这个问题出现在许多中文输入法当中，在实际打字过程中，如果前5个候选短句都不是用户想要的的话，那么用户想要的候选短句有99.9%的概率就根本不存在于词库里（毕竟前5个候选短句已经是根据用户习惯优化过权重的可能性最高的5个了），没必要再列出10~30个根本就不可能正确的短句来白白耗费用户寻找想要的单字的时间（因为短句在候选页中总是会先于单字显示）。就我个人而言，固定的5个候选短句已经足够多了。如果它们没能猜中我的意图，那我宁可立刻开始进行单字查找，这样通常效率更高。
--------
而我的建议是：
在default.yaml文件中，**给用户增加一个可以自定义最大候选短句数的功能**（就像它允许用户自定义每页候选词数那样）。
例如我设置最大候选短句数为5，那么候选页中就只会展示权重最高的5个短句，后面省略其它可能的短句，立刻进入单字展示。
再例如我设置的每页候选词数也为5，那么就只有第一页会用来展示候选短句，我只要前进到第二页即可立即开始浏览可能的单字。
--------
很多年前，输入法的词库还不像现在这样丰富时，候选短句也通常不超过5个，那时的输入法虽然低效，但很清爽。
而现在，当输入法词库逐渐成熟，打字效率已经被提升到一个临界值时，我注意到这些日趋臃肿的候选短句正在逐渐毁掉输入法的效率和便捷性。当候选短句逐年增加，我的打字效率并没有提升，反而在悄悄降低。
我认为真正使输入法效率提高的，不是候选短句的显示数量。而是储备数量，以及权重的准确性，但它们真的没必要全都显示出来。
**试想有一天，输入法词库壮大到，一次长输入里面包含了200个可能的短句，而其中刚好没有我需要的。那么我是否要为此去向后翻动几十页，就仅仅是为了能够开始去查找我想要的下一个字呢？**
在多年的输入法使用经验中，我认为我提议的这个改动能够大幅提升打字效率以及使用者的体验。
--------
最后祝RIME越来越出色，被更多的人喜欢。

**Comment by yanhuacuo** [comment]
连 GPT4 也得喂数据，RIME 里你选择正确的组合也是在喂数据，你翻页上屏，就是在喂权重。
什么也不想喂，建议直接用搜狗拼音，这家上市公司有足够成熟的，已经喂好的海量数据。

> 过多的候选短句浪费了我大量时间
> 当候选短句逐年增加，我的打字效率并没有提升，反而在悄悄降低

其实你该考虑选用一个具有确定性映射关系的输入法方案了。

**Comment by yanhuacuo** [comment]
连 GPT4 也得喂数据，RIME 里你选择正确的组合也是在喂数据，你翻页上屏，就是在喂权重。
什么也不想喂，建议直接用搜狗拼音，这家上市公司有足够成熟的，已经喂好的海量数据。

> 过多的候选短句浪费了我大量时间
> 当候选短句逐年增加，我的打字效率并没有提升，反而在悄悄降低

其实你该考虑选用一个具有确定性映射关系的输入法方案了。

**Comment by lotem** [comment]
Rime只給出一個整句結果，其他候選都是字詞。
