### ISSUE TITLE
希望实现/直接输入、  实际效果是每次总有一个菜单选项出来

### ISSUE THREAD

**Issue by sweepingmonk123** [rime/home#1248]
Mac上，版本是 Squirrel 0.16.2

按下/的效果实际上是：

![image](https://user-images.githubusercontent.com/6657119/227827195-85c21a70-2aad-4652-b688-c691ae1ec3f6.png)

**Comment by sweepingmonk123** [comment]
这个应该是个BUG，我从其他库git下来的，但我电脑上和作者原作者的电脑上不一样

**Comment by QingW-7023** [comment]
我是Windows，我知道有两个地方会造成这种，一种是关于符号的设置里，在对\的定义时，如果写为{ commit: 、 }，就不会有这个选单。还有一种是在方案yaml里，以我的xkjd6.schema.yaml为例，
speller:
  alphabet: "zyxwvutsrqponmlkjihgfedcba;=`"
  initials: "abcdefghijklmnopqrstuvwxyz;=`"
在speller下的两对引号中原本是有一个“/”的（现在已经删掉了），所以当按下/键时不会直接输入“、”，会出现跟你一样的选项。

**Comment by sweepingmonk123** [comment]
的确不是BUG，是我没把配置搞清楚，谢谢了
