### ISSUE TITLE
怎么改选词关键字

### ISSUE THREAD

**Issue by icydgx** [rime/home#126]
默认的1~5的选词键对我来说比较难按，我想知道在哪里定义

**Comment by icydgx** [comment]
我用的是dvorak键位布局。输入1的话要按"shift+("

**Comment by lotem** [comment]
可在輸入方案裏定義：
https://github.com/rime/rime-bopomofo/blob/master/bopomofo.schema.yaml#L58

**Comment by icydgx** [comment]
非常抱歉,现在才来回答,我用了以后,打字已经比原来舒适多了
