### ISSUE TITLE
为 rime 配方打包时，是否可以删除 .dict.yaml？

### ISSUE THREAD

**Issue by everyx** [rime/home#1263]
为了减小分发的软件包的大小，想能尽量删除无关文件。

我的理解是词库已经编译成 `build/<dict_name>.prism.bin` 文件了，因为每次更新都是更新的软件包（其中提供了预编译的二进制文件），用户不需要再编译了，作为源文件的 `[dict_name].dict.yaml` 就可以不需要了。

我做了测试，删除后好像也没有影响用户的「部署」操作，不知道理解的正不正确？

打包过程大概为：
1. 使用 `rime-prelude` 提供的默认配置配置编译环境
2. 运行 `rime_deployer --compile [name].schema.yaml` 来生成预编译的二进制部署文件
3. 将配方提供的相关文件（例如：`schema.yaml`、`lua` 脚本、`opencc` 相关文件等）和 `build/` 下除 `.txt` 的文件打包到 `/usr/share/rime-data/` 下

**Comment by everyx** [comment]
看了一下[源码](https://github.com/rime/librime/blob/8bf2cf7fb8062306ea064b6996650f8148538ce7/src/rime/dict/dict_compiler.cc#L84)，看起来是会线检查 `.dict.yaml` 文件存不存在，如果不存在就不会继续编译操作了，如果后续不需要此文件，应该是可以删除

**Comment by everyx** [comment]
> 如果你想隱藏碼表可以這麼做。如果想方便用戶則應該只提供dict.yaml，而不必提供bin文件 不過就算你不提供dict.yaml，有心的用戶也可以反編譯出碼表，其實是藏不住的

@LEOYoon-Tsaw  嗯嗯，我是考虑给发行版打包配方的时候是否需要删除以减小打包体积，考虑到用户可能自定义字典可能需要引用，应该还是需要包含会比较好。

**Comment by LEOYoon-Tsaw** [comment]
如果想減少打包體積，那就不需要.bin文件，用戶第一次使用時現編譯就行了
