### ISSUE TITLE
内存占用经常超过4G

### ISSUE THREAD

**Issue by freejenyu** [rime/home#1295]
Squirrel 0.16.2

MacOS 12.6.3

输入方案：https://github.com/iDvel/rime-ice

![2023-05-13_09-11-53](https://github.com/rime/home/assets/20198741/21c3d62c-e4c9-44f9-9b0c-a9b0876b5c13)

内存占用经常超过 4G 导致 Squirrel 卡死，不知道是不是跟使用的输入方案有关，还是新版 Squirrel 的 bug！

**Comment by LEOYoon-Tsaw** [comment]
詞庫太大唄

**Comment by wxyzh** [comment]
是不是和这个有关？
https://github.com/iDvel/rime-ice/issues/220

**Comment by eagleoflqj** [comment]
雾凇的问题已经解决，如还有问题可重开。
