### ISSUE TITLE
字典中是否可以使用假名作为码表?

### ISSUE THREAD

**Issue by Insomnia1437** [rime/home#1296]
**背景:**
日语输入中有不同的罗马字对应方案, Hepburn式和训令式. 
但实际使用中二者经常混用. 如Google日语输入法, macOS日语输入法, Windows IME 都是基于训令式(兼容部分Hepburn式). 
比如, 日语中的 `女子(じょし)`, 混合了Hepburn式和训令式后, 通常有四种方式输入, (zyosi, joshi josi, zyoshi). 

**问题:**
目前大多数网络上现成的字典都是基于Hepburn式编写的, 与这些输入法的使用习惯差异较大. 所以我打算基于`mozc`的数据自建字典.
但如果把(zyosi, joshi josi, zyoshi)都写入字典那会造成非常多的重复.

**我的设想:**
一个假名字典, 用于将罗马字母转为假名. 
例如: 
し -> si
し -> shi
じょ -> zyo
じょ -> jo
...

一个文字字典. 在其中可以找到这串假名对应的文字 (汉字或或平假名片假名或其组合)
女子 -> じょし
女子マラソン -> じょしまらそん
...

请问这种如何实现呢? 或者不使用假名字典, 把对应关系写到在`translator`的`preedit_format`里能实现吗?

**Comment by oniondelta** [comment]
應該可以，也強烈建議如果可行直接用假名轉！！！

之前用羅馬字母，碰到：
漢字中有 nya，是 にゃ 還是 んや ；
處理促音、拗音；
外語 てぃ 發 texi 也可發 thi 等一系列問題，
以上校對和用正則轉寫搞到頭昏！很容易誤轉其他不該轉寫之發音！

https://github.com/oniondelta/Onion_Rime_Files/blob/main/allfiles/jpnin1.schema.yaml

日文輸入還有個最大的問題，就是漢字字詞切分，
純假名沒什麼問題，複雜的是漢字！
日文漢字不像中文，一字一音節，
有一字多音節，
還有一個詞（多個字），多個音節，但無法切分！
Rime 字典中，字詞切分用空白間隔，
不切分也行，如以下網友方案，字詞典豐富齊全 👍🏻，
但沒切分，也沒作太多轉寫，打起來順暢，但沒你要的功能：

https://github.com/gkovacs/rime-japanese

字典中漢字切分沒作，又大量轉寫，如這邊的日文方案（第一個連結）
部屬後生成之 .prism.bin  容量會暴大，影響輸入時效能（順暢）！
要作切分，除非寫程式判斷，人力一年都作不來！

你說的可行，但重點不是轉寫，是日文漢字字詞典編排，不是現成別人日文字詞典拿來就可行！

**Comment by Insomnia1437** [comment]
感謝分享如此多的資源!!! (因爲最近剛開始使用Rime, 花了一些時間才理解您貼的內容 (｡>ㅅ<｡)

> https://github.com/lazyfoxchan/rime-jaroomaji

這個項目就是我想要的結果, 試用之後, 除開`translator`裏的`enable_completion`不起作用之外, 已經基本滿足我的需求了.

我本準備自己寫Python腳本從mozc中轉換dict, 結果這個項目已經實現了. 我只需要再添加一些代碼轉換下這個項目[https://github.com/utuhiro78/merge-ut-dictionaries](https://github.com/utuhiro78/merge-ut-dictionaries) 中的dict, 一個較爲可用的日語輸入法就完成了.

> 與其說明怎麼作，不如直接看別人方案的內容！

太對了!

**Comment by oniondelta** [comment]
enable_completion 一定不起作用，那是針對形碼 table_translator 用（基礎為一個字一個字出字）
日語方案如同拼音注音，多是使用 script_translator（基礎為連貫一串出字）
https://github.com/LEOYoon-Tsaw/Rime_collections/blob/master/Rime_description.md#%E4%B8%89translator

script_translator 要作到 enable_completion 類似效果，可用 speller 中的 abbrev 或 derive，
但 rime-jaroomaji 方案不適用，這就關於前面所提的切分，在字典中是當成字，還是詞，speller 只針對字。
把「東京」當作字：東京---toukyou
把「東京」當作詞：東京---tou kyou
把「東京」當作詞：東京---to u kyo u

**Comment by Insomnia1437** [comment]
我也覺得它對於促音的處理些許奇怪. 爲了適配如`っだ (dda)`這類詞, 所以直接將 `d` 映射爲`っ`, 導致鍵入`dga` 也可以打出っが.

對於切分, 抱歉, 我還是有些糊塗. 假設我們不適用羅馬字, 而使用假名編碼, 我是否可以理解爲: 倘若我們提供以下字典

一 -> いち
一 -> いっ
一 -> ひと
一つ -> ひとつ
生 -> せい
生き -> いき
生れ -> うまれ
懸 -> け
懸 -> けん
懸け -> かけ
命 -> めい
命 -> いのち
東京 -> とう   きょう
一生懸命 -> いっ  しょう   けん   めい
...

那是否相當於使用了形碼進行輸入. 輸入`いっ しょう` 後, `一生懸命`一詞就會提前顯示?
而輸入`いのちがけ`後, 並不會出現`命懸け`的候選, 因爲字典中`懸け`的碼錶僅列出了`かけ`, 而未列出`がけ`. 如果字典補足`がけ`, 則同樣會提示對嗎?

自然, 實際使用中, 字典內詞的切分是一樁大麻煩事...

**Comment by oniondelta** [comment]
以假名作為字典標注，和羅馬字作字典標注，區別為羅馬字在 speller/algebra 中轉寫容易誤轉！（nya是んや還是にゃ之類）
其可實現功能沒區別！

回首篇問題：

(zyosi, joshi josi, zyoshi) 變化可用  [speller/algebra](https://github.com/LEOYoon-Tsaw/Rime_collections/blob/master/Rime_description.md#%E4%B8%80speller) 轉寫，可不用在字典內附加。
在字典內附加也是一個方法！

 speller/algebra 作用和 dict 內〔空格（切分）〕有關，
電腦---diao〔空〕nao
以上編碼無法設定 dia 打出「電腦」， 使用 table_translator 中的 enable_completion 也無法！
電腦---diannao
以上編碼可設定 dia 打出「電腦」， 使用 table_translator 中的 enable_completion 也可！

推薦先摸中文方案，日語方案這邊實作感覺比中文還複雜，
心有戚戚焉，以上說很多，但感覺已經說太雜了！
