### ISSUE TITLE
哪里有 schema.yaml 的完整文档？

### ISSUE THREAD

**Issue by foldl** [rime/home#1297]
我在尝试移植王林快码。遇到以下问题：

1. 王林快码中用到了“;”，我理解需要配置 translator。但不知道如何配置。

2. 王林快码中习惯以“,”选择第2候选项，以“.”选择第3候选项。这两个在不同的输入状态下，需要映射为标点，或者候选快捷键。不知道应该如何配置 punctuator 和 key_binder。

查阅文档 [Rime 配置文件](https://github.com/rime/home/wiki/Configuration) 和 [Rime 定製指南](https://github.com/rime/home/wiki/CustomizationGuide) ，没找到答案。

**Comment by mokapsing** [comment]
https://github.com/LEOYoon-Tsaw/Rime_collections/blob/master/Rime_description.md

**Comment by foldl** [comment]
现在第2个问题基本已解决。

对于第1个问题，看了上面的文档，还是不明白如何配置。

**Comment by mokapsing** [comment]
> 现在第2个问题基本已解决。
> 
> 对于第1个问题，看了上面的文档，还是不明白如何配置。

https://github.com/LEOYoon-Tsaw/Rime_collections/blob/master/Rime_description.md#%E4%B8%80speller

alphabet: 定義本方案輸入鍵
initials: 定義僅作始碼之鍵
finals: 定義僅作末碼之鍵

请细心阅读

**Comment by foldl** [comment]
完美。
