### ISSUE TITLE
简体拼音方案下如何将部分简体字自动替换为繁体？

### ISSUE THREAD

**Issue by LaurentiusY** [rime/home#1298]
Hello, 我是拼音简体用户，但审美强迫症的我希望打出的一小部分简体字能够自动被转换为繁体字。就比如打出“爱人”能够自动替换为“愛人”这样子的。但是绝大部分字还是保留简体的。请问有什么方法能实现部分意义上的写简出繁嘛？

**Comment by LEOYoon-Tsaw** [comment]
可以的，自己定義（修改）一份OpenCC轉換表

**Comment by lotc** [comment]
可以参考 #420
