### ISSUE TITLE
希望能够为用户推出RIME输入法图形化设置

### ISSUE THREAD

**Issue by AkarinLiu** [rime/home#1302]
RIME输入法不是普通人用的，但是如果能有每个输入法对应的图形化设置功能，配置会对普通用户更加友好，同时建议为第一次使用RIME的用户提供初始化设置。

RIME输入法设置
小狼毫输入法设置
鼠须管输入法设置

**Comment by yanhuacuo** [comment]
不可能实现「通用设置」，只能由特定方案用户商定一个特定的 schema 结构，以实现不同参数的管理。

https://wubi98.gitee.io/2023/02/21/2023-02-21-01.rimetool/

**Comment by mokapsing** [comment]
不是给普通用户用的，无意和搜狗百度争市场

**Comment by pdog18** [comment]
[来提需求](https://pdog18.github.io/rime-soak/)

**Comment by AkarinLiu** [comment]
> 来提需求，[Rime 图形化设置助手](https://pdog18.github.io/rime-soak/)
这个可以，希望能够为这个网站做SEO优化。

**Comment by pdog18** [comment]
> > 来提需求，[Rime 图形化设置助手](https://pdog18.github.io/rime-soak/)
> 
> 这个可以，希望能够为这个网站做SEO优化。

现在还是太烂，等以后做的真正可用了再考虑小小宣传一下
