### ISSUE TITLE
小狼毫自动更新安装过程报病毒威胁

### ISSUE THREAD

**Issue by heiher** [rime/home#1312]
Windows 10系统弹出更新提醒，自动下载、安装过程中Windows Defender报安装程序存在病毒威胁。不知道是误报，还是发布构建环境被感染了。

![1](https://github.com/rime/home/assets/1407733/4a023448-1988-4850-84b1-3682d8cb4328)

**Comment by bugcat** [comment]
+1

**Comment by bmanex** [comment]
+1

**Comment by heiher** [comment]
关联 https://github.com/rime/weasel/issues/914
