### ISSUE TITLE
新版小狼毫之轉換規則似乎存在問題

### ISSUE THREAD

**Issue by HIRATEYURINA46** [rime/home#1314]
新版小狼毫「注音」方案下的「臺灣字形」無法使用，即使選中該方案，亦只能輸出「傳統漢字」之字形。

**Comment by fxliang** [comment]
> 新版小狼毫「注音」方案下的「臺灣字形」無法使用，即使選中該方案，亦只能輸出「傳統漢字」之字形。

您好，新修改修改都是前端上的修改，未修改opencc相关的内在逻辑
您可能要复查一下方案设定或者opencc相关文件，或者font_face选择
我使用粤拼检查了两个我知道的典型的字

![image](https://github.com/rime/home/assets/4023160/af1ea56e-2951-44b1-9844-4af721fa0b59)
![image](https://github.com/rime/home/assets/4023160/41a29dba-344a-4ce8-84ec-ba47b44fde1f)

![image](https://github.com/rime/home/assets/4023160/17be4582-b7b4-4f1d-a91a-fdc044d77a50)
![image](https://github.com/rime/home/assets/4023160/16cfb34b-3419-42e5-9f87-e9c79ec4f8ad)

**Comment by HIRATEYURINA46** [comment]
> > 新版小狼毫「注音」方案下的「臺灣字形」無法使用，即使選中該方案，亦只能輸出「傳統漢字」之字形。
> 
> 您好，新修改修改都是前端上的修改，未修改opencc相关的内在逻辑 您可能要复查一下方案设定或者opencc相关文件，或者font_face选择 我使用粤拼检查了两个我知道的典型的字


我確認了我的方案沒有異常。隨後，我嘗試使用舊版小狼毫的做法：

  - name: 方案名
    states: [ x, y ]

simplifier:
  option_name: 方案名
  opencc_config: 對應的opencc檔案

仍無任何效果。

**Comment by fxliang** [comment]
目前确认的情况是前端没有改动opencc的内容
不如您试试粤拼上看看是不是一样有问题？

min
lei

https://github.com/rime/rime-cantonese

**Comment by LEOYoon-Tsaw** [comment]
OpenCC 有過一次升級。你用的轉換檔現在不能有重復的key，檢查一下你用的轉換檔，合併重復key應能解決

**Comment by HIRATEYURINA46** [comment]
> OpenCC 有過一次升級。你用的轉換檔現在不能有重復的key，檢查一下你用的轉換檔，合併重復key應能解決

感謝閣下之解答。我現在已經找到了問題所在。當我使用OpenCC檢查轉換檔案時，其提示檔案內存在重複key，但我無論如何也沒有找到重複之所在。以下是我的轉換檔案之全貌，如有可能，煩請閣下幫我檢查具體重複在哪裏。

`爲	為
牀	床
痹	痺
癡	痴
皁	皂
祕	秘
竈	灶
糉	粽
繮	韁
羣	群
僞	偽
嫺	嫻
嬀	媯
峯	峰
棱	稜
檐	簷
污	汙
泄	洩
裏	裡
踊	踴
鉢	缽
鍼	針
鮎	鯰
麪	麵
齶	顎
着	著
睾	睪
潙	溈
潨	潀
蔘	參
蔿	蒍
值	値
勞動	勞働
羣	群
社羣	社群
羣組	群組
戶	戸
查	査
於是	扵是
身份	身分
窗	窓`

鄙人在此表示感謝。

**Comment by HIRATEYURINA46** [comment]
**▎此問題已得到解決 This issue has been solved**

我將最新版 `OpenCC` 內設的 `TWVariants.ocd2` 檔案轉換為 `txt` 格式檔案後，對其進行修改，再將其轉換為 `ocd2` 檔案，期間無報錯，且應用於最新版小狼毫中可正常工作。

我尚不明確這究竟是甚麼原理。我現在所用轉換方案與之前是一樣的，只是從最新版 `OpenCC` 中提取了其檔案，再對其進行修改，就可以了。

假若有人遇到與我類似之情況，請嘗試我的解決方法，庶幾能夠奏效。

**Comment by HIRATEYURINA46** [comment]
綜上所述，此問題已得到解決。
