### ISSUE TITLE
0.15.0 版本 sophos 报毒

### ISSUE THREAD

**Issue by xiaodong-lu** [rime/home#1315]
下载 0.15.0 安装包后，直接报毒被删，显示 Generic Reputation PUA detected. 公司电脑所以关不了杀毒检测。 0.14.3 版本是正常的，不报毒。

**Comment by mirtlecn** [comment]
goto https://github.com/rime/weasel/issues/914

**Comment by fxliang** [comment]
可以留意0.16.1的状态，我相信已有改善。如有另外需求，可再开此issue
