### ISSUE TITLE
输入英文字母后按小键盘回车键没反应

### ISSUE THREAD

**Issue by hmtrino** [rime/home#1323]
如题，按键盘主回车键后英文字母可以上屏，按小键盘回车没反应

**Comment by Plainct** [comment]
顺便插一个类似的问题，按Shift键无法像之前那样直接上屏会变成下划线的状态，需要按回车才能上屏。
请问有没有改回之前那种按Shift键直接上屏英文的方法

**Comment by hmtrino** [comment]
查了好久自己解决了，贴出来：
patch:
  "key_binder/bindings":
    - { when: composing, accept: KP_Enter, send: Return }

**Comment by hpyer2016** [comment]
> 查了好久自己解决了，贴出来： patch: "key_binder/bindings": - { when: composing, accept: KP_Enter, send: Return }

大佬，请问是修改哪个文件呢

**Comment by lotem** [comment]
> 修改哪个文件呢

輸入方案的補丁文件

**Comment by hmtrino** [comment]
> > 查了好久自己解决了，贴出来： patch: "key_binder/bindings": - { when: composing, accept: KP_Enter, send: Return }
> 
> 大佬，请问是修改哪个文件呢

我在这个文件加的
“C:\Users\admin\AppData\Roaming\Rime\default.custom.yaml”

**Comment by lotem** [comment]
能解決就好。

至於說，Caps Lock、數字小鍵盤不支持，是作者故意的，作者自己不用，所以就沒做……因爲我堅信，自己不用，就是瞎做，不能持續維護，勉強做出來的東西也好不到哪兒去。

總之，用戶不能罵我。
