### ISSUE TITLE
Debian 12 下 fcitx5-rime 设置 menu/page_size 只在输入法选择界面生效

### ISSUE THREAD

**Issue by wuyuyang0703** [rime/home#1326]
系统：Debian 12

桌面环境：KDE，使用了 KDE 自带的输入法面板

输入法前端：fcitx5-rime

包版本：5.0.15-3

问题：在 ~/.local/share/fcitx5/rime/default.custom.yaml 中设置

```yaml
patch:
  menu/page_size: 9
```

部署后，按下 Ctrl + ` 后一页显示了 9 个选项，但是在输入时候选词个数仍为 5 个。修改了 /usr/share/rime-data/default.yaml 之后问题依然没有解决。

**Comment by alim0x** [comment]
OS：Debian 12
DE：GNOME 43

ibus-rime: 1.5.0-3

same problem here.

after apply `menu/page_size: 9`, there is 9 items in `ctrl+\`` menu, and `~/.config/ibus/rime/build/default.yaml` shows `page_size: 9`, but still 5 candidate words when input.

**Comment by alim0x** [comment]
[log.txt](https://github.com/rime/home/files/11963704/log.txt)

some log from "dbus-monitor --address `ibus address`" 👆

it seems like when opening ctrl+` menu, there is 9 candidate and 9 numbers.

but when input, there is 6 candidate(5 words and 1 empty "") and 9 numbers.

**Comment by alim0x** [comment]
@wuyuyang0703 试试直接在 default.yaml 写入 page_size: 9 试试？似乎只影响写在 default.custom.yaml 的情形。
如果有测试结果，请更新信息。

**Comment by hosiet** [comment]
https://bugs.debian.org/1040403

**Comment by hosiet** [comment]
Debian 12.1 将修复此问题，预期 2023 年 7 月 22 日发布。
