### ISSUE TITLE
ascii模式下输入变音符号

### ISSUE THREAD

**Issue by hbghlyj** [rime/home#1332]
[在 Word 中](https://support.microsoft.com/zh-cn/topic/%E5%9B%BD%E9%99%85%E5%AD%97%E7%AC%A6%E7%9A%84%E9%94%AE%E7%9B%98%E5%BF%AB%E6%8D%B7%E6%96%B9%E5%BC%8F-108fa0c1-fb8e-4aae-9db1-d60407d13c35)按 Ctrl+Shift+ 符号键，然后键入字母，可以输入[变音符号](https://en.wikipedia.org/wiki/Diacritic)
<html><body>

To insert this | Press
-- | --
à, è, ì, ò, ù,À, È, Ì, Ò, Ù | CTRL+` (ACCENT GRAVE), the letter
á, é, í, ó, ú, ýÁ, É, Í, Ó, Ú, Ý | CTRL+' (APOSTROPHE), the letter
â, ê, î, ô, ûÂ, Ê, Î, Ô, Û | CTRL+SHIFT+^ (CARET), the letter
ã, ñ, õÃ, Ñ, Õ | CTRL+SHIFT+~ (TILDE), the letter
ä, ë, ï, ö, ü, ÿ,Ä, Ë, Ï, Ö, Ü, Ÿ | CTRL+SHIFT+: (COLON), the letter
å, Å | CTRL+SHIFT+@, a or A
æ, Æ | CTRL+SHIFT+&, a or A
œ, Œ | CTRL+SHIFT+&, o or O
ç, Ç | CTRL+, (COMMA), c or C
ð, Ð | CTRL+' (APOSTROPHE), d or D
ø, Ø | CTRL+/, o or O
¿ | ALT+CTRL+SHIFT+?
¡ | ALT+CTRL+SHIFT+!
ß | CTRL+SHIFT+&, s

</body>
</html>
请问能否设置Rime达到同样的效果呢？例如按 <kbd>Ctrl+Shift+`</kbd>，再按<kbd>a</kbd>，上屏 à

**Comment by JeffChien** [comment]
有啊，你可是看一下倉頡的設定檔，裡面的
```yaml
punctuator:
  import_preset: symbols
recognizer:
  patterns:
    punct: '^/([0-9]0?|[A-Za-z]+)$'
```
就是了，斜線+字母有你要的. 符號表在安裝目錄的 symbols.yaml 裡面
