### ISSUE TITLE
不支持dvorak编码

### ISSUE THREAD

**Issue by gadmyth** [rime/home#134]
' , . ; 这四个符号被我认为是 dvorak 键盘下的码，但是 rime_get_api()->process_key 直接处理成了 symbol。

**Comment by chinanoahli** [comment]
是什么操作系统呢？

macos的话，只需要在输入法设置里保留dvorak就可以将所有其他语言的布局改为dvorak，linux也是一样。

win想要完美dvorak的话，可能需要启动到恢复模式下，用命令行将`%windir%\System32\kbddv.dll`（dvorak布局）与`kbdus.dll`（美式键盘布局）进行对调。

**Comment by lotem** [comment]
樓主對相關概念的認識有偏差。
Dvorak 是一種 *鍵盤佈局*（定義來自硬件的按鍵掃描碼到字符的映射），不是一種 *編碼*。鍵盤佈局通常是操作系統或硬件驅動程序實現的，`' , . ;` 是字符，已經經過了鍵位映射，Dvorak 鍵盤上也有這幾個字符，輸入法會正確地把他們處理爲符號。
