### ISSUE TITLE
鼠须管配置中含有 patch 的全部失效

### ISSUE THREAD

**Issue by zeekliu** [rime/home#1344]
修改配置文件时，凡是其中含有 `patch` 的配置无效。

例如，将候选字横向选择时，若写成这样：
```yaml
style:
  horizontal: true
```
则配置有效，但若写成这样：
```yaml
patch:
  style/horizontal: true
```
则无效。

手打、复制、不同的写法都试过，全部无效。

而且，调整每页的候选字数量的代码：`menu/page_size: 9`，不论以
```yaml
patch:
  menu/page_size: 9
```
还是
```yaml
menu:
  page_size: 9
```
都无法生效。

请问这样如何解决？

**Comment by mokapsing** [comment]
配置文件 是哪个文件？

**Comment by a0193143** [comment]
關於橫向選單
```yaml
patch:
  style/horizontal: true
```
才是正確
而
```yaml
style:
  horizontal: true
```
會把style下的預設全部取代只剩下 `horizontal: true`
先確認沒有改其它東西，不記得的話試試刪掉重裝

`menu/page_size: 9` 可能是輸入方案本身會覆寫預設設定，放在 `<方案>.custom.yaml` 可以生效

**Comment by Aoshisen** [comment]
> 關於橫向選單
> 
> ```yaml
> patch:
>   style/horizontal: true
> ```
> 
> 才是正確 而
> 
> ```yaml
> style:
>   horizontal: true
> ```
> 
> 會把style下的預設全部取代只剩下 `horizontal: true` 先確認沒有改其它東西，不記得的話試試刪掉重裝
> 
> `menu/page_size: 9` 可能是輸入方案本身會覆寫預設設定，放在 `<方案>.custom.yaml` 可以生效

<img width="569" alt="image" src="https://github.com/rime/home/assets/66982800/1af0ca05-7c6a-4dda-a952-c06df86954db">

**Comment by LEOYoon-Tsaw** [comment]
@wuzhengqiang 

https://github.com/rime/squirrel/wiki/squirrel.yaml-%E9%85%8D%E7%BD%AE%E6%8C%87%E5%8D%97
