### ISSUE TITLE
关于table_translator自动切分方案

### ISSUE THREAD

**Issue by yueduz** [rime/home#137]
正确的切分
------------------
nvme	de
那么	多
-----------------
不想要的切分，如果按全码切分就不会切出这样了
--------------
nv	mede
那	猫冬

所以，关于table_translator我的建议是不要自动造词，不要自动调频。
在全码和空码时自动切分，有重码时自动根据上下文来选择重码。

**Comment by yueduz** [comment]
形码重码不多,如果能根据上下文自动选择重码,我想那是比较靠普的

**Comment by yueduz** [comment]
补充一下,全码有重码时才自动根据上下文来选择重码。

**Comment by lotem** [comment]
還需要一些信息才能看懂給出的例子：
碼表是什麼樣的，兩種切分各用到那些詞、編碼分別是什麼？

**Comment by yueduz** [comment]
码表最长4码，单字和词语都是最长4码。单字有一二三级简码。

全码切分：比如“nvmede” 4码切分的话就是“nvme de”，优先满足前面的4码来切。
空码切分：但是如果输入到nvm就不能出字了，那么就从nv开始切就是nv mede。
全码时自动重码选择：比如“nvme dede”，“nvme”打出的是“那么”，“dede”打出的是”多多“和”朵朵“ ，那么根据上下文来选择是“朵朵"还是”多多“。

这样就只须要在有重码时造词了。

**Comment by lotem** [comment]
抱歉。我不太熟悉你的碼，所以不能完全理解這個問題。
所謂「全碼」「幾級簡碼」這只是編碼人意識範疇內的概念吧，碼表裏是沒有反映的。因此輸入法也是無法分辨這些類型的。

不要自動造詞的話，在方案裏設 `translator/enable_sentense: false`
不要調頻的話，設 `translator/enable_user_dict: false`
