### ISSUE TITLE
关于智能标点的建议

### ISSUE THREAD

**Issue by calmwaves111** [rime/home#1386]
目前有了一个数字后面的句号和冒号自动转半角，能否实现这样一个功能，连续两个全角就自动转为一个半角，大致实现思路是这样的，以逗号为例：
记录提交历史，在按下全角逗号时，如果上一个提交为全角逗号，那么发送一个退格键和一个半角逗号,

**Comment by eagleoflqj** [comment]
不符合least astonishment原则
