### ISSUE TITLE
小狼毫rime 浏览器 无法用网页快捷键

### ISSUE THREAD

**Issue by thomasTAT** [rime/home#1389]
比如 在youtube（油管）上，按f 没有反应，不能 full screen 
在比如在google(谷歌)搜索上，按/没有反应，不能聚焦到搜索栏。
瀏覽器 edge, chrome 都不行.

**Comment by CorvinYu** [comment]
我也遇见同样问题！寻求解答！
完全卸载后重新安装没有解决此问题。
似乎是15版本后出现的新问题，此问题在之前到版本没有出现。
我使用 win 11 22H2。

**Comment by fxliang** [comment]
0.16.1已解决这个问题，留意更新
