### ISSUE TITLE
你好，请问下，有没有办法关闭造词功能

### ISSUE THREAD

**Issue by lluvio** [rime/home#141]
看了下wiki 没有找到配置项...

**Comment by lluvio** [comment]
输入法为五笔
OS: macOS

**Comment by lotem** [comment]
有辦法。
`patch: { translator/enable_encoder: false }`

https://github.com/rime/rime-wubi/blob/master/wubi86.schema.yaml#L57

**Comment by lluvio** [comment]
感谢！
