### ISSUE TITLE
为何我ibus-rime中的定制没有产生效果？

### ISSUE THREAD

**Issue by hwypengsir** [rime/home#1423]
系统信息：
```
uname -a
Linux debian 5.10.0-22-amd64 #1 SMP Debian 5.10.178-3 (2023-04-22) x86_64 GNU/Linux
```
设置
```
cd  ~/.config/ibus
mkdir  rime
cd  rime
vim  default.custom.yaml
patch:
  menu:
    page_size: 10      
```             
重新启动后，候选词为何还是5个呢？

**Comment by hwypengsir** [comment]
已经解决。

**Comment by playasmegumin** [comment]
> 已经解决。

这是怎么解决的？能否询问详细细节？

**Comment by playasmegumin** [comment]
> > 已经解决。
> 
> 这是怎么解决的？能否询问详细细节？
> 
> 我参照同样的步骤进行设置（区别是当我设置的时候 ~/.config/ibus/rime 已经有对应的文件目录了），无论是通过rime的“部署”或是在命令行中重新启动ibus（ ibus restart 与 ibus-daemon -drx ）都没有办法使配置生效。
> 
> 我使用的是 luna_pinyin ，但即使我把配置文件改到 ~/.config/ibus/rime/build/luna_pinyin.custom.yaml 也无济于事。

已经解决。环境是Ubuntu 22.04。

应该主要是 ibus 的问题，只要 ibus restart 能够在无异常的状态下完成就可以正常实现重新部署。具体过程无法复现，可能它想开了就好了。
