### ISSUE TITLE
站酷网页的输入框监听了输入框 input 事件 , 中文就输入不了闪烁一下就没了, 只能输入符号和数字 想知道这是输入法原因还是网页的问题

### ISSUE THREAD

**Issue by wangz-code** [rime/home#1437]
比如 https://www.zcool.com.cn 站酷的搜索框

**Comment by mirtlecn** [comment]
![image](https://github.com/rime/home/assets/76689045/7ae9c38d-1f5a-443e-8cb5-9d5bca784a7f)

不过很早之前，我在 GitHub Doc 上碰到了这种情况，不晓得是不是你说的「闪烁一下就没了」，现在已经正常了

![246744003-ccec45c6-4561-40ee-b9ec-cf198bcd677f](https://github.com/rime/home/assets/76689045/388f3558-ab71-461c-bbfc-67d126dfd25a)

根据其他人的回复，搜狗输入法也有一样的问题。原因不明

**Comment by wangz-code** [comment]
> ![image](https://private-user-images.githubusercontent.com/76689045/292110486-7ae9c38d-1f5a-443e-8cb5-9d5bca784a7f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDMxNDQyMjMsIm5iZiI6MTcwMzE0MzkyMywicGF0aCI6Ii83NjY4OTA0NS8yOTIxMTA0ODYtN2FlOWMzOGQtMWY1YS00NDNlLThjYjUtOWQ1YmNhNzg0YTdmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMjElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjIxVDA3MzIwM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTZiODQwZWNlZTIxZTU3YzFiZTYzNWNkNWUxZTFhY2I1ZTVlOWZkMWY5MzMwN2Y4NWQ5MDY5NmIzODY3Y2I2NzYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.tAhSDlL8bdS1LG-K32R6gDUfodhEQL1YT4zz7NhCqIo)
> 
> 不过很早之前，我在 GitHub Doc 上碰到了这种情况，不晓得是不是你说的「闪烁一下就没了」，现在已经正常了
> 
> ![246744003-ccec45c6-4561-40ee-b9ec-cf198bcd677f](https://private-user-images.githubusercontent.com/76689045/292110941-388f3558-ab71-461c-bbfc-67d126dfd25a.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDMxNDQyMjMsIm5iZiI6MTcwMzE0MzkyMywicGF0aCI6Ii83NjY4OTA0NS8yOTIxMTA5NDEtMzg4ZjM1NTgtYWI3MS00NjFjLWJiZmMtNjdkMTI2ZGZkMjVhLmdpZj9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMjElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjIxVDA3MzIwM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTFkMGI3ZDAyNDIyZWFjMGNmNDBhZjRiMjVhMjY1ZDBlM2RmMTJjY2NiNDZiZTEzYjFiNWM3ODljODVjNDViOWUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.VVgBL7KXtCaa-fmVhR8ecMvg7RirhrmLfafFCk7OVZs) [ ![246744003-ccec45c6-4561-40ee-b9ec-cf198bcd677f](https://private-user-images.githubusercontent.com/76689045/292110941-388f3558-ab71-461c-bbfc-67d126dfd25a.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDMxNDQyMjMsIm5iZiI6MTcwMzE0MzkyMywicGF0aCI6Ii83NjY4OTA0NS8yOTIxMTA5NDEtMzg4ZjM1NTgtYWI3MS00NjFjLWJiZmMtNjdkMTI2ZGZkMjVhLmdpZj9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMjElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjIxVDA3MzIwM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTFkMGI3ZDAyNDIyZWFjMGNmNDBhZjRiMjVhMjY1ZDBlM2RmMTJjY2NiNDZiZTEzYjFiNWM3ODljODVjNDViOWUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.VVgBL7KXtCaa-fmVhR8ecMvg7RirhrmLfafFCk7OVZs) ](https://private-user-images.githubusercontent.com/76689045/292110941-388f3558-ab71-461c-bbfc-67d126dfd25a.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDMxNDQyMjMsIm5iZiI6MTcwMzE0MzkyMywicGF0aCI6Ii83NjY4OTA0NS8yOTIxMTA5NDEtMzg4ZjM1NTgtYWI3MS00NjFjLWJiZmMtNjdkMTI2ZGZkMjVhLmdpZj9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMjElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjIxVDA3MzIwM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTFkMGI3ZDAyNDIyZWFjMGNmNDBhZjRiMjVhMjY1ZDBlM2RmMTJjY2NiNDZiZTEzYjFiNWM3ODljODVjNDViOWUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.VVgBL7KXtCaa-fmVhR8ecMvg7RirhrmLfafFCk7OVZs) [ ](https://private-user-images.githubusercontent.com/76689045/292110941-388f3558-ab71-461c-bbfc-67d126dfd25a.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDMxNDQyMjMsIm5iZiI6MTcwMzE0MzkyMywicGF0aCI6Ii83NjY4OTA0NS8yOTIxMTA5NDEtMzg4ZjM1NTgtYWI3MS00NjFjLWJiZmMtNjdkMTI2ZGZkMjVhLmdpZj9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMjElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjIxVDA3MzIwM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTFkMGI3ZDAyNDIyZWFjMGNmNDBhZjRiMjVhMjY1ZDBlM2RmMTJjY2NiNDZiZTEzYjFiNWM3ODljODVjNDViOWUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.VVgBL7KXtCaa-fmVhR8ecMvg7RirhrmLfafFCk7OVZs)
> 
> 根据其他人的回复，搜狗输入法也有一样的问题。原因不明


https://github.com/rime/home/assets/8155037/fb52d544-b9ab-4599-837d-4c031af95240

谢谢 估计是网页的问题,  目前我的解决方案就是先随便输入一个字符, 然后再输入内容
