### ISSUE TITLE
词库中包含#井号而被当成注释无法显示在候选项中

### ISSUE THREAD

**Issue by zerobikappa** [rime/home#144]
例子1：想连续输入两个字母来打出符号，在词库中加入：
（       zd       999996
）       zd       999995
！       zf        999999
@       zf        999998
＃        zf        999997
￥       zf        999996
%        zf       999995
？       zs       999999
：       zs       999998
（上面的井号我用了全角的井号，如果是半角的井号的话无法在这里正常显示）

例子2：做一个颜文字词库，在词库中加入：
ヾ(≧へ≦)〃      ze      999992
（＿´Д｀）      ze      999991
(*/ω＼*)        zq      999999
(/·ω·)/           zq      999998
ヽ( #`Д´)ﾉ      zw      999995

发现有井号的那一行被当成注释，无法在候选项中显示
例子2的情况，如果井号前有一个空格，那么井号后的内容会被当成注释，只要井号前有一个符号就没问题。把ヽ(  #`Д´)ﾉ改成ヽ(#`Д´)ﾉ这我还是能接受的。
但例子1的情况，还真是找不到解决的方法。这种情况可以怎么解决？

**Comment by lotem** [comment]
這樣寫：
```yaml
# no comment
#    ++++
```

**Comment by zerobikappa** [comment]
谢谢，成功搞定了，原来是在有井号那一行上方加一行# no comment，声明这一行不是注释，这样就能正常读取了。

！ zf 999999
@ zf 999998
＃ no comment
＃ zf 999997
￥ zf 999996
% zf 999995
？ zs 999999

**Comment by lotem** [comment]
補充說明：`# no comment` 不只針對緊接着的一行，下文所有 `#` 開頭的文本行都不再當作註釋。
