### ISSUE TITLE
每天都有 rime.im 访问互联网的网络记录，请问是在做什么，为什么要联网。

### ISSUE THREAD

**Issue by leyle** [rime/home#1443]
偶然发现的。
每天都有网络请求。

请问这个为什么要联网。做了什么事。是否可以在什么地方关闭了。

平台 macOS
软件 鼠须管

<img width="489" alt="image" src="https://github.com/rime/home/assets/1290013/fe31813a-cfed-4f84-afdb-82b2ceb8d1a2">

**Comment by lotem** [comment]
這個是檢查軟件版本更新的。

第一次檢查之前應當彈出對話框詢問過，如果用戶同意了檢查新版本，以後就會自動聯網檢查~

之後可以通過以下命令關閉：

```
defaults write im.rime.inputmethod.Squirrel SUEnableAutomaticChecks -bool false
```

**Comment by leyle** [comment]
> 這個是檢查軟件版本更新的。
> 
> 第一次檢查之前應當彈出對話框詢問過，如果用戶同意了檢查新版本，以後就會自動聯網檢查~
> 
> 之後可以通過以下命令關閉：
> 
> ```
> defaults write im.rime.inputmethod.Squirrel SUEnableAutomaticChecks -bool false
> ```

好的，谢谢。
