### ISSUE TITLE
自定义背景图片

### ISSUE THREAD

**Issue by hjkl01** [rime/home#1449]

**Comment by hjkl01** [comment]
可否添加 配置皮肤时 自定义背景图片

**Comment by LEOYoon-Tsaw** [comment]
圖片背景到底是幾個意思呢？候選框大小一直在變，圖片是直接裁切？還是拉伸？還是用AI自動填補？反正我是想不出來

**Comment by hjkl01** [comment]
我的需求是在练习双拼的时候可以把对应的键位图片显示出来。至于适配选择框，我认为皮肤作者们可以自行适配。

**Comment by LEOYoon-Tsaw** [comment]
那你自己做吧
