### ISSUE TITLE
个人词库突然改变

### ISSUE THREAD

**Issue by Neur1n** [rime/home#145]
系统是Windows 7，平时基本上只用朙月拼音打字，默认使用简体输出（不是朙月拼音·简体字），只有极少数时候使用五笔画或者粤音。今天词库感觉突然改变了，主要体现在：
1. 一开始用繁体输出“嗰”`ge`，然后切换回简体，会有“嗰”和“𠮶”两个结果，平时只用“嗰”，但是今天在简体输出时突然没了，繁体输出还是第一候选；
2. 之前用可以用`ze`输出“啫”，现在只能用`zhe`；
3. 之前`yeguai`第一个候选结果是“野怪”，现在成了“斜谷”；
4. “啩”`gua`字之前也是上了候选前列的，但是现在没有了。

但是这几个拼音这段时间很少用。
谢谢！

**Comment by lotem** [comment]
是不是配置了字符集過濾器，導致某些情況下第一個候選被過濾掉了。
看第三例：「斜谷」的註音是 yegu （且不論對錯），即只匹配輸入的前一部分。yeguai 預設詞典沒有對應的詞，按說要不然拆成單字自動組詞，我這裏是「也怪」，要不然檢索用戶自造詞如「野怪」，斷然不會沒有完全匹配該拼音的候選。所以推斷唯一一個與輸入完全匹配的候選被過濾掉了。

我建議 script_translator 不與字符集過濾功能一同使用。

**Comment by Neur1n** [comment]
谢谢回复。我查看了配置文件`luna_pinyin.schema.yaml`，`translator`和`filter`都是默认设置。关于上述第一个例子，也许是我少用所以记错了，因为简体输出应该不会有繁体候选。至于其他两个案例，我也没能测出受什么影响。

**Comment by lotem** [comment]
鑑於沒有更多線索及重現步驟，就此結案。

**Comment by xiaoqun2016** [comment]
如果用的是小狼毫，用户词典偶尔会丢失。更新rime.dll会不会解决？
类似的案例：  
http://tieba.baidu.com/p/3198174675
https://wapp.baidu.com/f?kz=4028878863&pn=0&
