### ISSUE TITLE
可不可以添加一个v的功能键，实现简单地数学加减法功能，这个真的很好用

### ISSUE THREAD

**Issue by Franklyn1987** [rime/home#1451]
能不能完善一下，添加一个v功能，可以计算加减法，用tab也能进行翻页，上下选择，就是百度输入法可以做的事情，咱们能不能也可以啊，这样就太完美了。

**Comment by mokapsing** [comment]
用lua可以实现，已经有人用上这种功能了
参考
https://github.com/hchunhui/librime-lua/wiki
https://github.com/shewer/librime-lua-script
