### ISSUE TITLE
Arm 架構的Win11，無法執行

### ISSUE THREAD

**Issue by xinghui1011** [rime/home#1456]
在M1系列上，使用Parallels Desktop安裝Arm架構的Win11，並且安裝小狼毫輸入法0.15.0.0版。
安裝完成正後，打字出來只有英文。切換其他輸入法之後，就無法再換回小狼毫輸入法。
請問其他人有遇過這個問題嗎？

**Comment by sd0116baka** [comment]
我也遇到了这个问题，应该是小狼毫没有支持arm架构的原因。

**Comment by fxliang** [comment]
> 我也遇到了这个问题，应该是小狼毫没有支持arm架构的原因。

最新的nightly  已有支持，正式版下次发版就会有了

**Comment by sd0116baka** [comment]
好的，谢谢解答，那我就继续耐心等待正式版吧

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________
