### ISSUE TITLE
请求增加HTTPS访问

### ISSUE THREAD

**Issue by RichardLiles** [rime/home#146]
开发者您好！
  经过我长期观察，大陆的网络路由有故意拖缓境外服务器的链接速度，从这一点上可以佐证出任何非加密的HTTP流量在这种网络环境中有被篡改的可能；特别输入法是进入网络世界的第一款工具之一，对于维权活动人士来说安全问题是很重要的，为避免rime windows用户在浏览器下载时受到APT攻击。在此我在这里有两点建议：1.增加主站，下载点强制SSL访问 2.对所发布的二进制文件公布高强度hash散列(非md5)。
   相信有和我一样关注的互联网用户，希望核心开发者们采纳！

**Comment by RichardLiles** [comment]
很多年前我已经开始使用rime了，以往在大陆下载rime不会受到限制，如今好像在大陆下载rime有些困难。（可能与地区有关）如果真是这样,大陆政府可能认为使用rime的是非普通用户。

**Comment by RichardLiles** [comment]
这里 https://letsencrypt.org/ 可以向作者提供一下，它背后包括了很多权威互联网安全群体，并且它不收费。Chrome,Firefox，IE都可以很好的兼容！

**Comment by RichardLiles** [comment]
经过一段时间观察，任何地区的境外服务器都有受到不同程度的流量干扰。现在下载小狼毫只能翻墙了，请问大家用windows有没类似情况？

**Comment by lotem** [comment]
好問題。
Rime 主頁架設在 Github Pages，因其使用自定義域名時不支持 HTTPS 協議，所以訪問 rime.im 用的是 HTTP 協議。
可以考慮把下載頁的內容搬運到 https://github.com/rime/home/wiki/Downloads

**Comment by lotem** [comment]
不太瞭解樓主的處境。

不過我是覺得這種經常需要更新的頁面適合直接用 GitHub 發佈，比更新網站方便。
當時還沒有 Releases 板塊。

**Comment by lotem** [comment]
Fixed via https://github.com/rime/rime.github.io/issues/7
