### ISSUE TITLE
请问下鼠须管是如何加载词典文件*.dict.yaml的？

### ISSUE THREAD

**Issue by jervainy** [rime/home#1468]
**测试的現象(所有的操作都在`~/Library/Rime`目录下)：**
初始目录如下
![](https://s2.loli.net/2024/01/30/tKESBX2ioZevsMW.png)  

我新建了一个luna_pinyin.dict.yaml词典文件，内容如下:  
```
# luna_pinyin
---
name: luna_pinyin
version: "1"
sort: by_weight
...

龍的傳人	a	100
```
新建了default.custom.yaml文件，内容如下:
```
patch:
  translator:
    dictionary: luna_pinyin
```
之后输入a，正常提示，当我将luna_pinyin.dict.yaml重命名为rime.dict.yaml后重载在次键入a，此时没有词典候选了；

**猜测**
是不是只有<方案名>.dict.yaml的词典文件才会被加载?

**Comment by eagleoflqj** [comment]
不要往default.custom.yaml放tranalator的配置，那个应该放在 方案名.custom.yaml
你之前输入a成功是因为，你的 luna_pinyin.dict.yaml 比共享目录的同名文件，而这个名字被共享目录里的 luna_pinyin.schema.yaml引 用。你改了名就引用不了了。
并没有字典名必须与方案名一样一说，完全看你的 方案名.schema.yaml 里引用了哪个字典。
