### ISSUE TITLE
小狼毫--小鹤双拼，无法打出shufu：舒服，请教解决方案

### ISSUE THREAD

**Issue by plainee** [rime/home#1471]
小狼毫--小鹤双拼，无法打出shufu：舒服，请教解决方案，换其他简拼可以打出，就小鹤双拼打不出，用的官方那个方案的yaml。
![image](https://github.com/rime/home/assets/54027179/4f9dc8e6-26d7-405a-921a-1732396ccf6b)

**Comment by mokapsing** [comment]
那你是不是找错地方了

**Comment by CaicoLeung** [comment]
<img width="325" alt="image" src="https://github.com/rime/home/assets/36806569/cb1fce80-5bab-4f31-a4f8-c72e2a535706">

**Comment by lotem** [comment]
可能是缺詞或者註音錯誤。
解決方案：可以自己造詞。

**Comment by plainee** [comment]
解决了，自己造了一个舒服

**Comment by plainee** [comment]
> 可能是缺詞或者註音錯誤。 解決方案：可以自己造詞。

谢谢，已解决，手动添加了
