### ISSUE TITLE
大家好，请问配置文件一定要这么多个吗，请问可以整合成一个 yaml 文件吗？

### ISSUE THREAD

**Issue by luxuxl** [rime/home#1489]
这是我查到的有关文档中的说明
- 〔全局设定〕 default.yaml
- 〔发行版设定〕 weasel.yaml
- 〔预设输入方案〕 <方案标识>.schema.yaml

我只想将我的配置写在一个 yaml 文件中，请问我该怎么操作？

**Comment by luxuxl** [comment]
此外，我没看懂文档里写的关于配置文件路径的部分，如下图
<img width="944" alt="image" src="https://github.com/rime/home/assets/111971103/5d441cd9-98ff-4409-820e-d44acbade69e">

我这个路径下并没有这些配置文件，而是要进入一个 `build` 文件夹，这里才有，我不确定能否修改他们

**Comment by LEOYoon-Tsaw** [comment]
第一個問題：不能
第二個問題：不要動build/，沒有文件就建一個custom

**Comment by luxuxl** [comment]
> 第一個問題：不能 第二個問題：不要動build/，沒有文件就建一個custom

多谢
