### ISSUE TITLE
MacOs下切換輸入法時會自動切換爲繁體

### ISSUE THREAD

**Issue by hxaohan** [rime/home#149]
當前輸入法爲鼠鬚管時，設置爲簡體，之後從系統英文鍵盤用cmd+space切換回來後又自動變成繁體了。
系統：10.12.4
版本：0.9.26.1

**Comment by lotem** [comment]
按 `` Control+` `` 鍵，從方案選單裏選擇「漢字→汉字」。
注意：快捷键（`Control+Shift+4`）做的是临时切换，即只对当前输入窗口有效，不保存状态。

**Comment by hxaohan** [comment]
仍然没解决，卸载重装恢复了，想来不知道是用图形化配置工具误点了哪里。
