### ISSUE TITLE
【功能请求】Windows的“开关键盘逻辑”默认为“切换中英文”

### ISSUE THREAD

**Issue by hzinchengdu** [rime/home#1498]
【功能请求】
Windows的“Ctrl+Space开关键盘逻辑”默认为“切换中英文”

或者

1. Windows可配置的“开关键盘逻辑为切换中英文”；
2. Windows可配置的“开关输入法全局一致，类似于global ascii: true”；
3. Windows可配置的“关闭输入法时：‘上屏正在输入的字母序列’或‘清除未上屏内容’”。

原因：
1. 所有的大众输入法在大众看来没有“开启/关闭输入法”的概念；
2. 所有的大众输入法都可配置“上屏正在输入的字母序列”或“清除未上屏内容”；
3. 现代Windows系统默认所有窗口使用相同的输入法状态（看见测试版已实现global ascii: true）。

希望实现和大众输入法相同的功能，目前有位开发者在[fork版](https://github.com/zhylmzr/weasel)上实现了（[在我的请求下](https://github.com/zhylmzr/weasel/issues/1)），这位开发者也贡献了global ascii的相关代码。

**Comment by iTomxy** [comment]
2024.10.7 升级到 0.16.3，现在 ctrl + space 默认是切换中英文了，那么怎么将此组合健换回原先的禁用输入法呢？vscode 中要用 ctrl + grave 呼出命令行，而 ctrl + grave 又是 rime 呼出设置界面的组合健，冲突了。所以我想将 ctrl + space 恢复回禁用输入法，要怎么设置呢？

**Comment by fxliang** [comment]
> 2024.10.7 升级到 0.16.3，现在 ctrl + space 默认是切换中英文了，那么怎么将此组合健换回原先的禁用输入法呢？
> 
> vscode 中要用 ctrl + grave 呼出命令行，而 ctrl + grave 又是 rime 呼出设置界面的组合健，冲突了。以前的解决方案是：在 vscode 中先用 ctrl + space 禁用输入法，再用 ctrl + grave 呼出命令行。
> 
> 所以我想将 ctrl + space 恢复回禁用输入法，要怎么设置呢？

看0.16.2的更新日志里有方法
