### ISSUE TITLE
設置「Shift+字母」，沒有效果！

### ISSUE THREAD

**Issue by zaqzrh** [rime/home#15]
把「Shift+字母」設置功能按鍵，沒有效果！
例如我想「Shift+j或J」當作Escape，如下設置都不行：
    - { when: composing, accept: Shift+j, send: Escape }
    - { when: composing, accept: Shift+J, send: Escape }
請問Shift不能獨立使用嗎？

**Comment by jakwings** [comment]
似乎是和输入大写字母「J」冲突了，建议用其它组合，我用的是 `Control+[`：

    - {accept: 'Control+bracketleft', send: Escape, when: composing}

也好像没有好的解决方法。Shift 和非普通字符键，如 Tab，还是合得来的。

**Comment by lotem** [comment]
`recognizer/patterns:` 有一條規則匹配大寫字母開頭的英文單詞
而明月拼音方案裏 `recognizer` 在 `key_binder` 之前

**Comment by zaqzrh** [comment]
@lotem 不明白怎麼寫，能按一樓寫個例子嗎？

**Comment by lotem** [comment]
@zaqzrh 只要寫 `J` 就好，不用 `Shift+J`——這不是重點
重點是，按鍵處理器是有先後順序的，大寫字母先被 `recognizer` 匹配到了

**Comment by zaqzrh** [comment]
@lotem 那一樓例子recognizer的表達式如何寫？

**Comment by lotem** [comment]
@zaqzrh 寫不出來。因爲這兩個功能是衝突的，無法共存。
要把大寫字母移作他用 ，只能禁止 recognizer 對英文單詞做模式匹配——這是通過 `recognizer/import_preset: default` 引進的。得把這一項設置拆掉，或者把 `recognizer` 拆掉。
