### ISSUE TITLE
找不到simplifier组件的详细使用文档

### ISSUE THREAD

**Issue by zerobikappa** [rime/home#150]
我是用linux ibus的rime的。正在做一个日语输入法，尝试用simplifier组件切换平假名和片假名。
看过雪斋的文档-设定项速查手册，在系统里找不到相关的simplifier组件的文件。另外也找不到有关simplifier组件的详细使用文档。
有没有这个组件的详细用法说明？

**Comment by lotem** [comment]
這個組件包裝了「開放中文轉換」庫。該項目的主頁有更詳細的介紹：
https://github.com/byvoid/opencc

**Comment by zerobikappa** [comment]
根据「在Rime五筆輸入方案中添加繁體輸出」 https://gist.github.com/gkzhong/3467172
的思路，配置一个平假名==》片假名的映射码表。opencc里用的是 .ocd 格式的码表，这个要怎么用txt的码表转换来？ 源txt码表要求用怎样的格式和编码？ （我是用linux系统的）

**Comment by lotem** [comment]
就你所問，該項目的主頁有更詳細的介紹：
https://github.com/byvoid/opencc
如果詞典不大，用文本文件也可以。
使用 ini 格式配置文件的是 opencc 0.4.x 版本。後來的版本改用 json 格式了。請首先確認文件格式與版本匹配。
如果會看 coredump 文件，通過調用棧定位到出錯的代碼位置，事情就簡單了。
否則從經驗看，程序出錯的一個可能是使用錯誤的配置文件或無法訪問到詞典文件。

**Comment by zerobikappa** [comment]
已经解决问题。重装一次opencc之后可以正确制作.ocd词库了。

**Comment by zerobikappa** [comment]
close #150
