### ISSUE TITLE
請問使用小鶴雙拼如何輸出臺灣正體？

### ISSUE THREAD

**Issue by as255287** [rime/home#151]
請問使用小鶴雙拼如何輸出臺灣正體？
目前使用的輸出爲繁體沒錯，但是並不是臺灣正體。
例如：
爲 為
着 著
裏 裡
羣 群

**Comment by osfans** [comment]
參考這裏：
https://github.com/rime/rime-luna-pinyin/blob/master/luna_pinyin_tw.schema.yaml#L83

**Comment by as255287** [comment]
您好：我有在double_pinyin_flypy.schema 裏面做了這樣的設定，
但是至要按Ctrl+Space 切換輸入法再切回來又會是一樣的狀況了，請問蓋如何解決。
感謝您。

**Comment by zzz67240** [comment]
FYI
https://gist.github.com/zzz67240/fa920d255d56b9fa310e4f0864e22a29

**Comment by imper0502** [comment]
這是我的設定檔，除了輸出正體外，還增加了注音的外觀。
yin 除了可以打 YB 之外，打YF也可以。（符合注音的習慣）
ying 除了可以打 YK 之外，打YG也可以。（符合注音的習慣）
https://gist.github.com/imper0502/ff63da3b8d006ef9646ed7f74a1204cc

**Comment by imper0502** [comment]
> 請問使用小鶴雙拼如何輸出臺灣正體？
> 目前使用的輸出爲繁體沒錯，但是並不是臺灣正體。
> 例如：
> 爲 為
> 着 著
> 裏 裡
> 羣 群

開兩個 opencc 轉換可以完全解決這個問題：

switches:
  - name: ascii_mode
    reset: 0
    states: [ "中", "En" ]
  - name: full_shape
    reset: 0
    states: [ "半形", "全形" ]
  - name: ascii_punct
    reset: 0
    states: [ "。，", "．，" ]
  - name: s2tw                  # 簡繁轉換
    reset: 1
#    states: [ "簡化字", "標準字" ]
  - name: t2tw                  # 正繁轉換
#    states: [ "傳承字", "標準字" ]
    reset: 1
    
engine/filters:
    - simplifier@s2tw  # 簡繁轉換
    - simplifier@t2tw  # 正繁轉換
    - uniquifier  　　　# 過濾重複的候選字，有可能來自正繁簡轉換
    - cjk_minifier

s2tw: # 簡繁轉換
  option_name: s2tw
  opencc_config: s2tw.json
  tips: none
t2tw: # 正繁轉換
  option_name: t2tw
  opencc_config: t2tw.json
  tips: none
