### ISSUE TITLE
Squirrel crashed? 

### ISSUE THREAD

**Issue by xerothermic** [rime/home#1510]
Hi, I'm facing issue when trying to customize the Squirrel input method.

I built the Squirrel.pkg from the source (277ebfa4c3efa8afaac61e4e8036842369ff960e) and installed it. 

I was able to install it and launch the default squirrel input method, but when I tried to customize (by adding the hello.schema.yaml) example, I didn't get the new input selection when I pressed ctrl+`.

Also, in the Console app, I'm seeing squirrel crash report: https://justpaste.it/eqznr

The logs also seemed truncated: [rime.log.zip](https://github.com/rime/home/files/14820412/rime.log.zip)

Can someone please suggest what I did wrong?

**Comment by ksqsf** [comment]
Hi, could you please provide the `hello.schema.yaml` file? The crash seems to be related to librime.

**Comment by ksqsf** [comment]
Just a guess: did you build Squirrel manually before? If so, please make sure your local librime submodule checkout is Squirrel's specified version. You can do so by `git submodule update`/

**Comment by xerothermic** [comment]
Thanks for the reply! Let me try to verify the librime submodule version and share the copy of hello.schema.yaml tomorrow once I have access to my computer again.

**Comment by ksqsf** [comment]
It turns out that previously there was a version mismatch in squirrel's build scripts `action-build.sh` and `action-install.sh`, which may result in crashes with similar backtraces to yours. This has been fixed.

BTW, we have nightly builds now (https://github.com/rime/squirrel/releases/tag/latest), so you no longer need to build squirrel manually for latest features.

**Comment by xerothermic** [comment]
This is great! Let me try out the nightly build now.

**Comment by xerothermic** [comment]
Yes, the new nightly builds works better, and I'm able to customize the input method and redeploy.
