### ISSUE TITLE
为何无法使用自己造的词库？

### ISSUE THREAD

**Issue by hwypengsir** [rime/home#1524]
我按照网页的提示  https://gist.github.com/lotem/5443073#file-luna_pinyin-kunki-dict-yaml.

设置 luna_pinyin.custom.yaml

```
 cat   luna_pinyin.custom.yaml
# encoding: utf-8
patch:
  translator/dictionary: luna_pinyin.my
```

自定义词库文件的设置：

```
cat  luna_pinyin.my.dict.yaml
# Rime dictionary
# encoding: utf-8

---
name: luna_pinyin.my
version: "2013.04.23"
sort: by_weight
use_preset_vocabulary: true
# 從 luna_pinyin.dict.yaml 導入包含單字的碼表
import_tables:
  - luna_pinyin
...

# table begins

# 自定義的詞條

钕载	nv zai 100
```
设置完成后，重新部署，并重启了电脑。

![输入](https://github.com/rime/home/assets/512610/3ac9ac4c-4f21-4b83-8197-6b16c9f903d0)

我输入  "nv zai"，并没有显示  钕载。
请问，为何无法使用自己造的词库？

**Comment by ksqsf** [comment]
```
钕载	nv zai 100
```
编码和权重之间也应该使用 tab 符分开。
