### ISSUE TITLE
使用双拼时使用shift+enter经过变换过的输入码,可以不加空格吗？

### ISSUE THREAD

**Issue by shanghaox** [rime/home#1529]
例如：输入vihu，shift+enter输出zhihu。而实际情况是输出zhi hu。
我希望能把shift+enter设为没有空格，各位大佬有办法吗？

**Comment by lotem** [comment]
我感覺這樣打的使用場景不多……

你有兩種選擇：

提交輸入碼（按原文打 `zhihu` 進去，回車）；
提交輸入碼的回顯形式，顯示成啥樣上屏就是啥樣，所以得改改 `translator/preedit_format` 把空格刪掉。根據使用場景。可能還要轉換一下拼音字母 ü。

**Comment by shanghaox** [comment]
收到，感谢
