### ISSUE TITLE
rime配置文件使用了何种语法？

### ISSUE THREAD

**Issue by hwypengsir** [rime/home#1531]
rime配置文件以yaml结尾，当然使用了yaml语法，可以这样的东西也是yaml语法吗？
` derive/([aei])n$/$1ng/ `
这是专门的脚本语言吗？lua的语法吗？

**Comment by lotem** [comment]
> derive/([aei])n$/$1ng/

這是一條 YAML 字符串，字符串的內容是 RIME 自定義的格式，詳見 [拼寫運算](https://github.com/rime/home/wiki/SpellingAlgebra#%E6%8B%BC%E5%AF%AB%E9%81%8B%E7%AE%97%E7%9A%84%E7%AE%97%E5%BC%8F)
