### ISSUE TITLE
如何删除快捷键?

### ISSUE THREAD

**Issue by JunnanZ** [rime/home#154]
不好意思，我找了半天也没找到该怎么删除(unbind)快捷键，求教～
比如我不想要"ctrl+."切换中英标点，该如何设置呢？
多谢！

**Comment by Voleking** [comment]
将 default.yaml 文件中定义的快捷键复制进 default.custom.yaml 文件中，注释掉想删除的快捷键设置。

**Comment by JunnanZ** [comment]
这样好像不行。不过我直接把default.yaml里的相关行注释掉好了。。

**Comment by Voleking** [comment]
@JunnanZ 不建议在 default.yaml 中改，可以参考我的 default.custom.yaml
[default.custom.yaml.txt](https://github.com/rime/home/files/2409574/default.custom.yaml.txt)
