### ISSUE TITLE
有个特定的字“㨃”打不出来，即使是关掉了所有的 engine/filters 之后

### ISSUE THREAD

**Issue by tankb52** [rime/home#1540]
**上报前请检查**
- [√] 我遇到的问题没有其他人在 issue 里提到过
- [√] 我的小狼毫版本于 rime/weasel 下载
- [√] 我在使用小狼毫的最新发布版本

- OS 详细版本: Windows 11 22H2 22631.3447, Debian GNU/Linux trixie, 手机 荣耀 MagicOS 7.0，android 12.
 - 小狼毫版本:  0.15.0.0 
 - fcitx5 版本：fcitx5: 5.1.7
 - fcitx5-rime_version: 1.10.0
 - fcitx5-android : 0.0.9-0-g8dc51356, 
 - fcitx5-android-rime : 0.0.9-0-g8dc51356
 
**描述遇到的问题**
码表中存在这个“㨃”字的编码，分别是 okhv，okhi，但是打编码后，不显示这个字，和这个字相同编码的其它字能正常打出来。

**复现步骤**
重现问题的步骤，如：
1. 检查码表中这个字是否存在和其编码：㨃  okhv， 㨃 okhi
2. 在任意编辑框中打出编码。
3. 检查输入法出现的候选字。
4. 没有出现这个“㨃”字，但和这个字相同编码的其它字能正常打出来。
5. 尝试过其它操作如下

> 5.1. 换成哲豆0501的新码表，依然打不出来。
> 5.2.1 从码表里面删除这个字→部署，每次部署时都先将build中的文件清空；
> 5.2.2 再修改码表，添加这个字和另外一个字，都使用okhv编码→部署。
> 5.2.3 能打出新加的字，但仍然打不出“㨃”字。
> 5.2.4 在码表中为这个字新造一个词如“㨃人”，依然打不出来。
> 5.2.5 把“㨃”加入到用户词库user_dict.txt 里面，能打出来。
> 5.2.6 关掉所有的 engine/filters 之后，并检查build出来的配置文件中不存在engine/filters 选项，仍然打不出来。

6. 通过命令把 rime 码表转换成 fcitx5 原生码表，用 fcitx5 也能打出来。
7. 在 windows 11 下面的小狼毫也打不出来，用多多编制的输入法程序也能打出来。
8. 安卓手机 fcitx5 能打出来；fcitx5-rime 打不出来，加入到用户词库user_dict.txt 里面，能打出来

**用户文件**
我使用的配置和码表文件已经上传到以下仓库   
[https://github.com/tankb52/rime-zzdyx] (https://github.com/tankb52/rime-zzdyx)    

![ksnip_20240502-140757](https://github.com/rime/home/assets/10082492/5051510d-b798-4183-baca-579c41b997c5)

**Comment by fxliang** [comment]
![Screenshot_20240502_165723](https://github.com/rime/home/assets/4023160/51e2c033-5b48-46ea-84a8-f8794520fa89)

**Comment by tankb52** [comment]
我也说过有几种情况下我能打出这个字来

但rime里面打不出来，我想知道是不是rime里面哪个配置出问题了吗？ 

 (https://github.com/tankb52/rime-zzdyx)
这个配置已经是我精简过后的了，我尝试过把engine/filters 全部删除了也打不出这个字“㨃”来。

**Comment by tankb52** [comment]
谢谢，我自己找到原因了，  translator/enable_charset_filter 这一项我填成了true，导致这个字被过滤了。改成false之后就能打出“㨃” 了。

**Comment by tankb52** [comment]
问题可以关闭了。

> 谢谢，我自己找到原因了， translator/enable_charset_filter 这一项我填成了true，导致这个字被过滤了。改成false之后就能打出“㨃” 了。

问题关闭。
