### ISSUE TITLE
关于皮肤的想法

### ISSUE THREAD

**Issue by jzliming** [rime/home#1541]
现在开发的皮肤比较少，和别的输入法比，皮肤的多样性是弱项，都是基于别的皮肤改的，改的时候，效率非常低能不能开发一个皮肤设计软件，搞一套标准，这样可用的皮肤会爆发式增长。

**Comment by LEOYoon-Tsaw** [comment]
有啊，我做了一個 Squirrel Designer

**Comment by jzliming** [comment]
说的是同文

**Comment by eagleoflqj** [comment]
同文不是官方前端，去trime仓库问效果更好
