### ISSUE TITLE
Failed to extract update

### ISSUE THREAD

**Issue by yepengfan** [rime/home#1543]
Hi there,

I am running 0.16 on my laptop and recently received version 0.18. While updating, it fails with the following message. Please let me know if it could be resolved. Thanks!

![image](https://github.com/rime/home/assets/7143356/5fb78aa1-7e7d-4c74-8cdc-e8a969a38cdf)

**Comment by donnior** [comment]
+1

**Comment by MiyamoriGithub** [comment]
I'm having the same problem, maybe you can try downloading the installer from [https://rime.im](https://rime.im )and installing the update

**Comment by LEOYoon-Tsaw** [comment]
Yes, there's a problem with check for update. while we are fixing it, if you don't want to wait, please download latest from rime.im or the releases here on GitHub.

**Comment by LEOYoon-Tsaw** [comment]
Should be fixed now
