### ISSUE TITLE
咨询一下 log 中的用词含义

### ISSUE THREAD

**Issue by Parantric** [rime/home#1553]
![Snipaste_2024-05-12_23-12-17](https://github.com/rime/home/assets/104410710/0479a1a1-886a-4577-bf27-c8c513781d3d)

`invalid entry definition at #1006806.`
这个 「1006806」是什么意思？我看每行最开始的时间戳，E 开始的应该是 Error W 开始的应该是 Warring.

**Comment by lotem** [comment]
是說碼表中第幾條記錄無效。
權重那個字段的數值無法解析會打印這條日誌。

**Comment by Parantric** [comment]
> 是說碼表中第幾條記錄無效。 權重那個字段的數值無法解析會打印這條日誌。

好的，谢谢告知。请问，那个权重的最大设定是多少（最大支持几位数）？我看我那个出问题的扩展词库，每个词条后面不是都带有权重数字，还有的设置的很大，权重位数很多。

**Comment by lotem** [comment]
找到第 1006806 個詞條看看吧

**Comment by Parantric** [comment]
> 1006806

我看了，词条的添加格式是没问题的，我是从「https://github.com/ssnhd/rime/blob/master/%E9%85%8D%E7%BD%AE%E6%96%87%E4%BB%B6/luna_pinyin.sogou.dict.yaml」这个仓库中下载的该词库文件，但是我放到我的输入法配置目录，然后编译，输入法就不能用。然后看日志，就是截图的那种了，不知道具体缘由。
![image](https://github.com/rime/home/assets/104410710/dbbc84bb-09f8-41d1-8ac7-c42e2687f53f)
这是「1006806 」行的词条，那个格式看上去是没有 tab 分割，其实有，在截图右下角选中搜索是可以显示 tab 的。

**Comment by lotem** [comment]
是碼表中第 1006806 條記錄，不是文件的第 1006806 行。

**Comment by Parantric** [comment]
> 是码表中第 1006806 条记录，不是文件的第 1006806 行。

😂 码表 是哪个文件？我不知道啊

**Comment by lotem** [comment]
如果只有這一個 `.dict.yaml` 文件，那就是這個文件去除文件頭部 YAML 配置、去除註釋行之後的行數。
如果詞典引用了其他 `.dict.yaml` 文件，行數還要累加計算。

簡單辦：加了哪個文件出錯，就不加他。

**Comment by Parantric** [comment]
> 如果只有这一个 `.dict.yaml` 文件，那就是这个文件去除文件头部 YAML 配置、去除注释行之后的行数。 如果词典引用了其他 `.dict.yaml` 文件，行数还要累加计算。
> 
> 简单办：加了哪个文件出错，就不加他。

好的，谢谢。扩展一个词库，词库也是从别的仓库下载的，感觉人家都用，应该没问题。我先用简单的排除法吧。先把所有词典的引用都注释了，然后只引用那个出问题的词库。知道了那个代码具体含义就有头绪了。

**Comment by ksqsf** [comment]
https://github.com/rime/librime/pull/874
