### ISSUE TITLE
Squirrel 0.18 的相關字詞提示

### ISSUE THREAD

**Issue by Wujidadi** [rime/home#1555]
鼠鬚管 0.18 起似乎多了個新功能，會自動提示相關組字碼的字詞，如下圖

![image](https://github.com/rime/home/assets/10349431/b4a98a76-eda1-4e9e-ba47-0d62a3d07288)

但有時候覺得不太方便，想取消，但從 5 月 8 日更新到現在還沒找到哪裡可調整。

求賜教！

**Comment by LEOYoon-Tsaw** [comment]
這應該是librime 1.11.0 的新功能
script_translator: preedit for predicted word ([f907369](https://github.com/rime/librime/commit/f90736938cbb3be6fac118b89082fa9f74394524))
script_translator: sentence over prediction ([729aa62](https://github.com/rime/librime/commit/729aa62b0126a5b59f26204fd6789d015bcbc50d))
script_translator: word completion from 2nd place (https://github.com/rime/librime/issues/848) ([5c7fb64](https://github.com/rime/librime/commit/5c7fb64be01f4f43f62c8d7dc4bee5d0ac34fed5))

**Comment by ksqsf** [comment]
用 `enable_completion: false` 取消

**Comment by kitawa1981** [comment]
> 使用`enable_completion: false`取消

好一点，但还是有部分不行
![CleanShot 2024-05-14 at 9  34 00@2x](https://github.com/rime/home/assets/129429050/32ba91be-ee24-4dfb-bdb0-494bfb7dc009)

**Comment by ksqsf** [comment]
可能说明你还有第二个script translator并且你没写enable completion false

**Comment by kitawa1981** [comment]
> 可能说明你还有第二个script translator并且你没写enable completion false

啊，明白，已经解决了，谢谢~

**Comment by Wujidadi** [comment]
我在 `xxx.schema.yaml` 的 `translator` 底下加上 `enable_completion: false` 解決了，如下：

```yaml
translator:
  enable_completion: false
```

感謝大家幫助！
