### ISSUE TITLE
ibus rime 無法使用雙拼（Arch Linux）

### ISSUE THREAD

**Issue by lkblkb** [rime/home#156]
請問要怎麼抓雙拼需要的 .prism.bin 等檔案？目前安裝在Arch沒有這些:

/usr/share/rime-data/double_pinyin.prism.bin
/usr/share/rime-data/double_pinyin.schema.yaml
/usr/share/rime-data/double_pinyin_abc.prism.bin
/usr/share/rime-data/double_pinyin_abc.schema.yaml
/usr/share/rime-data/double_pinyin_flypy.prism.bin
/usr/share/rime-data/double_pinyin_flypy.schema.yaml
/usr/share/rime-data/double_pinyin_mspy.prism.bin
/usr/share/rime-data/double_pinyin_mspy.schema.yaml

**Comment by lotem** [comment]
通過以下命令下載源文件到 `~/.config/ibus/rime/`，再點選輸入法狀態欄的「部署」按鈕。

```bash
curl -fsSL https://git.io/v13uY | bash -s -- double-pinyin
```

**Comment by lkblkb** [comment]
謝謝！不過我已經在別地方找到，忘記哪裡。
