### ISSUE TITLE
[Question] 小狼毫Windows安裝的提示語中“打盤”是一個詞嗎？

### ISSUE THREAD

**Issue by hbghlyj** [rime/home#1560]
weasel 0.15.0 Windows installer
https://github.com/rime/weasel/releases/download/0.15.0/weasel-0.15.0.0-installer.exe
“打盤”是一個詞嗎？似乎是“打算”？
>安裝前，我打盤先卸載舊版本的小狼毫。按下「確定」移除舊版本，按下「取消」放棄本次安裝。

![image](https://github.com/rime/home/assets/53823634/232fd80b-fdd2-422c-9530-144ed029366a)

**Comment by fxliang** [comment]
#rime/weasel#1223

typo在新版中有修了
