### ISSUE TITLE
自动造词不符合编码规则

### ISSUE THREAD

**Issue by yett1873** [rime/home#1565]
您好，如图所示，在使用encoder进行自动造词时，我的词典中出现了并不符合预设编码规则的词条，甚至有时无法造出正确的编码。
![image](https://github.com/rime/home/assets/75569851/f96c8c4e-9566-4437-a26b-7504c74c8387)

我目前的版本是0.18，相关设置如下，应该不是设置导致的问题？求赐教🙏
<img width="276" alt="image" src="https://github.com/rime/home/assets/75569851/78cc7af2-4322-4171-ba2e-155b5f86d312"> <img width="297" alt="image" src="https://github.com/rime/home/assets/75569851/fe074a5e-8343-4a6e-9ca0-57c485c62ce4">

**Comment by ksqsf** [comment]
检查一下码表里的单字编码？

**Comment by yett1873** [comment]
> 检查一下码表里的单字编码？

谢谢！不过码表编码没看出来什么问题。这些错码都是用`o`代替了本应该的`v`，不知道是什么导致的。

**Comment by lotem** [comment]
信息不足無法重現問題
