### ISSUE TITLE
鼠鬚管 如何关闭联想长候选词的拼音展示

### ISSUE THREAD

**Issue by lance6716** [rime/home#1567]
![image](https://github.com/rime/home/assets/1689766/87ac77cf-381d-4821-a5d4-d53f1fd6efd9)

在更新到鼠鬚管 0.18 后，发现候选词会出现额外的拼音。要如何关闭这个功能？看了一下 release note 并没有提到

**Comment by LEOYoon-Tsaw** [comment]
這是librime更新帶來的，我放了librime更新的🔗。要關閉需要設置enable_completion: false

**Comment by lance6716** [comment]
感谢。我将自己使用的拼音方案配置文件设置了 spelling_hints: 0，确实能解决问题
