### ISSUE TITLE
建議增加多個字符對單個或一組字符之轉換

### ISSUE THREAD

**Issue by DaengGWokFook** [rime/home#158]
我用漢字作爲字典（dict）裏的輸入碼，然後在方案（schema）裏轉換成羅馬字母。下圖是我目前發現能用最少字符所寫的碼。
![image](https://cloud.githubusercontent.com/assets/18633778/26525808/01c712cc-4331-11e7-84f3-40939b98260c.png)
既然xlit左邊轉成右邊的都是同一字符‘東’，爲何不省去重複字符？我建議如下圖，多字符對單字符轉換。
![image](https://cloud.githubusercontent.com/assets/18633778/26525826/9248703e-4331-11e7-80b2-0d46d171f711.png)
如此既省時間又省空間，而且還可以多字符對單組字符轉換，可省略derive。如下圖
![image](https://cloud.githubusercontent.com/assets/18633778/26525860/688bfc42-4332-11e7-9dd2-387841b794ef.png)

**Comment by xiaoqun2016** [comment]
`- xform/[董送冻红……]/ung/`

**Comment by lotem** [comment]
`- xform/甲|乙|丙|丁/東/`

**Comment by xiaoqun2016** [comment]
有个奇怪的现象。换个写法，出来的结果总是被重复三遍。 这要怎么理解呢？  
复现方法：
词典添加如下词条：  
```yaml
动	动
董	董
冻	冻
懂	懂
```
comment的拼写运算：  
```yaml
comment_format:
    - xform/[动董冻懂]/东/
```
然后出来的结果是这样：  
![210](https://cloud.githubusercontent.com/assets/16501929/26569984/814a42d2-44d3-11e7-8735-09dcb48d6fcd.png)
显示了三个“东” 。  

在speller/algebra里面做拼写运算：  
```yaml
speller:
  algebra:
    - xform/[动董冻懂]/dso/
```
结果要输入三次`dso`才能打出那几个字：  
![screenshot_21](https://cloud.githubusercontent.com/assets/16501929/26569869/d5ac5dfc-44d2-11e7-9d15-16c463ae6401.png)

**Comment by DaengGWokFook** [comment]
xiaoqun2016的無法顯示候選，無法打中文。
lotem的方法行得通

**Comment by osfans** [comment]
所以可能是正則不支持unicode？把一個漢字，當成三個字符？

**Comment by xiaoqun2016** [comment]
@osfans 看来是这样，当成三个字符来处理了。理解了，谢谢！    

另外在wiki上看到一段话：  
>「轉寫」是拼寫運算中目前唯一一則將運算元和參數作UTF-32編碼、而非UTF-8編碼處理的運算。 意味着，字母表可以採用ASCII範圍以外的字符、字母表的長度按照Unicode字符數來計算。

说的是只有`xlit`是以UTF-32编码来处理拼写运算的，言外之意是不是`xform`、`derive`这些是以UTF-8来处理的？不过结合后面那句话来看，应该不是UTF-8？

**Comment by DaengGWokFook** [comment]
lotem的方法可以令多個/組字符轉成一個/組字符，但是依舊無法省去重複的字符，只是把原來十幾個‘東’換成‘|’。xiaoqun2016 與我提出的方法可以省字符。

**Comment by DaengGWokFook** [comment]
多組字符轉單個/組字符就沒辦法省略分隔符‘|’，但多個字符轉單個/組字符是可以省略的。

**Comment by lotem** [comment]
毫無道理的要求。
不寫 `|` 那些字就不是或的關係。而你們提出的方法，現在沒有一個能用的。
爲方案寫手的簡便而做重複勞動型開發是不可能的事。不然方案可以只寫個名字以求最簡，具體功能都要求程序實現唄…
要配置簡便，可以用針對特定需求編寫的軟件，如更專注的平臺，甚至專門開發一個軟件，連配置都不需要了。Rime 追求軟件的通用性，寫方案以實現具體功能是方案寫手應當承擔的工作。
