### ISSUE TITLE
最新版本1.11.2，无法修改输入法外观

### ISSUE THREAD

**Issue by cedar-yxs** [rime/home#1582]
如标题所示，直接修改squirrel.yaml或者创建squirrel.custom.yaml文件后再修改path -> style，然后点部署，输入法的样式都无法修改！
还有一个问题，为什么每次更新样式就变成默认的了？

**Comment by LEOYoon-Tsaw** [comment]
是這個問題嗎？ https://github.com/rime/squirrel/issues/923

**Comment by LEOYoon-Tsaw** [comment]
> 更新后，修改参数不生效，horizontal: false # true横排，false竖排

https://github.com/rime/squirrel/blob/9e477f05dbbacd7d0aa89249788ae00fc07c738d/CHANGELOG.md?plain=1#L29-L30
