### ISSUE TITLE
整句输入怎么让没有词组时做尽量短的切分

### ISSUE THREAD

**Issue by yueduz** [rime/home#159]
![2017-06-03 12-07-59](https://cloud.githubusercontent.com/assets/1448159/26750454/74efebb4-47e8-11e7-84e8-1773e6f18e9e.png)
想要的正确切分:打(df)水(ssa)

**Comment by yueduz** [comment]
现在有一形码,
一码字规则:/[a-z]/
二码字规则:/[a-z][a-z]/
三码字规则: /[a-z][a-z][eiuoa]/
三码以上字规则: /[a-z][a-z][eiuoa]+/
所以[eiuoa]只会在二码一以后,整句输入应该是比较好确定切分的.
其实就是用顶功打整句

**Comment by lotem** [comment]
用的是 `script_translator` 嘛？看上去完全是按字頻計算的。

**Comment by lotem** [comment]
用的是 `script_translator` 嘛？看上去完全是按字頻計算的。

**Comment by yueduz** [comment]
是script_translator，那能不能让他优先用尽量短的切分呢

**Comment by yueduz** [comment]
能切词组切词组，不能切词组切尽量短的单字

**Comment by lotem** [comment]
已解決 https://github.com/rime/librime/commit/b0d985e8fe56179b23d551259b56aa197f4b8ed3
