### ISSUE TITLE
鼠须管如何更改用户文件夹的位置？

### ISSUE THREAD

**Issue by horasan106** [rime/home#1591]
目前为默认位置：/Users/username/Library/Rime
我想挪到OneDrive上。
请问应该如何部署？

**Comment by LEOYoon-Tsaw** [comment]
改不了的

**Comment by ksqsf** [comment]
> 我想挪到OneDrive上。

可以嘗試在 OneDrive 上創建目錄，然後把 ~/Library/Rime 改成指向這個目錄的符號鏈接
