### ISSUE TITLE
更新到1.0.2后，竖屏幕显示

### ISSUE THREAD

**Issue by Vergegung** [rime/home#1593]
更新到1.0.2后，竖屏幕显示
在custom中皮肤，设置
horizontal: true             # true横排，false竖排
也无法改为横排，求教。非常感谢

**Comment by LEOYoon-Tsaw** [comment]
https://github.com/rime/squirrel/blob/master/CHANGELOG.md#1.0.0

**Comment by Vergegung** [comment]
> https://github.com/rime/squirrel/blob/master/CHANGELOG.md#1.0.0

感谢，但是我更改后，还是竖排。

 mac_light:
      name: Mac浅色
      candidate_list_layout: stacked
      text_orientation: horizontal  # thorizontal 横排，vertical竖排
      candidate_format: "%c %@ "   # 用 1/6 em 空格 U+2005 来控制编号 %c 和候选词 %@ 前后的空间
      corner_radius: 5                             # 窗口圆角
      hilited_corner_radius: 0                     # 高亮圆角
      line_spacing: 10                             # 行间距(适用于竖排)
      border_height: 0                             # 窗口上下高度，大于圆角半径才生效
      border_width: 0                              # 窗口左右宽度，大于圆角半径才生效
      font_face: "PingFangSC"                      # 候选词字体
      font_point: 16                               # 候选字大小
      label_font_point: 13                         # 候选编号大小
      text_color: 0x424242                    # 拼音行文字颜色
      back_color: 0xFFFFFF                    # 候选条背景色
      label_color: 0x999999                   # 预选栏编号颜色
      candidate_text_color: 0x3c3c3c          # 预选项文字颜色
      comment_text_color: 0x999999            # 拼音等提示文字颜色
      hilited_text_color: 0x999999            # 高亮拼音 (需要开启内嵌编码)
      hilited_back_color: 0xD75A00            # 第一候选项背景背景色
      hilited_candidate_text_color: 0xFFFFFF  # 第一候选项文字颜色
      hilited_candidate_label_color: 0xFFFFFF # 第一候选项编号颜色
      hilited_comment_text_color: 0x999999    # 注解文字高亮

**Comment by LEOYoon-Tsaw** [comment]
text_orientation: horizontal # thorizontal 横排，vertical竖排
是中文橫排和豎排，你要的應該是候選排列方式：

candidate_list_layout: linear

**Comment by Vergegung** [comment]
非常感谢，问题解决了，😁
