### ISSUE TITLE
关于 symbols.yaml 的汉语拼音字母输入

### ISSUE THREAD

**Issue by Buernia** [rime/home#161]
现在的 symbols.yaml 默认只有以下拼音字母：
`    '/py': [ ā, á, ǎ, à, ō, ó, ǒ, ò, ê, ē, é, ě, è, ī, í, ǐ, ì, ū, ú, ǔ, ù, ü, ǖ, ǘ, ǚ, ǜ, , ń, ň,  ]`
这个名单还有诸多问题。一是缺少大写字母，二是字母的收录还不完全。最重要的一点是，（U+E7C7）和（U+E7C8）是 Unicode 私人使用区的字符，只有在部分国标字体中才会显示为 ḿ 和 ǹ。而真正属于 ḿ 和 ǹ 的码点分别是 U+1E3F 和 U+01F9。输入私人使用区的字符显然是舍近求远。
我在这里提供有全部带附加符号的拼音字母的修改代码，希望可以加入到默认配置中，为用户提供更多便利：
`    '/py': [ ā, á, ǎ, à, ō, ó, ǒ, ò, ê, ê̄, ế, ê̌, ề, ē, é, ě, è, ī, í, ǐ, ì, ū, ú, ǔ, ù, ü, ǖ, ǘ, ǚ, ǜ, ḿ, m̀, ń, ň, ǹ, ẑ, ĉ, ŝ, ŋ ]`
`    '/pyd': [ Ā, Á, Ǎ, À, Ō, Ó, Ǒ, Ò, Ê, Ê̄, Ế, Ê̌, Ề, Ē, É, Ě, È, Ī, Í, Ǐ, Ì, Ū, Ú, Ǔ, Ù, Ü, Ǖ, Ǘ, Ǚ, Ǜ, Ḿ, M̀, Ń, Ň, Ǹ, Ẑ, Ĉ, Ŝ, Ŋ ]`
参考：[《关于带声调汉语拼音字母的输入》](https://zhuanlan.zhihu.com/p/27416251)

**Comment by mhohai** [comment]
+1
