### ISSUE TITLE
macOS 下多语言键盘切换问题

### ISSUE THREAD

**Issue by loikein** [rime/home#162]
烦请查看：[StackExchange](https://apple.stackexchange.com/questions/287290/)
把鼠须管从输入法里删去就解决了，但这应该算 bug 吧……

**Comment by sihaiyi** [comment]
我在用英文，法文和rime输入法没有碰到键盘切换的问题，之前在ubuntu下用其他第三方输入法有切换键盘的问题但是用了rime之后自动解决了。
另外@loikein 这个thread我读了一下貌似并没有解决方法

**Comment by lotem** [comment]
那不如，把日文從輸入法裏刪除試試看吧。

**Comment by loikein** [comment]
其实这个问题也出现在关闭了鼠须管之后，所以我打算发到苹果的社区了……

@lotem 删了日文的话就会在从中文切换成英语之后输出中文……
@sihaiyi 请问为何无解？

**Comment by sihaiyi** [comment]
@loikein 不好意思刚开始看错了以为你post一个解决的帖子在这里，仔细一看是你发的求助贴。
