### ISSUE TITLE
0.16.1版本小狼毫可能经常卡死其他应用

### ISSUE THREAD

**Issue by Mion354D** [rime/home#1623]
平台: windows 10 22H2 / windows 11 23H2
小狼毫版本: 0.16.1

表现: 
当前活动程序未响应, 弹窗如图
![image](https://github.com/user-attachments/assets/176dc412-aca4-493b-a048-667cafb9f9dd)
该卡死可能发生在任何程序, 包括 task manager 也会被卡死

为什么我认为是小狼毫的问题:
1. 该卡死发生时一定是中文输入状态
2. 切换到英文语言有大概率解除卡死, 有少部分情况会直接卡至无法切换语言.
3. kill 掉 weasel server 可以立即解除卡死
4. 有两台设备, win10 的工作用与 win11 的日常用 PC, 它们之间除了小狼毫, chrome 与 vs code 外没有安装共同的程序. 它们都是在小狼毫从 0.15.x 升至 0.16.1 后出现问题. 0.15.x 版本没有问题
5. 有一台 win11 的游戏 PC, 停留在 0.15.x 没有升级, 没有问题. 还有一台 mac, 没有问题.

非常乐意提供更多信息, 如果有需要我会尽快po上来

**Comment by mirtlecn** [comment]
先卸载，然后删除用户文件夹里面的 build 文件夹。

再安装。

看看有没有好一些了。看到过类似的情况，卸载不完全（旧版本程序组件仍然存在）导致的。

**Comment by cangzhouyuhe** [comment]
+1，16.1在某些软件中直接把软件卡死，如果提前切换为微软拼音则不会卡死。
![Uploading 小狼毫在某些软件无法输入.gif…]()

**Comment by cangzhouyuhe** [comment]
+1，16.1在某些软件中直接把软件卡死，如果提前切换为微软拼音则不会卡死。

**Comment by zhao-yuan** [comment]
我是新装的0.16.1也经常有这个问题

**Comment by Mion354D** [comment]
这似乎是weasel独有的问题
[](https://github.com/rime/weasel/issues/1341)
