### ISSUE TITLE
切换到其它输入法比如gboard,然后切换回fcitx安卓版加rime插件时,中文输入会重新部署

### ISSUE THREAD

**Issue by LastFlydragon** [rime/home#1631]
我英语用gboard,中文用fcitx安卓版和rime插件来实现双拼音形输入.
rime里部署了墨奇音形自然码双拼.
切换到英语然后切换回fcitx时,中文输入会重新部署,所以每次要延迟10秒以上.
不知道是fcitx还是rime的原因.

**Comment by eagleoflqj** [comment]
Not rime issue. Frontend controls whether/when rime deploys.
