### ISSUE TITLE
构建词联想模块遇到的疑问~

### ISSUE THREAD

**Issue by xiangxianzhang** [rime/home#165]
您好，里面的prism.cc构建的double-tire可以用pingyin来查找，现在我在做个词联想模块，就用户点击了候选词，我用候选词进行前缀搜索提供联想词，请问这个double-tree支不支持中文前缀搜索呢？

**Comment by osfans** [comment]
支持，@lotem

**Comment by lotem** [comment]
prism 并不包含候选词

_Sent from my LGE Nexus 5X using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by lotem** [comment]
抱歉，原來不是問 prism。
回答原題：darts-clone 是支持中文（假定用UTF-8編碼）前綴搜索的。
