### ISSUE TITLE
Gentoo下安装出错

### ISSUE THREAD

**Issue by IceAmber** [rime/home#166]
Gentoo下用emerge fcitx-rime安装报错，安装日志如下
[build.log](https://github.com/IceAmber/Error/blob/master/librime_build.log)

**Comment by LdBeth** [comment]
同样有这个问题。

librime-1.2

**Comment by IceAmber** [comment]
[解决方案](https://forums.gentoo.org/viewtopic-t-1066400-highlight-.html)
去看上面那帖子，我在Gentoo论坛里发帖然后解决了

**Comment by LdBeth** [comment]
多谢
