### ISSUE TITLE
我想在輸入方案中實現以下2個功能

### ISSUE THREAD

**Issue by sheaahhoi1** [rime/home#1662]
1.按下enter輸出已選擇的詞句,知道要在方案中添加.schema.yaml
以下是失敗

key_binder:
  import_preset: default
  bindings:
    bindings:
    - { when: has_menu, accept: Return, send: confirm }    # 按 Enter 鍵选择并输出被标记的候选字
以下這些也失敗
```
confirm	上屏候選項
commit_comment	上屏候選項備注
commit_raw_input	上屏原始輸入
commit_script_text	上屏變換後輸入
```
editor:
  bindings:
    Return: commit_comment
以這種寫法也無法實現

2.另外想用按鍵擴展候選字區,平常是則常規模式,
像下圖別的輸入法一樣擴展選字區
![image](https://github.com/user-attachments/assets/cc8591ed-bbad-47ae-894a-b06d53496c9a)

能否通過設定按鍵實現擴展?

**Comment by ksqsf** [comment]
1.

```
editor:
  bindings:
    Return: confirm
```

2. 目前不支持。 #376
