### ISSUE TITLE
用分号和冒号选择第二三候选字的设置失效了？

### ISSUE THREAD

**Issue by naduancom** [rime/home#1674]
我在 default.custom.yaml 文件中写入以下代码：
```
key_binder/bindings: 
    - {accept: semicolon, send: 2, when: has_menu}  # 候选2 用分号
    - {accept: apostrophe, send: 3, when: has_menu} # 候选3 用单引号
```
我很自信我写入的代码，缩进没有问题。但是此设置无效。我怀疑是最新版本的问题。

**Comment by fxliang** [comment]
应该用`key_binder/bindings/+:`

其他的，可以确定的信息是，在方案里面加这个bindings是正常的，我日常就有在用

**Comment by naduancom** [comment]
我换了一种方式解决了。我把我的方法贴出来，希望能让後来人少走弯路：

default.custom.yaml

`
patch:
  "key_binder/bindings":
    - {accept: Return, send: Escape, when: composing}
    - {accept: semicolon, send: 2, when: has_menu}
    - {accept: apostrophe, send: 3, when: has_menu}
    - {when: composing, accept: ISO_Left_Tab, send: Shift+Left}
    - {when: composing, accept: Shift+Tab, send: Shift+Left}  # "Shift+Tab" 键向左选拼音分词
    - {when: composing, accept: Tab, send: Shift+Right}       # "tab" 键选拼音分词   
    - {when: composing, accept: Tab, send: Page_Down}        # "tab" 键翻页
    - { when: paging, accept: minus, send: Page_Up}            # "-"上一页
    - { when: has_menu, accept: equal, send: Page_Down}        # "="下一页
    - { when: paging, accept: bracketleft, send: Page_Up}      # "["上一页
    - { when: has_menu, accept: bracketright, send: Page_Down} # "]"下一页
    - { when: paging, accept: comma, send: Page_Up}            # ","上一页
    - { when: has_menu, accept: period, send: Page_Down}       # "."下一页
    - {accept: "Control+a", send: Home, when: composing}                   # 光标移至首
    - {accept: "Control+e", send: End, when: composing}                    # 光标移至尾
    - {accept: "Control+Shift+1", select: .next, when: always}             # 切换输入方案
    - {accept: "Control+Shift+2", toggle: ascii_mode, when: always}        # 中英文切换
    - {accept: "Control+Shift+3", toggle: full_shape, when: always}        # 全角/半角切换
    - {accept: "Control+Shift+4", toggle: simplification, when: always}    # 繁简体切换
    - {accept: "Control+Shift+5", toggle: extended_charset, when: always}  # 通用/增广切换（显示生僻字）
    - {accept: "Control+Shift+6", toggle: show_emoji, when: always}        # 是否顯示emoji切换
  "menu/page_size": 9
  schema_list:
    - {schema: wubixinshiji}
    - {schema: luna_pinyin_fluency}
    - {schema: wubixinshiji_trad}
  `
weasel.custom.yaml

`
patch:
  "style/font_face": "XHei"  
  "style/font_point": 14
`
