### ISSUE TITLE
0.16或之后版本无法在Edge浏览器切换成中文输入法

### ISSUE THREAD

**Issue by pigdull** [rime/home#1677]
Edge浏览器无法切换成中文输入法，其他软件都没这问题。
0.15或之前版本没这问题，只能卸了0.16装回老版本才能在Edge里换中文。是什么原因呢？

系统: Windows 11
浏览器： Microsoft Edge Version 123.0.2420.65 (Official build) (64-bit)
小狼毫:  0.16之后所有版本

**Comment by pigdull** [comment]
那会否是Win11才有的问题？

**Comment by sheaahhoi1** [comment]
> 那会否是Win11才有的问题？

個別問題吧,Win11 23H2/24H2也可以打字

**Comment by ksqsf** [comment]
可以打字。

- Win11 22H2
- Edge Version 129.0.2792.79 (Official build) (64-bit)
- Weasel 0.16.1.0

**Comment by pigdull** [comment]
那就奇怪了，不知道就我有这问题

**Comment by pigdull** [comment]
我再测了一下，连chrome和firefox都一样的问题。

**Comment by AoThen** [comment]
> 我再测了一下，连chrome和firefox都一样的问题。

+1,我也是,操作系统名称	Microsoft Windows 11 专业版
版本	10.0.22631 版本 22631

**Comment by pigdull** [comment]
我也是Microsoft Windows 11 专业版 64bit 版本是22631.4317

**Comment by AoThen** [comment]
我在浏览器尝试输入期间的日志文件：```I20241014 18:26:08.196790 15864 engine.cc:72] starting engine.
I20241014 18:26:08.197053 15864 engine.cc:133] updated option: _auto_commit
I20241014 18:26:08.197103 15864 dictionary.cc:360] loading dictionary 'rime_mint'.
I20241014 18:26:08.197172 15864 dictionary.cc:360] loading dictionary 'melt_eng'.
I20241014 18:26:08.222988 15864 engine.cc:395] ConcreteEngine::InitializeOptions
I20241014 18:26:08.222997 15864 engine.cc:400] found switch option: ascii_mode, reset: 0
I20241014 18:26:08.223001 15864 engine.cc:133] updated option: ascii_mode
I20241014 18:26:08.223005 15864 engine.cc:400] found switch option: emoji_suggestion, reset: 1
I20241014 18:26:08.223008 15864 engine.cc:133] updated option: emoji_suggestion
I20241014 18:26:08.223011 15864 engine.cc:400] found switch option: full_shape, reset: 0
I20241014 18:26:08.223013 15864 engine.cc:133] updated option: full_shape
I20241014 18:26:08.223016 15864 engine.cc:400] found switch option: transcription, reset: 0
I20241014 18:26:08.223019 15864 engine.cc:133] updated option: transcription
I20241014 18:26:08.223021 15864 engine.cc:400] found switch option: ascii_punct, reset: 0
I20241014 18:26:08.223024 15864 engine.cc:133] updated option: ascii_punct
I20241014 18:26:08.223048 15864 engine.cc:147] updated property: client_app
I20241014 18:26:08.223053 15864 engine.cc:147] updated property: client_type
I20241014 18:26:08.223056 15864 engine.cc:133] updated option: inline_preedit
I20241014 18:26:08.223061 15864 engine.cc:133] updated option: soft_cursor
I20241014 18:26:08.223128 15864 engine.cc:133] updated option: inline_preedit
I20241014 18:26:08.223133 15864 engine.cc:133] updated option: soft_cursor
I20241014 18:26:24.677807 15864 engine.cc:96] engine disposed.
I20241014 18:26:45.858070  4440 engine.cc:72] starting engine.```

**Comment by AoThen** [comment]
我好像找到问题了。。。。是ESET的浏览器防护功能。。。拦截了。。。 你看看是不是类似的杀毒软件@pigdull

**Comment by dennisxddxdd** [comment]
> 我好像找到问题了。。。。是ESET的浏览器防护功能。。。拦截了。。。 你看看是不是类似的杀毒软件@pigdull

我同樣是關了ESET的瀏覽器保護就沒有問題了

**Comment by pigdull** [comment]
@AoThen @dennisxddxdd 谢谢两位！ 是的，我用ESET，把浏览器键盘保护关掉后就能用了
