### ISSUE TITLE
双拼 Schema : 小浪双拼方案问题

### ISSUE THREAD

**Issue by tigren** [rime/home#168]
目前尝试在做小浪双拼的码表，[http://tieba.baidu.com/p/5114198524](小浪双拼)

遇到一个问题，在这个双拼方案中，E 键做声母的时候是转换成 zh 的，但是要打 e 开头的音时 e 要用 u 代替 （e = uu, en = un）

所以我想当然的用了 xform 下面两行
```
xform/^zh/E/
xform/^e/U/
```

显然是不行的，E 键完全不生效了。于是我又尝试了其他写法，比如 

```
xform/^zh/E/
xform/E/U/
```

结果还是不对

当然我觉得这个双拼方案 E 和 U 设计成这样有些诡异，但是怎么才能实现这个码表的需求呢？

**Comment by lotem** [comment]
這是全部拼寫運算代碼嘛？
以上兩行只是把 zh 轉換爲（大寫）E、把零聲母的 e 轉換爲 U。按照問題描述，還需要變成小寫的雙拼字符。

**Comment by tigren** [comment]
這只是其中的兩行，其他鍵位的替換都很簡單，xform 搞定

佛振大大的意思是再加其他行？完全沒有概念呢

**Comment by tigren** [comment]
搞明白了，我应该再加一行类似于
```
- xform/^(e.*)$/U$1/
```
这样的一行，细节我再研究下
