### ISSUE TITLE
小狼毫0.16.3在win11无法使用，望指点

### ISSUE THREAD

**Issue by tjyqd** [rime/home#1686]
今天在输入过程中突然小狼毫失灵，起初以为是算法服务闪退。但尝试重启算法服务后发现没有反应，重启电脑后仍然无法启动小狼毫算法服务，重新安装小狼毫也没有解决。右键语言栏选单，"参与讨论"以下的选项全部失效。

**Comment by tjyqd** [comment]
> 可能是被杀毒干掉了

我也有确认杀毒软件，没有针对算法服务的阻止记录。

**Comment by mirtlecn** [comment]
是 ESET 吗？如果是的话，那十有八九就是它干掉的，不会显示记录。 https://github.com/rime/home/issues/1677

**Comment by tjyqd** [comment]
> 是 ESET 吗？如果是的话，那十有八九就是它干掉的，不会显示记录。 #1677

是Microsoft defender…

**Comment by tjyqd** [comment]
回退0.14.3后解决，目前仍不清楚为何0.16.3突然无法使用。

**Comment by tjyqd** [comment]
回退0.14.3后解决，目前仍不清楚为何0.16.3突然无法使用。
