### ISSUE TITLE
在win11上与nilesoft shell冲突，右键打开菜单会导致explorer崩溃

### ISSUE THREAD

**Issue by CHminggao** [rime/home#1726]
nilesoft shell是个美化win11的右键菜单的工具，官网是这个： https://nilesoft.org/
右键小狼毫托盘图标会导致explorer崩溃
下面是事件管理器的错误日志
> 出错应用程序名称： Explorer.EXE，版本： 10.0.26100.2454，时间戳： 0xdc9c700e
出错模块名称： InputHost.dll， 版本： 10.0.26100.2454，时间戳： 0xb003c7f8
异常代码： 0xc0000409
错误偏移： 0x0000000000012f64
出错进程 ID： 0x63D0
出错应用程序开始时间： 0x1DB3FD10CC8B01F
Faulting 应用程序路径： C:\WINDOWS\Explorer.EXE
Faulting 模块路径： C:\Windows\System32\InputHost.dll
Report ID： 344fe91a-f516-42b6-9ae4-0b6f5bfdc859
Faulting 包全名： 
Faulting 程序包相对应用程序 ID：  个

**Comment by Dvoice9** [comment]
我也遇到了相同的问题，尝试这个命令依然无效
`exclude.where = !process.is_explorer && (process.name == 'WeaselServer' || process.name == 'Weasel Server')`

**Comment by fxliang** [comment]
如果是托盘那是WeaselServer的菜单，如果是language bar，那就是具体应用的子窗体的菜单（weasel.dll被应用加载，菜单是weasel.dll弹出）

**Comment by Dvoice9** [comment]
> 如果是托盘那是WeaselServer的菜单，如果是language bar，那就是具体应用的子窗体的菜单（weasel.dll被应用加载，菜单是weasel.dll弹出）

我更倾向language bar，尝试过寻找崩溃触发点，当从桌面打开浏览器窗口时，右键菜单样式变成了win10，取消并再次右键就会崩溃，当重启资源管理器后，崩溃消失无论是否切换窗口，且右键菜单外观变正常，但偶尔有几次右键打开的是任务栏菜单，大概等1-2分钟再次右键，崩溃复现，值得注意的是在测试过程中复现过rime的win11的菜单外观，而这个bug也在右键任务栏空白处出现过直到第二次点击就恢复成nilesoft皮肤。也许只是个无关痛痒的bug我看issue上没人提过，因为触发概率比较低不像rime这样频繁，任务栏中右键托盘图标还没出现过bug

**Comment by Dvoice9** [comment]
![PixPin_2024-12-06_14-04-41](https://github.com/user-attachments/assets/a9c9009e-c75a-497f-9f3f-d18e72a81da9)
终于解决了，是win11的任务栏不兼容

**Comment by CHminggao** [comment]
> ![PixPin_2024-12-06_14-04-41](https://private-user-images.githubusercontent.com/124578749/393116885-a9c9009e-c75a-497f-9f3f-d18e72a81da9.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzM0NzAzMTcsIm5iZiI6MTczMzQ3MDAxNywicGF0aCI6Ii8xMjQ1Nzg3NDkvMzkzMTE2ODg1LWE5YzkwMDllLWM3NWEtNDk3Zi05ZjNmLWQxOGU3MmE4MWRhOS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMjA2JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTIwNlQwNzI2NTdaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0wNDdlZjVjZjg0ZjQwMTkyMjhhN2M0YmFlMmY2NDg4NTVhNzFhMGVlNjk5YTUwNjU4ZjRiZjM4MDdmOGQwMDRjJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.lI8rqC8etxIPLOfk6uNyLeNdus_yzjvso2JkOhCZ6K4) 终于解决了，是win11的任务栏不兼容，换win10完美不崩溃

emmm抽象win11
