### ISSUE TITLE
快捷键设置问题

### ISSUE THREAD

**Issue by xdaniel9** [rime/home#1734]
rime_ice.custom.yaml配置如下（直接从default.yaml复制的）
```
    # 翻页 - =
    - { when: has_menu, accept: minus, send: Page_Up }
    - { when: has_menu, accept: equal, send: Page_Down }

    # 翻页 , .
    - { when: paging, accept: comma, send: Page_Up }
    - { when: has_menu, accept: period, send: Page_Down }

    # 翻页 [ ]
    - { when: paging, accept: bracketleft, send: Page_Up }
    - { when: has_menu, accept: bracketright, send: Page_Down }
```

现在有两个问题：
1. bracketleft/bracketright不生效
2. 这个配置只有在default.costum.yaml和rime_ice.custom.yaml里才有效，放在weasel.custom.yaml里不行，同样的还有`menu/page_size: 9`，这几个yaml到底是啥优先级关系呢，如果我想只对在win平台上的所有方案配置该如何修改

**Comment by lotem** [comment]
應當在輸入方案裏設置。

`default.yaml` 裏有相關代碼，是爲了讓採用默認翻頁鍵的輸入方案直接引用。

`weasel.yaml` 包含 Windows 前端的選項，主要是自定義界面風格。
