### ISSUE TITLE
rime对句号键「period	.」处理是否有问题？

### ISSUE THREAD

**Issue by ziloeng** [rime/home#174]
在使用prime的过程中发现按下句号键会影响正在输入的预编辑编码。

我在default.custom.yaml中绑定如下键值作为翻页键：
      - { when: has_menu, accept: comma, send: Page_Up }
      - { when: has_menu, accept: period, send: Page_Down }
      - { when: has_menu, accept: "[", send: Page_Up }
      - { when: has_menu, accept: "]", send: Page_Down }

当我输入“yi]ge”的时候，输出结果正常，可以显示候选字；
但当我用“yi.ge”，出现问题，rime将句号键也放进预编辑框中，影响之后的输入。

**Comment by lotem** [comment]
應該是開啓了輸入網址模式。代碼爲：
https://github.com/rime/rime-prelude/blob/master/default.yaml#L146

**Comment by ziloeng** [comment]
好像去掉了url那行还是不行~~

**Comment by lotem** [comment]
是`key_binder`對句點之後輸入字母和數字的情況做了特殊處理。用來實現句號翻頁功能和輸入網址、浮點數的兼容。

現在沒有其他改法，或者不用句號翻頁，或者稍稍改變習慣多翻頁一次（繼續向後或翻回上一頁均可）再繼續輸入字母。

**Comment by ziloeng** [comment]
好的，我改用其他键吧

**Comment by pihao** [comment]
我也有这个问题. 场景是:
1. 输入3个编码
2. 第一而没有匹配到, 用句号翻到第二页
4. 第二页也没有找到, 这时输入第四个编码进行更精确的匹配, 但在第三个编码和第四个编码之间却会多出一个句点(`.`, 就是刚才那次翻页时按的句号键), 以至于无法正常匹配编码.

以五笔98的`明天`(`jegd`)为例:
1. 输入`jeg`, 出现候选菜单
2. 用`.`翻页
3. 输入最后一码`d`
4. 出现的却是`jeg.d`

**Comment by kionz** [comment]
没有问题。符合设计。
字母之间的句点用来输入网址。
翻页后追加编码需要先向前翻页。

**Comment by pihao** [comment]
> 没有问题。符合设计。
> 字母之间的句点用来输入网址。
> 翻页后追加编码需要先向前翻页。

@kionz 这样设计是没问题的.
但这里的问题在于混淆了网址模式和翻页这两个操作.
存在候选菜单时按句号(`.`)键应该只命中一个操作: 要么切换到网址模式, 要么翻页.
而不是现在这样, 既翻页, 也触发了网址模式.
并且这时`.`还没显示出来.  这会让用户意识不到已经触发了网址模式, 进而误操作.
