### ISSUE TITLE
ctrl ~ 快捷键无法取消？

### ISSUE THREAD

**Issue by jiuyueshenhua** [rime/home#1743]
由于vscode的Ctrl+~与rime的冲突。
我使用的fctix5-rime，使用了雾凇拼音配置。
我跟着这篇[文章](http://spaceack.com/20210120-%E8%A7%A3%E5%86%B3vscode%E4%B8%8Elinuxrime%E4%B8%AD%E5%B7%9E%E9%9F%B5%E8%BE%93%E5%85%A5%E6%B3%95ctrl-~%E7%83%AD%E9%94%AE%E5%86%B2%E7%AA%81/)，把/usr/share/rime-data/default.yaml对应快捷键删了。
重新加载也无济于事。最后甚至把sitcher这一部分全删了也没用。

而且非常奇怪的是我在.config/fctix5没找到对应配置。不用在意ibus，那是我在安装雾凇拼音配置时装错了。
![image](https://github.com/user-attachments/assets/b623cd22-f68d-4bcd-9e76-e382c1f16b1c)

![image](https://github.com/user-attachments/assets/981ca700-d80e-4a20-8176-cc3e02331347)

本人刚入门ubuntu，很多东西都不太懂，望指教

**Comment by lotem** [comment]
同樣文件名和版本號的配置文件，用戶文件夾裏的那份優先於 rime-data 裏的。
因此不要刪改 /usr/share/rime-data/default.yaml

**Comment by jiuyueshenhua** [comment]
> 同樣文件名和版本號的配置文件，用戶文件夾裏的那份優先於 rime-data 裏的。 因此不要刪改 /usr/share/rime-data/default.yaml

好的，但是.config里没有找到fctix-rime的配置文件，这是什么原因呢？我如果想修改快捷键配置，又应该怎么做呢？

**Comment by kionz** [comment]
fcitx 我不了解。ibus-rime 的配置文件在 $HOME/.config/ibus/rime/

CatCat Ice ***@***.***> 于 2024年12月7日周六 13:28写道：

**Comment by eagleoflqj** [comment]
Linux 和 macOS 上 fcitx5-rime 的用户目录是
~/.local/share/fcitx5/rime
