### ISSUE TITLE
win11小狼毫, 用户词库里的候选词无法删除

### ISSUE THREAD

**Issue by asd25213** [rime/home#1744]
win11+小狼毫
尝试各种键删除下面这个词, 但是一直不行, 一开始还以为是按键配置的问题, 但是配来配去也没用. 
后来查到日志里, 看到也有删除记录, 但是就一直删不掉.
导出的用户词库文本码表也是, 无论尝试几次, 最后导出的都有这一条:

我測試一下你說呢但是我覺得可能還是不泰興	wo ce shi yi xia ni shuo ne dan shi wo jue de ke neng hai shi bu tai xing	1

因为我没有尝试删除成功过, 我也不知道应该截到哪里, 所以截取了两次删除以及之间的部分.

以下为日志: 

I20241206 15:30:59.667600 31728 engine.cc:133] updated option: soft_cursor
I20241206 15:31:00.901050 31728 simplifier.cc:35] initializing opencc: C:\Program Files\Rime\weasel-0.16.3\data\opencc\t2s.json
I20241206 15:31:04.373478 31728 memory.cc:127] deleting entry: '我測試一下你說呢但是我覺得可能還是不泰興'.
I20241206 15:31:09.403780 36936 engine.cc:72] starting engine.
I20241206 15:31:09.403891 36936 engine.cc:133] updated option: simplification
I20241206 15:31:09.404001 36936 engine.cc:133] updated option: _auto_commit
I20241206 15:31:09.404058 36936 dictionary.cc:360] loading dictionary 'luna_pinyin'.
I20241206 15:31:09.404193 36936 engine.cc:395] ConcreteEngine::InitializeOptions
I20241206 15:31:09.404199 36936 engine.cc:400] found switch option: ascii_mode, reset: 0
I20241206 15:31:09.404202 36936 engine.cc:133] updated option: ascii_mode
I20241206 15:31:09.404206 36936 engine.cc:400] found switch option: full_shape, reset: -1
I20241206 15:31:09.404209 36936 engine.cc:400] found switch option: simplification, reset: -1
I20241206 15:31:09.404213 36936 engine.cc:400] found switch option: ascii_punct, reset: -1
I20241206 15:31:09.404245 36936 engine.cc:147] updated property: client_app
I20241206 15:31:09.404251 36936 engine.cc:147] updated property: client_type
I20241206 15:31:09.404254 36936 engine.cc:133] updated option: inline_preedit
I20241206 15:31:09.404259 36936 engine.cc:133] updated option: soft_cursor
I20241206 15:31:09.404354 36936 engine.cc:133] updated option: inline_preedit
I20241206 15:31:09.404359 36936 engine.cc:133] updated option: soft_cursor
I20241206 15:31:20.436126 13908 engine.cc:72] starting engine.
I20241206 15:31:20.436222 13908 engine.cc:133] updated option: simplification
I20241206 15:31:20.436331 13908 engine.cc:133] updated option: _auto_commit
I20241206 15:31:20.436370 13908 dictionary.cc:360] loading dictionary 'luna_pinyin'.
I20241206 15:31:20.436559 13908 engine.cc:395] ConcreteEngine::InitializeOptions
I20241206 15:31:20.436567 13908 engine.cc:400] found switch option: ascii_mode, reset: 0
I20241206 15:31:20.436570 13908 engine.cc:133] updated option: ascii_mode
I20241206 15:31:20.436573 13908 engine.cc:400] found switch option: full_shape, reset: -1
I20241206 15:31:20.436576 13908 engine.cc:400] found switch option: simplification, reset: -1
I20241206 15:31:20.436579 13908 engine.cc:400] found switch option: ascii_punct, reset: -1
I20241206 15:31:20.436608 13908 engine.cc:147] updated property: client_app
I20241206 15:31:20.436613 13908 engine.cc:147] updated property: client_type
I20241206 15:31:20.436616 13908 engine.cc:133] updated option: inline_preedit
I20241206 15:31:20.436620 13908 engine.cc:133] updated option: soft_cursor
I20241206 15:31:20.436712 13908 engine.cc:133] updated option: inline_preedit
I20241206 15:31:20.436718 13908 engine.cc:133] updated option: soft_cursor
I20241206 15:31:30.157788 29032 engine.cc:72] starting engine.
I20241206 15:31:30.157938 29032 engine.cc:133] updated option: simplification
I20241206 15:31:30.158041 29032 engine.cc:133] updated option: _auto_commit
I20241206 15:31:30.158098 29032 dictionary.cc:360] loading dictionary 'luna_pinyin'.
I20241206 15:31:30.158265 29032 engine.cc:395] ConcreteEngine::InitializeOptions
I20241206 15:31:30.158272 29032 engine.cc:400] found switch option: ascii_mode, reset: 0
I20241206 15:31:30.158277 29032 engine.cc:133] updated option: ascii_mode
I20241206 15:31:30.158282 29032 engine.cc:400] found switch option: full_shape, reset: -1
I20241206 15:31:30.158287 29032 engine.cc:400] found switch option: simplification, reset: -1
I20241206 15:31:30.158292 29032 engine.cc:400] found switch option: ascii_punct, reset: -1
I20241206 15:31:30.158321 29032 engine.cc:147] updated property: client_app
I20241206 15:31:30.158326 29032 engine.cc:147] updated property: client_type
I20241206 15:31:30.158329 29032 engine.cc:133] updated option: inline_preedit
I20241206 15:31:30.158333 29032 engine.cc:133] updated option: soft_cursor
I20241206 15:31:30.158433 29032 engine.cc:133] updated option: inline_preedit
I20241206 15:31:30.158439 29032 engine.cc:133] updated option: soft_cursor
I20241206 15:31:30.692785 29032 simplifier.cc:35] initializing opencc: C:\Program Files\Rime\weasel-0.16.3\data\opencc\t2s.json
I20241206 15:31:31.321836 29032 engine.cc:133] updated option: ascii_mode
I20241206 15:31:34.305619 13908 engine.cc:96] engine disposed.
I20241206 15:31:35.908122 31100 engine.cc:72] starting engine.
I20241206 15:31:35.908299 31100 engine.cc:133] updated option: simplification
I20241206 15:31:35.908515 31100 engine.cc:133] updated option: _auto_commit
I20241206 15:31:35.908600 31100 dictionary.cc:360] loading dictionary 'luna_pinyin'.
I20241206 15:31:35.908820 31100 engine.cc:395] ConcreteEngine::InitializeOptions
I20241206 15:31:35.908827 31100 engine.cc:400] found switch option: ascii_mode, reset: 0
I20241206 15:31:35.908830 31100 engine.cc:133] updated option: ascii_mode
I20241206 15:31:35.908834 31100 engine.cc:400] found switch option: full_shape, reset: -1
I20241206 15:31:35.908837 31100 engine.cc:400] found switch option: simplification, reset: -1
I20241206 15:31:35.908842 31100 engine.cc:400] found switch option: ascii_punct, reset: -1
I20241206 15:31:35.908901 31100 engine.cc:147] updated property: client_app
I20241206 15:31:35.908908 31100 engine.cc:147] updated property: client_type
I20241206 15:31:35.908911 31100 engine.cc:133] updated option: inline_preedit
I20241206 15:31:35.908917 31100 engine.cc:133] updated option: soft_cursor
I20241206 15:31:35.909041 31100 engine.cc:133] updated option: inline_preedit
I20241206 15:31:35.909045 31100 engine.cc:133] updated option: soft_cursor
I20241206 15:31:36.964479 19480 engine.cc:72] starting engine.
I20241206 15:31:36.964569 19480 engine.cc:133] updated option: simplification
I20241206 15:31:36.964700 19480 engine.cc:133] updated option: _auto_commit
I20241206 15:31:36.964747 19480 dictionary.cc:360] loading dictionary 'luna_pinyin'.
I20241206 15:31:36.964900 19480 engine.cc:395] ConcreteEngine::InitializeOptions
I20241206 15:31:36.964906 19480 engine.cc:400] found switch option: ascii_mode, reset: 0
I20241206 15:31:36.964910 19480 engine.cc:133] updated option: ascii_mode
I20241206 15:31:36.964915 19480 engine.cc:400] found switch option: full_shape, reset: -1
I20241206 15:31:36.964919 19480 engine.cc:400] found switch option: simplification, reset: -1
I20241206 15:31:36.964922 19480 engine.cc:400] found switch option: ascii_punct, reset: -1
I20241206 15:31:36.964966 19480 engine.cc:147] updated property: client_app
I20241206 15:31:36.964972 19480 engine.cc:147] updated property: client_type
I20241206 15:31:36.964975 19480 engine.cc:133] updated option: inline_preedit
I20241206 15:31:36.964980 19480 engine.cc:133] updated option: soft_cursor
I20241206 15:31:36.965090 19480 engine.cc:133] updated option: inline_preedit
I20241206 15:31:36.965095 19480 engine.cc:133] updated option: soft_cursor
I20241206 15:31:39.032244 19480 simplifier.cc:35] initializing opencc: C:\Program Files\Rime\weasel-0.16.3\data\opencc\t2s.json
I20241206 15:32:05.208325 31100 engine.cc:96] engine disposed.
I20241206 15:32:07.547457 36936 simplifier.cc:35] initializing opencc: C:\Program Files\Rime\weasel-0.16.3\data\opencc\t2s.json
I20241206 15:32:12.924834 36936 memory.cc:127] deleting entry: '我測試一下你說呢但是我覺得可能還是不泰興'.

**Comment by asd25213** [comment]
> 請用導出文本碼表。
> 
> 快照文件需要包含刪除的記錄。

因为我才刚使用，如果我哪里理解错了还请告诉我。
另补充：
我曾想过将 *luna_pinyin.userdb* 下的文件删除，但由于占用，一部分文件被删除，另一部分未能删除。
似乎在那之后文本码表就没有变过了，每次导出都是 “导出了22条记录”。

快照不是很长，快照全文如下：

# Rime user dictionary
#@/db_name	luna_pinyin
#@/db_type	userdb
#@/rime_version	1.11.2
#@/tick	11
#@/user_id	051a12da-e4c5-4e14-9b2f-058fa91107a4
a a 	啊啊	c=1 d=0.985112 t=11
ba 	吧	c=1 d=0.980199 t=11
bu 	不	c=0 d=0.0960789 t=11
ce shi 	測試	c=0 d=0.0960789 t=11
dan shi 	但是	c=0 d=0.0960789 t=11
geng hao 	更好	c=0 d=0.099005 t=11
hai shi 	還是	c=0 d=0.0960789 t=11
jue de 	覺得	c=0 d=0.0985112 t=11
ke neng 	可能	c=0 d=0.195084 t=11
mo jie 	魔戒	c=1 d=1 t=11
na yang 	那樣	c=0 d=0.099005 t=11
na yang ke neng geng hao yi dian 	那樣可能更好一點	c=1 d=1 t=10
ni shuo ne 	你說呢	c=0 d=0.0960789 t=11
tai xing 	太行	c=1 d=0.970446 t=11
tai xing 	泰興	c=0 d=0.1 t=3
wo 	我	c=0 d=0.0960789 t=11
wo ce shi yi xia ni shuo ne dan shi wo jue de ke neng hai shi bu tai xing 	我測試一下你說呢但是我覺得可能還是不泰興	c=1 d=1 t=4
wo hai shi 	我還是	c=0 d=0.1 t=8
wo hai shi jue de 	我還是覺得	c=1 d=1 t=9
wo jue de 	我覺得	c=2 d=2.02739 t=11
yi dian 	一點	c=0 d=0.1 t=9
yi xia 	一下	c=0 d=0.1 t=3

导出文本碼表如下：
# Rime user dictionary export
#@/db_name	luna_pinyin
#@/db_type	userdb
#@/rime_version	1.11.2
#@/tick	11
#@/user_id	051a12da-e4c5-4e14-9b2f-058fa91107a4
啊啊	a a	1
吧	ba	1
不	bu	0
測試	ce shi	0
但是	dan shi	0
更好	geng hao	0
還是	hai shi	0
覺得	jue de	0
可能	ke neng	0
魔戒	mo jie	1
那樣	na yang	0
那樣可能更好一點	na yang ke neng geng hao yi dian	1
你說呢	ni shuo ne	0
太行	tai xing	1
泰興	tai xing	0
我	wo	0
我測試一下你說呢但是我覺得可能還是不泰興	wo ce shi yi xia ni shuo ne dan shi wo jue de ke neng hai shi bu tai xing	1
我還是	wo hai shi	0
我還是覺得	wo hai shi jue de	1
我覺得	wo jue de	2
一點	yi dian	0
一下	yi xia	0

**Comment by lotem** [comment]
> 但由于占用，一部分文件被删除，另一部分未能删除。

這樣做不行。數據庫可能被破壞了。須在關閉算法服務後進程時將整個 .userdb 文件夾全部刪除。

**Comment by lotem** [comment]
用家瞎刪文件，然後來報 BUG，這種問題沒辦法管。
