### ISSUE TITLE
同样的一套配置, 在linux和macos上可以动态调整词频, 也会记住用户输入的新词, 但是在windows上这两个功能都不行

### ISSUE THREAD

**Issue by netjune** [rime/home#1747]
三个系统的rime都是前些天刚下载安装的版本, 比较新.

配置文件是一样的, 但是有标题中的问题, windows上死活不能调整词频, 即使你连续反复四五次选择后面的词, 排序也完全不变化. 而且用户输入的新词也记不住. 但是另外两个系统试了下都没问题

即使在配置文件中添加了` translator/enable_user_dict: true`也不行, 没有用

windows上的版本是0.16.3.0

**Comment by ksqsf** [comment]
是不是直接复制了整个用户目录？请尝试删除 *.userdb/LOCK 再重启算法服务。

**Comment by netjune** [comment]
> 是不是直接复制了整个用户目录？请尝试删除 *.userdb/LOCK 再重启算法服务。

被你说中了, 不过删除LOCK好像还不行, 我把整个userdb目录都删了, build目录也删了, 然后重新部署, 重启系统, 现在好了

多谢
