### ISSUE TITLE
如何更換輸入法中的太極圖示‘☯？

### ISSUE THREAD

**Issue by sidottu** [rime/home#1749]
輸入時用於提示連打與自動組詞顯示的太極圖示不美觀。我想請教一下，怎麼更換或自訂這個圖示？Windows 10自帶的emoji讓人看着不適。像是安卓的fcitx5應有專門的設置項，PC端的小狼毫更換也是可以的吧？

![image](https://github.com/user-attachments/assets/e9326b4d-6de7-4cc3-b6b9-0958a68479b3)

### 參考：fcitx5的設置用於提示自動組詞的符號頁面
![fcitx5設置頁面](https://github.com/user-attachments/assets/b09f38d4-fb06-4e75-92da-5c24c13d4fa0)

> 關閉碼表輸入法連打  
> 註：這個選項僅針對 table_translator，用於屏蔽倉頡、五筆中帶有太極圖章「☯」的連打詞句選項，不可作用於拼音、注音、速成等輸入方案。  
> 
> 以【倉頡】爲例：
> 
> ```yaml
> # cangjie5.custom.yaml
> patch:
>   translator/enable_sentence: false
> ```

怎麼更換呢？這個是要用的，僅屏蔽的話，還是會出現的，還是想像fcitx5那樣自己更換其它的符號

**Comment by lotem** [comment]
patch `translator/comment_format` ，用 `xlit` 規則替換字符。

**Comment by sidottu** [comment]
@lotem 
  現在連打沒變，但是組詞變了，連打和組詞還是不一樣的麼，連打要怎麼換呢？


![image](https://github.com/user-attachments/assets/ba4057ed-5c6d-47fc-823c-48ad305d3635)
![image](https://github.com/user-attachments/assets/b2b7c541-3985-4861-a511-22713236218c)






```
translator:
  comment_format:
    - "xlit|🖋|"
```

**Comment by lotem** [comment]
看來這種方式不行。寫程序改吧。

或者關閉連打。連打大部分情況可以用自動上屏代替。

**Comment by sidottu** [comment]
> 看来种方不行。写过程法。
> 
> 逆向连字衔打印大部of可以自动上光。

換字體呢，怎麼做，主要win自帶的emoji太難看了，facebook和openmoji它們的彩色emoji陰陽做的都挺好看的，試過註冊表改成它們的但是win10還是用的自帶的彩色emoji,輸入法裏能指定emoji字體麼

**Comment by sidottu** [comment]
直接把系統的emoji字體換成win11（openmoji的☯）的了，安裝ttf後，註銷重登錄，全成win11的風格了，除了openmoji的☯，看網上說要替換系統目錄的.ttf,這個和我雙擊win11的seguiemj.ttf安裝有什麼區別呢？好像全局生效
![image](https://github.com/user-attachments/assets/1fba20f7-e0e8-4f81-ae61-a2c848a786b2)
![image](https://github.com/user-attachments/assets/d5f223cb-cb1f-4a5b-b04a-7e816f385dd5)

@lotem

**Comment by sidottu** [comment]
直接換了字體了Windows10自帶的emoji很多都不好看，直接修改的字體文件裏的陰陽換成其它字體太極了，

> 做有帮助 [#1755](https://github.com/rime/home/issues/1755)

**Comment by fxliang** [comment]
如果是0.15之后的小狼毫，可以设置指写码点范围使用特定字体来绘制的

在对应字体（当前这个应该是`style/comment_font_face`)的设定前面加上`Noto Color Emoji SVG:262f:262f, `就可以使用系统里有安装的Noto Color Emoji SVG来绘制U+262F这个字符了

![Image](https://github.com/user-attachments/assets/68405053-b01f-4870-ade4-693766a04708)
