### ISSUE TITLE
請問正在輸入中的文字可以還沒按Enter就顯示在文字編輯器當中嗎

### ISSUE THREAD

**Issue by fmnijk** [rime/home#1751]
<img width="211" alt="Snipaste_2024-12-17_15-03-31" src="https://github.com/user-attachments/assets/6e4b5513-cb73-48d2-8e4c-c758ad49efa0" />

請問正在輸入中的文字，想要在句子當中也顯示可以嗎，例如像下面這個微軟輸入法這樣，還沒按Enter就在文字編輯器裡以虛線底線顯示

<img width="85" alt="Snipaste_2024-12-17_15-03-55" src="https://github.com/user-attachments/assets/477b4d4d-f4ab-4bfa-a7e7-c03b3cf4dcb0" />

這樣只要自定義辭典設置足夠，需要選字的情況較少的話，基本上可以直接看著文章連貫的打字

**Comment by lotem** [comment]
這個功能由輸入法前端支持。比如[小狼毫](https://rime.im/release/weasel/)有這個選項：
`style/preedit_type: preview`
