### ISSUE TITLE
weasel.custom.yaml 设置不生效？

### ISSUE THREAD

**Issue by xiaohk** [rime/home#176]
我新建了`weasel.custom.yaml`

```
patch:
  "style/font_point": 6
  "style/horizontal": true
```

重新部署后界面没有变化。

版本: Squirrel 0.9.26.1

**Comment by osfans** [comment]
squirrel应该也有对应的yaml

**Comment by lotem** [comment]
請參考 https://github.com/rime/home/wiki/CustomizationGuide#鼠鬚管外觀與鍵盤設定
