### ISSUE TITLE
有计划做 候选词联想 的功能吗？

### ISSUE THREAD

**Issue by hydyy** [rime/home#177]
如题， 还是蛮须要这个功能的

**Comment by ilcn** [comment]
和词库功能有什么区别？

**Comment by ASC8384** [comment]
比方说，输入“中”后，继续显示“1.国2. 心3. 间”。
所以就是，你输入一个字母“z”，选择“中”字，联想出“国”字，又联想出“人”字，组成了中国人三个字，而不用输“zgr”

**Comment by lilydjwg** [comment]
我也想要这个功能了……因为我是在手机上使用 trime。联想功能在不少时候可以省一些按键，而手机上眼睛本来就一直盯着，再按按键的是话额外的成本了。不过需要语料库的支持，仅仅联想词库里已有的词比较鸡肋。

**Comment by gshmu** [comment]
@ASC8384 你是中国人，所以你不自己动手

**Comment by lotem** [comment]
同 https://github.com/rime/librime/issues/65 及 https://github.com/rime/librime/issues/49

**Comment by anndaming** [comment]
> 同 [rime/librime#65](https://github.com/rime/librime/issues/65) 及 [rime/librime#49](https://github.com/rime/librime/issues/49)

关于这个问题的issue相互引用，但没有一个地方明确说明支持或不支持

**Comment by QuXiang-code** [comment]
> > 同 [rime/librime#65](https://github.com/rime/librime/issues/65) 及 [rime/librime#49](https://github.com/rime/librime/issues/49)
> 
> 关于这个问题的issue相互引用，但没有一个地方明确说明支持或不支持

其实就是不行，还是要靠词库，这又是一个大工程
