### ISSUE TITLE
卷轴模式

### ISSUE THREAD

**Issue by abigdnboy** [rime/home#1770]
感谢大佬的软件，超级好用，希望可以加入卷轴模式，类似macos原生输入法的这种，大量同音候选词的时候会直观很多。

![截屏2024-12-29 16 17 32](https://github.com/user-attachments/assets/00745833-b64f-4732-8ec1-17b5a3b4ca47)

**Comment by abigdnboy** [comment]
。

**Comment by eagleoflqj** [comment]
重复 #376
可以用电脑在 https://rime.im/online/ 体验一下卷轴模式，和小企鹅 macOS 一个效果

**Comment by dyzdyz010** [comment]
> 重复 [#376](https://github.com/rime/home/issues/376) 可以用电脑在 https://rime.im/online/ 体验一下卷轴模式，和小企鹅 macOS 一个效果

请问如何设置？
