### ISSUE TITLE
无法生成用户词典，

### ISSUE THREAD

**Issue by Taamyuk** [rime/home#179]
无论怎么重装都不行

**Comment by lotem** [comment]
不瞭解你所反映的情況。問題表述也不明確（缺少主語）。
請詳細說明操作系統類型及版本，輸入法版本，使用什麼輸入方案。

用戶詞典並非一定會生成，這取決於當前輸入方案的配置，以及確實有可記錄的輸入。這是一項是對用戶透明的功能，意思是「生成了用戶詞典」這是輸入法的內部實現，用戶不必直接感知到。因此我還需要知道你是如何判斷出故障的，比如列舉具體的操作步驟，預期結果以及實際觀察到的結果。
