### ISSUE TITLE
求一個統計頻率的程式

### ISSUE THREAD

**Issue by zaqzrh** [rime/home#18]
@lotem @kunki @jakwings @osfans
----------------------------
文檔格式：字詞tab數字
----------------------------
中州韻	178951
中州韻	235090
中州韻	242959
中州韻	250956
中州韻	331354
中州韻	86212
中州韻輸入法引擎	209833
他	144401
他	203964
他	246257
小狼毫	243870
小狼毫	297457
小狼毫	340332
引擎	270779
引擎	280800
引擎	285526
引擎	96233

----------------------------
計算結果：
---------------------------
中州韻	1325522
中州韻輸入法引擎	209833
他	594622
小狼毫	881659
引擎	933338

**Comment by osfans** [comment]
這個用數據庫的分類彙總函數好像很容易做啊

**Comment by osfans** [comment]
https://github.com/osfans/rime-tool/blob/master/freq_sum.py
給你寫了一個python3的。輸入文件是同目錄下的input.txt文件，結果會自動輸出到output.txt。雙擊執行應該就可以。

**Comment by zaqzrh** [comment]
Excel的分类汇总能行，100万行的数据，要花2-3个钟。
；
这个freq_sum.py很好，不过，GBK格式文档能用，UTF-8格式不能用。
帮忙改改吧，GBK和UTF-8格式都能用吧，谢！
@osfans

**Comment by osfans** [comment]
已更新

**Comment by lotem** [comment]
高手啊 @osfans 寫得一首好 Python
