### ISSUE TITLE
On Ubuntu 17.04, How to change the default background colour of the Chinese words that are selected?

### ISSUE THREAD

**Issue by lixiaodongsql** [rime/home#182]
Hello, on Ubuntu 17.04, the default background colour of the Chinese words which are selected and which are typed out by ibus-rime Chinese characters input method is black. On Ubuntu 17.04, How to change the default background colour of the Chinese words which are selected and which are typed out by ibus-rime Chinese characters input method from black to other colours? Thank you very much for your help. I really appreciate it.

**Comment by lotem** [comment]
There are a few choices listed here in code
https://github.com/rime/ibus-rime/blob/master/rime_settings.c#L6
for the GSettings value `color_scheme` under the section `engine/Rime`.
It can be configured using [dconf](https://en.wikipedia.org/wiki/Dconf).

**Comment by lixiaodongsql** [comment]
Thank you very much for your help. I really appreciate it. On Ubuntu 17.04, How to use dconf to change the default background colour of the Chinese words which are selected and which are typed out by ibus-rime Chinese characters input method from black to white? Thank you so much for your help.
