### ISSUE TITLE
自动纠错功能能不能做个总结

### ISSUE THREAD

**Issue by CharlesHugh** [rime/home#184]
rime输入法很好用,但是他的纠错功能不知道是我的原因还是怎么,打字的时候一会别扭一下很不舒服,比如chengji,当我打成chnegji时,没法继续了!
我试过在luna_pinyin_simp.custom.yaml中增加如下字段:

> 'speller/algebra':
    - erase/^xx$/   
    - derive/(^[zcs])hn([aeiou])g$/$1h$2ng/ # chneg => cheng
重新部署了好几次都不行,还有huayuna=>huayuan,hcao=>chao,也没有试出办法来.
系统环境:鼠须管0.9.26.1 ,OS X Sierra 10.12.6
有哪位前辈知道应该修改哪里的文件可以达到自动纠正拼写的作用?

**Comment by lotem** [comment]
`- derive/(^[zcs])h([aeiou])ng$/$1hn$2g/`

**Comment by CharlesHugh** [comment]
谢谢大大，问题解决了。
纠错替换是前后颠倒的，被注释说明引导的偏了方向，没想到这点。😓
