### ISSUE TITLE
Bug 导致Edge浏览器无法使用等问题问题

### ISSUE THREAD

**Issue by programming2012** [rime/home#187]
您好：
    先提交两个直接影响使用的bug：
     bug 1
     只要把输入法切换到“小狼毫（TSF）”，然后打开Microsoft Edge浏览器，浏览器整个应用就是一个完全蓝色的状态，打开不首页及其它任何内容，已经实验多次，效果可重现
    使用微软自带输入法浏览器正常，使用“简体 小狼毫”，非TSF也没导致浏览器不能使用
    bug 2:
    使用“简体 小狼毫”在bing等搜索框或输入框，无法切换到中文状态，只能是英文输入，而且也无法使用Ctrl+“~”快捷键调出切换菜单。这个现象有时候出现，有时候正常。
    另外
    有一个不太确定的现象：
    我安装小狼毫输入法这两三天，经常出现开始按钮点不开、小娜点不开的现象，以前也从没发生过这个问题，不过这个不太确定是否是输入法导致的这种现象，可能性比较大而已。

系统:
Win10 14393 专业版

**Comment by mhohai** [comment]
建议 远离windows，远离Edge

**Comment by lotem** [comment]
@mhohai 爲什麼？

**Comment by lotem** [comment]
http://rime.im/download/ 尚不支持 Windows 10。
另請參考 https://github.com/rime/home/issues/25

**Comment by mhohai** [comment]
@lotem 安裝/更新軟件後被添加啟動項，註冊服務等。
我更加喜歡用包管理器的方式安裝更新軟件
