### ISSUE TITLE
请教一下, rime如何支持T9输入, 要怎么做

### ISSUE THREAD

**Issue by minwei0829** [rime/home#189]
请教一下, rime如何支持T9输入, 要怎么做

**Comment by lotem** [comment]
参考这篇文章，写一套输入方案。
https://github.com/rime/home/wiki/RimeWithSchemata
仿照文章的示例，在词典里定义字词的输入码。

**Comment by hydyy** [comment]
有类似的方案吗？@lotem

**Comment by lotem** [comment]
@hydyy 幾乎所有輸入方案都是這樣工作的。
比如說倉頡裏面「明」的輸入碼爲`ab`，故其詞典定義了這樣一行：
```
明    ab
```
上面那篇文章有詞典的詳細做法。仿照示例在詞典裏定義字詞的T9輸入碼即可。

**Comment by eagleoflqj** [comment]
https://github.com/xiaobai9978/rime-xiaobai_simp 供参考
