### ISSUE TITLE
能否显示一个状态小窗口？

### ISSUE THREAD

**Issue by arloan** [rime/home#190]
类似百度、搜狗输入法一样，一旦输入法处于开启状态，就显示一个小的状态窗口，提示当前的全角/半角、繁体/简体等相关输入法状态。没有这个小窗口的话有点不习惯，每次都得看一眼右上角才知道输入法是开着还是关着。

**Comment by ASC8384** [comment]
有系统托盘

**Comment by lotem** [comment]
沒有這個功能。
