### ISSUE TITLE
码表支持系统变量

### ISSUE THREAD

**Issue by gujunhk** [rime/home#194]
希望码表能支持输出系统变量，比如
在码表里配置：
date $date$
打字时键入：date，
能输出 2017-10-25

**Comment by LEOYoon-Tsaw** [comment]
已可由lua實現

**Comment by gujunhk** [comment]
确实可行；
1、先在 ~/Library/Rime下，添加rime.lua文件：
https://github.com/KyleBing/rime-wubi86-jidian/blob/master/rime.lua
如果不满意，可以再加上now编码的年月日时分秒：
```lua
    if (input == "now") then
        --- Candidate(type, start, end, text, comment)
        yield(Candidate("now", seg.start, seg._end, os.date("%Y-%m-%d %H:%M:%S"), ""))
    end
```
2、再在*.schema.yaml的translators节点下（不是translator节点！），添加一条：
```yaml 
   - lua_translator@date_translator
 ```
3、重新部署即可
