### ISSUE TITLE
有计划在做win10可用的版本么？

### ISSUE THREAD

**Issue by abelage** [rime/home#197]
有计划在做win10可用的版本么？

**Comment by lotem** [comment]
我做了。現在沒時間優化。
https://github.com/lotem/rime-gits

**Comment by GoGoogle** [comment]
有没有win10版本的五笔啊，现在一直用的微软五笔，上屏慢，打快了还不行，时不时就把字母直接上屏了。

**Comment by lotem** [comment]
最新進展： https://github.com/rime/home/issues/25
