### ISSUE TITLE
我编制了一个“单手笔顺输入法”的码表，希望各位程序员能在您正在开发的输入法中加入这个功能。

### ISSUE THREAD

**Issue by YQ-YSY** [rime/home#203]
我编制了一个“单手笔顺输入法”的码表，希望各位程序员能在您正在开发的输入法中加入这个功能。（我不会编程）
其中已经包括了近3万汉字、15万核心词汇、150万扩展词汇，全部都是TXT文本码表（而且都带拼音）。

笔顺的国家标准编码就是数字12345，我设计的六全码和精简码是0～9，
因此，“单手笔顺输入法”使用数字小键盘作为输入工具，不会与您开发中的输入法有冲突，
相反，两个输入法能成为互补关系，大大提高汉字输入效率。
用户不记得您的输入法时，就输入笔顺；用户不记得笔顺时，就输入您的输入法。

“单手笔顺输入法”开源项目网址：
https://github.com/YQ-YSY/stroke-seq_MB
发布在Ubuntu论坛的帖子介绍：
http://forum.ubuntu.org.cn/viewtopic.php?f=35&t=484603

因为笔顺码有个优点，它和拼音一样，每个人在上小学时就已经学会了，不用背字根。
所以，继五笔、拼音之后，笔顺输入也许是汉字输入法的又一个重大的改进机会，
未来甚至可以替代拼音输入法，成为最主流的汉字输入法。

**Comment by lotem** [comment]
Duplicate of https://github.com/rime/ibus-rime/issues/34
