### ISSUE TITLE
提示窗口不跟随光标，乱跳

### ISSUE THREAD

**Issue by xmokay** [rime/home#21]
环境：WIN7 32位，UAC 开启状态
重现步骤：
1 打开 NOTEPAD++
2 CTRL+F打开查找窗口
3 在查找窗口中输入文字
4 点击编辑窗口输入文字
重复步骤3、4，会发现输入法窗口不跟随鼠标。不是固定在左上角，就是固定在右下角。

小狼毫、小狼毫（TSF）都有这个问题。

后来测试发现，这个问题不稳定重现。

**Comment by lotem** [comment]
Merged into Issue #25
