### ISSUE TITLE
快捷键能否自由设置？Ctrl+` 和宇宙第一编辑器VS Code冲突

### ISSUE THREAD

**Issue by xianghongai** [rime/home#213]
使用小狼毫过程中发现，如题。

**Comment by nameoverflow** [comment]
[定製喚出方案選單的快捷鍵](https://github.com/rime/home/wiki/CustomizationGuide#%E4%B8%80%E4%BE%8B%E5%AE%9A%E8%A3%BD%E5%96%9A%E5%87%BA%E6%96%B9%E6%A1%88%E9%81%B8%E5%96%AE%E7%9A%84%E5%BF%AB%E6%8D%B7%E9%8D%B5)

**Comment by xianghongai** [comment]
@nameoverflow 自定义文件中patch项，官方wiki中是：

```
patch:
  "一級設定項/二級設定項/三級設定項": 新的設定值
  "另一個設定項": 新的設定值
```

但是官方中的说明，有的是带引号的，有的是不带引号的，这个到底是要引号了还是不要引号了？

还有带层级的，到底是要 一/1/a层级字符缩进？还是直接原对象式缩进？

最近操作中发现YAML不是很严谨和优雅，一点都不如JSON。

**Comment by xianghongai** [comment]
再记：应该取消所有的默认快捷鍵，输入法就是纯粹的输入用，用户**按需分配**快捷键，设定默认快捷键会与作业系统及其它软件产生冲突，适得其反，这样与用搜狐、腾讯输入法无二。

**Comment by nameoverflow** [comment]
手写 JSON 当配置？你是认真的吗……
用 YAML 就是为了方便书写。

**Comment by xianghongai** [comment]
我真的是认真的，YAML 这种上古时代的产物，我承认它是锐利的军刀，但是在上古时代。XML中古时代的利器，好在是标记，机读比较方便。而JSON在人去书写和解析数据这块方便多了，配置Sublime和VS Code时几乎不存在去提issues的情况。

**Comment by nameoverflow** [comment]
认为 JSON 好写的还是第一次见，我见过最虔诚的 JavaScript 教徒也承认 JSON 是给 parser 用的不是给人用的。

**Comment by xianghongai** [comment]
![2018-03-13_15-38-42](https://user-images.githubusercontent.com/2075006/37328300-a187f9c0-26d4-11e8-9279-15ee7de5e713.png)

![2018-03-13_15-44-19](https://user-images.githubusercontent.com/2075006/37328511-6c8b56a8-26d5-11e8-8be9-dd88b71a9cfd.png)

Rime是优秀的，THX。

😅  ~END~

- [也致第一次安装Rime的你](http://7xn4rm.com1.z0.glb.clouddn.com/rime/rime++.html)
- [Rime 主题在线编辑 /西米](http://7xn4rm.com1.z0.glb.clouddn.com/rime-skin/index.html)

**Comment by huangda1982** [comment]
请问在哪里能查到更全的按键名称列表。我想把日文键盘左上角的“全角/半角”键设定为快捷键按，但是不知道这个键在RIME配置文件中使用的名称。
