### ISSUE TITLE
关于markdown输入的问题

### ISSUE THREAD

**Issue by northleafup** [rime/home#214]
由于目前电脑上主力输入法是鼠须管，但是在写markdown文件时，需要来回切换中英文输入法，比如要输入markdown中的引用符号，就需要在英文状态下输入“>”， 请问有什么方法可以在不切换中英文的前提下，快速输入markdown的各种语法，谢谢。

**Comment by xianghongai** [comment]
我是直接做了一个 symbols.custom.yaml 文件，把里面的一些标点符号弄成英文状态下的了。比如：() [] {} ；还将有的弄成了成对输出，如：`` //  /**/。

**Comment by kls1991** [comment]
我现在有一个想法，还没精心设计+实现，简单提一句，也许能启发你
1. 完全使用英文标点
2. 以空格+标点符号为中文标点
3. 也许这样实现起来有难度，其实我是把空格键映射成了ctrl（中文输入用得到那么大的空格键吗？），在Rime里设置ctrl上屏（已实现），ctrl+.=。（未实现），相信不会太难
4. 这样是不是特别美好，你不必记住当前是中文还是英文，永远可以方便的输入各种标点符号。逗号句号甚至能提供三个功能：中文句号、英文句号、翻页

**Comment by kionz** [comment]
重新定义一下标点符号就可以了吧。
把ascii字符放第一位，中文标点第二位，按两下出中文标点。
kls1991 <notifications@github.com>於 2018年7月17日 週二，上午10:20寫道：

**Comment by lotem** [comment]
@kionz 按兩下不方便重複輸入字符。
另一種安排是用一個專門的鍵引導中文標點，比如用 `;`引導，則 `;.` 輸入「。」，這樣就把其他標點符號鍵解放出來了，可以直接上屏 ASCII 字符。
