### ISSUE TITLE
macbook中鼠须管不能输入ip地址

### ISSUE THREAD

**Issue by northleafup** [rime/home#215]
目前使用的电脑为macbook 10.13.3，关于输入法，最理想的状态是只保留一个鼠须管（说真心的，我个人特别喜欢鼠须管，目前用的五笔拼音输入方案），macbook上的默认的美国输入法是可以删除的， 但这就造成了一个问题，当修改ip地址时，使用鼠须管输入法无法输入ip地址，请问这个问题，各位是如何解决的。

一个临时的解决方案是： 先把macbook的美国输入法添加上，再用这个输入法去输入ip地址，输入完成后，再去删除这个输入法，不过这个方法，真的只是一个临时的方案，我就想只在电脑上保留一个鼠须管。

向各位求助，这个问题该如何处理下，谢谢。

**Comment by Prcuvu** [comment]
macOS 必须保留一个全键盘布局（如 ABC）用于限定字符的文本框和密码框的输入。在规范操作下，只保留鼠须管是做不到的。

鼠须管也无法绕过限制，在这些文本框中输入。因此最佳的做法是保留一个“ABC”。
