### ISSUE TITLE
win10 出现多个输入法选项，具体如何出现

### ISSUE THREAD

**Issue by xxlive** [rime/home#216]
![image](https://user-images.githubusercontent.com/2394609/37703973-7041d430-2d32-11e8-9013-711db3fff095.png)
win10 出现多个选项 具体原因不明 现在也不清楚怎么去除 一直用的TSF模式。
一般喜欢用Ctrl+空格 切换中英文  偶尔切换失败。

**Comment by nameoverflow** [comment]
控制面板删除。
如果是新 insider 版本控制面版没有输入法选项可以通过注册表删除。

**Comment by xxlive** [comment]
谢谢 已搞定
