### ISSUE TITLE
关于rime windows版小狼毫10的问题

### ISSUE THREAD

**Issue by tower200881** [rime/home#219]
在小狼毫0.10.0.0版中，无论使用预装的输入方案还是自制输入方案，在office word2010中卡顿，CPU资源占用急速升高，而且无输入提示窗口；

**Comment by nameoverflow** [comment]
是 WeaselServer.exe 的 CPU 占用高还是 word 的 CPU 占用高？

**Comment by tower200881** [comment]
word的CPU占用正常,是 WeaselServer.exe 的 CPU 占用高!

**Comment by tower200881** [comment]
已经找到原因，是安装，设定，重新部署后，要么重新启动电脑，要么重新启动word就好了！！估计我没重开接收输入的窗口，消息循环处发生了问题吧！

**Comment by tower200881** [comment]
一切正常了，速度还是那么快，其它的一些问题也随着重新启动电脑后消失了！还和原来一样好用！抱歉出现了这样一个弱智的问题，耽误您时间了！

**Comment by nameoverflow** [comment]
新版生成文件格式有变，第一次运行会自动重新部署。部署时会有较高的资源占用。
