### ISSUE TITLE
关于反查时有的字不提示的问题

### ISSUE THREAD

**Issue by huquanjun** [rime/home#220]
在输入方案的schema.yaml里加入了：
abc_segmentor:
  extra_tags:
    - reverse_lookup  
reverse_lookup:
  dictionary: luna_pinyin
  prism: luna_pinyin
  prefix: "`"
  tips:
    - "拼音"

但在使用过程中，有的字或词就会显示反查的结果，但是有的就没有，不知道是什么原因？如何调试？

**Comment by nameoverflow** [comment]
取决于方案词典。方案词典中有的词才会提示，没有的词（自造词）无法提示编码。

**Comment by huquanjun** [comment]
涉及到的都是方案词典中有的词，方案见附件。


[test.zip](https://github.com/rime/home/files/1845383/test.zip)

**Comment by lotem** [comment]
无重现步骤
