### ISSUE TITLE
rime是否还会考虑增加功能

### ISSUE THREAD

**Issue by llpub** [rime/home#222]
2018.3.14的时候weasel 出了win10版，可喜可贺，说明生命力还是旺盛的。
不过是否还会增加新的功能呢，比如：每页上都显示当前页number/总共候选项number（紫光输入法上看到的），
或者向mac原生输入法一样的支持候选页下拉（而不是翻页），
或者限制非单字候选项个数（词库变大时挺有用的），等等
感觉rime在功能方面是不是有点保守。。。

**Comment by lotem** [comment]
歡迎 pull request
