### ISSUE TITLE
有了build子目录后类似alternative.yaml的文件应该如何处理？

### ISSUE THREAD

**Issue by FirstLoveLife** [rime/home#223]
我知道虽然.schema.yaml现在基本都在/rime/build目录下，但是custom.yaml应该放在/rime目录下。不过我对[alternative.yaml](http://gist.github.com/2334409)这样的文件应该放在哪里感到很疑惑，两个目录都试过了，然而重新部署后都不能生效。而且luna_pinyin.schema.yaml中的punctuator/import_preset的值是symbol，并不是链接里说的default，并且两目录下都没有symbol.yaml文件，不知道是否与此相关。

**Comment by FirstLoveLife** [comment]
貌似把alternative.yaml的版本號改成luna_pinyin.schema.yaml一樣就行了.

**Comment by lotem** [comment]
放在「用戶文件夾」。跟版本号无关。

其内容被 luna_pinyin.schema.yaml 引用的部分，部署时会编译到输入方案里。 

具體解釋：[文檔](https://github.com/rime/home/wiki/Configuration) 還未寫好，先佔坑
