### ISSUE TITLE
这个不一定算Bug，算是一个安全方面的问题咨询

### ISSUE THREAD

**Issue by programming2012** [rime/home#226]
你好：
      我今天下载了0.11版本，在Virscan查毒，39个杀毒引擎中有3个报毒，报告见下方，这种情况是杀毒软件的误报，还是当前的软件触发了杀软的某些规则，这些问题是否会影响到输入法的安全性。请释疑

附：
查毒报告
http://r.virscan.org/report/24c2ca01e9b5f0c698eeb5b8879ed7d6

                                                                                                                 谢谢

**Comment by nameoverflow** [comment]
Duplicate of rime/weasel#139

**Comment by lotem** [comment]
应该不会影响安全性。但“安全软件”可能影响输入法正常工作。
