### ISSUE TITLE
使用五笔 86 方案以前按 z 可以打拼音，小狼毫 0.11.0 版本不能这样了

### ISSUE THREAD

**Issue by lll423** [rime/home#228]
在五笔状态下 以前按z可以打拼音，0.11版本后不能这样了。要怎么才能打出一些五笔不知道打的字？按z调出打拼音状态

就是旧版的    敲 z 鍵開始轉爲簡體拼音字詞輸入，反查五筆編碼。功能

新版本不知道要怎么调出

**Comment by Prcuvu** [comment]
请关注 rime/plum#1 的进展。

**Comment by lotem** [comment]
應該是缺少反查用的拼音詞典。
請按照說明安裝配方包：
https://github.com/rime/rime-wubi
