### ISSUE TITLE
Failed to emerge app-i18n/rime-data-0.35

### ISSUE THREAD

**Issue by highbuyer** [rime/home#229]
>>> Emerging (1 of 1) app-i18n/rime-data-0.35::gentoo
 * brise-0.35.tar.gz BLAKE2B SHA512 size ;-) ...                         [ ok ]
>>> Unpacking source...
>>> Unpacking brise-0.35.tar.gz to /var/tmp/portage/app-i18n/rime-data-0.35/work
>>> Source unpacked in /var/tmp/portage/app-i18n/rime-data-0.35/work
>>> Preparing source in /var/tmp/portage/app-i18n/rime-data-0.35/work/brise ...
>>> Source prepared.
>>> Configuring source in /var/tmp/portage/app-i18n/rime-data-0.35/work/brise ...
>>> Source configured.
>>> Compiling source in /var/tmp/portage/app-i18n/rime-data-0.35/work/brise ...
make -j8 
building rime data.
rime_deployer --build  /var/tmp/portage/app-i18n/rime-data-0.35/work/brise/data
>>> Source compiled.
>>> Test phase [not enabled]: app-i18n/rime-data-0.35

>>> Install rime-data-0.35 into /var/tmp/portage/app-i18n/rime-data-0.35/image/ category app-i18n
make -j8 DESTDIR=/var/tmp/portage/app-i18n/rime-data-0.35/image/ install 
installing rime data into '/var/tmp/portage/app-i18n/rime-data-0.35/image//usr/share/rime-data'.

/usr/bin/install: omitting directory '/var/tmp/portage/app-i18n/rime-data-0.35/work/brise/data/build'
make: *** [Makefile:32: install] Error 1
 * ERROR: app-i18n/rime-data-0.35::gentoo failed (install phase):
 *   emake failed

**Comment by lotem** [comment]
Not reproducible.
