### ISSUE TITLE
中文状态下 Shift_L 键能否直接 commit ascii 字符，不需再按Enter

### ISSUE THREAD

**Issue by x-ji** [rime/home#23]
这是目前不少中文输入法的默认行为。感觉再需要按Enter似乎有些多此一举。或者至少提供一个用户定制选项。目前似乎无法改变该行为。

**Comment by lotem** [comment]
可以的。有選項。
https://github.com/rime/home/wiki/CustomizationGuide#%E4%BD%BF%E7%94%A8control%E9%8D%B5%E5%88%87%E6%8F%9B%E4%B8%AD%E8%A5%BF%E6%96%87
默認值在一定程度上可以防誤操作，即再按 Shift 可以重新轉換成中文輸入碼。

**Comment by x-ji** [comment]
Thanks
