### ISSUE TITLE
Powerpoint 2016中無法正常的使用Delete

### ISSUE THREAD

**Issue by Ostrichbeta** [rime/home#232]
![35cc5578-c61c-488b-8b8b-0feb7feb2391](https://user-images.githubusercontent.com/25266479/38933805-9154050c-4309-11e8-9720-88a4c0e04480.gif)
如圖片所示，在使用TSF模式的小狼毫時，選一個圖形按下Delete會自動的切換到輸入模式，而使用非TSF模式卻沒有設置問題，是我的配置文檔在哪裡設置錯誤了嗎？

**Comment by nameoverflow** [comment]
Duplicate of https://github.com/rime/weasel/issues/193
