### ISSUE TITLE
簡體字無法設置

### ISSUE THREAD

**Issue by Acytoo** [rime/home#233]
我在使用kali linux 2018 rolling, kernel 4.15, gnome3, 使用apt-get install安裝的ibus-rime。
只能打出繁體字， 無法使用簡體字， ubuntu上的方法好像不能使用， 請問有沒有人能幫助灣解決這個問題， 或者能告訴請配置文件在哪裏？謝謝

**Comment by gshmu** [comment]
`Ctrl+~`  试试能否切换简体

**Comment by q171810031** [comment]
我在Ctrl+~試過了還是打不了簡體字 這要怎麼弄大佬幫忙解答一下
