### ISSUE TITLE
鼠鬚管 粵拼 下載問題

### ISSUE THREAD

**Issue by hkmkokpk** [rime/home#235]
不好意思 在下電腦白癡
已download squirrel master, plume master, rime-jyutping-master
但只能夠用國語拼音
已試過于mac os terminal輸入bash 指令
請問應如可解決?

**Comment by lotem** [comment]
輸入以下命令下載

`curl -fsSL https://git.io/rime-install | bash -s -- jyutping`

或者已下載 plum，用命令：

```sh
cd plum
./rime-install jyutping
```

然後按照以下說明啓用粵拼
https://github.com/rime/home/wiki/CustomizationGuide#%E5%88%9D%E5%A7%8B%E8%A8%AD%E5%AE%9A

**Comment by lotem** [comment]
猜想問題在於不知如何啓用輸入方案。簡化這一步驟，有賴於實現「啓用輸入方案」 [配方化](https://github.com/rime/plum/issues/4)。

**Comment by richardjhou** [comment]
Thanks!
