### ISSUE TITLE
使用 Karabiner 将 left-control 映射到 caps-lock 之后，中英文切换似乎有问题

### ISSUE THREAD

**Issue by adow** [rime/home#239]
为了让 HHKB 用 `left-control` 切换中英文，在 Karabiner 里面添加了一个将“单独按下左边 control 映射到大写键” 的配置，但是鼠须管似乎在切换的时候会有一个问题：在英文状态下可以切换到中文，但是在中文状态下不能切换到英文。似乎是因为这时候还是会发出两个键，“left-control” 和 "caps_lock"。我想既然能在英文状态下切换，那在中文状态下切换也应该是可以的吧，所以我想问问这里的设置是不是有问题？这个配置里有一个 `to` 和 `to_if_alone`,没法去掉 `to`，这样就真没有 `left-control` 了。

![img](https://pbs.twimg.com/media/DcUe8KUUQAAAQOX.jpg)

![img](https://pbs.twimg.com/media/DcUfLWoVQAAcZEs.jpg)

**Comment by lotem** [comment]
不熟悉 karabiner 的用法。
不过你似乎走了弯路。
rime 支持将 `Control_L` 定义为中西文切换键。

**Comment by adow** [comment]
macOS 下 rime 似乎区分不了 left/right，所以才用了 Karabiner

发自我的 iPhone

**Comment by adow** [comment]
用了这么多年 macOS 我居然才发现原来键盘上只有一个 ctrl，没有右边那个的，HHKB 也没有右边的 ctrol，所以这个看来其实不是个问题。

**Comment by lotem** [comment]
HHKB 不是只有左边的 Control 键嘛？

**Comment by adow** [comment]
是哦，我一直以为是有两个的😂

发自我的 iPhone

**Comment by gshmu** [comment]
@adow 改什么键位，你需要的是换个键盘，安利一个Kinesis Advantage
![image](https://user-images.githubusercontent.com/1797676/39613863-9f4aa882-4f9d-11e8-9883-73d5eb3bd5c7.png)
