### ISSUE TITLE
自动在中英字符之间加入空格

### ISSUE THREAD

**Issue by x-ji** [rime/home#24]
目前搜狗输入法等中文输入法提供该选项。这样的确会让文本可读性增加。不知implement起来有否难度？

例：`我用 rime 输入法引擎`

**Comment by lotem** [comment]
會做

**Comment by fishpaw** [comment]
这个目前做了么？

**Comment by lotem** [comment]
沒做…

**Comment by ooopscc** [comment]
@lotem 能提供个思路如何实现么？
我现在使用的是五笔输入法，怎么样实现如果当前是中文状态，按了一串英文按enter直接在输出的文字前加一个空格，如果刚才输出了英文就在下一次输出时也加上空格。
英文dict的方式不太行，因为我也不知道我会输出些什么字母。。
直接改Squirrel的源码也ok，有可行的思路就行。谢谢。
最后效果这样：
![1](https://user-images.githubusercontent.com/1056803/34070533-130ff60e-e2a3-11e7-9a62-b02c3e1e032b.gif)

**Comment by huangyafei** [comment]
所以现在这个做了么。

**Comment by alfredcai** [comment]
焦急等待中。。。

**Comment by lotem** [comment]
現在看來這個需求是不必要的。我不再打算實現該功能。

**Comment by s5unty** [comment]
输入法没有的，只有靠编辑器了

```vim
" ref: https://github.com/yuweijun/vim-space
function! SpaceAddBetweenEnglishChinese() range
    for linenum in range(line("'<"), line("'>"))
        let oldline = getline(linenum)
        let newline = substitute(oldline, '\([\u4e00-\u9fa5]\)\(\w\)', '\1 \2', 'g')
        let newline = substitute(newline, '\(\w\)\([\u4e00-\u9fa5]\)', '\1 \2', 'g')
        call setline(linenum, newline)
    endfor
endfunction

vmap <silent> <unique> ; :call SpaceAddBetweenEnglishChinese()<CR>
```

```vim
" ~/.vim/ftplugin/mail.vim
autocmd BufWrite mutt* call BetweenEnglishChinese()
function! BetweenEnglishChinese()
    " 到邮件签名为止，剩余部分不用管
    let tailine = search('^-- $', 'n')
    for linenum in range(1, tailine)
        let oldline = getline(linenum)
        let newline = substitute(oldline, '\([\u4e00-\u9fa5]\)\(\w\)', '\1 \2', 'g')
        let newline = substitute(newline, '\(\w\)\([\u4e00-\u9fa5]\)', '\1 \2', 'g')
        call setline(linenum, newline)
    endfor
endfunction
```

**Comment by ooopscc** [comment]
关键你不一定在哪里输入的....

**Comment by nb5p** [comment]
我认为中文和英文之间留有一定的距离的确可以使得排版更令人舒适。但这个间距应该由排版软件完成，而不是通过添加空格完成

**Comment by ooopscc** [comment]
可以体验一下清歌五笔输入法

**Comment by merak0514** [comment]
感觉这个功能挺重要的，作者可以考虑实现一下吗？

**Comment by PeterChen1997** [comment]
求问

**Comment by lotem** [comment]
我的理解是，自动增加空格并非所有情况都适用。例如在名词内部的汉字和拉丁字母之间，通常不加空格。《中文排版指北》对此举出一例：「豆瓣FM」等产品名词，按照官方所定义的格式书写。其他诸如「X光」「U盘」「阿Q」增加空格也有点儿奇怪。因此要不要加，在何处加还是要靠书写者自己把握。目前的实现，是最灵活、最精确的。

**Comment by PeterChen1997** [comment]
> 我的理解是，自动增加空格并非所有情况都适用。例如在名词内部的汉字和拉丁字母之间，通常不加空格。《中文排版指北》对此举出一例：「豆瓣FM」等产品名词，按照官方所定义的格式书写。其他诸如「X光」「U盘」「阿Q」增加空格也有点儿奇怪。因此要不要加，在何处加还是要靠书写者自己把握。目前的实现，是最灵活、最精确的。

了解，感谢回复，我之前一直在用 mac 上的搜狗输入法，发现里面应该是有一个术语库，然后同时会记录上一个输入的内容，术语库中的不做分割，除此之外的中英文会做处理，之前使用期间一直没发现明显问题，想请教下这块是否可行呢，可行的话，我空了去摸索一下，非伸手党，感谢~！

**Comment by chenyukang** [comment]
期待这个功能

**Comment by merak0514** [comment]
虽然听起来有点站着说话不腰疼，不过我觉得也许把功能实现出来给用户选择是否开启是不错的思路

**Comment by fastfading** [comment]
https://github.com/iDvel/rime-ice/issues/492
我的工作环境会大量用到中英混合输入
如果频繁切换会很麻烦。
所以我切到这个输入法。
但是遇到一个问题，
如果输入的是英文，需要敲2次空格，
第一次是确定英文输入，第二次才是真正的空格。
英文单词之间都是通过空格隔开的。 所以我希望这个智能一点。
省略第二个空格。

这个是有需求的
