### ISSUE TITLE
词库疑问求教

### ISSUE THREAD

**Issue by llpub** [rime/home#243]
据我所知Rime自带的词库应该是essay.txt。在增加其它词库的时候，想去掉essay.txt里已经有的词语（贴吧里有人说重码还是有影响的）。
但是还不清楚Rime中版本更新的时候essay.txt的变化是否很大？如果essay.txt变化很大，相当于每次更新Rime都要重新去词库的重复？
还想确认一下就是，如果不去掉增加多个词库带来的大量重复词语，这有多大可能会影响候选或者导致一些不可知的问题？
有点类似强迫症了，谢谢

**Comment by lotem** [comment]
essay.txt 不能直接使用，他提供了一份不含編碼的詞彙表，供韻書（*.dict.yaml）導入。
韻書提供字詞的編碼，可以選擇導入 essay.txt 詞彙，這時會按照韻書定義的單字編碼自動爲詞語編碼；
如果需要精確控制所需的詞彙，也可以選擇不導入，把所需的全部詞彙寫在韻書文件（*.dict.yaml）裏。

重碼是指 **不同** 字詞在某個輸入法裏具有相同的編碼。這取決於韻書定義的編碼方案，以及編入韻書詞彙量的多少。同一個字／詞在不同文件之間重複與重碼問題無關。

**Comment by llpub** [comment]
受教了，多谢大神耐心解释。
词库间重复的词语打算放着不管了，不然折腾太多。
