### ISSUE TITLE
请教一下, 如何设置 空格 逗号 句号 上屏英文

### ISSUE THREAD

**Issue by RRRRRm** [rime/home#249]
经常敲代码的时候忘记切成英文输入, 不小心按了空格上屏的却是中文, 有办法设置成英文吗

**Comment by Prcuvu** [comment]
不在 ascii_mode 下，按键自动提交的一定是候选项。
目前只能通过按 <kbd>Shift</kbd> + <kbd>Enter</kbd> 上屏转换后的编码。拼音的话只会被切分，如果是注音和仓颉之类还会将按键码转换成注音符号或字根的输入方案，就完全无法输入英文。
总之，请试着养成手动切换模式的习惯。这对于 Windows 10 自带的输入法也是如此。

**Comment by RRRRRm** [comment]
抱歉,是我没有描述清楚我的需求,我是想在按下空格键的时候转换到ascii_mode并将之前敲下的字母加上空格后上屏
比如我想输入`sudo do_something`, 而我忘记切成ascii_mode,现有的朙月拼音方案会打出来`速冻`,如果空格键的功能是"转换到ascii_mode",就不会有这个问题
试了下在`default.custom`加入
```yaml
ascii_composer/switch_key:
    space: commit_code
```
但是好像不起作用

加入
```yaml
key_binder/bindings:
    - {accept: space, send: Return, when: always}
```
可以临时转换到ascii_mode,但是空格本身就输入不了了

**Comment by lotem** [comment]
樓主的需求比較少見。
難道打中文不需要用空格上屏嘛？

**Comment by xiaoqun2016** [comment]
①空格上屏英文
若输入方案用的是 fluency_editor （语句流，如注音方案），可以这样：
```yaml
    - { when: has_menu, accept: space, send: Control+Return }
```

若用的是 express_editor，可以这样：
```yaml
    - { when: has_menu, accept: space, send: Return }
```


②空格上屏英文并转换到 ascii_mode ：
```yaml
    - { when: composing, accept: space, toggle: ascii_mode }
    - { when: composing, accept: Release+space, send: Control+Return }
```
（追加空格暂时做不到）  


以上，上屏英文或并转换 ascii_mode 的方法应该有些用处，至于是用空格键还是其它组合键来执行，就看个人习惯了  
可能下面这样更实用吧？：  
```yaml
    - { when: composing, accept: Control+Return, toggle: ascii_mode }
    - { when: composing, accept: Release+Control+Return, send: Control+Return }
```

**Comment by xiaoqun2016** [comment]
另有个现象：
方案用 fluency_editor 时，  
<kbd>Control</kbd> + <kbd>Return</kbd> 是 commit_raw_input 上屏原始输入  
<kbd>Shift</kbd> + <kbd>Return</kbd> 是 commit_script_text 上屏变换后输入  

而在用 express_editor 时，  
<kbd>Control</kbd> + <kbd>Return</kbd> 和 <kbd>Shift</kbd> + <kbd>Return</kbd> 都是 commit_script_text 上屏变换后输入  


 <kbd>Control</kbd> + <kbd>Return</kbd> 的行为不一致，貌似会增加记忆负担。有没有必要统一下？ 
@lotem

**Comment by debeetle** [comment]
temperatures-
