### ISSUE TITLE
小狼毫前端的兼容性問題將不再修復

### ISSUE THREAD

**Issue by lotem** [rime/home#25]
# 通告

https://github.com/rime/weasel
該前端程序一直存在與 Windows 8 以上的 Metro 模式、IE 保護模式、全屏遊戲以及某些應用軟件不兼容的問題，各個修復則工作量巨大，所以決定遷移到比較成熟的第三方 Windows 輸入法前端框架，以避免浪費開發資源。
完成遷移後，目前的前端代碼將不再維護。
新的輸入法將完整包含 https://github.com/rime/librime 的功能。產品名稱和發佈形式待定。不保證複刻舊版小狼毫的介面和特有功能。

因此，[Issues](https://github.com/rime/home/issues) 中記錄的此類問題會合併到這裏。

**Comment by wyxbc** [comment]
lotem在行动，赞！

**Comment by LEOYoon-Tsaw** [comment]
期待新前端的表現！

**Comment by Ansen** [comment]
期待ing

**Comment by daya-prac** [comment]
公子加油！期待公子的新作

**Comment by zaqzrh** [comment]
等待Windows 10 & Windows10 Mobile新版

**Comment by kunki** [comment]
期待Google Input Tools（前端）與Rime（後端）的合體。

**Comment by fouch** [comment]
加油！

**Comment by dirdir** [comment]
虽对小狼毫早有耳闻，但真正用起来还是在使用 Windows 8.1 之后，之前原本很好用的极点五笔、搜狗五笔、QQ五笔都出现了各种兼容问题，无奈之中，却让我有机会认识了这样一个界面简单、配置复杂，却努力把输入体验细节做到极致的输入平台--小狼毫，虽不完美，但却让人爱不释手，真的要谢谢佛大大！

但通过长时间的使用，发现尽管小狼毫提供了TSF和传统IME两个版本，但也偶尔会出现一些兼容性的问题，所以就一直盼望着盼望着小狼毫在这方面的改进，直到看到佛大大发布此消息，有些失望，但同时不知道这是不是意味着一个新的起点，也许在不久的将来就可以看到小狼毫的新生！佛大大的功力是毋庸置疑的，但我们也都清楚，一个人的精力是有限的，尤其是利用自己的业余时间来创作出如此伟大的作品，已经难能不易。我是真心的喜欢她，只能尝试着去包容她的一切……

经过一段时间对各种五笔输入法的测试，现在在系统上保留了两个输入法，基本上以小狼毫为主，百度五笔为辅，各自有问题时互补着使用。看着现在各种拼音输入法的百花齐放，争香斗艳，频频更新，想想相比之下五笔用户真是很可怜，难道随着Windows系统的升级和五笔新用户的减少，五笔终将消失吗？做梦都想着能有一款输入法能集“极点五笔、QQ五笔、百度五笔、小狼毫”之长，但也许这只能是梦了……

Windows 10 更新已经推送了，我却一直不敢点击升级，无他，只为五笔……

**Comment by ziloeng** [comment]
支持一下！！另外可以先提供下新版前端的開發文檔嗎？據說前端是Google Input Tools，但沒有搜索到相關內容……

**Comment by luciferz2012** [comment]
目前在考虑哪些第三方输入法框架呢？

昨天才开始用小狼毫的五笔，连打句子感觉太舒服了，却不能在Win10的Metro界面下使用，真可惜。
现在是小狼毫桌面版+微软自带五笔及拼音，期待新输入法！

**Comment by yimng** [comment]
不重新造轮子，聪明的选择

**Comment by lotem** [comment]
最近忙於俗務，還沒準備好發佈。
一項進展：諮詢了 Google 輸入法框架的開發團隊，官方沒有計劃爲其開源版本 IME 框架發佈二進制包，表示同意由其他開源項目發佈包含這套框架的輸入法。
已經準備好的集成方案是：把 Rime 封裝成一個 engine 以插件形式集成到 Google Input Tools。

**Comment by luciferz2012** [comment]
发现了一个叫多多中文的输入法生成器平台，可在Win10的Edge浏览器中使用。这个平台上面有人做了五笔、三拼、双拼等输入法。目前在用精灵五笔输入法，还不错，就是有点想念小狼毫的连打句子功能。

多多中文：http://chinput.com/portal.php

精灵五笔：http://jlwubi.com/

**Comment by daya-prac** [comment]
公子可否透露一下大概的发布时间？

**Comment by rimefan** [comment]
就等着双十发布

**Comment by daya-prac** [comment]
终于等到今天

**Comment by lotem** [comment]
散裝的 rime with gits
https://bintray.com/lotem/rime/rime-gits/0
http://pan.baidu.com/s/1i3GW9LV

**Comment by HouMuYi** [comment]
小弟用正體中文版Windows7x64安裝「rime-gits-20151010-alpha」後：
![2015-10-11 simg-004](https://cloud.githubusercontent.com/assets/15069632/10413841/6e1a41f2-6fec-11e5-96d1-df04b7ee2366.png)

輸入法出現在簡體處：
![2015-10-11 simg-005](https://cloud.githubusercontent.com/assets/15069632/10413845/8e7309de-6fec-11e5-9f0f-c9e828a509e8.png)

不知如何呼喚出注音（似乎未預選，找不到設定處）：
![2015-10-11 simg-007](https://cloud.githubusercontent.com/assets/15069632/10413865/9676c0c0-6fed-11e5-975b-5ac602dc9713.png)

UI沒有正常的文字（似乎是語系的變數名）：
![2015-10-11 simg-008](https://cloud.githubusercontent.com/assets/15069632/10413870/eef99b50-6fed-11e5-8e51-fa2a2c38a7ac.png)
![2015-10-11 simg-009](https://cloud.githubusercontent.com/assets/15069632/10413871/eefdaa7e-6fed-11e5-88c3-80c4c67226a0.png)

**Comment by daya-prac** [comment]
感謝公子忙到深夜爲大家帶來新版的Rime

**Comment by be5invis** [comment]
4K 分辨率下面跟随仍然有问题，比不上企鹅

**Comment by kunki** [comment]
@HouMuYi 
將輸入法安裝到臺灣，可參攷這篇貼子：http://tieba.baidu.com/p/4098749219
要呼喚出注音，可在安裝前編輯`default.yaml`，在`schema_list`後面加上一欄注音（id號爲`bopomofo_tw`），然後再安裝。

**Comment by HouMuYi** [comment]
@kunki 
感謝，我試試。

**Comment by ipcjs** [comment]
rime-gits-20151010-alpha不能使用以前的方式导入自定义词库吗？（[导入词库教程](http://tieba.baidu.com/p/2757690418)）

**Comment by littleq0903** [comment]
不用在安装前编辑 default.yaml，跟一般的 rime 一样，这个版本支持 custom.yaml 的，只是位置变了：```C:\Users\<username>\AppData\Roaming\Google\Google Input Tools\Rime```

如果需要重新部署，创建一个 ```DeployRIME.bat```，放入以下内容：

```batch
net stop googleinputservice
taskkill /f /im googleinputhandler.exe
net start googleinputservice
```

改完设定档后，点两下就可以重新 deploy 了，大家试试。

IT WORKS ON MY MACHINE!

**Comment by syler** [comment]
测试了，没有双拼方案，大家怎么加入双拼呢？

**Comment by ipcjs** [comment]
@syler 把老版的配置文件全部copy到新版的配置目录， 就有双拼了~~

**Comment by qqldd** [comment]
还是没有新版的repo和稳定发布？

**Comment by zhangnew** [comment]
新版什么时候发布啊。。

**Comment by biaoyinzi** [comment]
我是新用戶，非常喜歡RIME輸入法。個人覺得現有版本在Windows10上工作得挺好的，新框架要求並不緊迫？不過如果能開放開發分支，願意加入開發隊伍，幫助大大實現一些簡單的功能。

**Comment by osfans** [comment]
@biaoyinzi https://github.com/lotem/rime-gits 或者 https://github.com/osfans/PIME 或者小狼毫 欢迎加入

**Comment by lotem** [comment]
@biaoyinzi 歡迎。
以上由 osfans 提到的兩個分支，前端用了不同的開源技術。您可以先拉代碼把玩一下，看看哪裏需要改進，並且有興趣做，咱們再討論具體方案。

**Comment by qqldd** [comment]
谢谢 @osfans 的提示，发现 EasyIME已经可以支持Rime了，自己编译了 @osfans 版本，能看到输入法，但是输入不了字。当然这是另一个topic，会在@osfan 里面提出

**Comment by nameoverflow** [comment]
研究了一下现有的小狼豪代码，似乎不兼容问题主要出在使用 `SendWindowMessage` 和 `shared_memory` 来进行跨进程交互，而 `winrt` 的应用不允许这种 IPC。换个跨进程交互方式似乎可以改善……

Google Input Tool 和 PIME 都是用的 `NamedPipe` 来实现交互，或许近期我可以试试。

**Comment by lotem** [comment]
大讚。
另外 Google Input Tools 不好嘛？我覺得把 WeaselPanel 移植過去替代 widgets 介面也是個思路。

**Comment by nameoverflow** [comment]
@lotem Google Input Tools 太复杂了，也没个文档，看了一会也没搞明白那套插件要怎么弄……

**Comment by lotem** [comment]
@nameoverflow 支持你。 
那就分頭行動吧。反正我最近也沒有時間改裝 Google Input Tools。
只不過 weasel 還有和不少應用程序的兼容性問題。

**Comment by nameoverflow** [comment]
https://github.com/nameoverflow/weasel/tree/winrt

基本可用了，顺便修复了 inline preedict 的问题和高分屏适配，只是需要手动启动 WeaselServer，准备改成 win32 service。不知道能否兼容 windows 8.1 以下。

这几行字就是用小狼毫在 edge 下输入的😋

**Comment by littleq0903** [comment]
大神！太強了。

**Comment by nameoverflow** [comment]
放弃了，似乎 win32 service 不能直接支持创建窗口。暂时先用自启动和`RegisterApplicationRestart`也能满足保持 server 运行的需求了。

https://pan.baidu.com/s/1mkd1dSO `u959`

build 了个覆盖更新的散装版

**Comment by Prcuvu** [comment]
@nameoverflow 你可以先将代码提交到 Pull Request。为此我一定尽最大努力抽出时间审阅。一旦你的代码合并到主仓库，我会考虑尽快推出新的发行版。

**Comment by daya-prac** [comment]
@lotem Google input tools 最后一次代码提交是在2016年1月份，两年没有更新过，应该也有很多兼容性问题吧

**Comment by david50407** [comment]
太牛了 終於有機會在 UWP 下用 RIME

**Comment by llmm0o** [comment]
垃圾贴吧无法回复！

还没装上，浏览了批处理，有几处可以完善：
1、set 后面整个内容需要用双引号括起来，比如应该写成：set "WEASEL_INSTALL_OPTION=/s";
2、多层路径跳转，用一对pushd/popd比较理想：
```
set CD_BACK=%CD%
cd "%~dp0"
.........
cd "%CD_BACK%"
```
可以改成如下，跟你的原意一样：
```
pushd "%~dp0"
..........
popd
```
3、判断系统版本号，最简单通用的是 ver 命令了吧，你的意图只需要如下两行，不用借助js：
```
ver | find "5.1." > NUL && goto xp_install    
ver | find "5.2." > NUL && goto xp_install
```
4、获取管理员权限运行，只需要一行命令：
`%1 mshta vbscript:createobject("shell.application").shellexecute("""%~0""","::",,"runas",1)(window.close)&& exit`
5、判断是否64位，更简单准确的方法是这样：
```
if "%Processor_Architecture%%Processor_Architew6432%" equ "x86" (
echo x86
) else (
echo x64
)
```
6、如果需要安装为系统服务：
`sc create WeaselServer start= AUTO obj= "BUILTIN\Administrators" Binpath= "%cd%\WeaselServer.exe" DisplayName= "Weasel Server"`

依我的习惯，整个批处理改成这样，仅供参考：
```
@echo off
%1 mshta vbscript:createobject("shell.application").shellexecute("""%~0""","::",,"runas",1)(window.close)&& exit

rem argument 1: [ /s | /t ] register ime as zh_CN | zh_TW keyboard layout
set "WEASEL_INSTALL_OPTION=/s"
if /i "%1" == "/t" set "WEASEL_INSTALL_OPTION=/t"

pushd "%~dp0"

echo stopping service from an older version.
call stop_service.bat

echo configuring preset input schemas...
WeaselDeployer.exe /install

echo registering Weasel IME to your system.

ver | find "5.1." > NUL &&  goto xp_install
ver | find "5.2." > NUL &&  goto xp_install

if "%Processor_Architecture%%Processor_Architew6432%" equ "x86" (
:win7_install
WeaselSetup.exe %WEASEL_INSTALL_OPTION%
rem regsvr32.exe /s "%CD%\weasel.dll"
goto end
) else (
:win7_x64_install
WeaselSetupx64.exe %WEASEL_INSTALL_OPTION%
rem regsvr32.exe /s "%CD%\weasel.dll"
rem regsvr32.exe /s "%CD%\weaselx64.dll"
goto end
)
:xp_install
WeaselSetup.exe %WEASEL_INSTALL_OPTION%
goto end

:end
reg add "HKCU\Software\Microsoft\Windows\CurrentVersion\Run" /v Weasel /t REG_SZ /d "%CD%\WeaselServer.exe"
WeaselServer.exe

```

**Comment by llmm0o** [comment]
用批处理安装到win10，完全没法打汉字，很失望。

**Comment by llmm0o** [comment]
我发现小小输入法兼容性很好，可定制很强，只是我不懂怎么把它定制成双拼+声调。你们谁会？

**Comment by Prcuvu** [comment]
@lotem 可以关闭这个问题了。

**Comment by lotem** [comment]
感謝各位！克服了最大的兼容性問題。開發得以繼續。
@nameoverflow @Prcuvu

**Comment by nameoverflow** [comment]
还有 https://github.com/rime/home/issues/197 、https://github.com/rime/home/issues/69 都可以 close 了。
