### ISSUE TITLE
朙月拼音輸入簡拼「wa」選不到「無礙」

### ISSUE THREAD

**Issue by danny0838** [rime/home#252]
如題，使用預設的朙月拼音方案（luna_pinyin.scheme.yaml 版本 0.24）、預設的朙月拼音詞典（luna_pinyin.dict.yaml 版本 2018.04.15），在 Windows 7 上的小狼毫測試：**輸入「wa」時，候選詞不會出現「無礙」、「吾愛」、「霧靄」等詞**。

按 luna_pinyin.scheme.yaml 的 `abbrev/^([a-z]).+$/$1/`，「無」（wo）應產生簡碼「w」，「礙」（ai）應產生簡碼「a」；實際上輸入「w」候選字有「無」，輸入「a」候選字卻沒有「礙」，不曉得是什麼因素造成的影響？

**Comment by lotem** [comment]
有意爲之。
輸入串匹配完整音節時不解釋爲簡拼。

**Comment by danny0838** [comment]
請問此特性是由其他 .yaml 內設定的規則決定？或是寫死在程式碼內的？
