### ISSUE TITLE
怎样显示更多候选词

### ISSUE THREAD

**Issue by sunshoe** [rime/home#253]
习惯了搜狗输入法的设置，点击tab键即可看到更多候选词，这样在输入生僻字时比较节省时间， Rime 有实现这个功能吗 ?
如图
![image](https://user-images.githubusercontent.com/24785546/42130090-45f5da76-7c9e-11e8-8ba1-b859c5b6036e.png)

**Comment by lotem** [comment]
沒有這個介面。
可以把 `Tab`  鍵綁定到向後翻頁模擬該種行爲。
