### ISSUE TITLE
形码超出四码时能否清除输入

### ISSUE THREAD

**Issue by Deathseyes** [rime/home#255]
现在是可以正常使用第五码自动将第一候选上屏的，但是在没有候选时仍是继续输入的状态，能不能设置4码没有候选时自动清除输入

**Comment by nameoverflow** [comment]
方案里设置 `speller/auto_clear: auto`

**Comment by lotem** [comment]
對「空碼清屏」功能的討論 https://github.com/rime/librime/issues/60
