### ISSUE TITLE
若将 Control_L 设为 clear，按下 Control_L 后除清除已输入字符外，还会造成中英切换

### ISSUE THREAD

**Issue by x-ji** [rime/home#26]
也报告在了 https://github.com/rime/squirrel/issues/61 无法用其它系统测试，不确定是鼠须管的问题还是各版本共有。

如果我在`default.custom.yaml`中加入如下设置：

```
  "ascii_composer/switch_key":
    Caps_Lock: clear
    Control_L: clear
    Control_R: noop
    Eisu_toggle: clear
    Shift_L: commit_code
    Shift_R: commit_text
```

按下Control后会造成中英切换，无论我已输入一定字符还是并未输入任何内容。虽然`clear`的效用也起到了，但这个副作用就造成了这样的设置不可用。

**Comment by lotem** [comment]
你理解錯了。這項設置是在定義中英文切換時對已有輸入的處理方式。`clear` 意思是切換的時候（如果有，則）捨棄未提交的輸入內容。
只要清除輸入內容，請用 `Escape` 或 `Control+g`。
