### ISSUE TITLE
建議推出big5（大五碼）輸入方案

### ISSUE THREAD

**Issue by yurivikyi** [rime/home#263]
有些舊的遊戲（例如太閣立志傳5、暗榮三國志系列等）只能輸入大五碼來顯示正確文字，否則就是亂碼。

小弟目前只能使用搜狗輸入法來輸入大五碼，不過小弟一向討厭搜狗…………

所以建議rime日後可以推出big5（大五碼）輸入方案，用朙月拼音（或其他輸入方案）來輸入大五碼。

THX~

**Comment by lotem** [comment]
不管。
