### ISSUE TITLE
点击输入框导致chrome浏览器关闭

### ISSUE THREAD

**Issue by Dy64** [rime/home#264]
流程：
1.随便输入一些文字
2.点击浏览器空白处，输入框不消失（有一定概率不消失）
3.鼠标点击输入框，chrome浏览器会直接关闭（100%）

环境
win10 1803 17134.254
rime：最新0.11.1
chrome浏览器版本：
版本 68.0.3440.106（正式版本） （64 位）
版本 69.0.3497.81（正式版本） （64 位）

![default](https://user-images.githubusercontent.com/35034348/45067051-e2001d80-b0f3-11e8-8ec2-7d8890c913e1.png)

**Comment by nameoverflow** [comment]
Close via https://github.com/rime/weasel/commit/211550e4b094de8c6dbacbcf7400e47ee9b203fd
