### ISSUE TITLE
在Chrome地址栏打字的时候，删掉字母的同时会把已经打出来的字删掉。

### ISSUE THREAD

**Issue by Euniceisnice** [rime/home#267]
在Chrome地址栏打字的时候，删掉字母的同时会把已经打出来的字删掉。

举个例子，我打粤语拼音，想要打“香港牙科”这四个字

先打了“香港”

然后打“牙科”的拼音ngaa fo

然后打完ngaa这四个字母，我想要删掉，按退格键。

删掉一个a，没有问题。

删掉从右边数第二个a，同时“港”字也被删掉了！

Mac系统

Chrome浏览器

**Comment by ruiqi** [comment]
Hi，遇到同样的问题。有解决办法吗？

**Comment by flaming** [comment]
我使用的五笔86，某天开始也出现了同样的问题

**Comment by Euniceisnice** [comment]
我的方法治标不治本，那就是不要在地址栏打非英文的文字，想要搜索中文内容的话就去搜索引擎主页的搜索框里面打中文字……而不是在地址栏打中文字……
剩下的等开发者吧……

**Comment by someoneiscoding** [comment]
遇到同样的问题，插眼关注

**Comment by lanjuzi** [comment]
inline_preedit 参数为 false 的时候我也存在这个问题，改为 true 后正常了

**Comment by Wujidadi** [comment]
目前鼠鬚管仍有此問題，改 inline_preedit 的辦法治標不治本，未知究竟何解

**Comment by lotem** [comment]
fixed https://github.com/rime/squirrel/issues/299
