### ISSUE TITLE
拼音输入时输入越全按理来说准确度越高，也就是可选词越少

### ISSUE THREAD

**Issue by a1459919** [rime/home#27]
但是，安装后的缺省设置却不是这样。比如，如下图所示，我打 zheyang 按理说只“这样”和“遮阳”出现时合理的，但是，“遮掩”、“遮眼”甚至“中耳炎”也出现在选单上，就不合理了：

![rime_input](https://cloud.githubusercontent.com/assets/13673362/9105282/88023c84-3bd3-11e5-83d5-11b1200a2412.jpg)

那么，如何改动设置，以便只有准确的选择出现，而类似联想类的词不出现能？

**Comment by lotem** [comment]
是什麼版本？
「遮掩」等選項只對應拼音切分爲「zhe'yan'g」的前兩個音節。這種候選是需要包含的，比如輸入「tuan」候選中也會在「團」之後列出「土、圖」，從而逐字選出「圖案」等詞語。
但是因爲這一例第三個音節僅僅爲簡拼「g」，應該捨棄這種切分方式。懷疑：① librime 版本太低；或者 ② 詞典被改過，加入了「g」使其變成一個完整音節了。

**Comment by a1459919** [comment]
不知道什么版本。我的系统是Linux，是通过ibus装的这个输入法

**Comment by a1459919** [comment]
這可能是全拼或簡拼的設置？在哪裏有如此設定呢？

**Comment by lotem** [comment]
你設置了什麼？
如果沒有修改任何設定，那就是音節切分的錯誤。但是用最新版本無法重現。

**Comment by daya-prac** [comment]
你的Linuxmint是哪个版本的？会不会是源里的ibus-rime版本太旧了？

**Comment by a1459919** [comment]
我的 Linuxmint 是最新版本 17.2。如果iBus裏面的Rime太舊了，那麼，Rime還在其它哪裏有呢？除了iBus，Linuxmint 允許安裝這些輸入平臺： Fcitex, SCIM, UIM, gcin
