### ISSUE TITLE
如何删除“输入法（仅桌面）”这一选项

### ISSUE THREAD

**Issue by ragnaroks** [rime/home#270]
使用`windows+space`切换输入法，这样会造成额外需要切换一次，
如何删除“输入法（仅桌面）”这一选项，只保留“输入法（TSF）”

![](https://user-images.githubusercontent.com/7598199/45858124-745c1e80-bd8e-11e8-8d98-5fdc435dff1a.png)

输入法（仅桌面）不能删除
![输入法（仅桌面）不能删除](https://user-images.githubusercontent.com/7598199/45858129-77570f00-bd8e-11e8-857e-8175b6415ddc.png)

输入法（TSF）却可以删除
![输入法（TSF）却可以删除](https://user-images.githubusercontent.com/7598199/45858194-c4d37c00-bd8e-11e8-9681-d59fa5e61c18.png)

**Comment by nameoverflow** [comment]
下个版本就没有了。
目前删除方法见 rime/weasel#245
