### ISSUE TITLE
输入法使用问题报告

### ISSUE THREAD

**Issue by dgruan321** [rime/home#272]
您好。我用的是mac的鼠须管五笔输入法，在多语言键盘之间切换的时候输入法会出现问题。当我从法文键盘切换到鼠须管的时候，键位分布仍然是法文键盘的分布，即原q键对应的字根移去了a键，a键的去了q键等。要正常使用输入法，必须先从法文键盘切换到美式键盘，然后再切换到鼠须管。不知道这是不是程序本身的问题，未来是否有可能解决。

**Comment by lotem** [comment]
符合設計。默認會使用系統當前的鍵盤佈局。

要使用美式鍵盤，加這項配置：
https://gist.github.com/lotem/2290714#file-squirrel-custom-yaml-L6

參考 https://github.com/rime/home/wiki/CustomizationGuide

**Comment by dgruan321** [comment]
問題已修復，非常感謝。
