### ISSUE TITLE
在两种方案中切换可以设置快捷键吗？

### ISSUE THREAD

**Issue by BettyJJ** [rime/home#274]
本人需要使用两种方案（一个中文一个日语），现在如果要切换的话，需要按 ctrl` 呼出方案选单，再选择相应的方案。想问一下能不能设成按一下快捷键直接切换？感谢！

**Comment by nameoverflow** [comment]
https://github.com/rime/rime-prelude/blob/master/default.yaml#L132
默认 control + shift + 1 是下一个输入方案。
