### ISSUE TITLE
Rime 输入法近期频繁卡顿，直到我C盘空间下降至几GB时，我才查看到rime配置目录下生成大量“无关文件”占用空间

### ISSUE THREAD

**Issue by CS4Fly** [rime/home#275]

**Comment by CS4Fly** [comment]
Rime 输入法近期频繁卡顿，直到我C盘空间下降至几GB时，我才查看到rime配置目录下生成大量“无关文件”占用空间
![qq 20181030002159](https://user-images.githubusercontent.com/35210507/47664755-b3c22a00-dbda-11e8-88e9-ef32bcedd8d5.png)
![qq 20181030002248](https://user-images.githubusercontent.com/35210507/47664769-b91f7480-dbda-11e8-8078-bc55ddb7585b.png)
![qq 20181030002338](https://user-images.githubusercontent.com/35210507/47664779-bc1a6500-dbda-11e8-8d6d-359eba620323.png)

**Comment by nameoverflow** [comment]
这是用户词典文件，不是无关文件。

**Comment by CS4Fly** [comment]
> 这是用户词典文件，不是无关文件。

嗯，我大致知道，不过他生成了大量的微软连载证书存储文件，后缀为.sst，多达13G，这就不正常了吧

**Comment by lotem** [comment]
那是 LevelDB 數據庫文件。
我無法解決樓主的問題，因爲樓主使用了未知文件配置輸入法。
設計所支持的用法能保正常使用，不意味着任意的配置都能正常工作。
你可嘗試聯繫 easy_en 這個方案的作者退貨。
如果證實問題不限於 easy_en 方案、可在原裝方案上重現，請重新打開這個主題。
