### ISSUE TITLE
win10下合并两个小狼毫后的问题

### ISSUE THREAD

**Issue by zzz1king** [rime/home#280]
之前用的win10的小狼毫0.11.1，小狼毫、小狼毫（TSF）各司其职，小狼毫可以在全屏程序中打字，tsf可以在win10应用和开始菜单中打字，现在0.12合并了之后全屏程序不能打字了，有什么解决办法么

**Comment by Hug125** [comment]
1.之前的TSF在IE的某些窗口中会出现反应十分缓慢的问题，在小狼毫状态就不会有。升级到0.12之后在IE中自动切换到TSF 会感觉到卡顿，但是 又不能自由地切换。
2.全屏不能打字也有点困扰我。
3.小狼毫在WIN10 的最新版升级输入法之后重启电脑会出现小狼毫（IEM）还在输入法切换列表里，不能使用，在WIN10的设置中删掉之后重启还是会出现。
1和2的拟解决方案是：将自由切换TSF和IEM作为一个可以选择开启或者关闭的功能。
3的优先级不高 希望可以优先优化前两个。

**Comment by nameoverflow** [comment]
IME 仅当在使用 Windows XP 中的老旧程序时会激活。
TSF 的问题应另外提出。

**Comment by Deadalusmask** [comment]
现在要是在全屏游戏中使用的话，只能用0.11版本了，感觉合并并不好，或许可以发布为IME和TSF两个版本？

**Comment by Hug125** [comment]
没办法发行成两个版本，IME在开始菜单和Microsoft store以及Edge是没办法打字的 只能用TSF。
TSF在微软东西之外的表现都不如IME。
分开发行的话会出现某些地方完全没办法打字的情况。
目前只能先用0.11.1版本

**Comment by nameoverflow** [comment]
全屏的问题可以试用 https://ci.appveyor.com/api/buildjobs/09107s5l095thc0a/artifacts/output%2Farchives%2Fweasel-0.12.0.0-installer.exe

**Comment by Deadalusmask** [comment]
> 全屏的问题可以试用 https://ci.appveyor.com/api/buildjobs/09107s5l095thc0a/artifacts/output%2Farchives%2Fweasel-0.12.0.0-installer.exe
> （不需要重启）

测试在DOTA2中可以打字了，但是不显示候选词列表，另外win10的微软拼音输入法也有不显示候选词列表这个问题。
还想再测试下Rainbow six siege, 可是R6的Battle Eye会提示
`Blocked loading of file: "C:\Windows\System32\weasel.dll`

我觉得这大概是游戏自己的问题，不是输入法的问题吧。。

**Comment by nameoverflow** [comment]
> 还想再测试下Rainbow six siege, 可是R6的Battle Eye会提示
> `Blocked loading of file: "C:\Windows\System32\weasel.dll`

哈哈哈哈，用一个输入法被当作开挂的 anti cheating 事屑

**Comment by lotem** [comment]
@nameoverflow 有沒有可能在安裝程序裏提供一個只註冊安裝 IME 前端的選項？
當然提升 TSF 的兼容性也是很重要的。

**Comment by Hug125** [comment]
0.12可以在LOL中打字了 星露谷物语还没测试过 0.11的时候IME在星露谷还不能打字

**Comment by nameoverflow** [comment]
（星露谷物语除了刚开头还有要打字的地方吗www

**Comment by Hug125** [comment]
给动物起名字需要，联机偶尔也打字.我的马永远都是拼音名字2333333
