### ISSUE TITLE
無法打出這個字︰氹

### ISSUE THREAD

**Issue by fabopi** [rime/home#282]
字庫中有這個字，但就是無法打得出︰氹

**Comment by Prcuvu** [comment]
哪个方案？粤拼？

**Comment by Prcuvu** [comment]
已知预设方案集中的朙月拼音、地球拼音、仓颉和五笔画都可以打出这个字；额外方案集中的粤拼也可以打出这个字。
如果使用了第三方编写的方案，请在词典中加入缺少的单字。
