### ISSUE TITLE
TSF在IE内核中会出现卡顿问题，切换成IME就没有问题了

### ISSUE THREAD

**Issue by Hug125** [rime/home#283]
如题

**Comment by nameoverflow** [comment]
IE 内核？
具体在什么浏览器下什么版本的 IE 内核？
是否开启了 IE 的保护模式？

**Comment by Hug125** [comment]
应该是IE内核加上java插件在一起导致的问题，不加载java插件时IE内核不会出现卡顿。
加载java插件时不论IE11 或者Chrome中的IE内核都会出现卡顿。
