### ISSUE TITLE
win10 1803卸载不干净

### ISSUE THREAD

**Issue by dragon100a** [rime/home#286]
![_20181124115634](https://user-images.githubusercontent.com/5362072/48964366-a2edb400-efe0-11e8-9168-13e89f08e202.png)
如图，这里剩下的要怎么清除呢？

**Comment by Prcuvu** [comment]
卸载程序要求重新启动操作系统，重启后就会消失。

**Comment by dragon100a** [comment]
> 卸载程序要求重新启动操作系统，重启后就会消失。

重启后，问题依旧
