### ISSUE TITLE
zhge替换为zhege请问规则要怎么写?

### ISSUE THREAD

**Issue by chainofhonor** [rime/home#292]
#下面是我自己不小心敲错的
    - derive/zhege/zhge/
    - derive/neng/nng/

这个是我写的2条替换规则,neng那一条生效了,但是zhege没有生效
我希望的是只要遇到zhge的输入就一律替换为zhege,请问要怎么写表达式

**Comment by lotem** [comment]
拼音裏面的音節只有 `zhe` 和 `ge`，沒有 `zhege`。
