### ISSUE TITLE
反查功能怎麼可以提示多字詞的編碼（粵拼，拼音等等）

### ISSUE THREAD

**Issue by gkovacs** [rime/home#298]
我在用粵語拼音輸入法來學習粵語。我想能夠通過反查功能輸入漢語拼音的時候顯示整個詞的粵拼。

比如，輸入canjia（”參加“的漢語拼音）的時候想提示caam1 gaa1（”參加“的粵拼）

目前，反查功能只能顯示單字詞的粵拼，如下（輸入can會在”參“旁邊顯示caam1）

![screenshot_20190103_164949](https://user-images.githubusercontent.com/58937/50669033-ac6f2200-0f77-11e9-9e87-17e5bf2cd7e0.png)

但如果在反查模式輸入一個多字詞，比如canjia（參加），不會顯示粵拼，如下

![screenshot_20190103_164511](https://user-images.githubusercontent.com/58937/50669160-69617e80-0f78-11e9-8352-ec036863e005.png)

怎麼可以該設置來反查時顯示多字詞的粵拼？

我用的方案在 https://github.com/gkovacs/fcitx-rime-config/blob/master/leimaau_jyutping.schema.yaml

謝謝

**Comment by gkovacs** [comment]
好像如果詞典裏沒有空格的話這個問題就不會出現了

**Comment by lotem** [comment]
目前實現不支持多音節詞的編碼反查。

**Comment by sgalal** [comment]
@gkovacs 

> 好像如果詞典裏沒有空格的話這個問題就不會出現了

是的，但是打長句會變慢很多

**Comment by gkovacs** [comment]
@sgalal 我后来发现如果用`abc_segmenter/extra_tags`的话可以同时解决反查和长句子输入文字这两个问题。这样如果用汉语拼音来输入单词，比如“canjia”，会通过`extra_tags`功能显示对应的粤拼“caam1gaa1”，但输入长句子的时候不会反查，速度也不会被影响到。想看例子的话请参考 https://github.com/gkovacs/rime-double-jyutping-extra 或 https://github.com/gkovacs/rime-td-pinyin-flypy-extra 里面的`*.schema.yaml`文件

```
abc_segmentor:
  extra_tags:
    - jyutping_to_putonghua_lookup
```

**Comment by sgalal** [comment]
@gkovacs 感谢告知！但是我发现只要词典里没有空格，即使不加额外的翻译器或者反查，打长句也会变慢。

**Comment by sgalal** [comment]
@gkovacs 我找到更好的解決方法了，見 https://github.com/rime/home/issues/500
