### ISSUE TITLE
jyutping scheme 無法使用 symbols.yaml 定義的符號

### ISSUE THREAD

**Issue by Ginhing** [rime/home#299]
你好，十分感謝 rime 團隊。我在使用粵拼時遇到的一個問題，不知是我沒有配置正確，還是 bug？

版本信息：
macos 10.14.2 
Squirrel 0.10.0

問題現象：
jyutping.scheme.yaml 是原裝內容沒有修改。輸入 /fh 並沒有出現像「朙月拼音」裏的符號候選字。
把前述 yaml 內容中的 punctuator/import_preset 改爲 `symbols`也沒有效果。

期待：
使用粵拼時能用上 symbols.yaml 裏的符號。

**Comment by lotem** [comment]
該輸入方案沒有包含這項功能。
修要改裝方案。
將來會推出一個配方用來配置這項功能。
Rime 配置的配方化，就是方案以及功能配置可以組合的意思。

**Comment by nameoverflow** [comment]
好像除了要 `import_preset: symbols` 之外还要定义一个 `/` 开头的 `recognizer` ？

**Comment by nameoverflow** [comment]
只是配置错误不存在无法使用的问题。

**Comment by lotem** [comment]
@nameoverflow 的說法不準確。這裏沒有「配置錯誤」。
我對題目的理解是在討論原裝的粵拼方案不支持該項功能，而不是無法自定義實現該功能。

比較方便的實現方法，當然是和輸入方案一樣，把定製補丁也做成配方包，供組合選配。
