### ISSUE TITLE
Windows等软件报https://rime.im/上提供的下载文件有病毒

### ISSUE THREAD

**Issue by xtons** [rime/home#300]
Windows和chrome都会报以下文件有毒，什么 情况 ？

https://dl.bintray.com/rime/weasel/weasel-0.12.0.0-installer.exe

**Comment by lotem** [comment]
请详细说明本品的哪些操作对电脑安全形成了哪些实际损害。
题目转述的信息来自其他软件，我可以确认本品未向相关软件提供这些信息，请咨询告知您该信息的软件发行商以了解信息来源。

**Comment by lotem** [comment]
修改标题，并非下载的文件报「有病毒」，而是其他软件报「下载的文件有病毒」。

**Comment by xtons** [comment]
首先，由于rime.im网站上没有提供相应的HASH码，所以也有可能源代码是无毒的，但bintray.com上的文件染毒了。

我不是安全人员，不能确定这个文件是不是真的有危险电脑的操作，但今天下午我重装了系统后，用Windows 10中的edge下载该文件时，smartscreen（MS浏览器内置的安全审查机制）会阻止我下载，报告有病毒。我当时认为是误判，所以改用Google Chrome下载，但Chrome也说此文件有病毒，所以我就在这里发了一条。而且我在网上搜索后，发现此问题并不是只有我碰到过，也有人发现过同样的问题，但没有引起广泛的重视。

晚上我又试了一下，把文件下载回来，Windows Defende提供了更明确的报警：发现了木马Trojan:Win32/Spursint.F!cl。会执行来自攻击者的命令。

我想如果作者是在Windows 10的电脑上进行构建与测试的话，是不可能引入这个病毒的。而且由于rime.im与dl.bintray.com都是HTTPS方式访问，中途被劫持的可能性比较小。是不是很有可能发布的电脑或是dl.bintray.com中毒了，导致下载的二进制文件不可靠了。

建议能否通过github.com发布下载文件，或者在Windows 10上构建后，将二进制文件的HASH码发布在网站上供用户验证。

**Comment by lotem** [comment]
Bintray 下載頁面 https://bintray.com/rime/weasel/release 提供了 hash 可供驗證。
構建在 https://ci.appveyor.com/project/rime/weasel 上自動完成。不是在作者的電腦上構建的。
另外我估計殺毒軟件只檢查來自互聯網下載的程序，從不會報告在本機編譯生成的程序。如果是這樣，則意味着作者本地構建後第一手生成的 hash 也不可靠。
如果 Appveyor、Bintray 不安全，那會是嚴重的互聯網事件，上面發佈了衆多開源軟件。
所以這種狀況將考驗您的判斷力。
獲取更詳細的信息，定位可能的惡意代碼位於某個構建出的程序還是某個引用的第三方組件，會有助於判斷。

**Comment by xtons** [comment]
这里有几个问题，一是rime.im上并没有提供https://bintray.com/rime/weasel/release这个页面的连接，而是直接提供了EXE的下载URL。二是我访问了这个页面，上面的sha256显示是不全的，后面居然是...省略号了。三是这毕竟是一个for Windows的输入法，现在Windows却禁止它被安装，这难道不是一个严重的问题吗？
就我对Windows的了解，安全扫描并不仅限于网络下载的文件，对于本地文件也会扫描的，所以不管是误判还是bintray真的出了问题，这都是一个直接影响到Windows 10用户使用的问题。只是我目前的能力无法指出具体的错误发生在哪一个环节上。

**Comment by lotem** [comment]
@nameoverflow 我认为AppVeyor和Bintray不大可能出问题。怎样保证上传到Bintray的操作是安全的？

**Comment by nameoverflow** [comment]
这是在催更自动 deploy 吗……

**Comment by nameoverflow** [comment]
> 能提示一下代码树哪个目录下是配置安装包的吗？
https://github.com/rime/weasel/blob/master/output/install.nsi
