### ISSUE TITLE
mac鼠鬚管更新到0.10.0后沒有default.yaml怎么修改輸入方案

### ISSUE THREAD

**Issue by gaojjx** [rime/home#301]
今天通过`brew cask upgrade`升级了鼠鬚管到0.10.0版本并且重新login,但是现在不能自定义输入方案了,以前的`default.yaml`在升级后已经放到`trash`目录下了. 我试过把`default.yaml`复制出来但是重新部署以后又回到`trash`目录下了

**Comment by comenglish** [comment]
我也是这样的问题，之前定义的五笔拼音输入法 也不起效果了。只剩下五笔，没拼音功能了。
特别郁闷。早知道这样就不升了。

**Comment by lotem** [comment]
針對樓主提出的問題，請參考《定製指南》推薦的 [做法](https://github.com/rime/home/wiki/CustomizationGuide#%E5%AE%9A%E8%A3%BD%E6%8C%87%E5%8D%97)
以及 [ 代碼樣例](https://github.com/rime/home/wiki/CustomizationGuide#%E5%88%9D%E5%A7%8B%E8%A8%AD%E5%AE%9A)

另外最近還有一種自動化的方法：
https://github.com/rime/home/wiki/Recipes

**Comment by gaojjx** [comment]
重新仔细看了一遍文档,把之前的自定义配置放到一个新建的`default.custom.yaml`就好了
