### ISSUE TITLE
Error thrown during Deployment

### ISSUE THREAD

**Issue by gismatthew** [rime/home#304]
I'm running OSX 10.11.6. Just updated Rime but noticed the error shown below. Anybody knows what's going on? Typing seems to work but I cannot config the settings. Also I noticed that I couldn't type '堂', Why the heck it's not 'FBRG'？

See the screenshot:
<img width="265" alt="screenshot 2019-01-05 15 31 29" src="https://user-images.githubusercontent.com/3419900/50729437-136b1300-10ff-11e9-91ec-b78aa551f426.png">

**Comment by lotem** [comment]
Refer to https://github.com/rime/squirrel/issues/279
You may need to reinstall [cangjie](https://github.com/rime/rime-cangjie) data package

**Comment by lotem** [comment]
Closed as there is no more follow up.
