### ISSUE TITLE
after the recent updating, the Squirrel is not able to add jyutping input method (or any other methods beside the existing ones) 

### ISSUE THREAD

**Issue by QuentinLei** [rime/home#305]
I've been using jyutping to type in Chinese for a couple of years now, I was using the prior version without any problem but then when I got a notification yesterday that tells there was an update available and then I decided to give it a try to update it. and when I opened my computer again today tried typing with jyutping on Squirrel, as usual. I found out that the input method is not jyutping anymore... I was thinking maybe it's because of the updating then I tried to press control ` to reselect the jyutping method but I don't see the option jyutping... and then I clicked on settings in the menu to enter the user folder, attempt to add jyutping back but I can't find the default.yaml  :(((  

Can anyone please help... tell me how to switch back to the jyutping input method... otherwise I can't be typing in Chinese.... thank you...

**Comment by QuentinLei** [comment]
I found that the default.yaml file in a folder named trash... but it's still useless even though I released it to the rime folder from the trash folder...

**Comment by nameoverflow** [comment]
`default.yaml` is not intended to handwrite, so it was moved. Any customization should be placed into the `default.custom.yaml`.
I don't know about the new version of squirrel, maybe you should also download the jyutping schemata if not exists in your rime data directory.

**Comment by QuentinLei** [comment]
> `default.yaml` is not intended to handwrite, so it was moved. Any customization should be placed into the `default.custom.yaml`.
> I don't know about the new version of squirrel, maybe you should also download the jyutping schemata if not exists in your rime data directory.



> `jyutping` data is not pre-installed with the new version.
> please refer to [rime/squirrel#279](https://github.com/rime/squirrel/issues/279)

問題解決了~ 多謝兩位
