### ISSUE TITLE
there is no wubi_pinyin ?

### ISSUE THREAD

**Issue by comenglish** [rime/home#308]
the wubi_pinyin is not in the latest version!
how can i do ?
the older edition broken!

**Comment by lotem** [comment]
Here you are https://github.com/rime/rime-wubi

**Comment by comenglish** [comment]
yes, it's here.
但是 最新版本在 mac系统里  并没有拼音五笔，只有五笔或拼音。
就是这次升级带来的问题。
我现在只好在拼音和五笔 这两个输入法之间切换。

**Comment by lotem** [comment]
很抱歉帶來了問題。
不過五筆以及用於五筆的拼音都不再是鼠鬚管打包安裝的內容了。
請參考 https://github.com/rime/squirrel/issues/279 裏面的相關信息。
