### ISSUE TITLE
将mac鼠需管0.10.0的设定档复制到win的小狼毫0.12.0时，拼音模糊音无法生效

### ISSUE THREAD

**Issue by chinanoahli** [rime/home#309]
将mac鼠需管0.10.0的设定档复制到win的小狼毫0.12.0时，拼音模糊音无法生效。

复制的配置文件有：
```default.custom.yaml
installation.yaml
luna_pinyin.custom.yaml
luna_pinyin_fluency.schema.custom.yaml
luna_pinyin_simp.schema.custom.yaml
luna_pinyin_tw.schema.custom.yaml
squirrel.custom.yaml -> weasel.custom.yaml
```

我使用的是win10 x64，安装小狼毫时全部使用默认设置，设置文件路径设置为`C:\Program Files (x86)\Rime\configure`，并且已经将`squirrel.custom.yaml`重命名为`weasel.custom.yaml`。

重新部署后，自己设置的主题颜色，每页候选数量，翻页按键等都生效了。
但模糊音设置在win下没有生效。

**Comment by lotem** [comment]
模糊音設置在哪裏定義？

另外這幾個文件是沒有作用的：
```
luna_pinyin_fluency.schema.custom.yaml
luna_pinyin_simp.schema.custom.yaml
luna_pinyin_tw.schema.custom.yaml
```

**Comment by chinanoahli** [comment]
> 模糊音設置在哪裏定義？
> 
> 另外這幾個文件是沒有作用的：
> 
> ```
> luna_pinyin_fluency.schema.custom.yaml
> luna_pinyin_simp.schema.custom.yaml
> luna_pinyin_tw.schema.custom.yaml
> ```

emmm，我在mac系统里使用鼠须管……是将模糊音定义在这几个文件里面的，使用了四年也没问题？
