### ISSUE TITLE
Mac 办更新后 default.yaml 配置文件丢失

### ISSUE THREAD

**Issue by iahu** [rime/home#310]
新版本该把配置方式吗？

更新后原来的配置文件丢了。
新建 default.yaml 文件后，点重新部署会把新建的 default.yaml 文件删掉

**Comment by lotem** [comment]
這個文件是輸入法自帶的。用戶文件夾過去存放了一份自動生成的副本，這是程序緩存。新的版本裏不在這裏緩存了，程序會自己去找正本。詳見：
https://github.com/rime/home/wiki/UserData#%E5%85%A7%E5%AE%B9

用家通常不讓改輸入法自帶的文件。詳見定製指南：
https://github.com/rime/home/wiki/CustomizationGuide#%E5%AE%9A%E8%A3%BD%E6%8C%87%E5%8D%97

**Comment by lotem** [comment]
移除舊版本生成的緩存文件，符合設計。

**Comment by damonchen** [comment]
我在build目录下构建default.custom.yaml文件，没有生效。但不知道版本变更后的user.yaml里面，应该怎么填写用户自己的信息？

**Comment by lotem** [comment]
`build/` 和 `user.yaml` 都是程序自動生成的文件。不支持用戶編輯。

用戶自定義配置文件放在用戶文件夾。詳見：
https://github.com/rime/home/wiki/UserData#%E5%85%A7%E5%AE%B9

**Comment by AiWangZhenPing** [comment]
请问最后是如何解决的？我的也是这样的。/ibus/rime目录下，只有一个installation.yaml文件
