### ISSUE TITLE
关于自动同步

### ISSUE THREAD

**Issue by TomatoFryEggs** [rime/home#311]
目前RIME（Win&Mac）的同步是否可以设置成自动同步？
每天下班都要手动触发一次，真的不是一个好的体验。
或者可以有命令行设置为脚本。

**Comment by lotem** [comment]
因爲目前的實現在同步用戶數據過程中輸入法會臨時處於不可用狀態，自動同步會影響正常輸入。
因此用戶主動觸發該功能才有了合適（即不需要輸入法工作）的時機。

**Comment by TomatoFryEggs** [comment]
相比于每天下班回到家用电脑打字的时候，打不出来词组（五笔组词），原来是忘了同步；大多数人更愿意在下午五点的时候打着打着，突然打不出来字，卡了几秒，原来是在同步，况且每天五点整谁一定正好在打字呢？ @lotem

**Comment by nameoverflow** [comment]
可以使用 windows 计划任务定时同步。

**Comment by TomatoFryEggs** [comment]
> 可以使用 windows 计划任务定时同步。

有命令？

**Comment by nameoverflow** [comment]
Windows 下参见用户数据同步的快捷方式

**Comment by TomatoFryEggs** [comment]
> Windows 下参见用户数据同步的快捷方式

没有找到，可否给个链接？

**Comment by nameoverflow** [comment]
开始菜单里的「用户数据同步」。

**Comment by TomatoFryEggs** [comment]
> 开始菜单里的「用户数据同步」。

测试成功，感谢！

**Comment by loveminimal** [comment]
> > 开始菜单里的「用户数据同步」。
> 
> 测试成功，感谢！

开始菜单里这个如何设置定时任务嘞，试了下，没有生效

**Comment by 2234839** [comment]
@loveminimal 
![图片](https://github.com/rime/home/assets/28727933/02f304ec-202c-4e43-b9dd-38ddce6b1e7e)
![图片](https://github.com/rime/home/assets/28727933/e04c06e2-6502-4645-8eec-4302f9d56d8f)
输入此脚本可以
