### ISSUE TITLE
「小狼毫」繁體輸入模式下有至少兩個錯別字。

### ISSUE THREAD

**Issue by daixiaoluck** [rime/home#312]
「小狼毫」繁體輸入模式下的「爲」和「僞」兩字都是異體字。正確的繁體字應該是「為」和「偽」。請開發者修復。

**Comment by nameoverflow** [comment]
rime/weasel#177

> 「爲」是正字。「為」纔是異體字。

**Comment by nameoverflow** [comment]
要使用台标「為」字可以使用注音方案的「臺灣正體」版。

**Comment by daixiaoluck** [comment]
> [rime/weasel#177](https://github.com/rime/weasel/issues/177)
> 
> > 「爲」是正字。「為」纔是異體字。

https://www.moedict.tw/%E7%82%BA
這個詞典引用的是臺灣教育部的詞典。你可以看到這本詞典並未給「爲」設置單獨的詞條，而是直接把這個字指向「為」的詞條。

**Comment by nameoverflow** [comment]
台湾教育部的正字系统推荐使用「臺灣正體」版输入。
