### ISSUE TITLE
这的确与主题无关，关于语音输入。。

### ISSUE THREAD

**Issue by lunarjoll** [rime/home#313]
类似于百度云的服务接口有免费的语音识别。只用自己注册得到应用密码。
调用接口的事情虽然很简单，但自己写个就不简单了。现在linux里还没有语音输入法。
请问作者有兴趣添加一些免费的语音识别接口，让我们添加应用id和key完成语音输入吗？

**Comment by lotem** [comment]
既然百度雲已經做了，爲什麼還要寫？

**Comment by lunarjoll** [comment]
让rime调用baidu的api。。或者其他语音识别服务的api实现语音输入。
