### ISSUE TITLE
mac下更新到0.10.0后，五笔输入有些字输入不了，感觉不是86编码了，这个笔以改？

### ISSUE THREAD

**Issue by shotolee** [rime/home#314]
如题

**Comment by shotolee** [comment]
比如  打“蝗”字，会出一些奇怪的词组 “蝗五”，而不是蝗  jrgg

**Comment by nameoverflow** [comment]
蝗五 jrgg 是五笔 86 的合法词组。
从你的描述猜测可能是更新后原先的禁用用户词库设置失效了。参考 https://github.com/rime/home/wiki/CustomizationGuide 进行正确的设置。

**Comment by lotem** [comment]
參考 https://github.com/rime/squirrel/issues/279
