### ISSUE TITLE
在chrome地址栏使用鼠须管输入时，删除键会清空整个输入区

### ISSUE THREAD

**Issue by coolforce** [rime/home#315]
鼠须管输入时，删除键会清空整个输入区，而不是最近一个字母。

比如想要输入”这是一个“，在打完"zheshiyi"后按删除，不会回到“zheshiy"，而是清空所有的字母。

Google Chrome: 71.0.3578.98 (Official Build) (64-bit)
MacOS Mojave10.14.2 (18C54)

**Comment by minyaoli** [comment]
同樣的問題。

**Comment by KyleBing** [comment]
这应该不是程序问题，应该是方案设计的问题，我用的五笔方案没有出现这问题。

**Comment by zhuxiaoxi** [comment]
我测试也没出现问题

**Comment by lotem** [comment]
大約不是本品引起的問題，關閉工單。

**Comment by mathgo** [comment]
遇到同样的问题，请问 @coolforce @minyaoli  如何解决的呢？

**Comment by zhuxiaoxi** [comment]
我仔细想了想，好像出现过这种类似的情况，刚输入的内容，突然就没了。包括但不限于Chrome。macOS上出现过，Linux上好像没有

**Comment by mathgo** [comment]
MacOS Mojave 10.14.4
Chrome 74.0.3729.131（正式版本） （64 位）
在Chrome地址栏输入的时候，`Backspace`键会整个删除全部未上屏的输入。其他软件未现，Chrome其他位置也都正常。  @zhuxiaoxi

**Comment by dfshan** [comment]
遇到同样问题，将 `inline_preedit` 配置为 `true` 之后问题解决。

**Comment by pigLoveRabbit520** [comment]
我也遇到了这个问题，在chrome里输入，按backspace键，会让已经在输入框的字母被删除。。
```
版本 92.0.4515.107（正式版本） （64 位）

```

**Comment by minyaoli** [comment]
`squirrel.custom.yaml` 中在 `patch:` 下加一條 `style/inline_preeinlinedit: true`
感謝@dfshan 提供的解決辦法。

**Comment by gclintj** [comment]
遇到了类似的问题。
Ubuntu, Chrome下用86五笔，Backspase会同时删除尚未出汉字的一个字母，与一个字母前的汉字

**Comment by pingshunhuangalex** [comment]
Squirrel 最新的 `1.1.2` 在Chrome地址栏中仍能复现这个问题
`style/inline_preedit: true`能解决，但是不是我想要的体验
