### ISSUE TITLE
关于仓颉的几个问题（最大码长、通配符、空码、顶字清屏）求解

### ISSUE THREAD

**Issue by jumpsfire** [rime/home#318]
1、不知有无通配符的概念，有的话，请教怎么设置。
    如：解 nbshq，n*shq，n**hq，n***q假如我不会拆部分字根了，用通配符*（最好可自定义）也能打出字（那怕是在候选窗里）。
2、最大码长问题，要怎么设置。
   如：解 nbshq，我设置了max_code_length为5，会顶字上屏（我不想顶字上屏，习惯空格，才不影响盲打），不设置（注释掉）或为6，才不会顶字上屏，但是最大码长变为6了。
3、空码禁止功能，要怎么设置。
   如： 解 nbshq，nb后（v）为空码禁止输入，因为等我打了5个码时才发现错了，就要回退3个键，影响效率。
4、怎么禁止顶字自动清空码。
    如： 解 nbshq，我输入nbv（此时为空码）后再随便输入个s字母的话，nbv会被顶掉清除，我想要还能回退去修改，就不用全部重输。
谢谢！

**Comment by lotem** [comment]
請用原裝方案，沒有2、4的問題。其他的功能不支持。
