### ISSUE TITLE
0.9.x升級至0.10.0或者0.11.0部署失敗

### ISSUE THREAD

**Issue by minyaoli** [rime/home#319]
原本在0.9.x版本的/Rime目錄下的luna_pinyin_simp.custom.yaml和luna_pinyin_tw.custom.yaml會導致新版本部署失敗。

因為我只用了luna_pinyin，不知道是不是其他輸入方案的.custom.yaml文件也會導致相同的問題。

**Comment by lotem** [comment]
請查看日誌定位錯誤。不要修改 `build/` 目錄下的文件——屬於程序生成的緩存文件，不保存用戶的修改。
如果只用`luna_pinyin`，則不需要啓用`luna_pinyin_simp`和`luna_pinyin_tw`。
