### ISSUE TITLE
设定快捷键的问题。「已解决」

### ISSUE THREAD

**Issue by wy16W2pIilK1xgqN** [rime/home#324]
系统：win10 x64 
小狼毫 0.13.0

用设置工具，设置为朙月拼音 简体。

下面是做的唯一的修改

```
key_binder:
  bindings:
    - {accept: "Shift+space", toggle: ascii_mode, when: always}
    - {accept: "Alt+Shift", toggle: ascii_mode, when: always} 
```
按住Shift 再按空格无效，而按住空格，再按 Shift 有效。
Alt+Shift 怎么按都没有效果。

这种情况让人觉得很诡异。
快捷键设置有什么限制吗？

**Comment by lotem** [comment]
單擊Shift鍵的作用是切換`ascii_mode`。
`Shift+space`可以有效，可能未設置正確。
`Alt+Shift`不能表示一個完整的按鍵，他表示按下某個按鍵時Alt和Shift均處於按下狀態，但是缺少按鍵的key code。

**Comment by wy16W2pIilK1xgqN** [comment]
> 單擊Shift鍵的作用是切換`ascii_mode`。
> `Shift+space`可以有效，可能未設置正確。
> `Alt+Shift`不能表示一個完整的按鍵，他表示按下某個按鍵時Alt和Shift均處於按下狀態，但是缺少按鍵的key code。
谢谢回复。
删除  Shift_L: inline_ascii  后，按住Shift 再按空格 就有效了。
还想请教一下，有办法把 按住Alt，再按 Shift 设定为快捷键吗？

**Comment by wy16W2pIilK1xgqN** [comment]
> 單擊Shift鍵的作用是切換`ascii_mode`。
> `Shift+space`可以有效，可能未設置正確。
> `Alt+Shift`不能表示一個完整的按鍵，他表示按下某個按鍵時Alt和Shift均處於按下狀態，但是缺少按鍵的key code。

谢谢回复。
删除 Shift_L: inline_ascii 后，按住Shift 再按空格 就有效了。


还想请教一下，有办法把 “按住Alt，再按 Shift 设定‘ 为快捷键吗？

**Comment by lotem** [comment]
不同意以上陳述。
`ascii_composer`實現用Shift鍵切換狀態必得快速單擊，和組合鍵`Shift+space`互不影響。

`Shift+`只表示狀態，`Shift_L`和`Shift_R`纔是Shift鍵的key code。

**Comment by wy16W2pIilK1xgqN** [comment]
> 不同意以上陳述。
> `ascii_composer`實現用Shift鍵切換狀態必得快速單擊，和組合鍵`Shift+space`互不影響。
> 
> `Shift+`只表示狀態，`Shift_L`和`Shift_R`纔是Shift鍵的key code。

 排查后发现是其他软件冲突造成的。=￣ω￣=
浪费了你的时间，抱歉！

请关闭此帖。
