### ISSUE TITLE
使用 custom_phrase.txt 文件给极大权重固定单字，但发现组词无法进用户词典

### ISSUE THREAD

**Issue by huaxianyan** [rime/home#325]
之前查阅到 `custom_phrase.txt` 组自定义短语的方式，后来发现里面给单字极大权重能实现单字固定候选列表首位，于是就这么使用。
在使用了十几天之后我发现了一个问题，就是会出现与之相关的单字组词之后，下次再输入还要重新组。查阅了用户词典也没有发现相关的记录。
比如：
我在文件中加入了
`快	kuai	7777777`
然后打「特别快」，但是后面再键入「tebiekuai」的时候候选列表没有这个词。
使用的方案是「袖珍简化字拼音」，加入了去重功能，否则固定单字后候选列表有2个字。

在互联网上搜索可能存在的线索的时候，我也发现了几条 issue 是关于五笔输入法之中的讨论以及一些解决示例，尝试修改了其中一些，但是均不起效果。

**Comment by ChoicePhobiaDisorder** [comment]
custom_phrase.txt内的词是不加入记录的，所以如果你想加入应该自定义一个词典，在里面写入

**Comment by lotem** [comment]
符合設計。

自定義短語概念上屬於拼音詞典之外的特別編碼詞條，其編碼不屬於拼音。
用戶詞典嚴格按照「語言」劃分。這裏用的術語「語言」是指兼容的編碼種類。例如拼音和五筆在輸入法程序看來屬於不同語言。
來自不同語言的輸入片段不能計入同一個用戶詞典，因爲編碼的性質不同。例如「這、」雖一起上屏，頓號不會記爲用戶詞的一部分。「特别快」的例子裏，「快」的編碼種類不詳，可類比「、」。

屬於同一語言的詞典，名稱裏第一個句點之前的部分相同。可分別創建 `luna_pinyin` 和 `luna_pinyin.fixed` 兩份固態詞典，他們會對應到語言代碼爲 `luna_pinyin` 的用戶詞典。
