### ISSUE TITLE
weasel  0.13.0 候选栏 在pycharm 中不跟随光标

### ISSUE THREAD

**Issue by Ansen** [rime/home#326]
系统：win10 1809
pycharm 版本：2018.1.4
输入法：weasel 0.13.0 五笔86

一些图片

![qq 20190213104606](https://user-images.githubusercontent.com/676412/52683088-b162c080-2f7c-11e9-85b1-531f7ff50c39.png)

![qq 20190213104619](https://user-images.githubusercontent.com/676412/52683090-b162c080-2f7c-11e9-8ea8-dbda33107e09.png)

![snipaste_2019-02-13_10-46-43](https://user-images.githubusercontent.com/676412/52683091-b1fb5700-2f7c-11e9-904a-1d51ad9f15d8.png)

**Comment by CLannadZSY** [comment]
建议你升级一下pycharm试试,因为在pycharm中我的能够正常的使用,使用的版本也是0.13.0

**Comment by Ansen** [comment]
> 建议你升级一下pycharm试试,因为在pycharm中我的能够正常的使用,使用的版本也是0.13.0

升级到最新版本(2019.1.2)后就正常了，感谢！
