### ISSUE TITLE
Mac OS 上 'Ctrl' + '`' 不管用

### ISSUE THREAD

**Issue by franklinyu** [rime/home#33]
`Ctrl` + `Shift` + `` ` `` 也不行，`F4` 也不行。OS X 10.10.5

**Comment by franklinyu** [comment]
哦，要在輸入時按。我傻逼了。

**Comment by franklinyu** [comment]
等下，貌似 F4 還是不支持，爲什麼？雖然其實 `Ctrl` + `` ` `` 就差不多了，但感覺這應該是個 bug。

**Comment by franklinyu** [comment]
哦，原来 OS X 本来就不支持 `F4`。

**Comment by lotem** [comment]
下一個版本可以支持 `F4` 了。
