### ISSUE TITLE
有沒有辦法讓 Caps Lock 供系統使用？

### ISSUE THREAD

**Issue by asphoa** [rime/home#330]
Mac 中單擊 Caps Lock 可以用來在其它輸入法和 US Extended 之間做轉換。但在 Rime 中似乎無法這樣使用，只能限於在 Rime 內的中英文之間轉換。

有沒有辦法使 Rime 放棄對 Caps Lock 的控制？（因爲我需要打各種表音符號，而且還用到其它系統輸入法。）

**Comment by gshmu** [comment]
@asphoa 我用这个自定义修改键位
https://github.com/pqrs-org/KE-complex_modifications

**Comment by yu-soong** [comment]
可以用AutoHotkey改成任意你想要的样子 😊

**Comment by yycking** [comment]
自行修改`Info.plist`
https://github.com/rime/squirrel/issues/375#issuecomment-552323087

**Comment by lotem** [comment]
同 https://github.com/rime/squirrel/issues/375
