### ISSUE TITLE
如何調整Preedit

### ISSUE THREAD

**Issue by asphoa** [rime/home#331]
我想在倉頡中只看到中文字碼，或將 Preedit 移到候選字表的最末（而不是在 inline 或在候選字表的最上面），有沒有辦法呢？

preedit_format:
    - 'xform/^([a-z]*)$/$1\t（\U$1\E）/'
    - "xlit|ABCDEFGHIJKLMNOPQRSTUVWXYZ|日月金木水火土竹戈十大中一弓人心手口尸廿山女田難卜符|"

**Comment by lotem** [comment]
請參考
https://github.com/rime/rime-quick/blob/master/quick5.schema.yaml#L61
