### ISSUE TITLE
有没有办法可以自动添加空格

### ISSUE THREAD

**Issue by GreatBigWhiteWorld** [rime/home#338]
菜鸟一只，想问一下有没有办法实现可以切换到一种模式，这种模式下打字的时候自动添加空格。

比如你输入“你长得太帅了”，自动变成“你 长 得 太 帅 了”。或者添加其他可选的东西例如“_", "-", "/"

嗯。

**Comment by lotem** [comment]
可以編程寫 [過濾器](https://github.com/rime/librime/blob/master/src/rime/filter.h) 實現。

**Comment by nameoverflow** [comment]
你 打 字 带 空 格

**Comment by GreatBigWhiteWorld** [comment]
> 可以編程寫 [過濾器](https://github.com/rime/librime/blob/master/src/rime/filter.h) 實現。

谢谢回复。本人初学编程应该没这个能力了。有大神做一个我觉得造福无法用言语表达。
