### ISSUE TITLE
Mac 下输入出现大量问号

### ISSUE THREAD

**Issue by ghost** [rime/home#34]
想输入『孖』，于是输入拼音「ma」后翻页，结果找不到『孖』字，倒是出现一堆问号。
<img width="99" alt="ma" src="https://cloud.githubusercontent.com/assets/382763/10533203/c8596570-73f8-11e5-86d4-9596edd0dc44.png">

本地的语言设置是:
![lanset](https://cloud.githubusercontent.com/assets/382763/10533214/ed22694c-73f8-11e5-978a-3402531c9cbf.jpg)

**Comment by lotem** [comment]
那些是默认字体没有覆盖到的生僻字 所以无法显示

**Comment by ziloeng** [comment]
那么目前有方法在可以使两者都能同时正常显示吗？
目前看来没有哪个字体比较完整包含常用字和生僻字。例如windows中的宋体，常用字在simsun.ttc，生僻字在simsunb.ttf。
win下weasel可以显示，但新版rime-gits就有这个问题。

**Comment by eagleoflqj** [comment]
https://github.com/Fitzgerald-Porthmouth-Koenigsegg/Plangothic-Project
https://github.com/max32002/max-hana
