### ISSUE TITLE
在我的世界（Windows 10 UWP版）中输入中文光标会自动回退一格

### ISSUE THREAD

**Issue by 1316695312** [rime/home#341]
如题。

视频请见：
https://pan.baidu.com/s/1b26M_DtE7HqrztkmDHfm6w
提取码：avxd

或：
http://tieba.baidu.com/p/6072016576

**Comment by lotem** [comment]
duplicate

**Comment by 1316695312** [comment]
> 
> 
> duplicate

什么意思啊，不太明白，可以说的详细些吗？

**Comment by 1316695312** [comment]
> 
> 
> duplicate

哦是说我重复发帖吗😅
抱歉
