### ISSUE TITLE
双拼的自动补全问题

### ISSUE THREAD

**Issue by 3andero** [rime/home#343]
双拼方案中，两个字符确定一个汉字，在输入的时候若只输入第一个字符，rime并不会启用自动补全功能来显示可能对应的字。
举个例子：
（小鹤方案）打出“双拼输入法”需要键入“ul pb uu ru fa”，但当我只敲了"ul pb uu ru f"的时候，rime没有自动的识别处最后一个 "f" 可能对应的字，而且这个 "f" 还影响了前面的字的识别。

如何设置才能让双拼中也可以实现全拼的自动推测呢？

![image](https://user-images.githubusercontent.com/31029660/54831322-184e6480-4cf5-11e9-8d6a-91888c025abe.png)

**Comment by lotem** [comment]
`enable_completion: true` 不管用了。`luna_quanpin` 方案比較明顯。
@nameoverflow 最近改過這部分，代碼也比較熟，如果有空可以幫忙一起排查。

**Comment by lotem** [comment]
哈，是我看走眼了，改錯了。

**Comment by lotem** [comment]
Fixed via https://github.com/rime/librime/commit/27141315a2e6d9df427ea737beff66ebbc17f706

**Comment by laoshu133** [comment]
该问题似乎在 `0.14` 中依然存在，是还未发布吗？

**Comment by NomandChan** [comment]
并没有解决，是否开一个新的 issue ？

# [双拼的自动补全问题](https://github.com/rime/home/issues/343#top)#343 

## 问题重述：双拼用户希望有自动补全：
打 wei  正常简拼能出现候选  【微型柱】，但 双拼还是没有。
“wei ”↓↓
wei 微型柱 未来 为什么
微型柱是我输入的历史记录，非常需要；倒是后面那些常用短语也会出现在候选里，可有可无。

再例如打过：“长句输入模式” 或 “并不知道是干嘛的” 
在双拼下输入“ chang/ bing" 就能出来这两条历史，而用双拼码 "ug/ bq" 没有用。




下面是我尝试自己解决问题的过程，配置失败。 主要是手动升级 rime.dll 、升 版本也没用，修改 yaml 开关也没用。
## 失败过程
这里说解决了自动补全问题，git 修改过，但是没用在 weasel 发布：“在   [master](https://github.com/rime/librime)-   [1.7.3](https://github.com/rime/librime/releases/tag/1.7.3)   -   [1.5.0](https://github.com/rime/librime/releases/tag/1.5.0)  解决了。。 但是 windows weasel 一直在 0.14.3 ”  所以就去搜怎么「更新／编译」小狼毫，在这个讨论中，有些人编译好了，提供了 exe：

↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓
[隔壁的更新了，win的啥时候更新0.15呢？ · Issue #611 · rime/weasel (github.com)](https://github.com/rime/weasel/issues/611)
### **[lotem](https://github.com/lotem)** commented [on 11 Mar 2021](https://github.com/rime/weasel/issues/611#issuecomment-796517627)
​那只要下載、替換 rime.dll 就行了。

### **[pingshunhuangalex](https://github.com/pingshunhuangalex)** commented [on 11 Nov 2021](https://github.com/rime/weasel/issues/611#issuecomment-966325849)
>对啊 不维护了 上面有几个民间的版本 将就着用吧（我没测试过）  
[https://github.com/cnlog/warehouse/blob/main/weasel-0.14.5.0-installer.exe](https://github.com/cnlog/warehouse/blob/main/weasel-0.14.5.0-installer.exe)  
[https://github.com/crackself/weasel/releases/download/0.15.0/Pre-build_weasel-0.15.0.0-installer.exe](https://github.com/crackself/weasel/releases/download/0.15.0/Pre-build_weasel-0.15.0.0-installer.exe)  
[https://github.com/huquanjun/rime_build/releases/download/weasel_20210225/weasel-0.14.5.0-installer.exe](https://github.com/huquanjun/rime_build/releases/download/weasel_20210225/weasel-0.14.5.0-installer.exe)

↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑


通过上面信息得知：  
1. 替换 rime.dll 可手动更新   👷🏻
2. 也可以下载其他人编译的新版 🛠️ 🧰

先尝试第一条：👷🏻  去 librime 下载，rime-with-plugins-1.7.3-win32.zip  是一大堆文件夹，又没有说明书…… 
使用搜索发现 dist\lib 里面有个 rime.dll ，尝试替换「程序文件夹」 里面的 dll，重新部署之后，虽然 rime 还能使用，但是完全没有变化，双拼还是没有提示。
打 wei  正常简拼能出现候选  【微型柱】，但 双拼还是没有。

好的，轻松翻车。

然后再试试第二条：现在预编译好的版本 。🛠️ 🧰
先下载 0.15 版本；  上面回答里面的链接失效了……搜索这个人：[crackself (github.com)](https://github.com/crackself/) ， 找到了 [Release Pre-Test · crackself/weasel (github.com)](https://github.com/crackself/weasel/releases/tag/0.15.0)
和 crackself/weasel/releases/download/0.15.0/Pre-build_weasel-0.15.0.0-installer.exe 地址不一样。下载就挑[weasel-0.15.0.0-installer.exe](https://github.com/crackself/weasel/releases/download/0.15.0/weasel-0.15.0.0-installer.exe) 
安全起见先卸载 0.14 ；安装好以后发现 rime 用户文件夹还在，使用上变了一点设置——我的竖屏候选变横屏了，但是我自己的配置方案双拼+easy en 还在。
但 双拼还是没有历史提示。 只能考虑我自己的配置问题。👨🏻‍💻 👷🏻‍♂️

```
patch:

  translator/enable_completion: true

  # translator/preedit_format: []


或者  都不会影响自动补全，这肯定还有 bug
patch:

  # enable_completion: true

  enable_completion: false
```

**Comment by chenghuzi** [comment]
在0.16.2 中这个问题依然存在

![Xnip2023-02-05_17-25-41](https://user-images.githubusercontent.com/11160442/216849707-6901f2be-462c-4792-8bd8-2591c2bd21d4.png)
![Xnip2023-02-05_17-25-54](https://user-images.githubusercontent.com/11160442/216849714-01e58679-3179-4a27-91c3-1629a316967c.png)

**Comment by lotem** [comment]
> 在0.16.2 中这个问题依然存在
> 
> ![Xnip2023-02-05_17-25-41](https://user-images.githubusercontent.com/11160442/216849707-6901f2be-462c-4792-8bd8-2591c2bd21d4.png) ![Xnip2023-02-05_17-25-54](https://user-images.githubusercontent.com/11160442/216849714-01e58679-3179-4a27-91c3-1629a316967c.png)

程序的错误早已修复。属于方案配置问题的嫌疑较大。
自然码双拼（`double_pinyin`输入方案）测试通过，最后一个音节按到第一键时没有图上显示的情况。

从双拼编码不同，可知你用的是别的方案？自定义了哪些配置项？
如果所用的输入方案与 https://github.com/rime/rime-double-pinyin 不同，最好给出完整的YAML文件。

**Comment by chenghuzi** [comment]
> > 在0.16.2 中这个问题依然存在
> > ![Xnip2023-02-05_17-25-41](https://user-images.githubusercontent.com/11160442/216849707-6901f2be-462c-4792-8bd8-2591c2bd21d4.png) ![Xnip2023-02-05_17-25-54](https://user-images.githubusercontent.com/11160442/216849714-01e58679-3179-4a27-91c3-1629a316967c.png)
> 
> 程序的错误早已修复。属于方案配置问题的嫌疑较大。 自然码双拼（`double_pinyin`输入方案）测试通过，最后一个音节按到第一键时没有图上显示的情况。
> 
> 从双拼编码不同，可知你用的是别的方案？自定义了哪些配置项？ 如果所用的输入方案与 https://github.com/rime/rime-double-pinyin 不同，最好给出完整的YAML文件。

确实是，感谢解答。逐步削减配置文件以后找到原因了，是这样一个配置文件导致的 https://pastebin.com/szaefeRy 去掉以后就好了。
