### ISSUE TITLE
在Ubuntu 18.04.2 LTS 的 Sublime Text 中工作不正常

### ISSUE THREAD

**Issue by chinanoahli** [rime/home#344]
**express_editor** 在 ST 中似乎出现了bug，具体表现为：

我使用的键盘布局是*Dvorak*，所以我在*default.custom.yaml*中定义了以下的选项，将`[]`指定成翻页按键：
```
patch:
  "key_binder/bindings":
    - { when: paging, accept: bracketleft, send: Page_Up }
    - { when: has_menu, accept: bracketright, send: Page_Down }
```

然后还定义了一些模糊音选项在*luna_pinyin(_fluency / _simp / _tw).custom.yaml*这4个文件中：
```
patch:

# 以下設定爲Google Pinyin自帶模糊音設定全開
  'speller/algebra':
    - erase/^xx$/                       # 第一行保留

    - derive/^([zcs])h/$1/              # zh, ch, sh => z, c, s
    - derive/^([zcs])([^h])/$1h$2/      # z, c, s => zh, ch, sh
    - derive/^an$/ang/                  # an => ang
    - derive/^ang$/an/                  # ang => an
    - derive/^en$/eng/                  # en => eng
    - derive/^eng$/en/                  # eng => en
    .......(此处省略一部分类似的内容)
```

当我在ST中编辑时，在中文状态输入字串如`iphone`或者`ver`等字串后，会出现以下的情况：

按空格、回车或者退格键都无法对输入码产生影响。而是直接对ST中的内容进行了修改，例如回车键会将ST中的光标直接移到下一行，而退格键则是删除ST中的前一个字符。而输入码仍然保留在rime的buff中，既不上屏也不消失。但此时按*shift*则**可以**将输入码上屏，并继续回到中文输入模式。

已经尝试过在*方案.custom.yaml*与*default.custom.yaml*中分别加入：
```
patch:
  'engine/processors':              # 一、這批組件處理各類按鍵消息
    - express_editor
```
均无法解决问题。

**Comment by nameoverflow** [comment]
是 ibus/fcitx 的问题吧？

**Comment by chinanoahli** [comment]
> 是 ibus/fcitx 的问题吧？

但是在别的程序下是没有这样的问题的？

**Comment by chinanoahli** [comment]
已经换用archlinux，无法继续测试，关闭问题
