### ISSUE TITLE
怎么将候选的词语变成水平,而不是垂直啊?

### ISSUE THREAD

**Issue by CLannadZSY** [rime/home#345]

**Comment by lotem** [comment]
如果你问的是行文的方向，目前的输入法前端都只支持中文从左到右横排。

**Comment by CLannadZSY** [comment]
就比如我输入以下拼音:
会出现这种形式的候选
nihao
1. 你好 2. 你号 3. 你浩
而不是这种形式
1. 你好
2. 你号
3. 你浩

有这种配置吗?,我有查到一些方法但是都没有用,而且他们都说是已经支持了这种形式,所以我就上来问一问

**Comment by lotem** [comment]
這裏介紹了如何配置：
https://github.com/rime/home/wiki/CustomizationGuide#diy-%E8%99%95%E6%96%B9%E9%9B%86

**Comment by edwinhuish** [comment]
设置已失效？？？没有找到  ```weasel.custom.yaml``` 新建后添加对应的代码没反应。。

**Comment by CLannadZSY** [comment]
> 设置已失效？？？没有找到 `weasel.custom.yaml` 新建后添加对应的代码没反应。。

按照上面的链接进行配置之后,要重启输入法,或者是重启输入法的服务,才能生效

**Comment by edwinhuish** [comment]
@CLannadZSY 没有重启过，不过试过重新读取配置，没效果。

后来看到一个issue #66 ，通过设置 ```ibus-setup``` 搞定了。

不知道rime作者怎么想的，配置经常变，网上又全是老资料，配置个 rime 都能让人崩溃。

**Comment by NeAuNU** [comment]
candidate_list_layout: linear             # 候选词列表布局 stacked (堆叠的)/linear(线性的)
