### ISSUE TITLE
[提議?] Create a GitHub organization for hosting schemata

### ISSUE THREAD

**Issue by szc126** [rime/home#349]
如題。

**Comment by sgalal** [comment]
I think an organization overkills.

We could just record the location of schemata.

See https://github.com/rime/home/issues/336

**Comment by lotem** [comment]
As discussed in https://github.com/rime/home/issues/336, we agreed on decentralized hosting of Rime recipes. This keeps responsibility of maintaining the data to the owner, and encourages authors to be involved (doesn't require membership to publish their recipes).

**Comment by laubonghaudoi** [comment]
@szc126 這幅[流程圖](https://github.com/rime/home/issues/336#issuecomment-473566308)是我目前所總結出來的方案組織邏輯，尚不知道幾位前輩對此的認可程度。
