### ISSUE TITLE
仓颉五代打不出「迟」「魅」等字

### ISSUE THREAD

**Issue by Ace-Who** [rime/home#358]
Windows 7 64bit
Weasel 0.13.0

方案为 cangjie5 version 0.30，使用默认词典 cangjie5.dict.yaml version 0.18，确认包含：
 
> 魅  hijd
> 迟  yso

拼音反查也能查到这两字。

试了词典「迟」附近的字，也大多打不出。cangjie5_express 方案却都能打出。

**Comment by Ace-Who** [comment]
比照 cangjie5_express.schema.yaml，copy 了一份来测试。只要去掉 `translator` 下的 `prism: cangjie5_express`，就会打不出上面那些字。而只要给 cangjie5 方案 patch 上 `translator/prism: cangjie5_express`，就没有打不出字的现象了。

**Comment by Ace-Who** [comment]
按错 close issue 了。

**Comment by Ace-Who** [comment]
问题似乎解决了，与我一个自定义方案有关。在该方案里我 `__inclue: cangjie5.schema:/` 并作一些修改，但没有修改 `translator` 的 `prism`，同样有打不出字的问题。添上 `prism:  <方案名>` 后，这个方案问题依旧，但是 cangjie5 没问题了。

**Comment by Ace-Who** [comment]
自定义方案的问题，看起来与某处修改有关，去掉后就正常了。

**Comment by 1316695312** [comment]
迟 魅
