### ISSUE TITLE
按照rime-aka的教程为wubi86方案挂接扩展词库失败

### ISSUE THREAD

**Issue by donmor** [rime/home#359]
弄了完全没效果，一直是系统词库，就算在wubi86.custom.yaml中指定一个完全空白的码表，重新部署之后还是用了默认的词库，不管fcitx-rime还是prime都不行

**Comment by lotem** [comment]
什麼教程？怎麼指定碼表？
請把問題描述清楚。

**Comment by donmor** [comment]
https://github.com/rime-aca/dictionaries
呃 才发现aca打错了。。
wubi86.custom.yaml改translator/dictionary为wubi86.extended.dict.yaml，然后wubi86.extended.dict.yaml这边import_tables挂上wubi86还有转换的细胞词库

**Comment by lotem** [comment]
https://github.com/rime-aca/dictionaries 指示的方法有效。
