### ISSUE TITLE
仓颉五代重码候选字排序与仓颉码序不一致

### ISSUE THREAD

**Issue by Ace-Who** [rime/home#360]
在禁用用户词典的前提（固定了词序）下讨论。

仓颉五代对于重码字有一个处理方式，是给使用频率较低的重复字的编码添加前缀「难」来区分（超过 5 码则截掉尾部）。这使每一个字都有惟一编码，理论上敲此编码就会使该字被列为首选或惟一候选，从而**完全避免选字**。如重码字「犬、义、庆」，取码都是「戈大」，处理后的取码是：

1. 犬（ik 戈大）
2. 义（xik 难戈大）
3. 庆（xxik 难难戈大）

输入「戈大」时，合理的候选字排序也应当如上，输入「难戈大」时「义」自然是惟一候选，「庆」类似。rime 中这组字碰巧是这样排序的，但是其它重码字组就不一定了，而且从定制指南和 cangjie5.schema.yaml 和 cangjie5.dict.yaml 来看，并无机制处理这个问题。为说明这个问题的弊端，举一例：重码字组

1. 难（水人土）
2. 淮（难水人土）

在 rime 中输入「水人土」时的实际排序为

1. 淮
2. 难

导致用户为打「难」字就必须输入「水人土」再敲 2 选字。其它例子还有

- 还、尗（ymf 卜一火）
- 区、尹、刄（sl 尸中）
- 文、头、达（yk 卜大）
- 汉、双、沝（ee 水水）
- 从、仌（oo 人人）
- 类、炔（fdk 火木大）

以上是理想排序，而在 rime 中输入不前缀 x（难）的编码时，实际候选排序为

- 尗、还
- 尹、刄、区
- 文、达、头
- 沝、汉、双
- 仌、从
- 炔、类

有的是「本字」（仓颉码无「难」前缀者）未置顶（这是主要问题），有的是「重复字」的顺序与仓颉码序不一致。

**Comment by Ace-Who** [comment]
可能会（「伝、会」）有这样的意见：只要固定词序，前缀仓颉字母「难」与用数字键选字，本（「本、杠、扌、杢」）质上相同，操作难度也相当。的确如此，但是，尽可能合于标（「柰、标」）准，使候选顺序与仓颉码序一致，那是最好的。

**Comment by Ace-Who** [comment]
这可能是方案特定问题，从算法框架上解决，可能不是合理做法。如果能确知候选字排序逻辑，或许可以由用户自行修改码表来解决。

**Comment by Ace-Who** [comment]
估计与码表的 `sort` 属性有关，可将 cangjie5.dict.yaml 的

```
columns:
  - text
  - code
  - stem
```

改为

```
columns:
  - text
  - code
  - stem
  - weight
```

然后在重码字的行末添加水平制表符和适当的权重。如果一行原本只含两列，连续添加两个 `\t` 和权重，不知是否正确做法，有待测试。

**Comment by Ace-Who** [comment]
只含两列即表示不含造词码（stem）。研究 Rime_description 后明白了造词码的含义，造词码大约只出现在适用仓颉「包围省略原则」的字上。其余汉字其实应该也隐含了造词码，且就是该字的仓颉码，即第二列。所以添加 `\t仓颉码\t权重` 凑足 4 列应该是可行的。

**Comment by Ace-Who** [comment]
试验了一下，实际将 `weight` 插到了第 3 列：

```
columns:
  - text
  - code
  - weight
  - stem
```

仅为「原本字」（指惟一仓颉码无「难」前缀者）添加权重，欲使其成为候选字首选。方法是用 Vim 编辑 cangjie5.dict.yaml（或在「用户文件夹」创建的复本），除了上面的修改，再运行

```
:%s/^\S\t[a-wy][a-y]*\zs/\t1/
```

保存后重新部署即可。这样就为所有原本字（包括无重码的字）添加了权重 1，实际上可能任意正整数亦可。
这样做理论上的效果，只是保证将重码字中的原本字置于首选位，实际发现非原本字之间的顺序似乎也发生了变化，如「文、达、头」变成了「文、头、达」，与仓颉码序完全一致了，而以上修改并未改动「头、达」二字的权重，此现象原因不明，不过不是要紧的事，主要目的是将原本字置顶。

**Comment by Ace-Who** [comment]
又观察了一下码表，发现重复字都现过两次，一次前缀了「x（难）」，一次没有。理应如此，是之前忽略了。上面的修改可能只是让这些重码字在权重相等的条件下，按码表出现顺序排列而已。那么上面的修改如果有效，原因只是这个码表中的每一个重码字组的排列顺序都恰好符合仓颉码序。既然如此，那么上面的修改就绕弯子了，不如直接修改

        sort: by_weight

为

        sort: original

实测效果似乎相同，或许更好，不会有一些未知的副作用。

**Comment by lotem** [comment]
詞典是按傳統漢字字頻排序的。由 `sort: by_weight` 指定。

「X」選重屬於無理碼，我認爲他是受限於技術條件的產物，不主張重碼字符合「X」碼所定義的順序。
該輸入方案的設定下，選重碼與自動調頻、詞組自動編碼等功能都不相容。保留該組編碼，僅爲照顧舊有的用戶習慣，設計上不會受他限制。

如果希望按照碼表順序出字，詞典中可設爲 `sort: original`。

**Comment by Ace-Who** [comment]
> 詞典是按傳統漢字字頻排序的。由 `sort: by_weight` 指定。

谢谢。最后一点疑问是，从我举例子来看，「传统汉字字频」与当代白话文中的字频是不是两回事？而且是固定在程序中的，而不是在配置文件中？

即使指定了 `sort: by_weight`，若码表中定义了单字权重，也按照权重排序，而忽略「传统汉字字频」？
