### ISSUE TITLE
系统图标能否根据当前输入状态（中英文）自动切换？

### ISSUE THREAD

**Issue by vankizou** [rime/home#361]
因为不知道当前输入法是中文还是英文，会造成很多误输字符。
比如：我要输入英文，但此时是中文，可我也不知道，打了好些字符后得删了重新切换。
所以有自动切换系统图标的配置吗？让系统图标显示当前输入状态是中文还是英文。

**Comment by Ace-Who** [comment]
默认就显示中英文状态的。<kbd>LShift</kbd> 即可就地切换为英文，或者 <kbd>Enter</kbd> 直接将输入码上屏，不必删了重打。

**Comment by lotem** [comment]
什麼系統？
系統輸入法圖標通常用於指示當前使用的輸入法或鍵盤佈局。
