### ISSUE TITLE
將插件納入rime/squirrel, rime/weasel的自動化構建流程

### ISSUE THREAD

**Issue by lotem** [rime/home#363]
構建腳本支持已經齊備，主要在 rime/librime 裏實現，前端的構建工程只要設置一個變量，將所需的插件（slug形式）列出。

插件如用到第三方庫，有必要提供安裝腳本 [travis-ci](https://github.com/rime/librime/blob/master/travis-install.sh#L32) / [appveyor](https://github.com/rime/librime/blob/master/appveyor.install.bat#L66) 在構建平臺上安裝依賴。這個機制只經過簡單的測試，還沒有用於實戰。

**Comment by lotem** [comment]
@hchunhui 請幫助調試 librime-lua

**Comment by hchunhui** [comment]
我试着在 librime-lua 中修改了`CMakeList.txt`，增加了 `appveyor.install.bat` 和 `travis.install.sh` 两个文件。各位可以测试一下有没有问题。

librime-lua 目前唯一的依赖是 lua。现在 cmake 的逻辑是先从系统中找已有的 luajit 或 lua 库；若找不到则从源码编译（假设使用 lua 5.3，放在插件的 `thirdparty/lua5.3` 下）。

因为 windows 上没有现成的 lua，所以 `appveyor.install.bat` 所做的即是从 https://github.com/hchunhui/librime-lua/tree/thirdparty 获得源码。

macos 我不太熟悉，不知道是否有必要 link 外部的 lua。现在 `travis.install.sh` 行为暂时与 appveyor 上一样，后续可以再改。

**Comment by lotem** [comment]
@hchunhui 讚、多謝
mac 可以用 homebrew 安裝 luajit 或 lua 軟件包，但是問題來了，這樣安裝會得到 `*.dylib` 兼有 `*.a`，我的CMake功夫不咋樣，不會讓pkg-config只去找靜態庫，結果就是 `librime.dylib` 鏈接了一個 homebrew 安裝到 `/usr/local/...` 裏面的 Lua 庫，沒法用來發佈。
所以我傾向於和 windows 上一樣的辦法。我會找人試驗一下
