### ISSUE TITLE
關於黑莓機實體鍵盤

### ISSUE THREAD

**Issue by lb00743672** [rime/home#365]
想請問，是否可以開發對應黑莓實體鍵盤上的，表情功能與標點符號列表功能？
黑莓自家的輸入法，雖然有表情符號與標點符號的table，但是其本身在語言學習上，超笨！
一堆常用的字，根本找不到，很多時候都在非常後面！

如果同文可以補上表情與標點符號的table，市場上無人能敵了！

**Comment by lotem** [comment]
向 [同文](https://github.com/osfans/trime) 作者 @osfans  提問

**Comment by lb00743672** [comment]
我個人找到這個問題的解答。

雖然沒有辦法透過實體鍵盤叫出標點符號表格，但是除了本身鍵盤上有印的小老鼠、驚歎號、逗點句點那些，還可以透過按住sym鍵加a 叫出等於符號、sym加g叫出逗號那些，自己摸索加記一下就可以了！
