### ISSUE TITLE
很都字变成方框的问题

### ISSUE THREAD

**Issue by lunarjoll** [rime/home#368]
![Screenshot from 2019-05-14 09-28-01](https://user-images.githubusercontent.com/24384754/57664520-0f11b200-762b-11e9-89ef-19502d20b314.png)

如图，很都字都会变成方框。

**Comment by lunarjoll** [comment]
system:  archlinux

**Comment by lotem** [comment]
無法重現

預設方案在這個拼音下只有一個詞組候選。

**Comment by zhmars** [comment]
@lunarjoll 那个，你是不是配置了自定义词典 `dictionary`？

**Comment by lunarjoll** [comment]
> @lunarjoll 那个，你是不是配置了自定义词典 `dictionary`？

是的

**Comment by lunarjoll** [comment]
@zhmars 
![Screenshot from 2019-05-15 01-57-22](https://user-images.githubusercontent.com/24384754/57720647-dfa78780-76b4-11e9-96cd-1ef335c63331.png)

**Comment by lunarjoll** [comment]
但是 我换了用户，就是说配置文件都是空的。最后几页的候选项还是会出现方框

**Comment by lunarjoll** [comment]
这是我切换了用户后所使用的最后几排候选项的显示，在后面的都是方框了
![Screenshot from 2019-05-15 02-09-57](https://user-images.githubusercontent.com/24384754/57721368-97896480-76b6-11e9-9e43-e14d7096dcd1.png)

**Comment by nameoverflow** [comment]
换个好点的字体（比如花园明朝

**Comment by lunarjoll** [comment]
![Screenshot from 2019-05-15 12-06-36](https://user-images.githubusercontent.com/24384754/57748366-4310d400-770c-11e9-8572-57b187fff4d6.png)

用的是思源 字体，是字体不够大，or我没配置好？

**Comment by zhmars** [comment]
这个问题似乎不一定跟字体有关，在我的机器上，如果不配置 `dictionary`，显示是正常的，一旦配置了，也会出现这种情况。（用的是内置的五笔词典和自定义的几个词组，字体是 Noto Sans CJK Regular）

**Comment by zhmars** [comment]
刚测试了几种方案，输入 `ge` 一直按候选，`luna_pinyin`、`luna_pinyin_simp`都会出现 @lunarjoll  提到的情况 ，`pinyin_simp` 则不会

**Comment by nameoverflow** [comment]
@lunarjoll 
> 用的是思源 字体，是字体不够大，or我没配置好？
思源的字库确实不够大。Rime 框架中的许多词库的汉字覆盖远超思源的范围。

**Comment by lunarjoll** [comment]
有配置char filter 的说明吗？

**Comment by nameoverflow** [comment]
@lunarjoll 
> 有配置char filter 的说明吗？

按 Ctrl+` 选增广→常用

**Comment by lunarjoll** [comment]
@nameoverflow ？？？
![Screenshot from 2019-05-19 00-35-47](https://user-images.githubusercontent.com/24384754/57972496-15f34880-79ce-11e9-926e-4fb995d5d14d.png)

**Comment by nameoverflow** [comment]
发现朙月拼音默认没有字符集……
参考 https://github.com/rime/librime/issues/59#issuecomment-223907877
