### ISSUE TITLE
關於"一起"中"一"的注音

### ISSUE THREAD

**Issue by maple3142** [rime/home#373]
如題
"一起"這兩個字中的的"一"發音根據[教育部字典](http://dict.revised.moe.edu.tw/cgi-bin/cbdic/gsweb.cgi?ccd=DSnrR6&o=e0&sec=sec1&op=v&view=0-1)中是一聲，但一般我們在讀的時候都會讀成四聲的發音
因此win10下的微軟注音和手機上的google注音都是能用四聲來輸入"一"的音的，但是rime的"注音"輸入方案似乎做不到這件事

**Comment by lotem** [comment]
連讀變調統一用單字讀音。

**Comment by maple3142** [comment]
那這有辦法自己給「一」加上「ㄧˋ」的發音嗎？

**Comment by lotem** [comment]
有。
