### ISSUE TITLE
[GITS] Unable to hide the status bar completely, with only a "中/英" indicator on the task bar

### ISSUE THREAD

**Issue by be5invis** [rime/home#38]

**Comment by lotem** [comment]
https://github.com/lotem/rime-gits is not actively developed.

The status bar's UI design inherits typical Chinese IMEs. Originally implemented by Google's IME team, it was a non-trivial task for me to figure out how to change the UI components. I decided not to work on this item as @rime/frontend folks revived rime/weasel on modern Windows.
