### ISSUE TITLE
小狼毫皮膚編輯器鏈接失效

### ISSUE THREAD

**Issue by bennyyip** [rime/home#382]
由於百度貼吧最近刪除了舊帖，[wiki](https://github.com/rime/home/wiki/CustomizationGuide#%E4%B8%80%E4%BE%8B%E5%AE%9A%E8%A3%BD%E5%B0%8F%E7%8B%BC%E6%AF%AB%E9%85%8D%E8%89%B2%E6%96%B9%E6%A1%88)中的皮膚編輯器鏈接已經失效。

我曾經將其移植到 Github Pages(https://bennyyip.github.io/Rime-See-Me/ )，可否將鏈接加到 wiki 中？

**Comment by lotem** [comment]
謝謝幫忙。
請直接編輯wiki，替換失效的鏈接。

**Comment by bennyyip** [comment]
@lotem 但是我沒有wiki的編輯權限。

**Comment by kunki** [comment]
done

**Comment by kunki** [comment]
另外注意到配色編輯器不包含`hilited_candidate_label_color`和`hilited_comment_text_color`的配置項，不知可否補上？

**Comment by GJRobert** [comment]
> 另外注意到配色編輯器不包含`hilited_candidate_label_color`和`hilited_comment_text_color`的配置項，不知可否補上？

@kunki 我把 bennyyip 的作品 fork 了一個給鼠鬚管用的配色編輯器：[Rime 西米 for Squirrel](https://gjrobert.github.io/Rime-See-Me-squirrel/)
裡面有加上所有的 label 及 comment 相關選項了。只是我拿掉了 border，因為鼠鬚管沒有 border。歡迎給予意見。另外我也建議請有 wiki 編輯權限的朋友幫忙把這個配色編輯器也放到 wiki 中。
