### ISSUE TITLE
0.14.2自定义短语设置权重无效

### ISSUE THREAD

**Issue by segamop** [rime/home#383]
升级到0.14后，自定义短语设置权重为「1」，但是在候选词里不是排第一位的。0.14版本前都是正常的。

**Comment by lotem** [comment]
請升級到小狼毫0.14.2

預設方案朙月拼音 無法重現問題 可能和自定義配置有關

**Comment by segamop** [comment]
配置文件请见附件。已经是0.14.2了，问题依然存在。谢谢！
链接: https://pan.baidu.com/s/1XCbauZcBT4RUsJUS8_yEyg 提取码: 2971

**Comment by segamop** [comment]
重装了一次，重新配置了一下，好了。可能是旧配置文件某些配置，新的不认。谢谢！
