### ISSUE TITLE
形码码表，比如五笔、小鹤音形，能否识别空码时自动转为临时英文

### ISSUE THREAD

**Issue by ryan00zou** [rime/home#387]
如题。请问rime能实现形码码表的空码识别吗？有码时正常出字，低于或等于4码空码时自动切换为临时英文状态（候选能提示英文单词）。如果能实现，中英文混输衔接就更流畅了。
谢谢各位大佬解答。

**Comment by Ace-Who** [comment]
英文状态就是无方案状态，有候选就是有方案状态，是矛盾的。

**Comment by lotem** [comment]
不支持英文
