### ISSUE TITLE
最新的鼠须管似乎 single_char_filter 不起作用了

### ISSUE THREAD

**Issue by flyingns** [rime/home#389]
重新布置了还是单字和词组混在一起。

![Screen Shot 2019-06-22 at 17 40 52 ](https://user-images.githubusercontent.com/16456728/59962218-fabbb180-9514-11e9-9664-1f1985d3d879.png)

**Comment by Ace-Who** [comment]
以前不清楚，现在[single_char_filter 的作用是把单字提前](https://github.com/rime/home/issues/370)。是否无视词频就不知道了，还可能只对完全匹配的候选起作用。

**Comment by lotem** [comment]
Fixed with commit https://github.com/rime/librime/commit/6948a623632c23ef55071b77eca32c728fd786d3
