### ISSUE TITLE
安装完小狼毫后无法修改用户文件夹

### ISSUE THREAD

**Issue by alphagox** [rime/home#399]
即使重新安装软件也无法弹出设置用户文件夹路径的界面，只有系统第一次安装的时候才能修改用户文件夹路径，版本为目前最新版本

**Comment by alphagox** [comment]
找到设置界面了，打扰了

**Comment by lj123454321** [comment]
我也在找，请问在哪里。

**Comment by alphagox** [comment]
> 我也在找，请问在哪里。

* 首先我找到了开始菜单小狼毫的文件夹下，找到这个选项

![云之家图片20190709134223.png](https://i.loli.net/2019/07/09/5d242962d38a851545.png)
* 打开之后修改一下自己想修改的地址目录，然后确定

![云之家图片20190709134131.png](https://i.loli.net/2019/07/09/5d2429a2d588948122.png)

* 修改完成之后卸载小狼毫，原来的个人文件夹就可以删除了，重新安装小狼毫就发现用户文件夹已经部署到自己刚才设置的目录下了

**Comment by lj123454321** [comment]
> > 我也在找，请问在哪里。
> 
> * 首先我找到了开始菜单小狼毫的文件夹下，找到这个选项
> 
> ![云之家图片20190709134223.png](https://camo.githubusercontent.com/caa3cfad61b8ee147d2327222b129c2afde4219d/68747470733a2f2f692e6c6f6c692e6e65742f323031392f30372f30392f3564323432393632643338613835313534352e706e67)
> 
> * 打开之后修改一下自己想修改的地址目录，然后确定
> 
> ![云之家图片20190709134131.png](https://camo.githubusercontent.com/38cc3c68c25f47ba6101b740fba191d6c642eb9e/68747470733a2f2f692e6c6f6c692e6e65742f323031392f30372f30392f3564323432396132643538383934383132322e706e67)
> 
> * 修改完成之后卸载小狼毫，原来的个人文件夹就可以删除了，重新安装小狼毫就发现用户文件夹已经部署到自己刚才设置的目录下了

感谢！！
