### ISSUE TITLE
詞典快照文件 *.userdb.txt 中的 c、d、t 三個值分別是什麼意思

### ISSUE THREAD

**Issue by Wujidadi** [rime/home#40]
請問老大，詞典快照文件中每一個詞後面的 c、d、t 三個值分別是什麼意思，例如下面這個：

c=1 d=9.15797e-25 t=783834
c=4 d=4.06581e-31 t=783834

我自己猜 c 應該是該詞打過的次數？
d 則關係到候選詞列表中的排列先後？
t 是時間？

但是 c 好像又會減少？
我把兩個同碼詞其中之一的 d 調高之後（使之排在前面），另外一個詞的 d 不變，但 c 降低了
譬如

c=2 d=1 t=783834  →  c=2 d=1.2 t=784000
c=2 d=1 t=783834  →  c=1 d=1 t=784000

**Comment by shiami** [comment]
+1, how to change the value?

**Comment by lotem** [comment]
Don't necrobump...

The user dictionary is not designed to be edited manually.

`c` is commit count. It can be decreased if user
  - quickly deleted the previously committed word, or
  - deleted the user phrase via short-cut keys which resets the commit count.
