### ISSUE TITLE
无法用删词快捷键删除自造词

### ISSUE THREAD

**Issue by sakern** [rime/home#402]
快捷键都试过了，CTRL+D、CTRL+DELETE、SHIFT+DELETE、ALT+DELETE，建议能鼠标右键删词，最方便。
系统为WINDOWS 7 x64。

**Comment by charlestang** [comment]
不慎上屏了錯誤的詞組，再打同樣的編碼時，那錯詞出現在候選欄，令有潔癖的同學十分不爽。這時候可以：

先把選字光標（用上、下鍵）移到要刪除的用戶詞組上，再按下 Shift+Delete 或 Control+Delete（蘋果鍵盤用 Shift+Fn+Delete）。

只能夠從用戶詞典中刪除詞組。用於碼表中原有的詞組時，只會取消其調頻效果。


以上这段文档，我全部试过了，都不对的！

**Comment by lotem** [comment]
@charlestang 怎麼測試 如何不對 願聞其詳

**Comment by charlestang** [comment]
在我电脑上（MacOS 10.13.6），按下 ⇧ + Del 是没有任何效果的，⌃ + Del 也一样。⇧ + Fn + Del 只是把我用 上下 键选中位置往前挪了一个，也不会删除自造词。笔记本的键盘和外接键盘都试过了。没有任何办法删除打错出来的词。配置文件 $HOME/Library/Rime 里我也没有搜到相关配置。

**Comment by zcunlin** [comment]
ctrl del
发件人： Charles Tang
发送时间： 2019-08-20 10:48
收件人： rime/home
抄送： Subscribed
主题： Re: [rime/home] 无法用删词快捷键删除自造词 (#402)
在我电脑上（MacOS 10.13.6），按下 ⇧ + Del 是没有任何效果的，⌃ + Del 也一样。⇧ + Fn + Del 只是把我用 上下 键选中位置往前挪了一个，也不会删除自造词。笔记本的键盘和外接键盘都试过了。没有任何办法删除打错出来的词。配置文件 $HOME/Library/Rime 里我也没有搜到相关配置。

**Comment by lotem** [comment]
無法重現。
預設的快捷鍵是 <kbd>Control+k</kbd> 不是 <kbd>Control+d</kbd>。

**Comment by otakutyrant** [comment]
我 Windows 上也没法取消调频效果，很难受。

**Comment by gshmu** [comment]
> 無法重現。
> 預設的快捷鍵是 Control+k 不是 Control+d。

OSX `Control+k` 和 `fn+Control+delete` 两个都可以

**Comment by MLZC** [comment]
OSX我尝试用shift+fn+backspace删除候选词也是没有效果。

**Comment by MLZC** [comment]
> > 無法重現。
> > 預設的快捷鍵是 Control+k 不是 Control+d。
> 
> OSX `Control+k` 和 `fn+Control+delete` 两个都可以

尝试过还是不行

**Comment by c02y** [comment]
我最近也遇到同样的问题，最后发现我要删除的词不是自造词而是已经写到词典里面的固定词，所以如果发现删除自造词的快捷键无法删除你要删除的词可以看看那个词究竟是不是只出现在自造词文件里面

**Comment by renektonwu** [comment]
@c02y 多谢总结。 此外还可以上屏多几次你真正想输入的词语，这样就可以把在字典里你不想输入的词语给挤出首个位置或者首页

**Comment by AlbertWang2018** [comment]
先把选字光标（用上、下键）移到要删除的用户词组上，再按下 Shift+Delete 或 Control+Delete（苹果键盘用 Shift+Fn+Delete）。即使要删除第一个词，也要光标移动一下才行，我试了可以的。版本0.15.0.0，如果是词库文件里的词，我是直接从文件里删除的，例如编码 ‘excel’ 对应 ‘脑络通’，直接删除这词就行。
