### ISSUE TITLE
请问有大婶能写个详细帮助文档吗？

### ISSUE THREAD

**Issue by tianweilun** [rime/home#403]
按照官方文档操作，更改“/”直接显示“、”，操作无数次都不行，网上找的文档也不行，而且官方文档写的和文件实际还不同，哪位大神能写个最新的文档？

**Comment by lotem** [comment]
https://github.com/rime/home/wiki/CustomizationGuide#%E4%B8%80%E4%BE%8B%E5%AE%9A%E8%A3%BD%E6%A8%99%E9%BB%9E%E7%AC%A6%E8%99%9F
完全有效
