### ISSUE TITLE
如何去除光标,和空格.

### ISSUE THREAD

**Issue by xiaoxiong2333** [rime/home#407]
![snipaste20190719_222915](https://user-images.githubusercontent.com/53089381/61542695-ae608480-aa74-11e9-8b0f-cd656a875195.png)
1,我喜欢简洁,请问如图红色标记到位置如何去掉.
2,另一个问题,我尝试查找手册文档, 这个https://github.com/LEOYoon-Tsaw/Rime_collections/blob/master/Rime_description.md 文档并没有将可用到组件都介绍清楚.例如 selector navigator  两个字段就压根没有介绍,而且在所有的预设方案里面也没有看到定义,是否是只能使用,而不必(不能)配置?
我希望能左右键更改候选字,上下键移动光标.(因为改为水平显示后,左右键比较直观).
虽然我已经通过key_binder映射达到了效果,但是是否有更详细的文档.

----------
(还有个问题,不知道是新增个issues好,还是在一个里面提问好.)
3,是否有方法关闭切换中英的时候在屏幕上的提示.
![Clipboard Image](https://user-images.githubusercontent.com/53089381/61574238-41d69b80-aaef-11e9-8481-b2496c8eb128.png)
4,有没有什么方法修改上面提示以及任务栏的图标. 画风和其他图标太不一样,强迫症.
5,如何输入当前的日期和时间. 其他输入法都是可以 用[rq]等简拼就插入当前日期.

提前感谢

**Comment by Ace-Who** [comment]
1. 去掉光标不知道。去掉空格：

```yaml
patch:
  translator/preedit_format:
    - 'xform/ //'
```

2. 是预设组件，参考 https://github.com/rime/home/wiki/RimeWithSchemata。用按键映射没问题。

**Comment by lotem** [comment]
光標插入點是必須顯示的，因爲插入點不會永遠在輸入串的末尾。
如果用比較新的版本，候選框橫排的時候光標向右會選中右方的候選字。
不支持在拼音串橫書的情況下用上下鍵移動光標，這不科學。
其他修改需要編程實現。

**Comment by doglex** [comment]
> 1. 去掉光标不知道。去掉空格：
> 
> ```yaml
> patch:
>   translator/preedit_format:
>     - 'xform/ //'
> ```
> 
> 2. 是预设组件，参考 https://github.com/rime/home/wiki/RimeWithSchemata 。用按键映射没问题。

设了无效

**Comment by doglex** [comment]
> ```yaml
> - 'xform/ //'
> ```

有效，不能在dealut.custom.yaml里配置，得在 rime_forst.schema.yaml里
