### ISSUE TITLE
建議推出圖形化配置功能

### ISSUE THREAD

**Issue by mrdulin** [rime/home#408]
目前通過YAML文件配置的方式學習曲線很高，也很容易出錯。

讓我想起很早以前的vscode,也是通過json文件進行配置，後來推出了圖形化配置界面。

想問作者有沒有這方面的計劃？

**Comment by bosconb** [comment]
参见佛振的这个问答：[为什么鼠须管输入法的设置这么麻烦？为什么不弄个设置界面？](https://www.zhihu.com/question/21101540/answer/624549382)

**Comment by redchenjs** [comment]
現在比較缺少能夠fork&pr的相關技術人員

**Comment by lotem** [comment]
小狼毫已經有了。安裝時候會調用。
