### ISSUE TITLE
部分繁体中文无法在朙月拼音简体字下正常显示

### ISSUE THREAD

**Issue by updater1234** [rime/home#413]
部分繁体中文无法在朙月拼音简体字下正常显示，如图显示
![photo_2019-08-05_16-54-51](https://user-images.githubusercontent.com/31512600/62451918-c2f58a00-b7a1-11e9-9438-d2f1a93d3428.jpg)
请问一下在Linuxmint19下如何解决？

**Comment by redchenjs** [comment]
這應當是字體原因，在輸入法設置裏換個字體試試

**Comment by Prcuvu** [comment]
看编码应该是扩展 B 区的字，字体无法显示的话就会显示为方框中有 Unicode 标量值。请改用收录更全的字体。
