### ISSUE TITLE
請問倉頡有沒有關聯字選擇?

### ISSUE THREAD

**Issue by Nick838** [rime/home#422]
想請問大家，倉頡5代有沒有聯想字(關聯字)選擇功能?

例如: 打"台"會有"灣"字選擇，或其他字詞...

謝謝!...

以下是其他中文輸入法套件的cap圖

https://upload.cc/i1/2019/08/30/WYCxOl.jpg

**Comment by lotem** [comment]
没有。

**Comment by Nick838** [comment]
> 没有。

希望日後能夠加上這個功能。謝謝您！...
