### ISSUE TITLE
行列30輸入法無法打出「䈎」字

### ISSUE THREAD

**Issue by Reniastyc** [rime/home#426]
這個字是收入了字庫的，查到輸入碼是「䈎	lrsv」
然而當我輸入「lrsv」的時候，如圖：
 
![image](https://user-images.githubusercontent.com/37499529/64909674-f8e34200-d741-11e9-9304-2b941a068422.png)

列表中祇有「笹木，笹，壬，竹」，並沒有本應出現的「䈎」

請問我該如何處理？

**Comment by Ace-Who** [comment]
切换到「增广」或「扩充」字符集——<kbd>F4</kbd>/<kbd>Ctrl</kbd> + <kbd>\`</kbd> 选单，或默认快捷键 <kbd>Ctrl</kbd> + <kbd>Shift</kbd> + <kbd>5</kbd>。

**Comment by Reniastyc** [comment]
原來如此，感謝萬分
