### ISSUE TITLE
逗號、句號無法直接上屏

### ISSUE THREAD

**Issue by hlccwww** [rime/home#431]
![TIM图片20190926171037](https://user-images.githubusercontent.com/55830778/65677507-4d60b880-e084-11e9-92d8-f78013a9852f.png)

schema表里是这样的
`punctuator:
  import_preset: symbols
  full_shape:
    ',' : { commit: ， }
    '.' : { commit: 。 }
  half_shape:
    ',' : { commit: ， }
    '.' : { commit: 。 }`

跪求大佬帮忙。

**Comment by lotem** [comment]
因爲有兩個候選字。候選字唯一才可以自動上屏。
請檢查一下配置，確定候選1的來源。

**Comment by hlccwww** [comment]
> 因爲有兩個候選字。候選字唯一才可以自動上屏。
> 請檢查一下配置，確定候選1的來源。

檢查哪裡的配置？
我schema裡的punctuator是參照“朙月拼音”的，但我使用朙月拼音卻是直接上屏的。
我嘗試了好多個辦法也搜索過都沒有找到，只能賴求助了，希望能夠更加具體一點，拜託了

**Comment by lotem** [comment]
既然原裝配置好用，本品就不存在問題。
我無法查閱你的配置代碼，因此自定義配置中的錯誤需要你自己排查。如果找不到原因，請使用原裝配置。
