### ISSUE TITLE
中文切到英文，已输入的字符没有清空也没有变成英文输入模式

### ISSUE THREAD

**Issue by crosslife** [rime/home#432]
打字的时候以为是英文，打了之后才发现是中文，这时候 shift 切输入法，既没有清空之前输入的字符，也没有把之前输入的字符变成英文输入的方式，而是进入了一种奇怪的状态，比较尴尬。

![image](https://user-images.githubusercontent.com/1802419/65811690-eb709200-e1ee-11e9-8ab2-f0c2507448f9.png)

**Comment by lotem** [comment]
符合設計：左Shift默認設置爲臨時切換到拉丁文，上屏後自動切換回來。
