### ISSUE TITLE
style/display_tray_icon在0.14.3版本不起作用

### ISSUE THREAD

**Issue by whudwl** [rime/home#434]
我想要隐藏中英文指示icon， 于是在weasel.custom.yaml中加入了如下内容， 可是tray icon还是存在。 新版本中这个选项是否没有作用了？ 
```
patch:
  style/display_tray_icon: true
```

**Comment by lotem** [comment]
上述代碼含義是 *顯示* 托盤圖標。
另外，托盤圖標的功能已經被語言欄圖標取代。後者是始終顯示的。請注意區分圖標顯示的位置是托盤區還是語言欄。
