### ISSUE TITLE
弄个Web版Try Rime Input Tools online

### ISSUE THREAD

**Issue by aoezc** [rime/home#436]
很多时候不方便/不能安装输入法，就只能用网页版在线输入法了。（网页在线输入法较完善的好像就只有[Try Google Input Tools online](https://www.google.com/inputtools/try/)）但Google Chinese (Simplified,China)打拼音通常都只显示简体字，俺又不会打粤拼和台湾注音，又想用拼音打学繁体字，因此希望中州韻輸入法有网页版

@lotem @alswl @BYVoid @lembacon @wengxt @zouxu09 @liuzhiwei @LEOYoon-Tsaw @kunki @osfans @jakwings @Prcuvu @hchunhui @wishstudio @nameoverflow

**Comment by aoezc** [comment]
在官网弄个栏目专门整合像 Try Google Input Tools online那样的输入法

**Comment by lotem** [comment]
過去有人做過用wasm構建librime，誰記得在哪裏？

**Comment by sgalal** [comment]
> 過去有人做過用wasm構建librime，誰記得在哪裏？

https://github.com/rime/librime/issues/121#issuecomment-373952203

**Comment by lotem** [comment]
從過去的嘗試看，有必要把部署數據的程序從輸入法程序獨立出來。

**Comment by eagleoflqj** [comment]
https://github.com/LibreService/my_rime
