### ISSUE TITLE
能支持云词库吗

### ISSUE THREAD

**Issue by loricheung** [rime/home#44]
虽然导入各种扩充词库，鼠须管始终不能像国内的输入法一样更新最新词库，手动太麻烦啊

**Comment by kunki** [comment]
暫無計畫。

**Comment by lazywei** [comment]
@lorichueng 方便分享一下用於導入的擴充詞庫嗎？

**Comment by loicaplay** [comment]
第三方实现办法：  转自百度贴吧  半月湾C  
==============================================================================
RIME本身不可以实现云同步，但我们可以借助第三方云端实现此功能。我本人使用的坚果云网盘，类似的像是百度，115均可。
第一步打开用户文件夹中的installation.yaml文件，修改sync_dir指向位置（这个位置将是RIME的词典与配置存储的地方）
另外也可修改installation_id为自己喜欢的名称（为字母下划线数字，也可以不修改，我的是修改为了lin）
![0c282b46f21fbe0946ab880968600c338644ad1d](https://cloud.githubusercontent.com/assets/16322235/11865151/2cec54ce-a4dd-11e5-9f0f-4eb2cafe25e9.jpg)






第二部做好上述修改后，点击用户同步。同步完毕后，lin文件夹设置为同步文件夹。右击即可实现设置。
![81e0528da977391243d0ce7cfb198618377ae219](https://cloud.githubusercontent.com/assets/16322235/11865156/33a11dea-a4dd-11e5-86c5-3998f4572c2b.jpg)





以后若在其他电脑上使用RIME可做如下步骤：
① 安装好RIMR与你的坚果云客户端。
② 通过坚果云客户端下载好你的个人词库配置文件等（注意位置要与你在installation.yaml中修改的一致）
③ 修改用户文件夹中installation.yaml文件中的sync_dir指向，使其与坚果云下载好的个人配置等文件位置一致。
④ 点击“用户资料同步”同步个人词库等。

关于同步在说明几点：
⑴ 上述中的第四步同步是将从云端同步至本地的词库同步进你的RIME中，而个人配置没有同步进RIME中。个人配置需要手动将你设置好的几个文件手动拖入进“用户文件夹”，重新部署以实现配置的同步。
⑵ 词库的同步于RIME讲是一个双向的同步。
如你在甲电脑使用RIME积累了词汇ABCDE，而后将ABCDE词汇同步进云端。在乙电脑云端先同步进本地的同步文件夹（也就是sync_dir指向的文件夹）。乙电脑在之前积累了词汇为EFGH，当乙点击“用户资料同步”后，RIME实现的是一个双向的同步：即乙电脑积累的词汇EFGH同步进sync_dir指向的同步文件夹，sync_dir指向的同步文件夹中的ABCDE同步进“用户文件夹”
⑶ 配置的同步是单向的同步，即由“用户文件夹”指向“同步文件夹”
⑷ 原因也简单，如果不是这样，当“用户文件夹”与“同步文件夹”中的配置不一致时不知道采用哪个，那就乱了。

**Comment by herrdu** [comment]
能支持云词库吗？

**Comment by alswl** [comment]
@loicaplay 他想要的云词库是自动更新的词库，而非将用户自己的词库同步在云盘上。

@loricheung 我建议自己从第三方词库导出 txt，然后放到自己 Rime 配置中。
你可以参考一下我的第三方词库：https://github.com/alswl/Rime 。

**Comment by loricheung** [comment]
@alswl 嗯，我现在就是在这么用，不过还是不能实现自动化。作者似乎不考虑实现这个功能了

**Comment by alswl** [comment]
@loricheung Rime 的特性不允许它加上这个功能：它应当是没有第三方资源依赖的。从设计理念来说，Rime 期望用户的词汇库是慢慢自发形成的，所以应当避免导入大量词汇，这会增加重码率。

**Comment by osfans** [comment]
不過有開源的api，倒是可以單獨加一個translator。

**Comment by lotem** [comment]
我插句話。這個功能容易和「雲輸入」混淆，後者是指實時向服務器查詢當前輸入串的轉換結果——這個目前是不準備做的。
自動更新詞庫的事情，現在條件也不具備，因爲不支持在使用過程中無縫地卸載詞庫、並在後臺更新。
也許可以做成半自動的，一鍵更新。思路如下：
更新源，現在只能靠人工，定期向一個 GitHub 代碼庫提交更新。今後也許有協作的可能，比如用戶端共享一些片段，這需要一些腳本功夫。
在本地建立一個小型（拼音）詞典，對應新詞。從主要詞典獨立出來以求快速部署更新。
通過一個（打斷輸入的）命令執行更新腳本，從更新源拉取代碼，本地部署。

**Comment by keven1911** [comment]
云输入、云词库这种事情还是不做的好，本来选鼠须管就是不想用云输入的搜狗、百度输入法。

**Comment by lotem** [comment]
https://github.com/rime/home/issues/44#issuecomment-327373625 構想中的具體計劃，
在這裏另起討論： https://github.com/rime/plum/issues/5

**Comment by throughthewall** [comment]
没有云同步就没有个人隐私安全的问题。鱼和能熊掌。
所以还是动动手自己云第三方云端来实现这个功能，是很完美，不过也还不错，毕竟个人使用的输入法也不会常常增加太词汇。
