### ISSUE TITLE
訴求提升并升高ＲＩＭＥ小狼豪输入法的选字准确率和正确率。

### ISSUE THREAD

**Issue by a125907047** [rime/home#444]
也請ＲＩＭＥ小狼豪输入法者提升并升高ＲＩＭＥ小狼豪输入法的选字准确率到千万亿分之千万亿（１００００００００／１００００００）絕對准确并定然会选对字或無窮大分之無窮大（∞／∞）绝对准确并定然能选对字，也升高正确率为千万亿分之千万亿或無窮大分之無窮大的绝对正确率。

**Comment by lotem** [comment]
選配「八股文」(https://github.com/lotem/rime-octagram-data) 語言模型有助於提高選字準確率。
