### ISSUE TITLE
建议修改文档，写清“keyA/keyB/keyC”的用法仅限补丁文件

### ISSUE THREAD

**Issue by AlynxZhou** [rime/home#451]
修改 `~/.config/ibus/rime/ibus_rime.yaml` 添加水平设置时发现如下问题：

如果设置：

```
style:
  horizontal: true
```

没有问题，但是如果按这种语法设置：

```
style/horizontal: true
```

则不生效。

此类斜线语法是否仅限 `.custom.yaml` 文件？如果是，建议在文档里写清，以便明确何时使用 RIME 扩展语法，或者修改文档全部推荐使用 YAML 默认格式。

**Comment by lotem** [comment]
很抱歉。對用家造成了困擾。文檔的確需要加強。
不過對目前的程序而言，該用法不限於 `*.custom.yaml` 文件。

新作的文檔還不成系統，這是其中相關頁面：
https://github.com/rime/home/wiki/Configuration

**Comment by AlynxZhou** [comment]
这种语法是否仅限于 `patch` key 下面？按我的测试，第二种写法是没效果的，所以我猜这种只能限于打 patch 的情况。

**Comment by lotem** [comment]
是的。
`*.custom.yaml` 的 `patch` 節點是用`__patch`語法實現的
https://github.com/rime/home/wiki/Configuration#%E8%A3%9C%E9%9D%AA

設計這種語法的原因詳見
https://github.com/rime/home/wiki/CustomizationGuide#%E5%AE%9A%E8%A3%BD%E6%8C%87%E5%8D%97
