### ISSUE TITLE
我 fork 了一個配色編輯器，歡迎加到 wiki 中

### ISSUE THREAD

**Issue by GJRobert** [rime/home#453]
我把 bennyyip 的 [Rime 西米](https://bennyyip.github.io/Rime-See-Me/) fork 出了一個比較適用於鼠鬚管的版本：
https://gjrobert.github.io/Rime-See-Me-squirrel/

與原本小狼毫版最大的差別是去掉了邊框的設定，另外補上了所有的 comment 及 label 設定。歡迎把它加到 wiki 中〜

專案原始碼：[Rime 西米 for Squirrel](https://gjrobert.github.io/Rime-See-Me-squirrel/)

有機會也許我可以再 contribute 回去小狼毫版，或是甚至做一個合併版來切換小狼毫/鼠鬚管模式。

**Comment by GJRobert** [comment]
另外，我沒有辦法註冊登入百度貼吧，如果有朋友可以幫忙分享到那裡的話也很歡迎〜

（我只有臺灣 PTT 的帳號，有分享到 IME 板，不過好像沒什麼人關注 QQ）

**Comment by GJRobert** [comment]
想試著 clone 一下 wiki 來直接修改，結果也是需要權限 ^^; 否則無法 push……

**Comment by lotem** [comment]
Wiki是開放在線編輯的吧？

**Comment by GJRobert** [comment]
> Wiki是開放在線編輯的吧？

我之前那時候試，rime/squirrel repo 的 wiki 是我可以編輯的，至於 rime/home 這邊就無法了……^^;

目前看也是如此（在 Firefox 瀏覽器中使用 Tile Tabs 並排顯示兩個 wiki）
![2019-12-19_14-05-23](https://user-images.githubusercontent.com/655584/71149203-d09b4000-2268-11ea-99fc-5ca9eef9fe88.png)

如果 rime/home wiki 編輯權有開放的話，我可以編輯的～

**Comment by GJRobert** [comment]
@lotem 不知道是不是方便打開 rime/home wiki 的編輯權限呢

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by lotem** [comment]
在這裏改好了：
https://github.com/rime/home/wiki/CustomizationGuide

原來是曾有人亂改wiki，所以限制爲只允許團隊成員編輯。

**Comment by Ace-Who** [comment]
有个疑似错误想改很久了，看看改得对吗？

https://github.com/rime/home/wiki/Configuration/_compare/4f434d9a7554ea9337063f8494bb504e8e4a9d6c...c6ed018fd37b08945de4fc35895e8b4a53925d7c

**Comment by GJRobert** [comment]
@lotem 感激不盡
