### ISSUE TITLE
为什么五笔拼音只能打五笔不能打出拼音

### ISSUE THREAD

**Issue by skypinglee** [rime/home#455]
安装好0.14.3版本后，里面不包含五笔，在“获得更多输入法方案中”，命令行输入wubi，可以调出五笔拼音方案，但是只能五笔输入，没有办法用拼音输入，请哪位大神指点一下！
另外，安装好后，调用五笔86和五笔拼音方案，也没有办法进行反查！

# Rime schema settings
# encoding: utf-8

schema:
schema_id: wubi_pinyin
name: "五笔·拼音"
version: "0.9"
author:
- 發明人 王永民先生
description: |
五筆字型86版＋漢語拼音混合輸入。
碼表源自 ibus-table
dependencies:
- pinyin_simp

switches:
- name: ascii_mode
reset: 0
states: [ 中文, 西文 ]
- name: full_shape
states: [ 半角, 全角 ]
- name: extended_charset
states: [ 常用, 增廣 ]
- name: ascii_punct
states: [ 。，, ．， ]

engine:
processors:
- ascii_composer
- recognizer
- key_binder
- speller
- punctuator
- selector
- navigator
- express_editor
segmentors:
- ascii_segmentor
- matcher
- abc_segmentor
- punct_segmentor
- fallback_segmentor
translators:
- punct_translator
- reverse_lookup_translator
- table_translator

speller:
delimiter: " ;'"
#max_code_length: 4 # 四碼頂字上屏

translator:
dictionary: wubi86
prism: wubi_pinyin
enable_charset_filter: true
enable_sentence: true
enable_encoder: true
encode_commit_history: true
max_phrase_length: 4
disable_user_dict_for_patterns:
- "^z.*$"

abc_segmentor:
extra_tags:
- reverse_lookup

reverse_lookup:
dictionary: pinyin_simp
prefix: "`"
suffix: "'"
tips: 〔拼音〕
preedit_format:
- xform/([nl])v/$1ü/
- xform/([nl])ue/$1üe/
- xform/([jqxy])v/$1u/

punctuator:
import_preset: default

key_binder:
import_preset: default

recognizer:
import_preset: default
patterns:
reverse_lookup: "`[a-z]*'?$"

**Comment by yangzhaoyunfei** [comment]
你好，从你给出的配置文件看，这个输入方案，主要是适配五笔86，拼音方案只是反查，并且需要【`】键引导。并不支持同一个输入码既出五笔候选项、又出拼音候选项；
如果你需要实现这样的效果，需要在配置文件中在添加拼音的副translator，具体可以参考rime文档，和这份[配置文件](https://github.com/LEOYoon-Tsaw/Cangjie6)，

**Comment by yangzhaoyunfei** [comment]
你好，从你提供的配置文件，以及我以往的使用经验来看，这分配置文件主要是提供五笔86的输入方案，拼音方案只是提供了反查之用，且需要[ ` ]键引导，如果你需要一串输入码同时出现五笔候选项和拼音候选项，你可能需要参考rime文档，然后自行修改配置文件来实现；这里给你提供一个配置文件中整合了多种输入方案的参考[配置文件](https://github.com/LEOYoon-Tsaw/Cangjie6/blob/master/cangjie6.schema.yaml)

**Comment by leoorz** [comment]
配置里有：
  dependencies:pinyin_simp

即五笔拼音依赖简拼，下载地址：https://github.com/rime/rime-pinyin-simp

pinyin_simp.custom.yaml
pinyin_simp.dict.yaml

这两个文件放入 C:\Users\xxx\AppData\Roaming\Rime\ 后重新部署即可
