### ISSUE TITLE
突然出现的剪切板历史是那个快捷键？

### ISSUE THREAD

**Issue by shoyuf** [rime/home#459]
之前用的时候不知道按了什么突然出现了个剪切板历史记录的窗口，是输入法的界面，请问是哪个快捷键出发的？
系统 Ubuntu with Fcitx

**Comment by lotem** [comment]
不了解。请咨询 https://github.com/fcitx/fcitx

**Comment by meicale** [comment]
Ctrl + ; 调出系统剪切板最后五个内容，这个好像是fcitx框架带点内容，很想ibus框架也可以这样点去做，我安装fcitx的时候有问题，就卸载使用了ibus。

**Comment by gugu-py** [comment]
同问ibus的剪切板快捷键

**Comment by moshangluoying** [comment]
> 同问ibus的剪切板快捷键

ibus输入法框架没有自带历史剪贴板的功能；
 很想要这个功能的话，可以另外安装[copyq](https://github.com/hluk/CopyQ)

**Comment by SeaRat** [comment]
想做一个类似win10剪贴板那样的 简单的剪贴板历史工具，有办法用rime+lua脚本实现吗？
