### ISSUE TITLE
能否實現單字不識別簡碼

### ISSUE THREAD

**Issue by Reniastyc** [rime/home#461]
目前正在調整一箇字形輸入法
當設置簡碼時，能否讓輸出單字的時候不使用簡碼？
（因爲設置簡碼之後想輸出罕用字又變困難了）

嘗試過修改字典規則實現簡碼，但是這樣一來自造詞不能被簡碼規則應用到。
如果能讓字典規則也能作用於用戶字典，那也能解決目前的問題吧。

**Comment by Ace-Who** [comment]
没看明白。

**Comment by lotem** [comment]
能。

**Comment by lotem** [comment]
https://github.com/LEOYoon-Tsaw/Rime_collections/blob/master/Rime_description.md#%E4%B8%89translator

打開 `translator/strict_spelling` 選項
