### ISSUE TITLE
Could not use Super_L/Super_R as switch_key

### ISSUE THREAD

**Issue by haosdent** [rime/home#464]
Hi, I am trying to set Super_L/Super_R as switch_key, however, looks like only `Control_L/R`, `Shift_L/R` works in rime. From the code librime, I could not find such limitation. @lotem do you know which part I could modify in librime to make it support Super_L/Super_R as switch key? Thank you in advance.

**Comment by lotem** [comment]
Yes I do know.
Super keys are unsupported. They are not commonly used as input mode switch key. They may not be usable in all systems.
https://github.com/rime/librime/blob/master/src/rime/gear/ascii_composer.cc#L62
Control and Shift are implemented based on common request.
https://github.com/rime/librime/blob/master/src/rime/gear/ascii_composer.cc#L85

**Comment by huipengcheng** [comment]
need this feature too

**Comment by lotem** [comment]
Alt and Super modifier keys aren't supported because it is unclear if they work cross-platform. On some systems they are used as system or app shortcuts and as a result Rime won't receive these events.

If someone is dedicated to implement and test the feature, please send a PR to rime/librime.
