### ISSUE TITLE
请问有没有办法设置不进行繁简转换? (保持custom_phrase)

### ISSUE THREAD

**Issue by nutnutwin** [rime/home#467]
大家好
# 情况
Rime很好用我考虑把日语输入法并入Rime

不使用各个输入法的码表而是用
custom_phrase.txt
增加自定义词汇, 导入了几万个日语词汇
※使用明月方案

# 问题
因为简体汉字, 日语汉字, 繁体汉字有所不同
比如｢语｣和｢数｣在简日繁下分别为
语語語
数数數

我试了几种设置都不能保持日语输入
- f4设置成简体(失败 显示｢语数｣)
- f4设置成繁体(失败 显示｢語數｣)
- 改luna_pinyin.schema.yaml里的simplifier(comment)(还是失败)

请问有上面办法保持custom_phrase里的字? ★不要转繁体/简体

Rime实在太好用, 谢谢

**Comment by lotem** [comment]
就如你所言，在方案裏設置爲不做轉換，即可保持詞典文件原文的字形。

**Comment by nutnutwin** [comment]
你好能否请大神告诉我怎么设置成｢不做转换｣?
我试过把下面Simplifier Comment掉, 好像没有变化
> 改luna_pinyin.schema.yaml里的simplifier(comment)(还是失败)
不好意思新手太懂...求指教
> 
> 
> 就如你所言，在方案裏設置爲不做轉換，即可保持詞典文件原文的字形。

**Comment by lotem** [comment]
如果現在會做轉換，方案代碼裏應該已經配置了 `simplifier` 組件。
找到 `engine/filters` 列表中的 `simplifier`，例如 https://github.com/rime/rime-luna-pinyin/blob/master/luna_pinyin.schema.yaml#L53 ，刪除該項（或多項）。

**Comment by nutnutwin** [comment]
感謝!
我之前有試過這個辦法(刪除這行/或者Comment out)
｢custom_phrase｣里的詞彙的確不会轉換(as it is)
一般輸入(不在｢custom_phrase｣里的詞)就是默認繁體了

完全可以理解這樣的設計, 我想問的是, 
有沒有辦法對
- 一般輸入(不在｢custom_phrase｣里的詞)使用simplifier
- 對不在｢custom_phrase｣里的詞, 保持as it is(簡繁日問題)

晚上問這種問題, 非常抱歉

**Comment by nutnutwin** [comment]
更新: 在pinyin_simp里删除simplifier就可以了

谢谢建议

**Comment by lotem** [comment]
也許還可以這樣做到，沒有試過：
```yaml
simplifier:
  excluded_types: [ user_table ]
```

**Comment by nutnutwin** [comment]
我试试看, 谢谢

**Comment by nutnutwin** [comment]
在Windows上试了貌似不行, 也许是我没弄对
我测试后的结论是不要合并日语输入法, 因为变形太多
试图用custom_phrase来cover, 但是custom_phrase不能调整次序不够灵活

之后打算上传我的日语custom_phrase, 也许有人会需要(导入到GoogleIME, ATOK也是可以用的)
※微软拼音不能用
