### ISSUE TITLE
個人詞庫和模糊音發生衝突[ver.0.14.3]

### ISSUE THREAD

**Issue by wyg2ss** [rime/home#468]
系統：windows 10 ver.1903
RIME版本：0.14.3 Weasel
拼音方案：朙月拼音_簡化字
問題：個人詞庫和模糊音發生衝突，同時使用時只有模糊音生效。

使用的模糊音模板：
> 【朙月拼音】模糊音定製模板
> https://gist.github.com/2320943

**Comment by lotem** [comment]
有什麼在下可以效勞的

**Comment by wyg2ss** [comment]
> 有什麼在下可以效勞的

你好,今天在配置的時候可以同時生效了,應該是本人系統的問題,感謝回覆!
