### ISSUE TITLE
能否增加快捷键切换配置选项

### ISSUE THREAD

**Issue by wordfeng** [rime/home#471]
定义多套配置的情况下可以按键切换配置选项, 这样子就可以在编程模式下和非编程模式下快速切换标点符号了,一般来说,使用编程模式,如IDEA编辑的时候我可以不考虑;问题而需要考虑 . 。和, 的问题,因此我需要一套方案来切换至次状况 只改变, 和 。.的差别

**Comment by lotem** [comment]
能。
切換輸入法狀態的快捷鍵可以自定義。
