### ISSUE TITLE
五笔方案如何实现 z 键的通配功能

### ISSUE THREAD

**Issue by bosconb** [rime/home#473]
很多 win 平台上的五笔输入法（如冰凌五笔）都支持 z 键的通配功能。

就是不确定某一个字的编码时，用字母「z」来临时替代。
比如「雾霾」86 编码为 ftfe，如果有时候不确定「霾」的编码 feef，可以用 ftfz 来通配，再如，「学霸」86 编码为 ipfa，如果不确定「霸」的编码 fafe，用 ipfz 来通配。

请教各位熟悉五笔的大佬如何在 rime 平台实现 z 键的通配功能？

**Comment by iwsbiwy** [comment]
找编码支持反查的就可以，比如我用的就可以。[https://github.com/GuoBinyong/wubixinshiji]

**Comment by lotem** [comment]
不支持的。
