### ISSUE TITLE
請問如何可以直接輸出英文標點符號 `  (grave)?

### ISSUE THREAD

**Issue by sdugoten** [rime/home#477]
我在中文輸入法下, 使用了

patch:
  "punctuator/import_preset": alternative 

基本上可以在中文輸入法下, 直接輸出所有英文標點, 好像 ", . ; " 之類的.  不過, 每次輸入 ` (grave) 的時候, 就會出現這個

https://i.imgur.com/SJoVciD.jpg

請問怎樣做, 才可以直接輸出 ` 而不需要再選項? 謝謝.

**Comment by Ace-Who** [comment]
检查一下 `recogonizer/patterns`。

**Comment by sdugoten** [comment]
好啦, 用這個解決問題

patch:
  recognizer/patterns/reverse_lookup:
