### ISSUE TITLE
可否向百度输入法学习，加入v和u功能，可以做便捷的加减法，输入金钱大写，日期输入等特色功能

### ISSUE THREAD

**Issue by Franklyn1987** [rime/home#479]
可否向百度输入法学习，加入v和u功能，可以做便捷的加减法，输入金钱大写，日期输入等特色功能

**Comment by lotem** [comment]
可以。
本項目的目標不是複製其他輸入法的功能集，而是提供一個開發平臺，使得在此基礎上，**你**可以開發想要的功能。

**Comment by Franklyn1987** [comment]
> 可以。
> 本項目的目標不是複製其他輸入法的功能集，而是提供一個開發平臺，使得在此基礎上，**你**可以開發想要的功能。

本人对代码不是很熟悉，这个功能还是蛮好用，不是抄袭。

**Comment by Prcuvu** [comment]
> 本人对代码不是很熟悉

不熟悉如何编码的话，有两种解决方法：
1. 学习如何使用`librime-lua`并用它实现想要的功能；
2. 向另一位熟悉编码并**有志于实现这些功能**的人求助。
> 这个功能还是蛮好用，不是抄袭。

“复制”并不含有“抄袭”的意思。我们不做的原因单纯是因为**我们**没有实现这些功能的需要。不过，如果有人实现了这些功能，我们也会考虑收集常见的扩展功能以便用户安装。
