### ISSUE TITLE
【建议】建议在Rime跨平台分支中集成东风破配置管理器

### ISSUE THREAD

**Issue by PotoTan** [rime/home#483]
移动端，诸如Android、iOS中的rime分支中集成东风破，让用家可以直接通过命令行完成方案的配置！

另外，看到许多用家不理解开源软件，或者不愿意花小小时间去学习、动手配置而抱怨Rime。他们更加倾向于商业软件，诸如搜狗那种傻瓜式，功能及其有限的商业性质输入法，易用但是缺乏乐趣，就像嚼烂好喂给你一样，失去了动手探索的乐趣。虽然这样没问题，各有选择，但是听到不理解作者的言论，感觉非常难受，大家都是用爱发电，开源软件本身就像积木一样需要自己去组装，乐趣从中而生。这个是我小小的感受。借地发表

**Comment by lotem** [comment]
這取決於下游產品的設計。

**Comment by lotem** [comment]
樓主提到的移動端輸入法是由第三方開發者發佈的。
