### ISSUE TITLE
引进符号自动补全特性

### ISSUE THREAD

**Issue by PotoTan** [rime/home#485]
在输入（、【、｛等符号时希望rime能够自动帮我补全符号为（）、【】等等
这种特性非常便利用家。希望能够引进

**Comment by lotem** [comment]
無實現方法。

**Comment by yu-soong** [comment]
可能有点跑题。楼上的问题可以选择其他，比如第三方软件 AutoHotkey 来实现。以下是我的 AutoHotkey 代码（以中括号为例）：
`sc01a::  ;; 自动补全 []，如果是中文就是【】
Clipboard :=   ;Empty the clipboard
SendInput, ^c
sleep, 50
If Clipboard =
{
    SendInput []{left 1}
    return
}
else
{
    Clipboard := StrReplace(Clipboard, "`r`n", "`n") 
    sleep, 50
    Clipboard := Trim(Clipboard, " `t`n") ;trim whitespace, tab and paragraph mark
    sleep, 50
    Clipboard = [%Clipboard%]
    SendInput, %Clipboard%
    return
}
Return`

这段代码的作用：单击“【”自动输出“【】”，并将光标移至括号内。如果选中一段文字点击"【"，会自动将选中的文字加上中括号。其中 "sc01a" 是我电脑中左中括号的键位， “^” 是 control 键的意思，;后面是注释。

**Comment by pdog18** [comment]
> 無實現方法。

請求增加这项「符号补全」的功能。

我尝试使用 

```
- {accept: "comma", send_sequence: "{less}{space}{Insert}{greater}{space}{Left}", when: always}
```

这样的方式来达到「成对符号」的输入，并且在最终使用 Left 移动光标至符号中间，但是实际上上面的代码是无法达到预期效果的。

而成对符号这个需求又确实存在，是否可以在 `punctuator` 考虑支持呢？
