### ISSUE TITLE
【求助】五笔输入无法输入特殊字符。

### ISSUE THREAD

**Issue by gzjasonljx** [rime/home#486]
/BG等的特殊字符输入，对拼音输入法时起效，而在五笔输入时只会出现“、BG”。
不知道有什么办法可以输入相应的特殊字符。
现在用的版本是小狼毫0.14.3，win10。谢谢！

**Comment by Ace-Who** [comment]
试比较两个方案的配置中的 `punctuator` 节点。

**Comment by gzjasonljx** [comment]
你好，wubi86.schema.yaml按照luna_pinyin_fluency.schema.yaml文件修改后，能够输入特殊字符了，感谢。
但电脑重启后，wubi86.schema.yaml文件就自动恢复到原来状态，有没有解决办法？求助。谢谢。

**Comment by Ace-Who** [comment]
这就不知道了，没遇到过。

**Comment by lotem** [comment]
請確保按照《定製指南》所述方法修改配置 https://github.com/rime/home/wiki/CustomizationGuide#%E5%AE%9A%E8%A3%BD%E6%8C%87%E5%8D%97
