### ISSUE TITLE
MacOS 10.13.6终端上不能输入汉字，翻页按键建议

### ISSUE THREAD

**Issue by pardream** [rime/home#487]
1. 在Terminal中无法输出汉字。
    在设置export LANG=zh_CN.UTF-8后，Mac自带的pinyin输入法，可以输入，但squirrel不行。
    我分别试了Squirrel-0.14.0.zip与通过brew 安装，情况相同。
2.五笔输入，翻页可不可设置支持 前翻使用‘,'后翻使用'.'

**Comment by pardream** [comment]
不好意思，找到不能输入的原因了。是squirrel在terminal中，默认设置成了英文输入。需要按shift切换。这与我的使用习惯不一致。开始时没发现。
我看了下配置文件，发现"."也被设置成了上屏并显示为"。"，看来我想用"," "."来翻页的想法，也与开发设计不符。看来是行不能了。

**Comment by Ace-Who** [comment]
翻页可以用「,.」，配置即可。实际上默认配置就是如此。

**Comment by lotem** [comment]
五筆方案不預裝。
https://github.com/rime/rime-wubi/blob/master/wubi86.schema.yaml#L76 這個方案裏沿用默認的符號和翻頁配置。

**Comment by pardream** [comment]
感谢回复。我试了一下，这个wubi86确实是用, .来翻页。我用的是：https://github.com/KyleBing/rime-wubi86-jidian的方案。这个配置就不能用，与.来翻页。现在没时间，等有空了研究一下，应该可以修改配置来实现。
----- 原始邮件 -----
发件人：弓辰 <notifications@github.com>
收件人：rime/home <home@noreply.github.com>
抄送人：pardream <xianzhou_lu@sina.com>,  State change <state_change@noreply.github.com>
主题：Re:_[rime/home]_MacOS_10.13.6终端上不能输入汉字，翻页按键建议_(#487)
日期：2020年01月08日 12点02分

五筆方案不預裝。


https://github.com/rime/rime-wubi/blob/master/wubi86.schema.yaml#L76 這個方案裏沿用默認的符號和翻頁配置。

**Comment by pardream** [comment]
我用的是 https://github.com/KyleBing/rime-wubi86-jidian的方案。这个配置就不能用，与.来翻页。
现在没时间，等有空了研究一下，应该可以修改配置来实现。
感谢提示。
----- 原始邮件 -----
发件人：Ace-Who <notifications@github.com>
收件人：rime/home <home@noreply.github.com>
抄送人：pardream <xianzhou_lu@sina.com>,  State change <state_change@noreply.github.com>
主题：Re:_[rime/home]_MacOS_10.13.6终端上不能输入汉字，翻页按键建议_(#487)
日期：2020年01月07日 21点34分

翻页可以用「,.」，配置即可。实际上默认配置就是如此。



&mdash;
