### ISSUE TITLE
使用朙月拼音不能打出以ue为韵母的lue和nue相关字

### ISSUE THREAD

**Issue by dafeinayius** [rime/home#488]
使用fcitx+rime，选择朙月拼音，但是打不出lue发音的字比如略，或者nue发音的比如虐，联想出的都是lu发音之类，但是xue发音比如学字，jue发音的，都可以正确在备选栏出现，请问我该怎么设置让诸如lue和nue拼音的字也能正确打出来呢?

**Comment by lotem** [comment]
普通話裏沒有 lue 和 nue 這兩個音。
[原裝方案](https://github.com/rime/rime-luna-pinyin) 可以通過 `lve`或`lue`、`nve`、`nue`兩種形式輸入拼音音節 lüe 與 nüe。請檢查是否通過自定義文件修改了輸入方案的拼寫規則。

**Comment by dafeinayius** [comment]
明白了，谢谢佛振！
