### ISSUE TITLE
建议】方案中可以定义用户词典不记录系统词

### ISSUE THREAD

**Issue by xyzz10** [rime/home#491]
使得用户词典仅仅记录用户自造词
![2020-01-10-04-15-37](https://user-images.githubusercontent.com/59724491/72136769-7eab8d00-33c4-11ea-850a-09675561c6f7.png)

**Comment by xyzz10** [comment]
同时，作为副翻译器时也可以这样定义

**Comment by lotem** [comment]
用家不要管用戶詞典記什麼。這屬於輸入法的內部實現。

**Comment by xyzz10** [comment]
> 用家不要管用戶詞典記什麼。這屬於輸入法的內部實現。

使用一段时间后，方便转入主码表而已。
如果同时记录系统字词，要提取自造词出来，就需要正则去与enc匹配了
有的用户仅仅用引导造词，而不需要用户词典记系统字词的词频那些

**Comment by lotem** [comment]
> > 用家不要管用戶詞典記什麼。這屬於輸入法的內部實現。
> 
> 使用一段时间后，方便转入主码表而已。
> 如果同时记录系统字词，要提取自造词出来，就需要正则去与enc匹配了
> 有的用户仅仅用引导造词，而不需要用户词典记系统字词的词频那些

這不是設計的用途。

用戶詞典反映用戶使用字詞的習慣。
