### ISSUE TITLE
paging的判定逻辑是否可调整？

### ISSUE THREAD

**Issue by hyaray** [rime/home#493]
我理解的paging是只要按过下翻页，就为true，这时即使回到第1页，依然为true。
我认为更完美应该是：当前不在第一页，才为true。

**Comment by lotem** [comment]
不可以調整。
將符號鍵如 `,` 綁定到向上翻頁的情況下，這種設計是爲了支持連續按 `,` 鍵向上翻頁，避免回到首頁後輸出標點符號。
