### ISSUE TITLE
支持用 Shift_L 等修饰键单键选重吗？

### ISSUE THREAD

**Issue by Ace-Who** [rime/home#497]
测试 `key_binder` 不成功。

**Comment by hyaray** [comment]
这些特殊键，可能优先被default.yaml 里的 ascii_composer 强制定义了，这里调整了再试试？

**Comment by Ace-Who** [comment]
谢谢，试过删除 `ascii_composer/switch_key/Shift_L`，不成功。

**Comment by hyaray** [comment]
那涉及更底层的内容了，不知道engine里删除 ascii_composer 会产生怎样的情况

**Comment by Ace-Who** [comment]
这倒没试过，试了下也不行。

**Comment by Girsun** [comment]
你这个想法可以的， 加我我教你，Q201563858

**Comment by Girsun** [comment]
我知道怎么弄

**Comment by Ace-Who** [comment]
发现我认识你啊，不过说着说着我就找到办法了，按键绑定要定义为 `Shift+Shift_L`。下次搞不定的再找你。

**Comment by haihaicn** [comment]
> 
> 
> 发现我认识你啊，不过说着说着我就找到办法了，按键绑定要定义为 `Shift+Shift_L`。下次搞不定的再找你。

好棒啊，困扰我的问题在这里找到答案了

**Comment by lotem** [comment]
這麼改的，​都從來不打上檔字符嗎？
