### ISSUE TITLE
在網站上添加繁簡轉換功能

### ISSUE THREAD

**Issue by lotem** [rime/home#5]
本站內容大部分是傳統漢字，因此可以通過簡單的文字替換提供簡化字視圖。
可參考：
https://github.com/hustlzp/jquery-s2t
http://www.xichuangzhu.com/

要注意處理「一繁對多簡」字，如「乾」；
還要避免代碼（如 OpenCC 詞典樣例）中的漢字被轉換。

**Comment by kunki** [comment]
本站用字採用了OpenCC標準，與一般的通行繁體有一定差別。若是不用OpenCC作轉換，恐怕要自己定製轉換詞庫。（比如一般的簡繁轉換器不會去處理「羣」、「峯」等字）。

另，據我所知www.byvoid.com的簡繁轉換就是用OpenCC實現的。

**Comment by lotem** [comment]
Fixed by https://github.com/rime/blog/commit/c4e6d741ddcb1f10afe7ec7f36603958154ea542
