### ISSUE TITLE
有计划支持联想功能吗

### ISSUE THREAD

**Issue by fanple** [rime/home#50]
比如输入“中”后，能联想到“中国”，“中间”，“中间商”...

要实现这个功能很复杂吗，后续有考虑添加吗

**Comment by jakwings** [comment]
很明显目前的方案是以码表中指定的权重定词序，不接着输入是没进一步提示的。可能的实现方法之一：按下指定快捷键切换查询相关词汇，重复快捷键还原到原有模式；或者直接提供另一种可配置的提示模式，固定生效，且仅提示有限数量的词汇以免影响查询单字。

既然你都跑到 rime/librime#65 去问了……

**Comment by fanple** [comment]
谢谢回复，我的意思是在输完一个字并返回后，如比“中”字己经输出了，此时再以“中”字为首个字，在词典中查找以“中”字开头的词，显示在候选区域。在手机端的百度，搜狗等输入法设置中都有一个联想开关，打开后，在输入文字后就能一直循环产生联想词。

**Comment by jakwings** [comment]
感觉还是很简单的，可能就是要稍微纠结一下各平台上的界面吧（摊手）。

**Comment by fanple** [comment]
要实现联想功能，还得修改rime_api，添加接口，并且也得实现搜索联想词的算法，添加联想词库，原有的搜索算法词库是否可以复用？

**Comment by lotem** [comment]
同 https://github.com/rime/librime/issues/65
