### ISSUE TITLE
“/”的输入

### ISSUE THREAD

**Issue by TobbyLALALA** [rime/home#506]
输入“/”时
无法用数字键1234选择，只能用Ctrl+n选择，猜测是将特殊符号输入功能与“/”的输入混淆
特殊符号的输入里无“/3”这一类的指令，希望恢复成普通的符号输入

**Comment by Ace-Who** [comment]
检查方案配置。

**Comment by FDUZS** [comment]
如果你说的「特殊符号的输入里」指的是 `symbols.yaml` 的话，其实是有的

<img width="82" alt="eDeyF6qp4G" src="https://user-images.githubusercontent.com/20297872/74810176-d2958400-5329-11ea-8942-db6372d03adb.png">

我的做法是在 `symbols.custom.yaml` 中更改半角形式下的符号映射

```
      '/' : [ / ]
      '?' : [ ？, '?' ]
      ';' : [ ；, ; ]
      ':' : [ ：, ':' ]
      '''' : [ '‘', "''", '’' ]
      '"' : [ '“', '""', '”' ]
      '\' : [ 、, ､, ／, ÷, '\', ＼ ]
```

**Comment by TobbyLALALA** [comment]
哇，谢谢您 : )




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "IamZS"<notifications@github.com&gt;; 
发送时间: 2020年2月19日(星期三) 下午3:16
收件人: "rime/home"<home@noreply.github.com&gt;; 
抄送: "1012988718"<1012988718@qq.com&gt;; "Author"<author@noreply.github.com&gt;; 
主题: Re: [rime/home] “/”的输入 (#506)




如果你说的「特殊符号的输入里」指的是 symbols.yaml 的话，其实是有的
 

 
我的做法是在 symbols.custom.yaml 中更改半角形式下的符号映射
       '/' : [ / ]       '?' : [ ？, '?' ]       ';' : [ ；, ; ]       ':' : [ ：, ':' ]       '''' : [ '‘', "''", '’' ]       '"' : [ '“', '""', '”' ]       '\' : [ 、, ､, ／, ÷, '\', ＼ ]  
&mdash;

**Comment by TobbyLALALA** [comment]
嗯，已經解決了，謝謝您




------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"Ace-Who"<notifications@github.com&gt;;
发送时间:&nbsp;2020年2月9日(星期天) 中午12:44
收件人:&nbsp;"rime/home"<home@noreply.github.com&gt;;
抄送:&nbsp;"1012988718"<1012988718@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [rime/home] “/”的输入 (#506)




检查方案配置。
