### ISSUE TITLE
如何在并击方案中使用多键并击作为功能键

### ISSUE THREAD

**Issue by qr0o** [rime/home#508]
如UI并击作为退格键

**Comment by Ace-Who** [comment]
在现有功能下，只能先将并击定义为一不用的符号，再将此符号键绑定为功能键。

**Comment by lotem** [comment]
可以轉義按鍵名，如輸出 `nihalo{Left}{BackSpace}{Right}`。
但轉換所得的功能鍵只能在Rime引擎裏消化。
