### ISSUE TITLE
求教：五笔拼音输入法，如何设置默认半角输出符号？

### ISSUE THREAD

**Issue by VergilChin** [rime/home#516]
五笔拼音输入法，如何设置默认半角输出符号？

**Comment by lotem** [comment]
默认就是半角标点。从方案选单切换全半角，参考文档：
https://github.com/rime/home/wiki/UserGuide#%E8%BC%B8%E5%85%A5%E6%A8%99%E9%BB%9E%E7%AC%A6%E8%99%9F

如果需要的是切换中文标点/西文标点，也在方案选单里有相应的开关选项。

**Comment by VergilChin** [comment]
收到，谢谢！有没那种设置，可以单单设置符号为英文符号的？

**Comment by lotem** [comment]
有。
