### ISSUE TITLE
请教:如何设定快捷键只能切换到英文

### ISSUE THREAD

**Issue by yisuixinq** [rime/home#517]
如何在rime中设定一个快捷键，使其只能切换到英文

**Comment by leenzhu** [comment]
这个单子怎么关了啊，我也想要这个功能。如何设定特定快捷键，定向切换，而不是来回切换啊？

**Comment by yisuixinq** [comment]
> 这个单子怎么关了啊，我也想要这个功能。如何设定特定快捷键，定向切换，而不是来回切换啊？

{ when: always, accept: Control+Shift+2,  set_option: ascii_mode }

使用 set_option 就行了

**Comment by leenzhu** [comment]
搜了一下set_option，找到类似的单子了：
https://github.com/rime/home/issues/454
