### ISSUE TITLE
Did rime support in New ipad？

### ISSUE THREAD

**Issue by lewwong-deep** [rime/home#519]
請問現在最新型號的ipad可以支援rime嗎

**Comment by liangqi** [comment]
There is a https://github.com/jimmy54/iRime , but the source code is outdated and perhaps not from https://rime.im/ community.

**Comment by eagleoflqj** [comment]
https://github.com/imfuxiao/Hamster/commits/main/

**Comment by mirtlecn** [comment]
> https://github.com/imfuxiao/Hamster

这个就像当年的 iRime 一样，目前已经 4 - 5 个月没有更新源代码了。App Store 今年发布了两次大版本更新，源代码是去年 12 月更新，没办法编译出当前的版本。

如果 App 本身还以 GPLv3 分发（不清楚是否已经修改），它自己就违反了自己的许可证（发布必须附带源代码的要求）

看 issue 看作者似乎（大概）打算后续版本不再开源。

当然软件很优秀，但应当更新下项目说明，表明不再开源，App 也需要换掉 GPL 的协议。

**Comment by fxliang** [comment]
水果有重税，要收费正常，不然要开发者用血开源不合理

**Comment by mirtlecn** [comment]
都是很优秀的应用，没有说收费的和私有不好的意思，尤其是有苹果税的生态内。

只是说作者自己需要说明一下后续版本转为私有，不再使用 GPLv3，不然是和自己声明的协议是矛盾的。
