### ISSUE TITLE
设置全局强制切换英文快捷键在某些应用上不起作用

### ISSUE THREAD

**Issue by yisuixinq** [rime/home#521]
设置全局强制切换英文快捷键在某些应用上不起作用。
     我按照 https://github.com/rime/home/issues/454#issuecomment-563533316_
提供的方法，设置了 Control+Alt+F2 的快捷键，强制切换英文输入，只是在某些应用上按下快捷键又不起作用。比如windows的CMD，还有vs code

_Originally posted by @cy18 in https://github.com/rime/home/issues/454#issuecomment-563533316_

**Comment by yisuixinq** [comment]
- { when: always, accept: "Control+Alt+F2", set_option: ascii_mode}
我也设置了这个快捷键，但是这个快捷键在某些应用不起作用，比如windows的CMD，还有vs code
另外有个疑问，这个快捷键设置只有设定某些特定到组合键才起作用吗，比如我设置过"Control+Alt+F9",就没有起作用，这是什么情况？

**Comment by yisuixinq** [comment]
@lotem 能帮忙看一下是什么原因吗

**Comment by lotem** [comment]
Control+Alt+ 的組合鍵多被操作系統和應用軟件使用。
https://code.visualstudio.com/docs/getstarted/keybindings#_keyboard-shortcuts-reference
VSCode快捷鍵裏可能有關係的是
> Ctrl+F2 Select all occurrences of current word

衝突比較少的是 Control+Shift+ 的組合。

**Comment by yisuixinq** [comment]
感谢指导，确实是这个原因，修改之后能用了。
