### ISSUE TITLE
0.14版的速成候選字

### ISSUE THREAD

**Issue by figotome** [rime/home#523]
以前用老版本，沒問題。但最近重裝了系統，更新到0.14版，發現這個版本的速成候選字都是生僻字。

弄得現在都要組詞才能打出正常想用的字，不然找好幾版才找到想用的字

**Comment by lotem** [comment]
是小狼毫嘛？
小狼毫0.14版已經不再打包安裝速成的輸入方案。
可以從這裏下載方案的YAML源文件到[用戶目錄](https://github.com/rime/home/wiki/UserData)：
https://rime.im/download/#%E5%AE%89%E8%A3%9D%E6%9B%B4%E5%A4%9A%E8%BC%B8%E5%85%A5%E6%96%B9%E6%A1%88

**Comment by figotome** [comment]
MAC 版的。
速成輸入法是官網下載的，但就是候選字清單的生僻字太多，我要花更多時間找出我想打的字

**Comment by lotem** [comment]
無法重現問題。
https://github.com/rime/rime-quick 這個方案的數據文件4年來未更新過。
推測是部署未成功。

**Comment by figotome** [comment]
我個人猜測不是輸入法文件的問題，是主程序的問題。

**Comment by figotome** [comment]
標簽irreproducible
 
我也不知道問題在哪，換回0.9.26.2版就正常使用。
我只想說這問題的確存在，因為我在IOS版的irime也有這個問題。
而且我也是換回舊版本去解決。

**Comment by lotem** [comment]
> 速成輸入法是官網下載
下載鏈接在哪裏？

0.9.26.2版打包了該輸入方案。新版本裏沒有，需要自行下載安裝方案的yaml源文件再重新部署。

**Comment by figotome** [comment]
yaml源文件 4年沒更新，那最大可能主程序算法有問題。

**Comment by lotem** [comment]
無法重現問題。
