### ISSUE TITLE
如何理解 xform/<模式>/<替換式>/

### ISSUE THREAD

**Issue by Denis-Oakley** [rime/home#524]
### 1

> 拼寫運算
> 變形／Transformation : 若拼寫（或其子串）與<模式>匹配，則將所匹配的部份改寫爲<替換式>；否則拼寫保持不變。模式、替換式遵循Perl正則表達式語法。
> 格式：`xform/<模式>/<替換式>/`
> 實例：算式 `xform/^([nl])ue$/$1ve/` 運算元 `nue` 結果 `nve`

按照定義, `<模式>` -> `<替換式>`, 應該是: 輸入 `nue(lue)` 可以獲得源碼表中與編碼 `nve(lve)` 對應的候選, 但效果卻不是這樣

> 效果：輸入 `nve(lve)` 可以獲得源碼表中與編碼 `nue(lue)` 對應的候選；輸入 `nue(lue)` 無候選

該怎麼理解呢?

例如, 在小鶴雙拼中, `speller/algebra` 中有 `xform/uan$/R/` 一條, 效果爲將 `r` 替換爲 `uan`, 但按照定義, 應該是將 `uan$` 替換爲 `R`

### 2

> 將所匹配的部份改寫爲<替換式>

但如果不在 `translator/preedit_format` 指定, 編碼區域的字母不會被替換

該怎麼理解呢?

**Comment by Ace-Who** [comment]
1. 答案已在引用内容里。
2. 不设置替换就不会发生替换。

**Comment by Denis-Oakley** [comment]
1. 我写的理解与引用中的效果不一样
2. 我的意思是, 比如双拼, 是在 `speller/algebra` 中替换的, 編碼區域的字母没有被替换, 但候选词仍正确, 那是如何生效的呢

**Comment by lotem** [comment]
從詞典裏的拼音開始變換。最終結果是用戶可以輸入的拼寫形式。

**Comment by Denis-Oakley** [comment]
明白了, 謝謝
