### ISSUE TITLE
能否设置成多行候选(减少翻页次数)

### ISSUE THREAD

**Issue by kktt007** [rime/home#528]
例如首先page_size: 5 #一行设置成5个候选，
然后设置成有5行这样的候选，就能看到25个候选字，就不需要翻页。
类似这个 #376
![](https://user-images.githubusercontent.com/22665058/58529019-05627f80-81d1-11e9-877e-4c16aba72a60.png)

**Comment by lotem** [comment]
同 https://github.com/rime/home/issues/376

**Comment by kktt007** [comment]
> 
> 
> 同 #376

谢谢，我会跟踪哪个帖子的，谢谢Lotem
