### ISSUE TITLE
五笔如何显示(候选窗提示功能)特殊字根

### ISSUE THREAD

**Issue by kktt007** [rime/home#529]
五笔字根大部分字体不能正常显示在候选提示框中
weasel.custom.yaml 可以设置"style/font_face"来设置字体
linux下fcitx如何设置字体，让输入框正常显示呢

安装了98五笔字根后不能正常显示字根，如下:

![image](https://user-images.githubusercontent.com/7880005/77601036-9d8dda00-6f44-11ea-987a-991a6e4a44ff.png)

**Comment by lotem** [comment]
請移步 https://fcitx-im.org/wiki/Fcitx/zh-hans 瞭解如何配置Fcitx界面

**Comment by kktt007** [comment]
> 
> 
> 請移步 https://fcitx-im.org/wiki/Fcitx/zh-hans 瞭解如何配置Fcitx界面

谢谢

**Comment by kktt007** [comment]
> 請移步 https://fcitx-im.org/wiki/Fcitx/zh-hans 瞭解如何配置Fcitx界面

来反馈下,给其他人
系统Archlinux 
桌面KDE
安装好fcitx-rime需要安装"fcitx-table-extra"
提供一些额外码表支持，包括仓颉 3, 仓颉 5, 粤拼, 速成, 五笔, 郑码等等
www.archlinux.org/packages/community/any/fcitx-table-extra/

### 参考
> https://wiki.archlinux.org/index.php/Fcitx_(简体中文)

**Comment by lotem** [comment]
> > 請移步 https://fcitx-im.org/wiki/Fcitx/zh-hans 瞭解如何配置Fcitx界面
> 
> 来反馈下,给其他人
> 系统Archlinux
> 桌面KDE
> 安装好fcitx-rime需要安装"fcitx-table-extra"
> 提供一些额外码表支持，包括仓颉 3, 仓颉 5, 粤拼, 速成, 五笔, 郑码等等
> [www.archlinux.org/packages/community/any/fcitx-table-extra/](http://www.archlinux.org/packages/community/any/fcitx-table-extra/)
> 
> ### 参考
> > [https://wiki.archlinux.org/index.php/Fcitx_(简体中文)](https://wiki.archlinux.org/index.php/Fcitx_(%E7%AE%80%E4%BD%93%E4%B8%AD%E6%96%87))

fcitx-rime 和 fcitx-table-extra 是兩款獨立的輸入法軟件。

**Comment by kktt007** [comment]
> > > 請移步 https://fcitx-im.org/wiki/Fcitx/zh-hans 瞭解如何配置Fcitx界面
> > 
> > 
> > 来反馈下,给其他人
> > 系统Archlinux
> > 桌面KDE
> > 安装好fcitx-rime需要安装"fcitx-table-extra"
> > 提供一些额外码表支持，包括仓颉 3, 仓颉 5, 粤拼, 速成, 五笔, 郑码等等
> > [www.archlinux.org/packages/community/any/fcitx-table-extra/](http://www.archlinux.org/packages/community/any/fcitx-table-extra/)
> > ### 参考
> > > [https://wiki.archlinux.org/index.php/Fcitx_(简体中文)](https://wiki.archlinux.org/index.php/Fcitx_(%E7%AE%80%E4%BD%93%E4%B8%AD%E6%96%87))
> 
> fcitx-rime 和 fcitx-table-extra 是兩款獨立的輸入法軟件。

好吧,但是我确实能正常的显示98五笔字根了,而且用的还是fcitx-rime中州韵图标
