### ISSUE TITLE
请问色值如何转换为 0x 开头？

### ISSUE THREAD

**Issue by masonincn** [rime/home#531]
如何将 `#215BD0` 或 `RGB 33 91 208` 转换为 `0x` 开头？

>例：hilited_candidate_back_color: 0xEE6E00

**Comment by lotem** [comment]
每8bit一組，從低位到高位分別代表Red、Green、Blue、Alpha，共32bit。
Alpha值（如果界面支持）是可選的，默認爲`0xF`F即不透明。
把這個顏色值寫爲十六進制數，即 `0xAABBGGRR` 或 `0xBBGGRR`。

題解：`#215BD0` 寫成十六進制數 `0xD05B21`。
