### ISSUE TITLE
Rime 设置卷轴模式？

### ISSUE THREAD

**Issue by masonincn** [rime/home#532]
默认的是单行模式，请问如何修改？

![WiBeaSuc3Vz869A](https://i.loli.net/2020/04/03/WiBeaSuc3Vz869A.png)

**Comment by lotem** [comment]
Rime沒有這個界面。你用的可能是其他的輸入法。

**Comment by masonincn** [comment]
搜狗截图，我的意思不是皮肤，是想知道候选词是否支持卷轴模式？

弓辰 <notifications@github.com> 于2020年4月3日周五 下午9:15写道：

**Comment by lotem** [comment]
`librime`不限定候選詞顯示的樣式，並且提供了獲取大量候選詞的API，輸入法前端程序可以在此基礎上開這些展現邏輯的界面。
而據我所知，目前並沒有任何一款Rime的前端程序實現了這樣的選詞界面。

**Comment by eagleoflqj** [comment]
> 目前並沒有任何一款Rime的前端程序實現了這樣的選詞界面

现在有一款了：[小企鹅 macOS 中州韵版](https://github.com/fcitx-contrib/fcitx5-macos-installer/blob/master/README.zh-CN.md)
[效果](https://github.com/fcitx-contrib/fcitx5-macos/pull/164)
