### ISSUE TITLE
Emacs中无法激活输入法

### ISSUE THREAD

**Issue by amosbird** [rime/home#54]
emacs版本： 24.5.1
操作系统：Arch Linux
桌面：i3

**Comment by lotem** [comment]
有關輸入法的一般問題，或 ibus 框架的問題，此處不受理。
如果不是 ibus-rime 特有的問題，請移步 https://github.com/ibus/ibus/issues

**Comment by raawaa** [comment]
@amosbird 请确认在启动`ibus-daemon`的时候使用了`--xim`选项，像这样：
``` bash
$ ibus-daemon -d -x
```

**Comment by jccode** [comment]
虽然这个主题已经关了，但今天遇到这个问题又跑这里来了。
有可能是 `LC_TYPE` 的问题。 
在命令行运行 

     LC_TYPE=zh_CN.UTF-8 emacs

试一下。
如果是的话，就确定是这个问题。
解决办法，就是设置下 `LC_TYPE` 的值。
[参考链接](https://emacs-china.org/t/topic/974)
