### ISSUE TITLE
如何设置不定长编码顶字上屏？

### ISSUE THREAD

**Issue by royshi** [rime/home#543]
请问rime能否实现不定长顶字上屏吗？ 我的编码是形码（郑码的变种）最长是三码。RIME能够通过设置最大码长3实现3码顶屏，现在有些二码的位置上是不存在第三个编码的。如下码表，在“aa”的位置上不是唯一码，但是并没有第三个编码了，并没有aaa，aab，aac……这种。
“
一aa
亍aa
型aeb
干aed
” 

再例如如下码表所示，在“af”的位置上是唯一码，只有一个“末”字。但是并没有第三个编码了，并没有afa，afb，afc……这种。
“
邗aey
末af
天agd
蚕agi
吞agj
”

想要实现的效果是，碰到前两个编码存在，第三个编码不存在的时候，输入完这个字的两个编码，输入下一字的第一个编码时候自动上屏上一个字，无论前面这个字是否有重码。
例如上面的“一”字，想要输入“一型”，输入aaaeb一共5个按键应该能够上屏这两字，同时输入aa之后，继续输入第二个字的首个编码“a”时候，“一”字能够上屏。

我自己研究了很久很久都实现不了，您能否帮忙看一看能不能实现？万分感谢！拜谢！！

这个功能在极点和小小输入法上面都是可以正常实现的。所以RIME不能实现我有些困扰。

**Comment by royshi** [comment]
我知道大部分四码的形码（五笔和郑码）用户，是希望二码不要顶字上屏的，原因是会有记忆量（和平常输入简码必然加空格的习惯不一致）。
但是如果全长只有三码，且只打单字的话，反而可以利用这一点增加很少部分的记忆量来显著提升输入效率。
所以对这个功能有需求。

不知道能否有办法实现呢？

**Comment by lotem** [comment]
設置：
```yaml
speller:
  auto_select: true
```
