### ISSUE TITLE
如何只在特定输入法中禁用“-”和"="按键翻页？

### ISSUE THREAD

**Issue by idyllist123** [rime/home#546]
如题，正在使用日语输入法，打算只在日语输入法中把翻页的按键绑定改掉。

**Comment by lotem** [comment]
沒有禁用一說。
翻頁的按鍵默認爲`Page_Down`、`Page_Up`，用何種字符按鍵翻頁取決於輸入方案裏定義的按鍵綁定。
請參考輸入方案設計書的「用符號鍵換頁」部分：

https://github.com/rime/home/wiki/RimeWithSchemata#%E7%94%A8%E7%AC%A6%E8%99%9F%E9%8D%B5%E6%8F%9B%E9%A0%81
