### ISSUE TITLE
MacOS 下 punctuator 在部分第三方终端中无法正确替换字符

### ISSUE THREAD

**Issue by fuzhouch** [rime/home#550]
可重现于：mac OS High Sierra，系统版本10.13.6，squirrel 版本 0.14.0

步骤：
1. 通过 homebrew 安装 Hyper：brew cask install hyper
2. 通过 homebrew 安装中州韵输入法：brew cask install squirrel
3. 从 Mac Settings 面板添加 Squirrel 输入法；
4. 执行 Deploy 命令载入默认设置。

现象：
 Hyper 启动后选择明月拼音半角模式输入中文，当键盘输入“,”和“.”时，正常情况下应输入全角逗号（，）和句点（。），但实际输入的则是英文逗号（,）和句点（.）。

交叉测试：
正常安装中州韵输入法之后，可从 https://github.com/jobinson99/mongolian-ime 安装基于中州韵的蒙古文输入法。此输入法提供的两种输入 schema 均基于 punctuator 的方法实现替换西文字符到蒙古文字符（胡都木蒙文字符或西里尔字符）。这两种输入法在 Hyper 输入窗口中均无法输入目标字符，只能输入正常的英文键盘布局字符。

在其它 app，如 Atom（和 Hyper 同样基于Electron）和Firefox 可正常工作。而另一个开源终端，Terminus，则同样无法正常工作。

我不熟悉 Rime 的内部工作机制，故只能做黑盒测试。测试的结果看，这两者的共同点是工作不正常的部分都使用了 punct_translator，故报此 bug。如果这是因错误配置问题，也请告知正确方法，不胜感谢。

**Comment by lotem** [comment]
请检查 [方案选单](https://github.com/rime/home/wiki/UserGuide#%E4%BD%BF%E7%94%A8%E6%96%B9%E6%A1%88%E9%81%B8%E5%96%AE) 中中西文标点切换【，。-> ,. 】这组开关的状态。

**Comment by fuzhouch** [comment]
> 请检查 [方案选单](https://github.com/rime/home/wiki/UserGuide#%E4%BD%BF%E7%94%A8%E6%96%B9%E6%A1%88%E9%81%B8%E5%96%AE) 中中西文标点切换【，。-> ,. 】这组开关的状态。

谢谢。报告此 bug 之前我已经查过状态切换开关：这个开关在 Hyper 下是失效的。从 CTRL-` 调用菜单选择明月拼音并显式选择中西文标点，无论如何选择，打出的都是英文逗号和句点。同样的动作在 Firefox，Safari，包括系统内置 Terminal，都可以正常工作。

**Comment by fuzhouch** [comment]
或者如果您可告知 Rime 的日志如何启动，我可以在本地重现并收集日志帮助调试。

**Comment by lotem** [comment]
綜合 https://github.com/rime/weasel/issues/510 看，鑑於Squirrel、Weasel各自獨立地實現了輸入法與系統的交互，問題更有可能是Hyper對符號鍵做了一些處理，而使輸入法無法完成處理。
日誌：
https://github.com/rime/home/wiki/RimeWithSchemata#%E9%97%9C%E6%96%BC%E8%AA%BF%E8%A9%A6
恐怕沒有有用的信息，因為詳細的按鍵日誌只有Debug版才輸出。

**Comment by fuzhouch** [comment]
谢谢回复。我先去联系 Hyper 社区，看看能不能有效描述这个问题（他们自己可能平时工作不需要 IME 支持）。您可以先关掉这个 issue。我目前也暂时可以绕开，因为 macOS 的内建拼音和蒙古文输入法都可以正常输入。PS - 如果日志可以通过配置启停就最好。
