### ISSUE TITLE
关于“𫍽”字的问题

### ISSUE THREAD

**Issue by xiantailang** [rime/home#553]
大陆字典里“譞”这个字的简体字写法和繁体字是一样的，而不是“𫍽”。

**Comment by lotem** [comment]
「𫍽」是「譞」的類推簡化字。
 [通用规范汉字表](https://zh.wikisource.org/wiki/%E9%80%9A%E7%94%A8%E8%A7%84%E8%8C%83%E6%B1%89%E5%AD%97%E8%A1%A8) 將「𫍽」列爲「规范字」，並註明 (譞) 爲其對應的繁體字。
