### ISSUE TITLE
关于小狼毫特殊符号输入的问题

### ISSUE THREAD

**Issue by wuguangwuze** [rime/home#555]
请问可以把/输入特殊符号改为\输入特殊符号吗

**Comment by Ace-Who** [comment]
将符号定义和 `recognizer/punct` 作相应修改即可。

**Comment by wuguangwuze** [comment]
> 将符号定义和`recognizer/punct`作相应修改即可。

我试了，但只有\这个符号不行

**Comment by Ace-Who** [comment]
`\` 在 Perl 正则表达式中是转义符，如果在双引号内表示 `\` 本身，则需要转义，如 `"\\"`。

**Comment by lotem** [comment]
與正則表達式無關，YAML雙引號字符串中符號 `\` 用作轉義。
