### ISSUE TITLE
关于spelling algebra中speller/algebra这一字段的理解

### ISSUE THREAD

**Issue by yys-github** [rime/home#557]
我正在阅读双拼的schema，并试图理解speller/algebra中的正则式。式子本身不难理解，只是感到其运作原理和我粗略猜测的有所不同，因而感到困惑。

我原先猜测的双拼运作原理是，对输入的单个字符，以正则规则翻译为全拼，再从词典查表得到候选。
然而我看到speller/algebra中的正则式，对照文档解读后，发现却是反过来的：正则式将全拼中多个字符的拼写，一步步转换为了双字符拼写。

因而产生了一个新的，不知是否正确的猜测：speller/algebra的操作对象并非输入串，而是词典中的全拼key。相当于以双拼的这组新的key重新构造词典，之后在输入过程中，直接以双拼的key查询这个新的词典，给出的结果。

自己的能力有限，无法快速地阅读源码确认这一猜想，所以发帖求问询证。请不吝赐教，谢谢~

（顺便，如果上述推论成立的话，那么模糊音的数量增加是否会导致新生成词典体积的快速膨胀呢？不禁有这样的浅薄思考的结论，请不吝一并斧正。）

**Comment by lotem** [comment]
`speller/algebra` 是從詞典源文件的音節表出發推算雙拼方案的音節輸入碼。
模糊音不會大幅增加詞典裏的索引數據。詞典中的詞條是按照源文件的音節表編制索引的。

**Comment by yys-github** [comment]
> `speller/algebra` 是從詞典源文件的音節表出發推算雙拼方案的音節輸入碼。
> 模糊音不會大幅增加詞典裏的索引數據。詞典中的詞條是按照源文件的音節表編制索引的。

感谢解惑！基本理解了~

**Comment by staylet** [comment]
最近在参考 [double_pinyin_flypy.schema.yaml](https://github.com/rime/rime-double-pinyin/blob/master/double_pinyin_flypy.schema.yaml) 定制一个双拼输出方案，遇到了一模一样的问题🫠。

为啥`translator/preedit_format`里的运算规则是“正向”转换，即按键输入**运用正则转换**之后输出上屏；而 `speller/algebra`里的正则转换是“反向”转换，即按键输入是放在正则式的后面，跟“输入 >> 查（对比）码表 >> 输出”的**浅显**理解相悖。从各个角落翻看了文档及本 Issue @lotem 的解答让我理解了一些原因。

在 [拼写方案详解 - 在Rime輸入方案中的用法](https://github.com/rime/home/wiki/SpellingAlgebra#%E5%9C%A8rime%E8%BC%B8%E5%85%A5%E6%96%B9%E6%A1%88%E4%B8%AD%E7%9A%84%E7%94%A8%E6%B3%95) 提到：
> 編譯輸入方案時，將運用這組運算規則完成音節表上的投影，求得可解析爲音節代碼的有效拼寫集合； 輸入過程中，這組有效拼寫決定着輸入碼的音節切分方式。

我的理解是之所以`speller/algebra`的规则看起来是“反向”转换，原因在拼写运算须先转换音节表，再与输入码匹配（1）以便确保拼写的正确性；（2）生成正确的音节划分，处理完成之后再进行后续的匹配、上屏等。

不过我有一些小小的思考。在标准普通话语境下， 暂不考虑多音字的情况，一组声母+韵母是可以精确匹配到期望的汉字的，那如果按照准确的按键顺序输入，就满足了直接查表的条件；进一步讨论到如 `zh ch sh >  z c s` 的模糊匹配功能，输入时比较依赖输入方案的内部“二次转换”，而逐渐养成错误的习惯，在切换到没有模糊匹配支持的输入环境时，输入效率明显下降。这也是我自定义输入方案的原因，如果输错了，输入法不予输出，那就是我按键不对，从而纠正自己的按键。

当然，个人对输入法的开发实现还比较陌生，也不是专业语言学相关从业者，以上仅仅是一些思考。
