### ISSUE TITLE
请问能否设置成不生成log? 

### ISSUE THREAD

**Issue by nutnutwin** [rime/home#558]
比如数据文件夹下的
luna_pinyin.userdb\000015.log

不好意思, 因为我在几台电脑上使用小狼毫, 通过Dropbox 同步数据文件夹实现字库的同步

log文件似乎一直被打开/占有导致Dropbox 一直在同步状态

谢谢

**Comment by lotem** [comment]
不可以。請不要同步 `*.userdb` 文件夾。這是LevelDB的數據庫文件。用來支持Rime的用戶詞典。

需要手動操作，按下菜單裏的用戶資料同步，用Dropbox同步用戶文件夾下的`sync`子文件夾。其中用戶詞典會寫成可同步、合併的快照格式。在另一臺電腦也用相同的步驟同步。
詳見：
https://github.com/rime/home/wiki/UserGuide#%E5%90%8C%E6%AD%A5%E7%94%A8%E6%88%B6%E8%B3%87%E6%96%99

**Comment by nutnutwin** [comment]
你好｢Rime的用戶詞典。｣是指从用户输入中获得的词典的意思吗? 

比如本来没有｢青色的菠萝｣但是用户输入了这个词, 会被记入userdb的意思吗? 

谢谢

**Comment by lotem** [comment]
@nutnutwin 是的。

**Comment by nutnutwin** [comment]
好的谢谢, 如果是这样的话就没问题
※我定义了20,000〜的custom_phrase.txt
因为喜欢固定词序

谢谢
