### ISSUE TITLE
注音方案 (bopomofo) 如何新增字典檔？

### ISSUE THREAD

**Issue by lazywei** [rime/home#56]
一般使用拼音輸入法的時候字典檔形式如下：

```
字典 zi dian
```

前方是詞，而後方是碼。那麼如果是在注音的情況下後方的碼要怎麼寫呢？

**Comment by lotem** [comment]
加上聲調 jia1 shang4 sheng1 diao4
如果詞裏面沒有多音字，可以不寫碼。

**Comment by lazywei** [comment]
那麼如果我想輸出像是注音的聲調，例如：
```
ˊ ˋ ˇ
```
並把他們對應到數字鍵 `6 4 3`（也就是注音鍵盤上的符號），我應該怎麼做？
我常是直接寫 `6` 做為二聲的字典碼，不過似乎不可行。

謝謝！

**Comment by lotem** [comment]
@lazywei 字典只用來注音，並不是最終的輸入碼。
改這裏：
https://github.com/rime/brise/blob/master/preset/bopomofo.schema.yaml#L100
和這裏：
https://github.com/rime/brise/blob/master/preset/bopomofo.schema.yaml#L106
https://github.com/rime/brise/blob/master/preset/bopomofo.schema.yaml#L149

語法說明：
https://github.com/rime/home/wiki/SpellingAlgebra#%E6%8B%BC%E5%AF%AB%E9%81%8B%E7%AE%97%E7%9A%84%E9%81%8B%E7%AE%97%E5%AD%90

**Comment by lazywei** [comment]
@lotem 感謝！
改 `speller/algebra` 中的 `xlit` 是為了把數字對應到聲調對吧？
但是更改 `translator/preedit_format` 和 `reverse_lookup/comment_format` 是為什麼呢？
我沒在 wiki 中找到關於 preddit_format 和 comment_format 的說明，能否請你說明一下這兩個選項的目的為何？

謝謝！

**Comment by lotem** [comment]
https://github.com/rime/home/wiki/CustomizationGuide#%E8%A8%AD%E5%AE%9A%E9%A0%85%E9%80%9F%E6%9F%A5%E6%89%8B%E5%86%8A

**Comment by lazywei** [comment]
> 改這裏：
> https://github.com/rime/brise/blob/master/preset/bopomofo.schema.yaml#L100
> 和這裏：
> https://github.com/rime/brise/blob/master/preset/bopomofo.schema.yaml#L106
> https://github.com/rime/brise/blob/master/preset/bopomofo.schema.yaml#L149

我發現我的 bopomofo_tw.schema.yaml 和這三處是一樣的，我想應該是我沒有把我的需求說清楚。
我是想讓 `3` 對應到 `ˇ`，也就是我如果輸入 `3` 然後輸入 Enter，可以直接出現 `ˇ` 這個符號。
這樣是不是只能從 `punctuator` 那邊來改了？
例如：

```
  'punctuator/half_shape/3': ["3", "ˇ"]
  'punctuator/half_shape/4': ["4", "ˋ"]
  'punctuator/half_shape/6': ["6", "ˊ"]
```

這樣？

**Comment by lotem** [comment]
不是。最好修改這裏指出的代碼。
https://github.com/rime/home/issues/56#issuecomment-237447699
不過你開心就好。
