### ISSUE TITLE
在 Firefox 的设置的搜索框里，无法输入中文

### ISSUE THREAD

**Issue by Kennnnnnji** [rime/home#562]
[UTOOLS1590121826999.png](http://yanxuan.nosdn.127.net/49665d0fe0edd71df27e0b1d44b09660.png)
如上图，在这一搜索框中，无法直接输入中文，但是可以输入英文。另外，在输入一段英文后，又可以继续输入中文。
[UTOOLS1590121947273.png](http://yanxuan.nosdn.127.net/20e6c28b7896db86898b8daf7cc2d291.png)
应用版本：
Firefox 76.0.1 (64 位)
Rime weasel 0.14.3

**Comment by lotem** [comment]
同 https://github.com/rime/weasel/issues/518
