### ISSUE TITLE
朙月拼音打不出「濛」

### ISSUE THREAD

**Issue by masonincn** [rime/home#568]

**Comment by Ace-Who** [comment]
关闭简化字开关。

**Comment by masonincn** [comment]
> 关闭简化字开关。

patch:
  schema_list:
    - schema: double_pinyin_flypy
    # - schema: luna_pinyin_simp  # 朙月拼音 简化字
    - schema: luna_pinyin

这算是关闭了吗，好像无效，词库里有「濛」这个字

**Comment by Ace-Who** [comment]
不是指这个，这个不是「开关」，而是另一个方案。参考 https://github.com/rime/home/wiki/UserGuide 「繁簡字切換」。

**Comment by masonincn** [comment]
> 不是指这个，这个不是「开关」，而是另一个方案。参考 https://github.com/rime/home/wiki/UserGuide 「繁簡字切換」。没有修改过的话，默认快捷键是 Control + Shift + 4。

朋友，能帮忙看下在哪里修改，因为刚接触鼠须管不久，很少研究
![](https://tva3.sinaimg.cn/large/007Gs0Tegy1gfpadghxxqj30ro182wnm.jpg)

**Comment by lotem** [comment]
若使用「朙月拼音·簡化字」方案，或在其他方案中打開了「繁→簡」轉換，[OpenCC](https://github.com/BYVoid/OpenCC)會把「濛」轉換成「蒙」。
https://github.com/BYVoid/OpenCC/blob/master/data/dictionary/TSCharacters.txt#L1150

**Comment by yar999** [comment]
可以把 TSCharacters.txt 里面 濛 那一行删除,
然后把 TSCharacters.txt 转成 TSCharacters.ocd2
最后用我们修改过的 TSCharacters.ocd2 替换掉默认的 `/usr/share/opencc/TSCharacters.ocd2`

转换
```
opencc_dict -i TSCharacters.txt -o TSCharacters.ocd2 -f text -t ocd2
```
