### ISSUE TITLE
为何打“昇”，输入“升”？

### ISSUE THREAD

**Issue by kangdalei** [rime/home#570]
使用的地球拼音。 sheng 拼符里找不到 “昇” 这个字。

custom_phrase.txt  里 写入 “昇”， 打字输入的时候直接变成了 “升”。

这俩字 unicode也不一样啊。

**Comment by Ace-Who** [comment]
https://github.com/rime/home/issues/568

**Comment by LEOYoon-Tsaw** [comment]
被簡化了唄

**Comment by sndnvaps** [comment]
昇，升，在用wubi的时候，不会出现这个问题。。
