### ISSUE TITLE
rime最新版本下載不了粵拼

### ISSUE THREAD

**Issue by QuillonChan** [rime/home#571]
<img width="744" alt="下不了粵拼" src="https://user-images.githubusercontent.com/67405364/85655870-ac6e5f00-b6e2-11ea-9ed3-b4f63dd534d5.png">
一直顯示不出來

**Comment by LEOYoon-Tsaw** [comment]
`bash rime-install cantonese ` 或前往 https://github.com/rime/rime-cantonese 手動下載
