### ISSUE TITLE
小狼毫如何不切换即时输入繁简字，比如徐幹

### ISSUE THREAD

**Issue by ricoeur** [rime/home#583]
小狼毫如何不切换即时输入繁简字，比如徐幹，这个幹我想是不能写成干的，但rime怎么调，还是找不到，但其他的输入法内好像不成问题。

**Comment by Ace-Who** [comment]
需要定制 opencc 词典。

首先**定位词典文件**，方法是看方案配置中的 `simplifier/opencc_config` 所定义的 `.json` 格式配置文件，到 `程序目录/data/opencc` 或 `用户目录/opencc` （优先）查看该文件中定义的 opencc 词典文件。

然后**修改词典内容**，如果词典文件是 `text` 格式，则扩展名一般为 `.txt`，可直接修改之；如果是 `ocd` 格式，则需要用 [opencc_dict](https://github.com/BYVoid/OpenCC) 命令行工具转换为 `text` 格式再修改，改好之后再转换为 `ocd` 格式。

一个 opencc 配置中的词典可能有一个或多个，以自带的 `t2s.json` 为例，配置了 `TSPhrases` 和 `TSCharacter` 两个 `ocd` 词典，分别对应词组和单字。将单字词典转换为 `text` 的命令为：

    opencc_dict -i TSCharacters.ocd -o TSCharacters.txt -f ocd -t text

再转换为 `ocd` 的命令为：

    opencc_dict -i TSCharacters.txt -o TSCharacters.ocd -f text -t ocd

具体修改，如果想同时保留「干」「幹」两个候选，可将

    幹	干

一行改为

    幹	干 幹

注意区分水平制表符和空格。

**Comment by lotem** [comment]
规范字写作「徐干」。
如果需要输入繁体字，最好使用繁体为主的输入方案，字形比较准确。

**Comment by ricoeur** [comment]
感谢！
