### ISSUE TITLE
Rime配置俄語輸入法

### ISSUE THREAD

**Issue by xinian2020** [rime/home#587]
Hello，我想使用Rime配置一個支持自動聯想的俄語輸入法，請問應該怎麼做？

**Comment by hhtmp88** [comment]
you need to create the corresponding:
# dictionary file, e.g russian.dict.yaml
# and Schema file, e.g. russian.schema.yaml

**Comment by lotem** [comment]
目前程序還不能有效支持西方語文。
如果只需要輸入西里爾字母，可以用多面體博士的方案：
https://github.com/biopolyhedron/rime_schemata
