### ISSUE TITLE
rime_dict_manager for windows

### ISSUE THREAD

**Issue by hxse** [rime/home#588]
有办法在windows上使用rime_dict_manager 命令吗
我知道windows上有图形工具，但是我想要一个命令行工具，方便写脚本

**Comment by lotem** [comment]
源碼在此 https://github.com/rime/librime/tree/master/tools
`rime_dict_manager` 所需接口不能從`rime.dll`調用
可以嘗試修改構建腳本或手書cmake命令，將程序庫的鏈接方式設為靜態鏈接 `BUILD_SHARED_LIBS=OFF`

**Comment by hxse** [comment]
不太懂C语言, 哭~
