### ISSUE TITLE
配置自定义符号输入 , 默认输入会跳出候选栏 , 但是设置为commit后无法直接上屏 ?

### ISSUE THREAD

**Issue by bogeol** [rime/home#589]
1.导入自定义符号配置
```  
punctuator:
    import_preset: luna_pinyin.symbols
recognizer/patterns/punct: '^/([0-9]0?|[A-Za-z]+)$' 
```

2.修改自定义符号配置
```
punctuator:
    half_shape:
        # "[" : [ 「, 【, 〔, ［ ]     //有候选栏
        # "[": { commit: "「" }    //无候选栏, 直接上屏
```
```
punctuator:
    symbols:
        # "/test" : [ test1, test2, test3, test4 ]     //有候选栏
        # "/test": { commit: "test1" }    //无候选栏, 直接上屏❓️
```
问题就是half_shape中「候选栏 | 直接上屏」两种设置都是正常的, 但是symbols中`/test`设置了commit无法直接上屏, 还是会跳出候选栏 ?

**Comment by lotem** [comment]
`punctuator`實現自動上屏的邏輯只針對符號鍵。因此按字母鍵不會自動上屏。
猜想把`punct`模式改為最後一個字符也是符號就可以達成，不過這樣改並不比按下空格上屏簡便，所以沒有必要。

**Comment by bogeol** [comment]
### 1.开始的想法是 : 
在特殊符号输入的时候
- 「开始输入」`/t` 有候选栏`t1 , t2 , t3`
- 「继续输入」 `/te` 有候选栏`te1 , te2 , te3`
- 「继续输入」 `/tes` 有候选栏`tes1 , tes2 , tes3`
- 「继续输入」 `/test` 直接上屏`test1`「添加commit」

但是如果之后想要添加`/testX` , 就必须修改前面的commit
- 「开始输入」`/t` 有候选栏`t1 , t2 , t3`
- 「继续输入」 `/te` 有候选栏`te1 , te2 , te3`
- 「继续输入」 `/tes` 有候选栏`tes1 , tes2 , tes3`
- 「继续输入」 `/test` 有候选栏`test1 , test2 , test3`「删除commit」
- 「继续输入」 `/testX` 直接上屏`testX1`「添加commit」

也就是每个输入匹配commit之前必须没有commit , 如果有的话就被截止了( 修改太麻烦了)

### 2.现在的想法是 : 
在特殊符号输入的时候「给每个输入匹配commit的情况添加**特殊匹配**」

`/test/`
- 「开始输入」`/t` 有候选栏`t1 , t2 , t3`
- 「继续输入」 `/te` 有候选栏`te1 , te2 , te3`
- 「继续输入」 `/tes` 有候选栏`tes1 , tes2 , tes3`
- 「继续输入」 `/test` null
- 「继续输入」 `/test/` 直接上屏`test1`「添加commit+特殊匹配」

`/testX/`「不会被`/test`截止 , 因为`/test/`才会直接上屏」
- 「开始输入」`/t` 有候选栏`t1 , t2 , t3`
- 「继续输入」 `/te` 有候选栏`te1 , te2 , te3`
- 「继续输入」 `/tes` 有候选栏`tes1 , tes2 , tes3`
- 「继续输入」 `/test` null
- 「继续输入」 `/testX` null
- 「继续输入」 `/testX/` 直接上屏`testX1`「添加commit+特殊匹配」

> 到头来发现 , 添加*后缀特殊匹配/*不就是*候选栏的时候空格匹配* ?
>
> 一个是 : null + /匹配
> 另一个是 : 候选栏 + 空格匹配
