### ISSUE TITLE
如何卸载？

### ISSUE THREAD

**Issue by FantasRu** [rime/home#59]
页面不喜欢
```作为输入法，安装包里不放卸载工具 好没良心啊```

**Comment by jakwings** [comment]
1. 開啓系統輸入法設定面板，移除「鼠鬚管」。
2. 打開 Finder 並按下 command+shift+G 前往 `/Library/Input Methods` 檔案夾，移除「鼠鬚管.app」。
3. 如上，前往 `~/Library` 並移除個人鼠鬚管設定資料夾 `Rime`。
4. 重新登入系統，確保清理完畢。

**Comment by jakwings** [comment]
這是鼠鬚管的卸載方法：

1. 開啓系統輸入法設定面板，移除「鼠鬚管」。
2. 打開 Finder 並按下 command+shift+G 前往 `/Library/Input Methods` 檔案夾，移除「鼠鬚管.app」。
3. 如上，前往 `~/Library` 並移除個人鼠鬚管設定資料夾 `Rime`。
4. 重新登入系統，確保清理完畢。

Windows 的「小狼毫」和 Linux 的「中州韵」請其它人補充。

**Comment by lovezwy** [comment]
thanks

**Comment by FantasRu** [comment]
thx

**Comment by DarinJi** [comment]
@jakwings THX man！

**Comment by Keystion** [comment]
进行第二步之前需要先注销当前登录账户，然后重新登录才能移除「鼠鬚管.app」。

Ps：在 macOS Sierra 10.12.2 (16C67)

**Comment by mhohai** [comment]
@FantasRu 苹果系统本身就不带卸载，这是常识。

**Comment by D0zingcat** [comment]
> 进行第二步之前需要先注销当前登录账户，然后重新登录才能移除「鼠鬚管.app」。
> 
> Ps：在 `macOS Sierra 10.12.2 (16C67)` 上。
也可以直接打开monitor然后搜索squarrel，force quit 一下就好

**Comment by lotem** [comment]
這樣可以吧
```shell
"/Library/Input Methods/Squirrel.app/Contents/MacOS/Squirrel" --quit
rm -rf "/Library/Input Methods/Squirrel.app"
rm -rf "$HOME/Library/Rime"
```

**Comment by D0zingcat** [comment]
哇！可以～

**Comment by bush911** [comment]
Macos 15吧，用了几天不习惯，按你这个方法卸载了。但最后移除了鼠鬚管.app后，它停留在废纸篓里面怎么都删不掉




> 這是鼠鬚管的卸載方法：
> 
>     1. 開啓系統輸入法設定面板，移除「鼠鬚管」。
> 
>     2. 打開 Finder 並按下 command+shift+G 前往 `/Library/Input Methods` 檔案夾，移除「鼠鬚管.app」。
> 
>     3. 如上，前往 `~/Library` 並移除個人鼠鬚管設定資料夾 `Rime`。
> 
>     4. 重新登入系統，確保清理完畢。
> 
> 
> Windows 的「小狼毫」和 Linux 的「中州韵」請其它人補充。

**Comment by zhong-yy** [comment]
MacOS 26 Tahoe 不适用这个方法，在/Library/Input methods 中没有鼠须管.app
