### ISSUE TITLE
bindings 无法识别冒号

### ISSUE THREAD

**Issue by hxse** [rime/home#592]
- { when: has_menu, accept: ";", send: 2 }
    - { when: has_menu, accept: ":", send: 3 }
同样的代码，分号可以正常识别但是冒号就不行

**Comment by lotem** [comment]
`accept`接受一個按鍵名稱，不是按鍵產生的字符。
大小寫字母鍵、主鍵盤區數字鍵的按鍵名稱即是字符本身，其他請參閱
https://github.com/LEOYoon-Tsaw/Rime_collections/blob/master/Rime_description.md
