### ISSUE TITLE
请问有没有动态码长调整的功能

### ISSUE THREAD

**Issue by hxse** [rime/home#593]
比如说: 抱 beieua -> 抱 bei
这种动态码长调整功能有办法实现吗, 自动根据使用频率动态调整码长, 从而把常用的高频字词码长缩短
这个功能对于顶功类方案是非常重要和有用的, 希望能得到重视

**Comment by LEOYoon-Tsaw** [comment]
你可以試著把規則講清楚一點，比如使用頻率到多少減少碼長？減多少？原來碼長不同的字要不要區別對待？減了碼長後原碼還要不要保留？

**Comment by hxse** [comment]
1. 可以设置第n码之后, 码长参与动态调整, 第n码及之前的码长固定
2. 可以设置保留n个候选, 如果n为1, 就是只有一个候选, n为2可以用分号键或数字键来选择第二个重码
3. 频率算法可以套用现有的重码调频算法, 根据使用频率依次切割码长, 高频字词调到短码位置(码长缩短), 低频字词调到长码位置(码长增加)
4. 考虑到是根据频率来调整, 那么就得有保留原编码的空间, 这样才能够在"某个现阶段不常用的字词"被后置的时候, 作为给它增加码长的依据
保留1个重码, 举例如下:
```
原码 单字 动态码长
beuioo 不 b
bauoaa 边ba
baaeaa 骉 baa
baaeee 绑 baae
baaeei 骠 baaee
baaeio 剝 baaei
baaeoa 编 baaeo
baaeoo 缤 baaeoo
baaeou 绊 baaeou
baaeua 绷 baaeu
```
保留2个重码, 举例如下:
```
原码 单字 动态码长
beuioo 不 b
bauoaa 边b
baaeaa 骉 ba
baaeee 绑 ba
baaeei 骠 baa
baaeio 剝 baa
baaeoa 编 baae
baaeoo 缤 baae
baaeou 绊 baaeo
baaeua 绷 baaeu
```

**Comment by lotem** [comment]
沒有。
