### ISSUE TITLE
How to make Capital Letters as the input alphabets?

### ISSUE THREAD

**Issue by hhtmp88** [rime/home#594]
Dear all,

In addition to the small letters, I want to use the Capital Letters  **"ABCDEFGHIJKLMNOPQRSTUVWXYZ"** as the input alphabets of my input method too.
and 
I have set this in the schema file of my input method:
***************
speller:
  alphabet: 'abcdefghijklmnopqrstuvxyz.,''ABCDEFGHIJKLMNOPQRSTUVWXYZ'
  delimiter: ' '
*************

but when I hit the **"Caps Lock" key**, the input method turned-off to English mode and preventing me from using my input method!
-> so how to make things happens as I want?

Inputing using small letters  "abcdefghijklmnopqrstuvxyz" and ".,"  work perfectly without any problems!

Thanks for any kind of help!

**Comment by lotem** [comment]
duplicate: the same question is answered somewhere else.
