### ISSUE TITLE
请教字体输入出来出现方框问题

### ISSUE THREAD

**Issue by pennleung** [rime/home#595]
问题１．有些字输入拼音选字的时候是方框，我搜网上说字库问题，我也试着换字库，字体显示是全了，但这个字是能在选字的时候没问题，但输入出来，还是方框，很奇怪，不知道怎么处理。我试过ｃｔｒｌ＋｀，换成繁体后，这些字倒是可以显示和输入了。

问题２．有些字，比如广东人经常用的“瞓”，拼音是ｆｅｎ，但打不出来，其他输入法是可以的。有没有什么方法补全这些字呢？
谢谢！

**Comment by pennleung** [comment]
刚刚发现了问题所在，其他输入法要输入 简体的言字旁+分这个字，是找不到的，dime换了字库能找到但输入不出来。
另外瞓这个字也能找到了，但拼音错了的问题，这个字只有fen的音，没有xun这个音，这个请问怎么能矫正过来？

**Comment by LEOYoon-Tsaw** [comment]
「瞓」讀「訓」，fan3是粵語音，普通話音就是xùn，沒有任何問題。
字無法顯示是字體問題，無論在哪顯示方框都是字體不支持。

**Comment by pennleung** [comment]
> 「瞓」讀「訓」，fan3是粵語音，普通話音就是xùn，沒有任何問題。
> 字無法顯示是字體問題，無論在哪顯示方框都是字體不支持。

这个字多个字典显示都只有fen的音，并不是xun
字体找到方法处理了谢谢
![微信截图_20200812083505](https://user-images.githubusercontent.com/69492655/89962348-05845900-dc77-11ea-93d2-d384e9fe6cbe.png)
![微信截图_20200812083547](https://user-images.githubusercontent.com/69492655/89962350-074e1c80-dc77-11ea-989e-1596abec253f.png)

**Comment by LEOYoon-Tsaw** [comment]
粵語輸入法係度：https://github.com/rime/rime-cantonese
拼音不是用來打粵語的

**Comment by pennleung** [comment]
> 粵語輸入法係度：https://github.com/rime/rime-cantonese
> 拼音不是用來打粵語的

“瞓”不是一个标准汉字吗？标准汉字不就有一个拼音吗？这个汉字对应的汉语拼音是fen不是xun，你可以查下字典。我用的是拼音输入法，要打“瞓”这个字不应该用普通话拼音吗？用关佢系方言用字乜事？

**Comment by laubonghaudoi** [comment]
@pennleung 要查漢字粵語發音請用 jyut.net，這是最標準權威的粵語字典，別的網上詞典都有各種錯訛。你要查的「瞓」字在這裏 https://jyut.net/query?q=瞓

Unicode中的漢字有十三萬個，大陸中小學裏教的只有幾千個，新華字典裏也只收錄不到兩萬個，絕大多數漢字都是你不認識的。漢字是一個普適的系統，普通話所用到的漢字只是其中的一個子集，還有粵語漢字、朝鮮語漢字、日本語漢字、越南語喃字等等，都用到各種**普通話不會用到漢字**。因爲這些字本來就不是普通話，所以不會有普通話讀音，就算有也是用音系推導來的。這些字查新華字典也沒用，因爲新華字典只會收錄「普通話會用到的漢字的普通話發音」。

這些漢字可以在三個地方查詢，第一個是北師大的漢字全息資源應用系統：https://qxk.bnu.edu.cn/#/danziDetail/49c12ccb-35cc-437b-af4a-3fe126df8fca/瞓/ 
第二個是臺灣中央研究院國際電腦漢字及異體字知識庫：https://chardb.iis.sinica.edu.tw/char/17368
第三個是漢典：https://www.zdic.net/hans/瞓

如果你想輸入這些字，就不要用普通話拼音輸入法。普通話拼音是拿來打普通話的，打粵語要用粵語拼音輸入法：https://github.com/rime/rime-cantonese

**Comment by pennleung** [comment]
> @pennleung 要查漢字粵語發音請用 jyut.net，這是最標準權威的粵語字典，別的網上詞典都有很多錯訛。你要查的「瞓」字在這裏 [https://jyut.net/query?q=瞓](https://jyut.net/query?q=%E7%9E%93)
> 
> Unicode中的漢字有十三萬個，大陸中小學裏教的只有幾千個，新華字典裏也只收錄不到兩萬個，絕大多數漢字都是你不認識的。漢字是一個普適的系統，普通話所用到的漢字只是其中的一個子集，還有粵語漢字、朝鮮語漢字、日本語漢字、越南語喃字等等，都用到各種**普通話不會用到漢字**。因爲這些字本來就不是普通話，所以不會有普通話讀音，就算有也是用音系推導來的。這些字查新華字典也沒用，因爲新華字典只會收錄「普通話會用到的漢字的普通話發音」。
> 
> 這些漢字可以在三個地方查詢，第一個是北師大的漢字全息資源應用系統：[https://qxk.bnu.edu.cn/#/danziDetail/49c12ccb-35cc-437b-af4a-3fe126df8fca/瞓/](https://qxk.bnu.edu.cn/#/danziDetail/49c12ccb-35cc-437b-af4a-3fe126df8fca/%E7%9E%93/)
> 第二個是臺灣中央研究院國際電腦漢字及異體字知識庫：https://chardb.iis.sinica.edu.tw/char/17368
> 第三個是漢典：[https://www.zdic.net/hans/瞓](https://www.zdic.net/hans/%E7%9E%93)
> 
> 如果你想輸入這些字，就不要用普通話拼音輸入法。普通話拼音是拿來打普通話的，打粵語要用粵語拼音輸入法：https://github.com/rime/rime-cantonese

增长知识，谢谢
