### ISSUE TITLE
Add rime-putonghua as an offical schema

### ISSUE THREAD

**Issue by ayaka14732** [rime/home#597]
I have created a new schema [ayaka14732/rime-putonghua](https://github.com/ayaka14732/rime-putonghua).

This schema is different from the current [rime-pinyin-simp](https://github.com/rime/rime-pinyin-simp), [rime-luna-pinyin](https://github.com/rime/rime-luna-pinyin) and [rime-terra-pinyin](https://github.com/rime/rime-terra-pinyin) in the following aspects:

1\. Unlike rime-luna-pinyin and rime-terra-pinyin, the dictionary is in Simplified Chinese. Therefore, (1) we can utilize many dictionary resources that is available in Simplified Chinese only, and (2) it can avoid the conversion problems that keep appearing like 复投 and 徵羽摩柯 for Simplified Chinese users.

2\. Unlike rime-pinyin-simp, the dictionary is large enough (around 160,000 words) for daily use.

I hope that this schema can be the official schema for Simplified Chinese _Pinyin_ users. It would be great if this schema can be included in rime organization.

**Comment by ayaka14732** [comment]
中文翻译：

我创造了一个新的方案 [ayaka14732/rime-putonghua](https://github.com/ayaka14732/rime-putonghua)。

这一方案与现时的 [rime-pinyin-simp](https://github.com/rime/rime-pinyin-simp), [rime-luna-pinyin](https://github.com/rime/rime-luna-pinyin) 和 [rime-terra-pinyin](https://github.com/rime/rime-terra-pinyin) 在以下几个方面有所不同：

1\. 与 rime-luna-pinyin 及 rime-terra-pinyin 不同，这个方案的词库是用简体中文编写的。因此，(1) 我们可以利用许多只有简体中文的词典资源，(2) 可以避免简体中文用户不断出现的转换问题，例如「复投」和「征羽摩柯」。

2\. 与 rime-pinyin-simp 不同，这本字典对于日常使用来说足够大（大约 16 万个词语）。

我希望这个为了简体中文拼音使用者设计的方案能成为官方方案。如果这个方案能被包含在 rime 组织中，那就太好了。

@lotem

**Comment by lotem** [comment]
啥叫官方方案？要取代luna-pinyin？那不必吧。

雖說有（1）（2）等好處，反過來也有：
（1）無法利用繁體中文資源、無法利用爲數更多的不帶調拼音的詞典資源；
（2）繁體中文用戶出現更多簡繁轉換的錯誤；
恐怕一時無法取代現有的拼音方案。
pinyin-simp 則主要是爲五筆等形碼做反查而設立（技術不成熟無法在反查同時轉換字形），並不主張日常使用，所以才沒有下力擴充維護。否則何不把 lotem/rime-c2h6-pinyin 扶正呢。

我覺得現在的配方架構下，是否由rime組織託管代碼已經沒有區別。要不你先拿着孵化一段時間。看看效果。

**Comment by ayaka14732** [comment]
No, I did not mean that rime-putonghua should replace rime-luna-pinyin. Instead, I think it can co-exist with current schemata.

As far as I know, there is not officially a Simplified Chinese schema (the original dictionary should be Simplified Chinese). rime-putonghua is such a schema. It can be beneficial for Simplified Chinese _Pinyin_ users.

**Comment by lotem** [comment]
我覺得在配方架構下，是否由rime組織託管代碼已經沒有區別。不需要有一款「官方的」簡體中文拼音方案。

既然已經有了所謂官方的拼音方案，那麼就當集中力量維護和改進，通過技術的進步逐步淘汰受歷史侷限已經存在的重複方案，而不必再針對各種細微差別創建更多類似方案了。否則只會分散力量，各自維護越走越遠的代碼庫，這本質上就是開源社區不同組織獨立運作的方式，何必強行歸納爲同一個官方組織？
每個人根據自己的理念都可以創建一個拼音方案，現在就有不少。大家的方案又都不完全一樣，要是極端一點，都可以成爲官方方案、卻互不兼容、維護工作也沒有交集的話，也就無所謂官方了。不如從開始就認清社區方案的性質。
 
再者，就算要找一款官方的簡體中文拼音方案，鑑於大多數簡體拼音用戶都不輸入拼音的聲調，且大部分可利用的拼音詞庫資源也是不標註聲調的，最優的選擇也應當是詞典用不標調的拼音。如果還覺得帶聲調的簡體拼音也有價值成爲「官方收錄的」方案，是不是就印證了上面一段話關於多樣性只存在於社區而非「官方」的分析。
