### ISSUE TITLE
无法记住每个应用的输入状态

### ISSUE THREAD

**Issue by linchangyi** [rime/home#598]
我使用shift键来切换/激活输入法.
1. 如果使用rime自带的中英文切换功能, 则无法记住每个应用的输入状态,  会在所有应用中共享中英文状态, 这点不太好.
2. 而如果不使用rime英文输入功能(将fcitx的shift快捷键设为切换/激活输入法),  则切换输入法时无法将已经输入的字母自动上屏.

是否可以参考fcitx-sunpinyin, 切换/激活输入法时可以将已经输入的字母自动上屏, 这样可以利用fcitx框架的特性以区分不同程序的输入法状态.

**Comment by lotem** [comment]
https://github.com/rime/weasel/issues/454#issuecomment-570224435

若要参考fcitx-sunpinyin的切換時自動上屏的行爲，得由[fcitx-rime](https://github.com/fcitx/fcitx-rime)實現。
