### ISSUE TITLE
Emacs中默认英文

### ISSUE THREAD

**Issue by casouri** [rime/home#599]
不知道为啥在Emacs中rime默认为英文输入，我试图用
```
patch:
  app_options/org.gnu.Emacs:
    ascii_mode: false
```
让rime默认中文，但是没有作用。版本为0.14.0，mac版本为10.15.6。

**Comment by casouri** [comment]
iTerm2也是一样。

**Comment by lotem** [comment]
如上修改 `~/Library/Rime/squirrel.custom.yaml` 有效。

**Comment by liebkne** [comment]
将一楼的配置放到`~/Library/Rime/squirrel.custom.yaml`之后deploy貌似会失败，然后所有设置恢复到默认设置…
