### ISSUE TITLE
shortcut remap not work I want to map comma and period to pageup and down in my situation

### ISSUE THREAD

**Issue by woshichuanqilz** [rime/home#600]
[rime_data.zip](https://github.com/rime/home/files/5093514/rime_data.zip)

I already change the config in the `default.custom.yaml` and `/build/default.yaml`
file but not work in my machine. 

System : Manjaro 20.1 Mikah
Rime: version Sorry I dont know how to check the version `rime --version`  in terminal not work for me

Attach files is my config

**Comment by Ace-Who** [comment]
一、

```yaml
key_binder/bindings:
```

缩进不对，应改为

```yaml
  key_binder/bindings:
```

二、不要、不用修改 `build` 目录下的文件。

三、该配置是默认配置，你的默认配置丢失了吗？

**Comment by woshichuanqilz** [comment]
> 一、
> 
> ```yaml
> key_binder/bindings:
> ```
> 
> 缩进不对，应改为
> 
> ```yaml
>   key_binder/bindings:
> ```
> 
> 二、不要、不用修改 `build` 目录下的文件。
> 
> 三、该配置是默认配置，你的默认配置丢失了吗？


[rime_data.zip](https://github.com/rime/home/files/5100401/rime_data.zip)
1. 
缩进修改了， 现在[]也不能翻页了 
2.3.
我的配置直接拿得这里的
https://github.com/cnfeat/Rime

**Comment by lotem** [comment]
既然使用了第三方的配置，是不是直接向配置的作者提問，或許問題可以更快得到解答？

本品[出廠配置](https://github.com/rime/rime-prelude/blob/master/default.yaml#L49)即爲可以使用逗號、句號翻頁。
另外，[Wiki](https://github.com/rime/home/wiki/CustomizationGuide#%E4%BB%A5%E6%96%B9%E6%8B%AC%E8%99%9F%E9%8D%B5%E6%8F%9B%E9%A0%81)列舉了設置爲其他翻頁鍵的方法，可以參考。
