### ISSUE TITLE
About commercial purpose

### ISSUE THREAD

**Issue by Jabez13410** [rime/home#605]
您好，
    请问我可以在商业行为上使用此输入法吗？主要是写程序和使用电脑的时候使用。如果不可以的话，请告知我，我将停止在商业行为中使用，并对用于商业行为感到非常抱歉（注：我只是一个普通的雇员）。

**Comment by LEOYoon-Tsaw** [comment]
可以的，但是基於此開源項目的成果必須同樣開源

**Comment by lotem** [comment]
個人或在商業機構內部使用本品不受任何限制。
如果使用本品的源碼進行二次開發，需要按照授權許可規定的方式發佈衍生的產品。
不專業的解釋： 
https://github.com/rime/librime 這個程序庫使用相對寬鬆的BSD許可證，要求發佈衍生產品時包含一份版權聲明。
而 https://github.com/rime/squirrel, https://github.com/rime/weasel, 以及一些包含數據的代碼庫使用GPL許可證。使用這些代碼的產品須按照GPL協議的要求的方式發佈，即不改變軟件的授權方式（GPL）、獲得衍生產品的用戶可以自由使用修改後的產品源代碼。

**Comment by lotem** [comment]
@Jabez13410 
如果確有需要發佈基於本品開發的軟件，請通過郵件與我聯繫，溝通一下具體細節。
