### ISSUE TITLE
关于一个汉字的输入问题

### ISSUE THREAD

**Issue by iPolluxGem** [rime/home#607]
”囃“字的简化字是否是”𠱞“？

经查，该字 五笔KYWY，仓颉RYDG
在简体字下只能输入”𠱞“，而必须调为繁体字才能输入”囃“。（读音为ca4或za2）
目前我没法确定该汉字是否以”𠱞“为”囃“的简化。如果不是，还请替换。

令：经查，”𠱞“为异体字，且读音为ran3，应该不是同一个字。

**Comment by LEOYoon-Tsaw** [comment]
OpenCC原則上使用Unihan的kSimplifiedVariant屬性

**Comment by iPolluxGem** [comment]
在查过unihan之后发现确实是将“𠱞（U+20C5E）”和“囃（U+2B75C）”作为简繁对应了，那就暂时没有办法了。
