### ISSUE TITLE
请教一个配置的问题，关于 luna_pinyin.custom.yaml

### ISSUE THREAD

**Issue by 990753707** [rime/home#609]
系统是manjaro 20  安装玩 ibus-rime 后在目录里并没没有 luna_pinyin.custom.yaml  这个文件，也没有任何 *.custom.yaml 的文件，应该怎么搞？

下面是 .config/ibus/rime/build   目录下的文件

terra_pinyin.reverse.bin
cangjie5.reverse.bin
cangjie5.table.bin
terra_pinyin.schema.yaml
terra_pinyin.table.bin
stroke.table.bin
stroke.schema.yaml
bopomofo_tw.schema.yaml
luna_pinyin.prism.bin
default.yaml
cangjie5.prism.bin
luna_quanpin.prism.bin
stroke.reverse.bin
bopomofo.schema.yaml
luna_pinyin.table.bin
luna_pinyin.reverse.bin
bopomofo_tw.prism.bin
bopomofo.prism.bin
stroke.prism.bin
terra_pinyin.prism.bin
luna_pinyin_simp.prism.bin
luna_pinyin_fluency.prism.bin
cangjie5.schema.yaml

**Comment by lotem** [comment]
沒有問題。
默認配置是可用的。
`*.custom.yaml` 是用戶自己寫的自定義的配置。

**Comment by gclintj** [comment]
*.custom.yaml应该放在build 目录下还是 Rime 目录下？
