### ISSUE TITLE
F4 按鈕 會跳出 ctrl + ~ 的選單 無法使用F4原本的按鍵功能

### ISSUE THREAD

**Issue by vasilyalexsanov** [rime/home#61]
F4 按鈕 會跳出 ctrl + ~ 的選單

導致所有會用到F4按鍵的地方 都會無法使用

程式也好 遊戲也好 影響十分之大

希望能把F4 跳選單部分移除 只有ctrl + ~ 即可

**Comment by osfans** [comment]
這行刪掉，再重新部署就好：

https://github.com/rime/brise/blob/master/default.yaml#L18

**Comment by vasilyalexsanov** [comment]
我不懂程式啊.....具體來說應該是怎麼做?
我看到F4 那邊刪掉 然後呢

**Comment by vasilyalexsanov** [comment]
我去掉了F4
重新部署還是在啊?
