### ISSUE TITLE
在macos多个应用里面无法输入

### ISSUE THREAD

**Issue by yousong** [rime/home#610]
- macos 10.13.6
- squirrel 0.14.0

通过`brew cask install squirrel`安装

初次使用，自定义的配置很少，只额外启用了wubi86

```
➜  ~/Library/Rime ll
total 12K
drwxr-xr-x 18 yousong staff 576 Sep  3 15:02 build
drwxr-xr-x  9 yousong staff 288 Sep  3 15:06 luna_pinyin.userdb
drwxr-xr-x 10 yousong staff 320 Sep  3 14:47 rime-wubi
drwxr-xr-x  4 yousong staff 128 Sep  3 16:57 sync
drwxr-xr-x  9 yousong staff 288 Sep  3 15:06 wubi86.userdb
-rw-r--r--  1 yousong staff 194 Sep  3 14:47 default.custom.yaml
-rw-r--r--  1 yousong staff 209 Sep  3 13:12 installation.yaml
-rw-r--r--  1 yousong staff 207 Sep  3 15:06 user.yaml
lrwxr-xr-x  1 yousong staff  26 Sep  3 14:47 wubi86.dict.yaml -> rime-wubi/wubi86.dict.yaml
lrwxr-xr-x  1 yousong staff  28 Sep  3 14:47 wubi86.schema.yaml -> rime-wubi/wubi86.schema.yaml
➜  ~/Library/Rime cat default.custom.yaml
# 文档
#
# - https://github.com/rime/home/wiki/RimeWithSchemata
# - https://github.com/rime/home/wiki/CustomizationGuide
#
patch:
  schema_list:
    - schema: luna_pinyin
    - schema: wubi86
➜  ~/Library/Rime
```

试了几个，不能执行输入的应用包括Notes，Terminal，还有Spotlight Search的输入框。

 - 无法用Shift键切换，无法输入中、英文字符
 - Terminal里面回车链有效，Notes里不响应任何输入
 - 可以Ctrl-Space切换到系统的英文输入法，此时可以输入

当无法输入时，状态栏里Squirrel相关条目都为省略号

![image](https://user-images.githubusercontent.com/4948057/92104627-2bcf8b80-ee14-11ea-8f69-efc01166038e.png)

在Finder，Chrome，iTerm2里是可以的工作的。

**Comment by yousong** [comment]
`brew cask remove squirrel`，确认`/Library/Input Methods`目录为空，`brew cask install squirrel`重装后问题依然存在

**Comment by yousong** [comment]
混乱了，尝试在系统输入法配置里移除再添加Squirrel，重复几次，然后退出再打开Notes，就这2个操作，上面说的几个应用都可以使用输入了…

**Comment by lotem** [comment]
同 https://github.com/rime/squirrel/issues/281

應該是要重新登錄才好用。但是通過brew cask安裝則不會提示退出登錄。
