### ISSUE TITLE
词库没有"划"

### ISSUE THREAD

**Issue by dgsasf** [rime/home#614]
简化字[hua]划 输入后只有畫[画]增加了打字次数 并没有单独的划
![notepad_OTqUgbAmoU](https://user-images.githubusercontent.com/70845950/92325817-1363a900-f080-11ea-96f2-be11301c6065.png)

**Comment by LEOYoon-Tsaw** [comment]
有需要簡化字的可以自己加

**Comment by lotem** [comment]
哪個詞庫？
出廠的詞庫都有這個字。

**Comment by dgsasf** [comment]
那应该不是用户词库是用户词典[搞混了]  导出文本码表后 没有划这个字 只有繁体"畫"

**Comment by lotem** [comment]
詞典是繁體的。而簡繁不一一對應，簡體字的「划」是由「划」「畫/劃」合併而來。
用家不用關注詞典怎麼記錄。只要能用簡體打出來就不成問題。
