### ISSUE TITLE
如何把切换候选字的快捷键改为【<>】

### ISSUE THREAD

**Issue by shauncathe** [rime/home#617]
现在默认是 -+，能改吗？

**Comment by lotem** [comment]
能改。
參考資料:
https://github.com/rime/home/wiki/CustomizationGuide#%E4%BB%A5%E6%96%B9%E6%8B%AC%E8%99%9F%E9%8D%B5%E6%8F%9B%E9%A0%81
https://github.com/rime/librime/blob/master/thirdparty/include/X11/keysymdef.h#L556
https://github.com/rime/librime/blob/master/thirdparty/include/X11/keysymdef.h#L558

**Comment by shauncathe** [comment]
太棒了，感谢








Shaun He
M +86 1370 1664 529
在 2020年9月16日 +0800 08:42，弓辰 <notifications@github.com>，写道：

**Comment by shauncathe** [comment]
再请问，候选字数量哪里可以设定？








Shaun He
M +86 1370 1664 529
在 2020年9月16日 +0800 08:42，弓辰 <notifications@github.com>，写道：

**Comment by LEOYoon-Tsaw** [comment]
在default.custom.yaml

**Comment by shauncathe** [comment]
感谢，搞定了








Shaun He
M +86 1370 1664 529
在 2020年9月21日 +0800 20:45，LEO Yoon-Tsaw <notifications@github.com>，写道：
