### ISSUE TITLE
鼠须管是否可以配置反查时的正确输入编码？

### ISSUE THREAD

**Issue by qianjigui** [rime/home#620]
我目前使用新世纪五笔+拼音(反查)进行输入，由于个人水平有限。
需要如下支持：
1. 拼音支持模糊输入
2. 通过反查后，可以提示正确的五笔编码，便于学习与以后改正

目前我的配置：在拼音后面直接加上编码。
https://gitee.com/wang-pc/rime-xinshiji_wubi_pinyin-config

**Comment by lotem** [comment]
可以。參考方案： https://github.com/rime/rime-wubi/blob/master/wubi_pinyin.schema.yaml

**Comment by qianjigui** [comment]
参见自己的最终方案:
https://gitee.com/wang-pc/rime-xinshiji_wubi_pinyin-config

![wubitip1](https://user-images.githubusercontent.com/127572/93757042-ae3fb400-fc38-11ea-8923-80a07b17b795.png)
![wubitip2](https://user-images.githubusercontent.com/127572/93757054-b1d33b00-fc38-11ea-9aae-253141ba3c96.png)
