### ISSUE TITLE
自訂詞可否支援多行文字

### ISSUE THREAD

**Issue by cpc1854** [rime/home#625]
您好，
剛剛使用RIME不久，非常驚豔可以達到很多客製設定，
請教自訂詞可否支援多行文字，或類似插入制式短回覆文字(帶有分行符號)，
如需插入char(13) char(10)或特殊符號代表分行也可以。

感謝各位。

**Comment by cpc1854** [comment]
上述功能的好處是，不只可以自訂詞彙，也可自訂短文、甚至不同語言程式碼的範例：
C#:
for (int i = 0; i < 5; i++) 
{
  Console.WriteLine(i);
}

Python:
for x in range(5):
  print(x)

**Comment by LEOYoon-Tsaw** [comment]
可以，用Vim输入换行符^@

**Comment by cpc1854** [comment]
非常感謝 @LEOYoon-Tsaw 解答，
但在windows環境下 使用vim/Visual Studio Code/Notepad++輸入^@代表換行符號，但輸出仍然沒有轉換成換行。
此外也試過輸入\n\r 及\\n\\r，也是不行。
感謝您。

**Comment by sfzylx** [comment]
在windows环境下，notepad++中输入特殊字符0D，即CR即可换行。

**Comment by Ace-Who** [comment]
在 Vim 中换行符显示为「^@」，不是指输入「^」和「@」两字符。输入方法是 <kbd>Ctrl + V</kbd><kbd>Ctrl + J</kbd>。

**Comment by cpc1854** [comment]
@LEOYoon-Tsaw  @sfzylx  @Ace-Who 可以在windows環境下輸入CR符號，自訂詞可以支援多行，非常非常感謝您們。

**Comment by poorich** [comment]
@cpc1854 能否提供一个完整的例子呢，我也突发奇想想要设定好一系列跨行的代码命令
试验的结果或是依然成一行，或是结果都跳不出来还把输入文本的平台搞崩溃了

**Comment by LEOYoon-Tsaw** [comment]
用`\x0D`(`^M`, carriage return)換行
在Vim中插入方法：依次鍵入`ctrl+v`, `x`, `0`, `d`

**Comment by leolulu** [comment]
经过楼上各位的启发，我现在在windows下采用notepad++添加CR符，留个截图供后来人参考
![image](https://github.com/user-attachments/assets/be6da21c-1bcd-4f28-b431-c87c24951c9f)
