### ISSUE TITLE
請問 fcitx-rime 是否支持 lua 相關功能

### ISSUE THREAD

**Issue by catscarlet** [rime/home#626]
系統：Linux Mint 20，使用 fcitx 作爲輸入法引擎。
我今天嘗試 lua_translator 使其支持輸出時間日期，但是完全沒有任何效果。
我查到的資料多數都是 Windows 用戶，不知道 linux 上的支持狀態如何？
請問 fcitx-rime 是否支持 lua 相關功能？

**Comment by lotem** [comment]
這個問題不屬於librime項目的範疇，能否使用lua腳本取決於[fcitx-rime](https://github.com/fcitx/fcitx-rime)是否加載了[librime-lua](https://github.com/hchunhui/librime-lua)插件。您可以向fcitx開發團隊進一步確認。

相關技術討論：https://github.com/rime/librime/issues/369

從Ubuntu的[軟件包搜索結果](https://packages.ubuntu.com/search?suite=default&section=all&arch=any&keywords=librime&searchon=names) 看，librime-lua大概沒有收錄到Ubuntu的軟件倉庫。
