### ISSUE TITLE
漢字和拼音同時產生 Generate hanzi and pinyin at the same time

### ISSUE THREAD

**Issue by svenper** [rime/home#628]
After inputting “raw” pinyin (terra), I can press either
* <kbd>Space</kbd> to get “諸如此類”
* <kbd>Shift</kbd><kbd>Enter</kbd> or <kbd>Ctrl</kbd><kbd>Enter</kbd> to get “zhū rú cǐ lèi”

However, I am looking to get both at the same time, to write the pinyin only once, and then press another key combination to automatically get something like:

```text
諸如此類（zhū rú cǐ lèi）
```

or perhaps even HTML like

```html
<ruby>諸<rt>zhū</rt>如<rt>rú</rt>此<rt>cǐ</rt>類<rt>lèi</rt></ruby>
```
> （<ruby>諸<rt>zhū</rt>如<rt>rú</rt>此<rt>cǐ</rt>類<rt>lèi</rt></ruby>）

or even crazier stuff like
```html
<ruby lang="zh-Hant"><!--
    -->諸<rt lang="zh-Latn">zhū</rt><!--
    -->如<rt lang="zh-Latn">rú</rt><!--
    -->此<rt lang="zh-Latn">cǐ</rt><!--
    -->類<rt lang="zh-Latn">lèi</rt><!--
--></ruby>
```
> （<ruby lang="zh-Hant">諸<rt lang="zh-Latn">zhū</rt>如<rt lang="zh-Latn">rú</rt>此<rt lang="zh-Latn">cǐ</rt>類<rt lang="zh-Latn">lèi</rt></ruby>）

Is this possible?

**Comment by lotem** [comment]
You need to create a `rime::Processor` to handle the key combos and implement the formatting logic there, then push the output string to `engine_->sink()`.
The information needed to format the output are available as `engine_->context()->GetCommitText()` and `engine_->context()->GetScriptText()`.

**Comment by svenper** [comment]
Thanks for replying. So this needs to be an addon of some kind? Or any chance of inclusion in a future update? (unfortunately beyond my ability) :pray:

**Comment by lotem** [comment]
Sadly you have to tweak the code a little to suit this particular needs at the moment.
To better serve common needs, what is to be introduced in librime shall be a more general feature that allows user to configure preedit text with string templates. But that means more work and I guess it won't happen very soon.
