### ISSUE TITLE
朙月拼音是如何使包含多音字的词只有一种输入方式的？

### ISSUE THREAD

**Issue by A205B064** [rime/home#634]
比如`shoudu`可以打出`首都`这个词，但`shoudou`则不能打出。（标题中的`一种`可能在措辞上不够准确，因为启用简拼的话`shoud`同样可以，但应该不影响理解）
个人猜测是`luna_pinyin.prism.bin`和`luna_pinyin.table.bin`导致的。因为双拼输入法挂`luna`的词典，也能保证上述特性，但自制的词典挂八股文，就没有上述特性了。
如果想自定义一些词库、辅助码之类的，如何才能保证上述特性？

**Comment by lotem** [comment]
須在詞典源文件(`*.dict.yaml`)裏註明詞組的拼音編碼。
