### ISSUE TITLE
在地球拼音中，如何設置Ctrl+Shift+4等快捷鍵來切換臺灣正體和大陸簡體？

### ISSUE THREAD

**Issue by 86d4a37** [rime/home#637]
如何恰當設置開關？提前謝謝幫助。

**Comment by StayTherapy** [comment]
可以嘗試增加一條 patch
```yaml
patch:
  key_binder/bindings/+: "{accept: "Ctrl+Shift+4", toggle: simplification, when: always}"
```
參考：[Schema.yaml 詳解](https://github.com/LEOYoon-Tsaw/Rime_collections/blob/master/Rime_description.md#%E5%85%AB%E5%85%B6%E5%AE%83) 第 6 點

**Comment by StayTherapy** [comment]
> 可以嘗試增加一條 patch
> 
> ```yaml
> patch:
>   key_binder/bindings/+: "{accept: "Ctrl+Shift+4", toggle: simplification, when: always}"
> ```
> 
> 參考：[Schema.yaml 詳解](https://github.com/LEOYoon-Tsaw/Rime_collections/blob/master/Rime_description.md#%E5%85%AB%E5%85%B6%E5%AE%83) 第 6 點

抱歉，我仔細看了一下「地球拼音」的 `schema`，好像`key_binder`下已經有一條 `- {accept: "Control+Shift+dollar", toggle: simplification, when: always}`，也就是說默認方案已經支持 Ctrl+Shift+4 進行繁簡轉換。

**Comment by lotem** [comment]
原裝配置定義了此項快捷鍵：
https://github.com/rime/rime-terra-pinyin/blob/5a445e2953c4b8149daac9d4625782fd5f80d9f2/terra_pinyin.schema.yaml#L194
https://github.com/rime/rime-prelude/blob/f372f522d095cfde272893b827f0a406fb7b861d/default.yaml#L50
https://github.com/rime/rime-prelude/blob/f372f522d095cfde272893b827f0a406fb7b861d/key_bindings.yaml#L41

**Comment by 86d4a37** [comment]
抱歉，我說不清楚。
默認的Ctrl+Shift+4快捷鍵只能在傳統字（爲、裏、 麪等）和簡體字之間切換，沒有台灣標準字（為、裡、麵等）。
如何設置Ctrl+Shift+4來切換【台灣標準字 ↔ 簡體字】？
