### ISSUE TITLE
[無關程式] 平常行文拼 Rime 還是 RIME？

### ISSUE THREAD

**Issue by GJRobert** [rime/home#638]
抱歉，我是個「自我規範控」/「自我一致控」
我看官網標題是 `RIME`，
但其他行文都是以 `Rime` 為多。

是不是因為 Rime Input Method Engine 縮寫才會變 RIME？（但若說「Rime」是指什麼？好像會變成類似 GNU 式的回文，好像也作不得準）日常是不是打 Rime 就好？

**Comment by VimWei** [comment]
RIME是 Rime Input Method Engine 的縮寫，是Rime的三大核心概念之一“逻辑对象”（输入法中解决某类问题的算法，以及描述输入法的工作流程中纯粹的逻辑部份，用程序写出来，就是输入法引擎RIME）。

Rime则不仅仅包括逻辑对象RIME，还包括数据对象和交互对象。

日常使用，Rime 更准确。
而使用 RIME，可以是仅表示输入法引擎本身，也可以用其代表 Rime整体，毕竟该输入法区别于其他输入法的地方正是最核心的 RIME。

**Comment by GJRobert** [comment]
> RIME是 Rime Input Method Engine 的縮寫，是Rime的三大核心概念之一“逻辑对象”（输入法中解决某类问题的算法，以及描述输入法的工作流程中纯粹的逻辑部份，用程序写出来，就是输入法引擎RIME）。
> 
> Rime则不仅仅包括逻辑对象RIME，还包括数据对象和交互对象。
> 
> 因此，日常使用，Rime 更准确。而使用 RIME，可以是仅表示输入法引擎本身，也可以用其代表 Rime整体，毕竟该输入法区别于其他输入法的地方正是最核心的 RIME。

我想不到 RIME 原來是 Rime 的子集合。好的，看來 Rime 本身就是一個專案的名稱，並不只是因為它是個輸入法 IME 所以才取這個名字的。那這樣我想平常應該是用 Rime 就好。
