### ISSUE TITLE
Windows 10 英文介面下無法輸入中文

### ISSUE THREAD

**Issue by doodoohow** [rime/home#64]
環境：Windows 10，系統語言英文
版本：０.９.３０
輸入法：烱月拼音中文正體
問題：無法輸入中文，不管怎麼切換，裝卸，重新啟動，都卡在英文

**Comment by littleq0903** [comment]
我也遇到一樣問題，Desktop-only 可以在 legacy app 中正常使用，但是 TSF 的就完全沒有反應了。

**Comment by fourfries** [comment]
在解壓Zip檔的資料夾開啓 WeaselServer.exe，僅開一次IME之後會如常運作，重新開機後也沒有問題。剛剛在Windows 10 英文 1903版試過。

**Comment by lotem** [comment]
從0.10版本開始支持Windows 10
