### ISSUE TITLE
一个

### ISSUE THREAD

**Issue by a1064295263** [rime/home#643]
你好  

安装选项 那里  一个  简体。中国大陆    一个繁体
![微信图片_20201108094336](https://user-images.githubusercontent.com/31720744/98455108-38bb8300-21a7-11eb-96dc-f26100d3bbb6.png)
  台湾

**Comment by Prcuvu** [comment]
无法理解这个问题想问什么。
请编辑问题，改善措辞后再考虑重新开启。
