### ISSUE TITLE
weasel.custom.yaml不生效的问题

### ISSUE THREAD

**Issue by appleyuchi** [rime/home#647]
我的环境是:
ubuntu 20.04 xfce

请问这个文件
weasel.custom.yaml
需要被luna_pinyin_simp.schema.yaml引用后才能生效吗？
如果需要引用，请问应该怎么引用？

https://github.com/rime/home/wiki/CustomizationGuide#鼠鬚管外觀與鍵盤設定
这个已经看过了，无效额
谢谢

**Comment by lotem** [comment]
要在Windows上用。

**Comment by appleyuchi** [comment]
> 要在Windows上用。

那linux上请问有相关方案吗?
谢谢

**Comment by lotem** [comment]
界面由輸入法框架提供。請首先嘗試在IBus（或Fictx）設置與界面相關的選項。
爲了應對IBus的接口變化，ibus-rime設了幾個選項，不過是否使用該配置視軟件版本而定。參考 https://github.com/rime/ibus-rime/issues/42
