### ISSUE TITLE
rime输出乱码

### ISSUE THREAD

**Issue by appleyuchi** [rime/home#649]
您好！
我是ubuntu 20.04系统(xfce桌面)
当我输入"kaiji"时，第8个滦南吗乱码
![乱码](https://user-images.githubusercontent.com/27613483/99059483-a0276780-25d9-11eb-89e6-aa6cc1c516cc.jpg)
求问怎么解决啊，谢谢

**Comment by lotem** [comment]
码没有乱。是界面的字体不能显示这个字。
