### ISSUE TITLE
shift 键能不能自定义其它功能?

### ISSUE THREAD

**Issue by AffiNiNy** [rime/home#651]
已阅读  [使用Control鍵切換中西文](https://gist.github.com/lotem/2981316) 关于更改 shitf 及 ctrl 键切换上屏功能的说明.

现在有一个需求是: Shift_R 键, 取消中英文切换的同时, 能复制同时按下的组合键, 并自动上屏. 
例如按下 a+Shift_R, 电脑端输出 aa; Esc + Shift_R 等于按下两次 Esc.
鉴于左 shift 与右 shift 功能相同, 左 shift 与左 ctrl 使用频率高于右 shift 右 ctrl, 因此想定制位于右侧的 shift 与 ctrl.

Window可设置的地方少, 基本找不到设置.  Rime输入法能自定义做到这个功能否??

**Comment by lotem** [comment]
不能。所述這些不是輸入法的功能。輸入法用於輸出文字而不是輸出按鍵。
樓主需要的是可編程鍵盤或複雜的按鍵映射軟件。
