### ISSUE TITLE
请问如何添加多个文本词典(custom_phrase.txt), 以及词典上限? 

### ISSUE THREAD

**Issue by nutnutwin** [rime/home#659]
你好, 请问如何添加多个文本词典(custom_phrase.txt)

(防止歧义) ｢custom_phrase.txt｣指用户数据文件夹下的词典文件
✦请问可否设置多个词典文件? 
理由是家里用的词典Merge 到公司, 但是想和公司里专用词典分离(防止泄漏)
谢谢

✦另外请问词典文件有容量上限吗? 

谢谢

**Comment by lotem** [comment]
可以。
`custom_phrase`是任选的名字。可以添加translator并替换相关配置里的`custom_phrase`。
程序没有限制词典的容量，不过如果文件过大有可能性能不佳，需要实验。

**Comment by nutnutwin** [comment]
@lotem 
不好意思请问translator设置有文档说明吗

关于容量: 我现在有20,000左右词典还没有觉得卡, 看来是挺优秀的

**Comment by lotem** [comment]
参考资料：
https://github.com/LEOYoon-Tsaw/Rime_collections/blob/master/Rime_description.md#%E4%B8%89translator
https://github.com/rime/rime-luna-pinyin/blob/master/luna_pinyin.schema.yaml#L81

**Comment by lotem** [comment]
相關問題及文檔鏈接： https://github.com/rime/librime/issues/410#issuecomment-788014012

**Comment by iamqiz** [comment]
@lotem  custom_phrase.txt 里能不能使用时间日期函数? 我想在输入 sj 时候打出当前时间, 搜狗自定义短语中可以使用 $year  $day 这样特殊变量,来表示时间,  rime支持吗?

**Comment by LEOYoon-Tsaw** [comment]
不支持。用lua

**Comment by iamqiz** [comment]
@LEOYoon-Tsaw 能不能官方支持一下?主要原因是lua是c语言吧,难度大,不像python; 且某些用户自定义短语可能需要大量的日期格式, 比如 x年x月x日  和  yy/mm/dd 这样的, 那每个短语都需要实现一个lua且没法共享吧?   
我觉得理想的方法是 官方提供一些预定义函数,用户也可用lua自定义函数, 然后用户自定义短语时可以通过一个表达式来引用函数的结果,比如像JavaScript那样:  ${ year() +"年"+mouth() + "月" }

**Comment by iamqiz** [comment]
我找到一个文章,看了下 貌似可以复用 , 我研究一下
