### ISSUE TITLE
请问ibus-rime如何设定候选词字号以及横排

### ISSUE THREAD

**Issue by caoli5288** [rime/home#66]
配置文件patch是不起效的。软件包信息如下。
```
$ rpm -qa | grep ^ibus
ibus-qt-1.3.3-8.fc23.x86_64
ibus-libs-1.5.11-1.fc23.x86_64
ibus-wayland-1.5.11-1.fc23.x86_64
ibus-hangul-1.5.0-5.fc23.x86_64
ibus-rawcode-1.3.2-6.fc23.x86_64
ibus-libpinyin-1.7.4-1.fc23.x86_64
ibus-rime-1.2-2.fc23.x86_64
ibus-chewing-1.4.14-4.fc23.x86_64
ibus-m17n-1.3.4-19.fc23.x86_64
ibus-1.5.11-1.fc23.x86_64
ibus-gtk2-1.5.11-1.fc23.x86_64
ibus-typing-booster-1.3.1-1.fc23.noarch
ibus-gtk3-1.5.11-1.fc23.x86_64
ibus-libzhuyin-1.7.6-1.fc23.x86_64
ibus-setup-1.5.11-1.fc23.noarch
ibus-kkc-1.5.22-3.fc23.x86_64
```

**Comment by lotem** [comment]
界面由 IBus 提供
可以在终端输入`ibus-setup` 进入设置页面来修改 https://wiki.archlinux.org/index.php/IBus_(%E7%AE%80%E4%BD%93%E4%B8%AD%E6%96%87)

**Comment by caoli5288** [comment]
@lotem 您好。在`ibus-setup`里面调整，随后执行`ibus restart`重启后依然是不起作用的。Gnome桌面对ibus做了较大程度的整合可能是问题的原因。
我尝试`gsettings set org.freedesktop.ibus.panel lookup-table-orientation 0`成功使候选词横向，但是`gsettings`里面提供的修改字体的方法依然是无效的。

```
$ gsettings get org.freedesktop.ibus.panel custom-font
'Sans 12'
$ gsettings get org.freedesktop.ibus.panel use-custom-font
true
```
望跟进，谢谢！

**Comment by caoli5288** [comment]
不好意思，漏看了可以通过修改shell主题的方式修改字体字号。虽然感觉挺不方便但是没有其他办法了，这个issue可以关闭了，谢谢！

**Comment by lunarjoll** [comment]
arch linux 使用ibus-setup，依然不能橫屏

**Comment by lotem** [comment]
configuration via `ibus_rime.yaml` is fixed by this commit
https://github.com/rime/ibus-rime/commit/8e081264977bfefdd233ebeb1235f11be55b28f8

**Comment by BoyanXu** [comment]
Arch Linux:

单独使用 ibus-setup 无法调整字号

先下载 gnome extension: [ibus font setting](https://extensions.gnome.org/extension/1121/ibus-font-setting/), 再使用 ibus-setup 可以调整字号

**Comment by AXFOX** [comment]
Debian KDE同样存在这样的问题。
