### ISSUE TITLE
用户词典的命名机制是什么？实际与文档描述不一致

### ISSUE THREAD

**Issue by VimWei** [rime/home#660]
我看了文档 “[RimeWithSchemata](https://github.com/rime/home/wiki/RimeWithSchemata)”，其中提到：
* `方案標識由小寫字母、數字、下劃線構成`，`爲了兼容不同的文件系統，不要用大寫字母、漢字、空格和其他符號做方案標識`。
* “碼表與詞典”提到：`name: 詞典名，內部使用，命名原則同「方案標識」`
* `記錄用戶寫作習慣的文件：<詞典名>.userdb/`。

实践中，我在“luna_pinyin_simp.custom.yaml” 中定义了词典 `  "translator/dictionary": vimwei`，但是却得到 `luna_pinyin.userdb/`。

不过，我在“double_pinyin_flypy.custom.yaml” 中定义了同样的词典 `  "translator/dictionary": vimwei`，却可以得到  `vimwei.userdb/`。

**请问：用户词典的命名机制到底是什么？**

以下是示意图：

![image](https://user-images.githubusercontent.com/25874852/101235685-68f23500-3705-11eb-8a9b-61b1a49c1d61.png)

**Comment by ZenamLeong** [comment]
Use user dictionary
User dictionary and dictionary are separated

**Comment by lotem** [comment]
`luna_pinyin` 是輸入方案 `luna_pinyin_simp` 出廠設置的詞典名。
僅憑截圖無法分析和驗證問題中的情況。只能猜測是補丁（如包含其他錯誤）沒有生效。

**Comment by VimWei** [comment]
> `luna_pinyin` 是輸入方案 `luna_pinyin_simp` 出廠設置的詞典名。
> 僅憑截圖無法分析和驗證問題中的情況。只能猜測是補丁（如包含其他錯誤）沒有生效。

这是我的主要配置文件，应该足以供您分析：
[RIME配置文件.zip](https://github.com/rime/home/files/5648139/RIME.zip)

我只所以提出这个问题，主要是我们会在朙月拼音、四叶草拼音、小鹤双拼三个输入法方案切换使用，同时希望它们能共用一个用户动态词库，因此我自定义了vimwei词库，可是按照文档却做不到。还请指导该如何实现。

**Comment by lotem** [comment]
只有先确认这个问题，才有进一步分析的必要。没有这个前提，调试个人配置的服务，我是拒绝的。
如果能排除其他配置错误，您仅需列出用以重现问题的最小配置。

**Comment by VimWei** [comment]
问题已解决，好像是：import_tables 所列的词库在之后 + “Tab + 注释”。
