### ISSUE TITLE
使用了模糊拼音的双拼，提示词能否 有中文 + 准确全拼？

### ISSUE THREAD

**Issue by VimWei** [rime/home#661]
目前大量使用模糊拼音，为学习准确的拼音，能否类似反查一样，在常规的“模糊拼音的双拼”中，提示词也能同时出现 “中文 + 准确拼音”？

**Comment by VimWei** [comment]
也就是输入的是：模糊拼音
出来的提示词是：准确全拼

**Comment by VimWei** [comment]
看到“小狼毫 0.9.11 (2012-04-14)  輸入簡拼、模糊音時提示正音，【粵拼】【吳語】中默認開啓”，

不知道是否就是我所说的功能？

**Comment by lotem** [comment]
可以显示当前候选字（词）在词典中定义的编码。
如果词典用「准确全拼」注音，则可以。

**Comment by VimWei** [comment]
> 可以显示当前候选字（词）在词典中定义的编码。
> 如果词典用「准确全拼」注音，则可以。

接触Rime还只有一周时间……关于如何“显示当前候选字（词）在词典中定义的编码”，有什么线索可供学习參考的吗？

**Comment by VimWei** [comment]
找到一個動圖，就是心中想要的效果：

![帶準確拼音提示的動圖](https://camo.githubusercontent.com/e5aca6479474f6c2ff6df83277592cc5bc173aca4ab8f780d338f1af8282a22e/68747470733a2f2f692e696d6775722e636f6d2f6a48706b3742542e676966)

**Comment by VimWei** [comment]
原来只要加入以下patch即可：
translator/spelling_hints: 8

**Comment by VimWei** [comment]
主要是这个。但RIME的设置比较复杂，其影响需要整体分析。

**Comment by HenryLau0220** [comment]
谢谢回复，我找到原因了：我用的模板有一个过滤器，被过滤掉了

**Comment by fun8e** [comment]
> 看到“小狼毫 0.9.11 (2012-04-14) 輸入簡拼、模糊音時提示正音，【粵拼】【吳語】中默認開啓”，
> 
> 不知道是否就是我所说的功能？

您好！我使用粵拼，希望隱藏候選字的拼音，請問如何操作？

**Comment by fun8e** [comment]
> > > 看到“小狼毫 0.9.11 (2012-04-14) 輸入簡拼、模糊音時提示正音，【粵拼】【吳語】中默認開啓”，
> > > 不知道是否就是我所说的功能？
> > 
> > 
> > 您好！我使用粵拼，希望隱藏候選字的拼音，請問如何操作？
> 
> Hints 設為0就行吧

我在default.custom.yaml中進行如下設置，但無效
patch:
  schema_list:
    - {schema: jyut6ping3}
  "translator/spelling_hints": 0
  "menu/page_size": 7


如果修改Rime\build\jyut6ping3.schema.yaml 如下 
spelling_hints: 0
試過一兩次可以奏效，但是重啓電腦或重新部署後，又變回無效

**Comment by fun8e** [comment]
> 别修改 build 下的任何文件

我在default.custom.yaml中進行如下設置，但無效
patch:
schema_list:
- {schema: jyut6ping3}
"translator/spelling_hints": 0
"menu/page_size": 7

**Comment by fun8e** [comment]
> 别修改 build 下的任何文件

已解決了，感謝！原來是優先級的問題，應該先創建一個jyut6ping3.custom.yaml，才可進行覆寫。
因爲jyut6ping3.custom.yaml > jyut6ping3.schema.yaml > default.custom.yaml
