### ISSUE TITLE
如何从字库里删除没用的字啊？

### ISSUE THREAD

**Issue by zYeoman** [rime/home#662]
比如这个 𨈖，是输入 din 出来的。不知道有多少人看到它看到的不是一个方框。。。

我发现了—— `Ctrl+Delete` 是可以删除候选字，但是只能删除联想的候选字，如果读音完全一致的话，是删除不了的：比如𠱞𪊗。

PS. 在google这个字的时候，发现我的chrome会变卡
PS2. 我用的是ibus-rime

**Comment by LEOYoon-Tsaw** [comment]
找到方案對應的dict.yaml，從中刪字，既刪，重新部署

**Comment by zYeoman** [comment]
感谢！
另外，发现Windows用的SimSun-ExtB会支持这些异体字。

**Comment by zYeoman** [comment]
> 找到方案對應的dict.yaml，從中刪字，既刪，重新部署

发现还有很多貌似是异形字？比如「𫔭」，和「开」是一起出现的，字频也用的「开」的。但是它既不是繁体字也不是简体字，SimSun-ExtB也不支持它，怎么把它删掉？

**Comment by LEOYoon-Tsaw** [comment]
修改opencc轉換表

**Comment by zYeoman** [comment]
咋修改？

另外像这个字「𫚥」，也没在字库里发现，感觉也和opencc无关。。。

**Comment by LEOYoon-Tsaw** [comment]
在你自己的rime用戶文件夾建一個opencc文件夾，把你鍾意的轉換表放進去，rime會優先使用這裡的
