### ISSUE TITLE
luna_pinyin.dict.yaml中多音字的权重（百分比%）的数据是怎么得到的？

### ISSUE THREAD

**Issue by ethanlinys** [rime/home#663]
如：
栖	qi	64.80%
栖	xi	35.20%

**Comment by lotem** [comment]
来自按字的不同注音统计字频的码表。

**Comment by ethanlinys** [comment]
> 来自按字的不同注音统计字频的码表。

你好，谢谢答复，这个码表哪里可以看到。

**Comment by lotem** [comment]
不记得。太久了。可能是这里面的某些：
https://github.com/rime/rime-luna-pinyin/blob/master/AUTHORS
