### ISSUE TITLE
默认配置下使用仓颉五代，无法打出 《第五代倉頡輸入法手冊》61页的案例

### ISSUE THREAD

**Issue by VimWei** [rime/home#664]
http://www.cbflabs.com/book/5cjbook/05.htm

![image](https://user-images.githubusercontent.com/25874852/101611839-f8208500-3a44-11eb-8b3d-e2720c88fbaa.png)

**Comment by VimWei** [comment]
P68 页的如下字也不行：

![image](https://user-images.githubusercontent.com/25874852/101628019-2a88ad00-3a5a-11eb-9dbd-b6fea9b54bcb.png)

**Comment by VimWei** [comment]
P83页的如下字也打不出来：

![image](https://user-images.githubusercontent.com/25874852/101636587-835e4280-3a66-11eb-8141-77e8abee666d.png)

**Comment by LEOYoon-Tsaw** [comment]
𫥞也許沒收吧，你查查碼表。⿰光遂Unicode無此字，不可能鍵得出。帶「重」的我不知道，從來不用這種碼。

**Comment by VimWei** [comment]
> 𫥞也許沒收吧，你查查碼表。⿰光遂Unicode無此字，不可能鍵得出。帶「重」的我不知道，從來不用這種碼。

是否意味着，只有码表（cangjie5.dict.yaml）里有的字才能打出？

**Comment by lotem** [comment]
是。
這是開源社區製作的碼表。
要還原官方的第五代倉頡輸入法必須配套使用倉頡系統。
