### ISSUE TITLE
如何定义多音字情形的词库，让仓颉和双拼共用？

### ISSUE THREAD

**Issue by VimWei** [rime/home#668]
目前，我同时使用仓颉和双拼方案，为了方便维护，使用如下方法让仓颉和双拼共用一套词库：首先是分别引用单字的仓颉码和拼音，然后其余词组等各类词库则共用（仅保留词条和权重，无仓颉码和拼音）。

但这会造成一个问题：多音字难以处理。比如“给予”，使用双拼时，RIME只认识“geiyu”，而不是正确的“jiyu”。

请教你们是如何处理类似的情形呢？

**Comment by lotem** [comment]
不要在一套詞庫裏混用不同的編碼。
