### ISSUE TITLE
English support for RIME?

### ISSUE THREAD

**Issue by hangon1234** [rime/home#669]
Do you have an English version of RIME? (or a plan?)
I need Changjie(倉頡輸入法) which can do 繁體->簡體 conversion.
I think Windows Changjie doesn't support this feature.
I am Korean who doesn't understand standard Mandarin, but I still need to use Changjie for Cantonese conversation.
(So I can't use MS Pinyin IME)
Thank you in advance.

**Comment by hangon1234** [comment]
Also, wish has the feature to permanently disable English input mode, so I don't have duplicated English mode in both Korean / Chinese keyboard...

**Comment by lotem** [comment]
I guess this is about UI localization.
When the project was started it was designed for Chinese only. Therefore, UI localization wasn't a planned feature initially.
https://github.com/rime/ibus-rime and https://github.com/rime/squirrel do have localized UI strings, while https://github.com/rime/weasel only has UI in traditional Chinese.
In fact text is not used much in the IME UI. I guess it's mostly in the installer, settings and app menu.

In IME logic, there are a few places that use hard-coded strings, I tried to avoid Chinese text as much as possible by using symbols instead, with exceptions like `全角/半角` etc.
More strings used in the IME are made configurable through YAML config, like this one for IME switcher
https://github.com/rime/rime-prelude/blob/master/default.yaml#L17
and labels for the IME states defined in the input schema:
https://github.com/rime/rime-cangjie/blob/master/cangjie5.schema.yaml#L17
These strings in YAML can be easily changed by user.

Likely, you can remove the `ascii_mode`switch to have a fixed "Chinese" input state.
https://github.com/rime/rime-cangjie/blob/master/cangjie5.schema.yaml#L18

 But currently you have to do these customizations as user. There is not a systematic plan to provide alternative configuration for localized UI language.

**Comment by hangon1234** [comment]
Hi, sorry for the late response. Maybe it's time for me to start to learn Pinyin/Mandarin.  😢

**Comment by lotem** [comment]
Actually there's not that much reading in the app UI.
The UI is minimal, you only need to know a handful of words in order to make the full use of it. The hardest part is to read the documentation in order to customize the IME if the default doesn't work for you.
