### ISSUE TITLE
请问“地球拼音”如何设置不提示拼音？

### ISSUE THREAD

**Issue by zaqzrh** [rime/home#67]
请问“地球拼音”terra_pinyin.schema.yaml中
translator/spelling_hints: 5  # ～字以内候选标注完整带调拼音
参数该为0，还是显示‘字’的拼音提示？？参数不是0-9吗？
如何改不提示拼音？
(注：把这句spelling_hints: 5删了，是不提示拼音的，不想删。)

**Comment by lotem** [comment]
設爲
```
translator:
  spelling_hints: 0
```
可以奏效。

**Comment by zaqzrh** [comment]
设为0，还是显示‘一个字’的拼音提示，我不想任何提示的

**Comment by zaqzrh** [comment]
设为0，还是显示单字’的拼音提示
原来是设置了：
reverse_lookup_filter
行了，谢了。
