### ISSUE TITLE
怎么在让权重在没输入完全时启用.

### ISSUE THREAD

**Issue by vvyoko** [rime/home#670]
我用的是五笔86字形
我也不知道具体名词
如下图所示
`没`在第一是因为词库里有
`没	im	344089771`
![1](https://user-images.githubusercontent.com/2145741/102419470-c312c480-403a-11eb-828b-45f8d4acf825.jpg)

排除这个不说,其他的不是按照权重排序,而是按照下一字符的字母排序的
假设没有上面的那个词库
而是
`没	imcy	441000000`
那么当输入 im 时
没(imc) 就会在 澧(ima) 和 湍的(imd) 的中间

怎么让这种情况按照权重排序呢?
```
没	imcy	441000000
油	img	167000000
沿	imk	62700000
澧	imau	2200000
```

假如按照权重排序(省略了其他字假设只有我说的这些字)
应该是
```
没
油
沿
澧
```

**Comment by vvyoko** [comment]
具体例子我也暂时找不出,只是偶尔觉得有些词不应该按在前面
仔细翻了一下才发现是因为没输入完全时是按字母排序的,所以导致这些词排在前面

PC上可以盲打还没察觉,手机上不能盲打经常要选字这个问题就特别突出了.
希望能够在没输入完全时按照权重排序.

**Comment by lotem** [comment]
目前還不支持這項功能。
因爲沒有對編碼前綴匹配的候選字單獨建立索引。如果要按權重排序，那麼輸入單個字符編碼時就需要取得佔整個詞庫1/25的詞條並對其排序。從性能出發，Rime目前的策略是只取出所需顯示的候選字，因此無法完成按權重排序。

**Comment by vvyoko** [comment]
在部署时排序有可行性吗?
就如这个例子,
没在前面是因为词库有
`没	im	344089771`
而它本身的码应该是
`没	imcy	441000000`
由于在事先在词库添加了排序输入 im 所以排在前面.

不在输入时排序,在部署时一次性对所有词进行排序.这样就用硬盘占用来换取输入时的排序性能.
比方说`油`
`油	img	167000000`
在部署时依次添加这些词库
```
油	i	167000000
油	im	167000000
油	img	167000000
油	imgg	167000000
```

在这种情况下部署硬盘占用极限也就增加到5-7倍吧
五笔是一个字母一个字母增加
拼音大概就是
```
你好 ni hao 1000
你好 ni 1000
你好 nh 1000
```

我不是程序员,所以也不知道这是否有可行性.

**Comment by vvyoko** [comment]
好像这个我自己能实现,我先去试试,不是程序员还得废得脑筋

**Comment by lotem** [comment]
五筆的碼表專門設有一級、二級、三級簡碼，大部分是全碼的前綴形式。
在特別設置的簡碼之外，採用直接在碼表裏添加冗餘編碼這種具體操作方式是不行的。
