### ISSUE TITLE
用户资料同步的“单向备份”具体机制是什么？

### ISSUE THREAD

**Issue by VimWei** [rime/home#671]
[https://github.com/rime/home/wiki/UserGuide#同步用戶資料](https://github.com/rime/home/wiki/UserGuide#同步用戶資料) 提到：“同步時，依次將各子文件夾中的詞典快照合併到用戶詞典，最後爲合併後的用戶詞典生成一份新的快照文件。 另外，還會**把用戶文件夾中非自動生成的 YAML 文件及 .txt 文件單向 備份 到同步文件夾**。”

困惑：
1. 假定同步文件夹内有A1 B1 C1
2. 在用户文件夹中，删除C1，并将A1更改为A2
3. 用户资料同步
4. 此时，同步文件夹内容为 A2 B1 C1，其中 C1 并没有删除。

这是正常的逻辑吗？目前我都要先将同步文件夹下的本机ID文件夹内容清空，然后再“用户资料同步”。

**Comment by lotem** [comment]
A1, B1, C1 等是什麼文件？
「将A1更改为A2」是什麼操作？
所謂備份就是留存一份文件的副本，以備用家查閱曾在其他地方用過的配置文件。

**Comment by VimWei** [comment]
A1、B1、C1指.dict.yaml或.custom.yaml

将A1更改为A2：指修订文件内容，生成不同不同于原有内容的版本。

**Comment by lotem** [comment]
沒有做刪除的操作。設計這個功能的時候考慮的是讓用戶的工作不丟失：
我發現用戶詞典以外的文件沒法支持同步時自動合併來自不同終端版本的文件內容，此外用戶也可能給不同終端做不同的配置，後續要利用這些備份時，少不了手動操作所需的文件。
於是爲達到備份文件的目標而簡單的實現爲複製符合條件的文件到本機的同步文件夾。如果現在來做的話，用git做個版本控制比較好。

**Comment by VimWei** [comment]
了解了，感谢！
