### ISSUE TITLE
"db_class: tabledb " 格式的用户词典能同步吗?

### ISSUE THREAD

**Issue by vvyoko** [rime/home#675]
我用的是 Windows 的小狼毫和 Android 的同文
基本配置是一样的.

我有需求要指定  `db_class:` 

一,可以清理一下不常用的

二,可以清理自造词,当时造词了,后面可能不需要了.

二,可以清理已经在本地词库中删除的词
这个可以解释下,本地词库中是指 `dict.yaml` 中的词库
然后只要你输入一次就会同步到 用户词库中(用来同步的那个)
即使你在 `dict.yaml` 中删除了, 用户词库中还是会存在,也可以输入.
所以需要手动在 用户词库.txt  中删除(我手动删除试过能行)

 `db_class: userdb`  格式会在用户文件夹创建一个包含二进制文件文件夹
暂时没找到进行上面操作的方法.
同步时会创建一个txt的文件用于同步,但是单纯修改这个文件是无效的,因为那个二进制文件夹还有存在原始文件.

综上,所以我选择了 `db_class: tabledb` 这个格式的用户词库
这个会在用户文件夹创建一个 指定文件名的txt 文件作为用户词库
可以很方便的进行上面的操作.

但是现在不能同步,不说双端,
只在一个平台也不行,
比方说我手动复制一下sync 里的同步文件夹并重命名为1
然后我删除用户文件夹和 sync 文件夹的用户词库
然后进行同步,按照逻辑会把1里的用户词库同步过来
但是完全没反应.
而以上操作在  `db_class: userdb`  是能正常同步的

所以我想问下 `db_class: tabledb` 是不能同步吗?

我知道有shift+del,但是不方便而且不能批量整理
而且既然有  `db_class: tabledb`  这个配置,要求下能同步也算正常需求吧.

**Comment by lotem** [comment]
完全由Rime處理的用戶詞典即`userdb`才能實現自動同步。
如果你選擇`tabledb`，並自己手動維護文本詞典的內容，那就只會在同步時備份詞典文件。該文件包含的信息不足以實現自動同步。
總結起來說，或者選擇自動同步，或者手動維護。兩者用不同的格式。你可以隨時將自動同步的詞典改爲手動維護，反之則沒有辦法在又想要自動同步的時候變回去，因爲已經丟失了部分只能由程序記錄的信息。
