### ISSUE TITLE
用 rime 制作日语输入法

### ISSUE THREAD

**Issue by BettyJJ** [rime/home#68]
作者你好～现在网上没有特别好用的日语输入法，看到 Rime 之后，就想利用它来自己做一个。从网上下了一个码表，现在已经做到勉强可用了。然而还想实现下面的效果，不知道 Rime 有没有办法能实现？

日语可以分成三种符号，平假名、片假名、汉字。平假名和片假名之间是一一对应的。假名和拉丁字母串之间也基本是一一对应的关系（有少数假名有多种拉丁转写法，但可以先忽略不计）。示例如下：

| 拉丁字符 | 平假名 | 片假名 |
| --- | --- | --- |
| a | あ | ア |
| i | い | イ |
| ka | か | ヵ |

所有的日语词都可以写成假名形式，其中一部分也可以写成汉字形式。

现在希望，输入一串拉丁字符后，用户能快捷选择是要打出平假名、片假名，还是汉字（如果存在）。

比如说，输入 aika，软件根据上面的表知道这能拆分成 a、i、ka 三部分，分别对应平假名的 あ、い、か，于是把 あいか 作为第一候选词。同理，把片假名的 アイヵ作为第二候选词。

同时，在这个例子中 aika 还对应汉字“哀歌”，那么就把“哀歌”作为第三候选词。有时，一串拉丁字符会对应多种汉字写法，那么就根据常用程度依次列出。有时，一串拉丁字符并不对应汉字写法，那么就不列出。

现在我设置的程度已经勉强可用，是在于码表里存在的词都可以打出来了，但是软件还不会自动把平假名片假名都列出来。

如下图所示，
![Uploading 20160407140358.png…]()

希望说清楚了。请问这种功能 Rime 能实现吗，要怎么做？谢谢～

我的 schema 文件可在这里看到：
https://gist.github.com/BettyJJ/7b4af0d24f2ed7dc6a91549e20f09f47

**Comment by lotem** [comment]
一些想法：

需要使用三個 script_translator 配備不同的詞典，分別提供純平假名（整句）、純片假名（整句）和全部詞彙（整句、詞組）的結果，前兩者設置較高優先級以固定爲前兩個候選。
做法樣例：
https://github.com/LEOYoon-Tsaw/Cangjie6/blob/master/cangjie6.schema.yaml#L56
https://github.com/LEOYoon-Tsaw/Cangjie6/blob/master/cangjie6.schema.yaml#L97
`initial_quality:` 設爲足夠大的數值（四位數以上），可保證不被調頻影響到。

之所以說第三個「全部詞彙」而不是「漢字詞」，是因爲要提供「漢字詞+助詞（平假名）」、「外來語詞（片假名）+助詞（平假名）」甚至包含多個成分的短語。所以前兩個詞典只要收錄所有音節的平假名、片假名形式，以供自由組合，而第三個詞典不僅要收錄漢字詞，還要儘量多收錄以平假名、片假名書寫的詞彙，配以恰當的詞頻。從 Mozc 等開源項目可以取得數據。

**Comment by xiaoqun2016** [comment]
日语中的平假名、片假名、汉字三者之间的关系，可否看成是汉语中的：简体字、繁体字、异体字？ 如果有这种对应关系，那可以试试用OpenCC来做，就依照简繁转换的做法，应该可以达到比较理想的效果。    
同时，也可以用快捷键切换平假名与片假名。还可以使平假名与片假名共用词频数据，  这对输入的流畅性大有帮助。

**Comment by BettyJJ** [comment]
感谢～
按照 @lotem 的方法试验，基本成功。
@xiaoqun2016 平假名、片假名、汉字三者之间的关系与汉语中的简体字、繁体字、异体字关系不太一样，平假名和片假名之间是严格一一对应的，假名与汉字的关系则是有可能一对零（没有汉字写法）、一对一、一对多（多种汉字写法）。并且大量的词汇是假名汉字混合书写的。不过你说的“用快捷键切换平假名与片假名，还可以使平假名与片假名共用词频数据”如果能做到会是很理想的效果～不知道日语这种情况是否可以用 OpenCC 来做。
@lotem 用 initial_quality 设置可以使假名固定在前两位，那么如果想让假名固定在第四位和第五位，有办法吗？

**Comment by xiaoqun2016** [comment]
@BettyJJ  假名汉字混合输写不是问题，怕的是平/片假名混合输写。用OpenCC做的话，虽然可以简化词库内容，也有一些独特的优势，但平/片假名不能混输。所以并不完美。也许可以找出一些规律再优化一下，但我不会日语，这里帮不上忙了。    

@lotem 懂日语，他的方法更切合实际。但你可能需要看看混合翻译器造词会不会有问题？

**Comment by lotem** [comment]
@BettyJJ 目前還不支持任意定位候選。
對於只提供平假名或片假名的詞典，我覺得沒有太大必要動態調整詞頻，因爲很多時候沒有重碼。擔心調頻反而會弄亂切分。比如 anan 應該切成 a'na'n 比較符合習慣？

平假名通過 OpenCC 轉換爲片假名可行，但是兩者也有不完全一一對應的地方，比如長音的記法：
遇到平假名書寫的 a'a, e'i, 或 o'u 有可能是長音，也有少數情況下是連在一起的兩個元音，對這兩種情況片假名記法是不同的。

**Comment by xzer** [comment]
@BettyJJ 你的方案能够共享出来吗？

**Comment by BettyJJ** [comment]
@xzer 首楼贴的 gist 就是。
不过后来我发现不用这么麻烦……用按词频排列的码表文件效果更好……
开始我用的码表没有词频，默认排在前面的都是一些不常用的汉字，所以想要能出假名，因为我主要需要输入日语的地方是查字典，全假名就可以查字典了。
后来改用了 Google 日语输入法对应的开源项目 morz 里的码表，常用的词汉字、假名形式都有，所以就不需要专门再搞一个假名码表了。

**Comment by ipcjs** [comment]
@BettyJJ  最终完成版的方案能不能共享下？

**Comment by xtay573269555** [comment]
找到一个 rime 的日语输入方案，https://github.com/biopolyhedron/rime-jap-poly

**Comment by Zilong-Li** [comment]
@BettyJJ 可以参考这个老外做的： https://github.com/gkovacs/rime-japanese

**Comment by snomiao** [comment]
rime-snomiao 方案分享

https://github.com/snomiao/rime-snomiao

目前自用，特点：

集成 五筆86+拼音，羅馬字（日語），英語単詞l混合輸入，経過中英+英日詞典翻訳，可切換 中日英+絵文字 輸出+反査

相信今後此类輸入法方案可以成為語言学習者的利器。
