### ISSUE TITLE
添加自用字典后，候选项出现了缺失情况

### ISSUE THREAD

**Issue by Core00077** [rime/home#681]
如题，我之前使用的是其他输入法，通过转换工具将原有的字典转换为`.yaml`格式的字典后，候选项有不同程度的缺失，具体看下图对比

引用自己的字典之前：
![image](https://user-images.githubusercontent.com/28624864/104150647-85287680-5415-11eb-9dd8-58dc1fac4e4e.png)

引用自己的字典之后：
![image](https://user-images.githubusercontent.com/28624864/104150636-7b067800-5415-11eb-9d9d-7db9a7359a14.png)

此时整个`ding`一共就**只有**4个选项可选且**无法翻页**。但字典确实被引入了进去，通过键入某些我常用的地名、人物名等均可验证。

例如：
![image](https://user-images.githubusercontent.com/28624864/104151084-016f8980-5417-11eb-815f-4809b3ca584e.png)

我的词典文本文件有5.4MB，大概有十年左右的累计数据，不知是否是由于某些数据导致词典被引入不全或是由于bug导致，以下列出我的词典中`ding`开头的词语以供参考。

希望可以解惑，不胜感激

```
定	ding	92
订	ding	30
顶	ding	75
顶啊	ding a	8
定案	ding an	1
定吧	ding ba	4
定宾馆	ding bin guan	2
顶部	ding bu	4
顶不住	ding bu zhu	7
顶层模块	ding ceng mo kuai	10
订单	ding dan	193
订单编号	ding dan bian hao	2
订单表	ding dan biao	4
订单查询	ding dan cha xun	3
订单池	ding dan chi	2
订单对	ding dan dui	2
订单号	ding dan hao	9
订单联系人	ding dan lian xi ren	2
订单列表	ding dan lie biao	6
订单系统	ding dan xi tong	6
订单详情	ding dan xiang qing	11
订单详情页	ding dan xiang qing ye	1
订单信息	ding dan xin xi	3
订单页面	ding dan ye mian	2
订单状态	ding dan zhuang tai	9
定的	ding de	7
订的	ding de	3
顶得住	ding de zhu	2
定点	ding dian	4
顶点	ding dian	13
顶顶顶	ding ding ding	2
定夺	ding duo	3
顶多	ding duo	50
顶多就是	ding duo jiu shi	2
顶多是	ding duo shi	5
定额	ding e	6
定额发票	ding e fa piao	2
定发展	ding fa zhan	2
定风波	ding feng bo	7
定稿	ding gao	4
定格	ding ge	4
订购	ding gou	3
订购了	ding gou le	2
丁光业	ding guang ye	3
定好	ding hao	5
订好	ding hao	3
订好了	ding hao le	2
顶会	ding hui	2
定级	ding ji	13
定积分	ding ji fen	4
顶级勾引	ding ji gou yin	1
定计划	ding ji hua	1
顶级赛	ding ji sai	4
定级赛	ding ji sai	13
定价	ding jia	6
顶尖	ding jian	6
定金	ding jin	2
定居了	ding ju le	1
定了	ding le	13
订了	ding le	6
订了计划	ding le ji hua	1
定理	ding li	5
顶楼不留人	ding lou bu liu ren	2
定论	ding lun	3
盯你	ding ni	2
顶你	ding ni	7
丁宁	ding ning	6
顶配	ding pei	1
订票	ding piao	19
定期	ding qi	9
顶起	ding qi	30
顶起来	ding qi lai	4
定上分	ding shang fen	1
盯上了	ding shang le	2
定身法	ding shen fa	2
定时	ding shi	12
定时间	ding shi jian	3
定时量体温	ding shi liang ti wen	2
定时祝福	ding shi zhu fu	2
定塔	ding ta	3
顶塔	ding ta	2
顶替	ding ti	2
定投	ding tou	4
定为	ding wei	2
定位	ding wei	27
定位电话	ding wei dian hua	3
顶我	ding wo	2
顶下	ding xia	2
定下来	ding xia lai	3
定向	ding xiang	1
定向移动	ding xiang yi dong	2
定心丸	ding xin wan	2
定压	ding ya	4
定义	ding yi	110
定义标准	ding yi biao zhun	2
定义的	ding yi de	5
顶一个	ding yi ge	6
定义函数	ding yi han shu	2
定义和谐	ding yi he xie	2
定义接口	ding yi jie kou	2
定义了	ding yi le	5
定义是	ding yi shi	3
定义使用	ding yi shi yong	2
定一下	ding yi xia	5
定义一个	ding yi yi ge	2
丁宇新	ding yu xin	2
订阅	ding yue	6
定在	ding zai	15
盯着	ding zhe	6
顶着	ding zhe	3
定着	ding zhe	1
顶着拆	ding zhe chai	1
盯着我	ding zhe wo	2
订正	ding zheng	13
定制	ding zhi	5
定制化	ding zhi hua	2
定住	ding zhu	4
顶住	ding zhu	7
定住了	ding zhu le	3
钉子	ding zi	4
顶嘴	ding zui	2
定做	ding zuo	4
```

**Comment by Core00077** [comment]
另外，目前我了解到的资料均为：将`其他源的词典`以`固有词典`的形式引入，但这个词典是我自己积累的词典数据，希望可以直接并入`用户词典`，但尚未查到该如何做，可否提供一些指引资料，再次感谢！

**Comment by Core00077** [comment]
不好意思打扰啦，第一个问题搞清楚了，是因为引入的时候仅引入了我自己的词库，把luna_pinyin的字库也覆盖了，现在没有问题啦。但是还是希望可以把其它源的词典导入到用户词典中，希望目前有资料可以查阅，感谢🙏🏻

**Comment by lotem** [comment]
https://github.com/rime/home/wiki/UserGuide#%E5%B0%8E%E5%85%A5%E5%85%B6%E4%BB%96%E4%BE%86%E6%BA%90%E7%9A%84%E7%A2%BC%E8%A1%A8

**Comment by Core00077** [comment]
我有看过文档，但是对于一些细节感觉依旧不太清晰，例如：
> 如此導出的文本碼表，可反向導入到指定的用戶詞典。

该如何反向导入到指定的`用户词典`呢？是否可以认为直接将我的`外部词典`粘贴到sync里的`*.userdb.txt`即可？

(使用平台为linux)

**Comment by Core00077** [comment]
当然，上述描述是基于以下前提：
> 如果你認定要將碼表導入已存在的用戶詞典，則要注意：
>
>- 碼表文件的格式是否 Rime 所要求的 UTF-8 (no BOM) 編碼
>- 文本行是否爲製表符分隔，至少有文字、編碼兩列，及一列可選的頻次
>- 文字的字形（繁、簡字）是否與源碼表一致
>- 編碼的形式是否源碼表中定義的標準形式

**Comment by lotem** [comment]
> 
> > 如此導出的文本碼表，可反向導入到指定的用戶詞典。
> 

這一處討論的是從Rime導出的文本碼表。
你的情況則不同，是來源於其他輸入法的碼表。因此務必保證格式以及拼音的拼寫與Rime一致。

該文檔提到怎樣導入到用戶詞典：
https://github.com/rime/home/wiki/UserGuide#%E7%94%A8%E6%88%B6%E8%A9%9E%E5%85%B8%E7%AE%A1%E7%90%86

**Comment by Core00077** [comment]
啊搞定了！！我之前其实有用过该工具，可是当时看错了命令行指令，少写了<dict_name>这一参数，仅指定了我的词典😂。

不好意思耽误大佬时间啦，再次感谢解惑🙏🏻，rime真的太好用啦！
