### ISSUE TITLE
ibus-rime 在ubuntu系统下的小鹤双拼添加"/"特殊字符不成功

### ISSUE THREAD

**Issue by YaoLiMuMu** [rime/home#682]
原来使用luna pinyin simp一直可以使用/dw, /sx等派生特殊符号, 现在使用小鹤双拼, 无法输入特殊字符
1. 使用目录下存在可用的symbols.yaml
2. double_pinyin_flypy.schema.yaml中添加了    recognizer/patterns/punct: "^/([A-Z|a-z]*|[0-9]|10)$"和import_preset: symbols
3. 布署完成后还是无法输入特殊字符
请帮忙查看下如何处理!!! 感激不尽

**Comment by Ace-Who** [comment]
1. `recognizer/patterns/punct: "^/([A-Z|a-z]*|[0-9]|10)$"` 是补丁（`*.custom.yaml`）的语法，不适用于原文件（`*.schema.yaml`）——如果添加的原文如此——需要更改写法。
1. `import_preset: symbols` 没问题，但要确保添加的位置在原文件的 `puncuator:` 节点下。
1. 确保缩进正确。

该配置也可采用另一方法实现，即在原文件根节点添加指令：

```yaml
__patch:
  - symbols:/patch?  # 要求 symbols.yaml 文件的 patch 节点未被更改或删除。
  - double_pinyin_flypy.custom:/patch?  # 没有这行则会因 `__patch` 指令的加入而忽略补丁文件。
```

**Comment by YaoLiMuMu** [comment]
感谢, 确实是 recognizer/patterns/punct: "^/([A-Z|a-z]*|[0-9]|10)$" 这个配置语句的问题
改为punct: "^/([A-Z|a-z]*|[0-9]|10)$" 就解决了
