### ISSUE TITLE
Are all RIME schemas based on qwerty layout?

### ISSUE THREAD

**Issue by ba11aStone** [rime/home#683]
When I switch to the `azerty` (french) layout, I can type in symbols more efficiently and simultaneously use the previous RIME schemas without having a headache.

I should have been happy, but I found that when I pressed `shift` to enter the temporary English mode, the layout was not consistent with my system settings, even the shortcut keybindings have changed back to `qwerty` style.

How can I make the layout of RIME follow the system settings?

Thx!

**Comment by lotem** [comment]
Rime doesn't implement keyboard layout.
The effective keyboard layout for Rime depends on how keyboard layouts are managed in the operating system.

**Comment by liangqi** [comment]
macOS Big Sur 11.6
Squirrel 0.15.2

ABC-Extended: [\';
Switch from ABC-Extended to Squirrel: 「、‘；

Norwegian: å@æø
Switch from Norwegian to Squirrel: å@æø

It works fine.
