### ISSUE TITLE
截屏软件截屏后做批注的时候，可以正常输入， 但是看不到悬浮窗。

### ISSUE THREAD

**Issue by yy306525121** [rime/home#688]
![image](https://user-images.githubusercontent.com/12985872/106284090-b3afa980-627d-11eb-9174-d3e3d71ed288.png)

**Comment by LEOYoon-Tsaw** [comment]
哪版Rime？哪個截屏？

**Comment by yy306525121** [comment]
鼠须管0.14.0      截图软件：ishot 1.7.7,    刚试了一下微信截图没问题。

**Comment by yy306525121** [comment]
> 哪版Rime？哪個截屏？
鼠须管0.14.0 截图软件：ishot 1.7.7, 刚试了一下微信截图没问题。

**Comment by LEOYoon-Tsaw** [comment]
沒用過ishot，系統截圖沒問題
