### ISSUE TITLE
Archlinux安装ibus-rime无法输出中文

### ISSUE THREAD

**Issue by LvLaoTou** [rime/home#690]
按照文档操作执行pacman -S ibus-rime发现无法输入中文，根据网上其他资料需要再安装ibus-qt，希望能看一下是什么问题
我需要这样安装才能输出中文：
sudo pacman -S ibus-rime
yay -S ibus-qt
环境信息：
OS: Manjaro 20.2.1 Nibia
Kernel: x86_64 Linux 5.10.7-3-MANJARO
Shell: zsh 5.8
DE: GNOME
输入法信息：
IBus 1.5.23
ibus-rime-1.4.0-2

**Comment by lotem** [comment]
不太懂。ibus-qt大概是用來支持ibus在Qt程序裏輸入的。跟ibus-rime沒有直接聯繫。先驗證一下iBus在所使用的系統、應用環境中能否正常工作。如果用其他iBus引擎表現一樣，就可以排除ibus-rime的問題。

**Comment by LvLaoTou** [comment]
> 不太懂。ibus-qt大概是用于支持ibus在Qt程序里输入的。跟ibus-rime没有直接联系。先验证一下iBus在所使用的系统，应用环境中能否正常工作。如果用其他iBus引擎表现一样，就可以排除ibus-rime的问题。

抱歉，我现在已经安装了ibus-qt，所以我没有当时的环境了，不能验证是否是ibus引擎的问题。如果说真的需要ibus-qt用于支持ibus在qt程序的输入，那咱们ibus-rime是否能够考虑添加该依赖呢或者在文档里面标注提醒一下和我一样的新人

**Comment by lotem** [comment]
> > 不太懂。ibus-qt大概是用于支持ibus在Qt程序里输入的。跟ibus-rime没有直接联系。先验证一下iBus在所使用的系统，应用环境中能否正常工作。如果用其他iBus引擎表现一样，就可以排除ibus-rime的问题。
> 
> 抱歉，我现在已经安装了ibus-qt，所以我没有当时的环境了，不能验证是否是ibus引擎的问题。如果说真的需要ibus-qt用于支持ibus在qt程序的输入，那咱们ibus-rime是否能够考虑添加该依赖呢或者在文档里面标注提醒一下和我一样的新人

​不能的。
ibus-rime與iBus的關係並不是前者依賴於後者而成爲一款獨立的輸入法軟件。他只是實現了iBus的接口、與其單方面通信的一個「iBus引擎」組件。與用戶和系統的交互是由iBus框架完成的，iBus引擎只負責爲iBus框架解釋輸入邏輯，完全隔離桌面系統和應用程序。簡而言之，用戶使用的不是ibus-rime輸入法，而是載有ibus-rime引擎的iBus輸入法。
故而ibus-qt與ibus-rime是完全沒有聯繫的。如果ibus-qt都不屬於ibus的必要依賴，那就更沒有理由成爲ibus-rime的依賴項。可以類比的是：不安裝中文字體，輸入法也無法使用，但不會將字體軟件包列爲輸入法的依賴項。
