### ISSUE TITLE
rime 输入时可能出现漏字情况

### ISSUE THREAD

**Issue by vcup** [rime/home#693]
输入法在正常打字的时候可能会出现输入 ri chu zhi cheng 的时候只出现 r hu zhi chen 的现象
而缺失的icg直接被输出到文本框中

输入法框架时fcitx5
系统为Arch Linux

**Comment by vcup** [comment]
https://user-images.githubusercontent.com/53596976/106709743-ea940f80-662f-11eb-98a1-12269ed47447.mp4

**Comment by lotem** [comment]
​這個問題得報給fcitx團隊。

**Comment by vcup** [comment]
> ​這個問題得報給fcitx團隊。

但事实上，我用同样运行在Fcitx5下的mozc就不会出现这样的问题

**Comment by lotem** [comment]
fcitx-rime 也由fcitx團隊維護。
類似問題常見的是與軟件的兼容問題。比如有腳本程序的輸入框。很可能在Rime處理之前時序已經有問題了。
如果有進一步的線索，比如發現是librime沒有正確處理fcitx傳過來的按鍵，可以再跟進。

**Comment by vcup** [comment]
这个问题确实是fcitx5的问题，今天mozc也出现了一样的问题，只是平时比较少用mozc，测试的样本太少
