### ISSUE TITLE
0.15.0 的”拼音輸入法詞典擴展包“ 该如何配置？

### ISSUE THREAD

**Issue by StayTherapy** [rime/home#696]
发现 Squirrel 更新了 `0.15.0` 🍻️，看更新日志写到 “支持顯示輸入方案自定義的候選序號 menu/alternative_select_labels”，高兴得赶紧升级，之前因为 0.14.0 release 版不支持 alternative_select_labels ，用的一直是 Squirrel-0.14.0+git118aee6 测试版。

另外还注意到一项更新 “**支持拼音輸入法詞典擴展包**”，但是我找了一圈没找到这个功能该怎么用？

目前自定义拼音字典是通过 `schame.dict.yaml` 的 `import_tables` 来导入自定义的字典，再结合 `custom_phrase.txt` 来使用。这次更新所说的 ”**词典扩展包**“ 难道是一种新的方式？

**Comment by lotem** [comment]
參考 https://github.com/rime/home/wiki/DictionaryPack

**Comment by StayTherapy** [comment]
> 參考 https://github.com/rime/home/wiki/DictionaryPack

原来如此，在此谢过~😁

**Comment by Johnleegy** [comment]
> 參考 https://github.com/rime/home/wiki/DictionaryPack
@lotem 这个功能很好啊，为什么现在失效了？小狼毫下部署时不会编译packs：下面的词典。
