### ISSUE TITLE
chaset_filter@gb2312 滤掉了「ⅰ ⅱ ⅲ ⅳ ⅴ ⅵ ⅶ ⅷ ⅸ ⅹ」

### ISSUE THREAD

**Issue by Ace-Who** [rime/home#698]
「ⅰ ⅱ ⅲ ⅳ ⅴ ⅵ ⅶ ⅷ ⅸ ⅹ」应该是 GB2312 字符。

**Comment by LEOYoon-Tsaw** [comment]
這個濾鏡是調用的boost的方法，不可能改的。

**Comment by lotem** [comment]
我當時就覺得不該通過加入過濾字符集功能的PR。
那些不必要的功能不支持嘛，這就是最好的。
可是小盆友們我看你們這樣熱情啊，我不合併也不妥。
現在用家都發現這個東西問題很多，卻沒人來維護。我怎麼辦？

**Comment by LEOYoon-Tsaw** [comment]
非要用過濾的讓他們折騰lua_filter吧

**Comment by Ace-Who** [comment]
这功能我自己也用不着，只是某时发现了，就加入了我分享的方案。如果确实是不可能解决的问题，这本身也是一个有用的信息，那目前只能先将就着用。用回 `translator/enable_charset_filter` 吧，它只支持 `table_translator`。`lua_filter` 虽然灵活，但是 lua 目前不是主要发行版的标配，而字符集影响到打字的条件反射，各发行版不统一支持的话，暂时不能考虑使用。

**Comment by lotem** [comment]
既然字符集有這麼重要的影響，那麼絕對應該爲打字的條件反射而優化碼表。
修改詞典就能實現精確的字符集控制，反而要用一個很大的詞典再做過濾，這不是多此一舉嗎？
特別是有人主張的「自定義字符集過濾」，有定義過濾字符集的功夫，完全可以直接把詞典改成所需要的字符集。

---

據我所知，GB2312只包含大寫羅馬數字，不包含小寫。
所以沒有錯。

**Comment by Ace-Who** [comment]
码表是一人维护，使用者是未知的，一张表省事儿。
我找到了 GB2312 未收录小写罗马数字的说法，不知道为什么有些资料与此矛盾，提供的字符表包含了小写罗马数字。
