### ISSUE TITLE
升级之后出现选词错误问题

### ISSUE THREAD

**Issue by xiaolinpg** [rime/home#703]
Mac OS Mojave系统，最近升级后：
问题一：输入法在中英文切换时不再能自动切换全角／半角
问题二：用数字选词的时候时常会选错词，数字和所选择的字词对不上位置，切换输入法也是如此

**Comment by xiaolinpg** [comment]
没认真看作业。问题同#513 ，并且采用 @grasonchan的配置文件已经解决

**Comment by lotem** [comment]
等等。
升級到那個版本出現的問題？
