### ISSUE TITLE
fcitx-rime 無法加入行列輸入法

### ISSUE THREAD

**Issue by jico67** [rime/home#704]
我已經有新增行列輸入法在清單裡面了
可是新增行列之後都是失敗的
下次在打開還是只有rime預設的那些輸入法

**Comment by lotem** [comment]
沒有理由不可以加入。
不知道您電腦上發生了什麼。
需要瞭解更多具體情況，比如已安裝的相關軟件包以及修改後的配置文件。

**Comment by jico67** [comment]
用終端開了fcitx-configtool
不曉得有沒有幫助 

(fcitx-config-gtk3:32533): GLib-GObject-CRITICAL **: 19:37:21.900: g_value_set_boxed: assertion 'G_VALUE_HOLDS_BOXED (value)' failed

(fcitx-config-gtk3:32533): Gtk-WARNING **: 19:37:21.930: Theme parsing error: gtk.css:3611:22: 'none' is not a valid color name

(fcitx-config-gtk3:32533): Gtk-WARNING **: 19:37:21.961: Failed to set text '第一個輸入法將作為非激活狀態。通常您需要將<b>鍵盤<b>或者<b>鍵盤 - <i>配置名稱</i></b>放到第一個。' from markup due to error parsing markup: 第 1 列第 151 個字發生錯誤：Element “markup” was closed, but the currently open element is “b”

** (fcitx-config-gtk3:507): WARNING **: 19:39:41.674: GDBus.Error:org.freedesktop.DBus.Error.UnknownMethod: Method "GetLayoutForIM" with signature "s" on interface "org.fcitx.Fcitx.Keyboard" doesn't exist

dde.dsvg: set cache file modified date time failed, error message: "Permission denied" , cache file: "/home/kek/.cache/deepin/icons/007fb604421098094470f081a68ff596b2d841bb.png" , svg file: "/usr/share/icons/bloom/actions/24/edit-clear-locationbar-rtl.svg"
dde.dsvg: set cache file modified date time failed, error message: "Permission denied" , cache file: "/home/kek/.cache/deepin/icons/007fb604421098094470f081a68ff596b2d841bb.png" , svg file: "/usr/share/icons/bloom/actions/24/edit-clear-locationbar-rtl.svg"
dde.dsvg: open cache file failed, error message: "Existing file /home/kek/.cache/deepin/icons/007fb604421098094470f081a68ff596b2d841bb.png is not writable" , cache file: "/home/kek/.cache/deepin/icons/007fb604421098094470f081a68ff596b2d841bb.png" , svg file: "/usr/share/icons/bloom/actions/24/edit-clear-locationbar-rtl.svg"
dde.dsvg: open cache file failed, error message: "Existing file /home/kek/.cache/deepin/icons/007fb604421098094470f081a68ff596b2d841bb.png is not writable" , cache file: "/home/kek/.cache/deepin/icons/007fb604421098094470f081a68ff596b2d841bb.png" , svg file: "/usr/share/icons/bloom/actions/24/edit-clear-locationbar-rtl.svg"
libpng error: Read Error
dde.dsvg: can't read the cache image: "/home/kek/.cache/deepin/icons/007fb604421098094470f081a68ff596b2d841bb.png" file size: 0 , permissions: QFlags(0x4|0x40|0x200|0x400|0x2000|0x4000)
dde.dsvg: set cache file modified date time failed, error message: "Permission denied" , cache file: "/home/kek/.cache/deepin/icons/007fb604421098094470f081a68ff596b2d841bb.png" , svg file: "/usr/share/icons/bloom/actions/24/edit-clear-locationbar-rtl.svg"

**Comment by lotem** [comment]
> 用終端開了fcitx-configtool
> 不曉得有沒有幫助

跟這個沒有關係。

分析問題需要知道您爲加入行列輸入法而對系統做過哪些具體的修改，比如額外安裝的軟件包以及修改的配置文件內容。

Rime的運行日誌位於 `/tmp/rime.*.INFO` 您也可以嘗試從日誌找到線索。

**Comment by jico67** [comment]
Log file created at: 2021/02/14 21:17:54
Running on machine: kek-PC
Log line format: [IWEF]mmdd hh:mm:ss.uuuuuu threadid file:line] msg
I0214 21:17:54.729406 32375 core_module.cc:20] registering core components.
I0214 21:17:54.729794 32375 registry.cc:14] registering component: config_builder
I0214 21:17:54.729809 32375 registry.cc:14] registering component: config
I0214 21:17:54.729815 32375 registry.cc:14] registering component: schema
I0214 21:17:54.729822 32375 registry.cc:14] registering component: user_config
I0214 21:17:54.729831 32375 dict_module.cc:25] registering components from module 'dict'.
I0214 21:17:54.729837 32375 registry.cc:14] registering component: tabledb
I0214 21:17:54.729843 32375 registry.cc:14] registering component: stabledb
I0214 21:17:54.729849 32375 registry.cc:14] registering component: plain_userdb
I0214 21:17:54.729856 32375 registry.cc:14] registering component: userdb
I0214 21:17:54.729862 32375 registry.cc:14] registering component: corrector
I0214 21:17:54.729871 32375 registry.cc:14] registering component: dictionary
I0214 21:17:54.729888 32375 registry.cc:14] registering component: reverse_lookup_dictionary
I0214 21:17:54.729897 32375 registry.cc:14] registering component: user_dictionary
I0214 21:17:54.729903 32375 registry.cc:14] registering component: userdb_recovery_task
I0214 21:17:54.729918 32375 gears_module.cc:43] registering components from module 'gears'.
I0214 21:17:54.729923 32375 registry.cc:14] registering component: ascii_composer
I0214 21:17:54.729929 32375 registry.cc:14] registering component: chord_composer
I0214 21:17:54.729936 32375 registry.cc:14] registering component: express_editor
I0214 21:17:54.729943 32375 registry.cc:14] registering component: fluid_editor
I0214 21:17:54.729950 32375 registry.cc:14] registering component: fluency_editor
I0214 21:17:54.729956 32375 registry.cc:14] registering component: key_binder
I0214 21:17:54.729962 32375 registry.cc:14] registering component: navigator
I0214 21:17:54.729969 32375 registry.cc:14] registering component: punctuator
I0214 21:17:54.729975 32375 registry.cc:14] registering component: recognizer
I0214 21:17:54.729981 32375 registry.cc:14] registering component: selector
I0214 21:17:54.730044 32375 registry.cc:14] registering component: speller
I0214 21:17:54.730055 32375 registry.cc:14] registering component: shape_processor
I0214 21:17:54.730062 32375 registry.cc:14] registering component: abc_segmentor
I0214 21:17:54.730075 32375 registry.cc:14] registering component: affix_segmentor
I0214 21:17:54.730083 32375 registry.cc:14] registering component: ascii_segmentor
I0214 21:17:54.730090 32375 registry.cc:14] registering component: matcher
I0214 21:17:54.730098 32375 registry.cc:14] registering component: punct_segmentor
I0214 21:17:54.730104 32375 registry.cc:14] registering component: fallback_segmentor
I0214 21:17:54.730110 32375 registry.cc:14] registering component: echo_translator
I0214 21:17:54.730116 32375 registry.cc:14] registering component: punct_translator
I0214 21:17:54.730123 32375 registry.cc:14] registering component: table_translator
I0214 21:17:54.730129 32375 registry.cc:14] registering component: script_translator
I0214 21:17:54.730135 32375 registry.cc:14] registering component: r10n_translator
I0214 21:17:54.730141 32375 registry.cc:14] registering component: reverse_lookup_translator
I0214 21:17:54.730147 32375 registry.cc:14] registering component: schema_list_translator
I0214 21:17:54.730154 32375 registry.cc:14] registering component: switch_translator
I0214 21:17:54.730160 32375 registry.cc:14] registering component: codepoint_translator
I0214 21:17:54.730167 32375 registry.cc:14] registering component: history_translator
I0214 21:17:54.730173 32375 registry.cc:14] registering component: simplifier
I0214 21:17:54.730178 32375 registry.cc:14] registering component: uniquifier
I0214 21:17:54.730185 32375 registry.cc:14] registering component: charset_filter
I0214 21:17:54.730191 32375 registry.cc:14] registering component: cjk_minifier
I0214 21:17:54.730198 32375 registry.cc:14] registering component: reverse_lookup_filter
I0214 21:17:54.730206 32375 registry.cc:14] registering component: single_char_filter
I0214 21:17:54.730211 32375 registry.cc:14] registering component: shape_formatter

**Comment by lotem** [comment]
分析問題需要知道您爲加入行列輸入法而對系統做過哪些具體的修改，比如額外安裝的軟件包以及修改的配置文件內容。

**Comment by jico67** [comment]
fcitx為系統原生，裝fcitx-rime後載了plum

$rime_frontend=fcitx-rime bash plum/rime-install array
Installing for Rime frontend: fcitx-rime
Updating package: array
Already up to date.
Installing: array30.dict.yaml
Installing: array30.schema.yaml
Updated ~ 2 files from 1 packages in '/home/kek/.config/fcitx/rime'

**Comment by jico67** [comment]
fcitx為系統原生，裝fcitx-rime後載plum

$ rime_frontend=fcitx-rime bash plum/rime-install array
Installing for Rime frontend: fcitx-rime
Downloading package: array 
Cloning into 'plum/package/rime/array'...
remote: Enumerating objects: 7, done.
remote: Counting objects: 100% (7/7), done.
remote: Compressing objects: 100% (7/7), done.
remote: Total 7 (delta 0), reused 5 (delta 0), pack-reused 0
Unpacking objects: 100% (7/7), done.

登出在登入，rime還是預設那8種輸入法

**Comment by lotem** [comment]
還需要把`array30`加入方案選單。
參考：
https://github.com/rime/home/wiki/CustomizationGuide#%E4%B8%80%E4%BE%8B%E5%AE%9A%E8%A3%BD%E6%96%B9%E6%A1%88%E9%81%B8%E5%96%AE
