### ISSUE TITLE
倉頡字碼錯誤----假

### ISSUE THREAD

**Issue by pk197197** [rime/home#724]
使用本輸入法時發現倉頡碼誤
放假的假正确碼為：人口卜水-----“卜”
而本輸入法中的倉頡碼為:人口尸水----“尸”

**Comment by LEOYoon-Tsaw** [comment]
證據

**Comment by pk197197** [comment]
![image](https://user-images.githubusercontent.com/61800471/108679421-78746380-7527-11eb-8298-1b7e1532badb.png)
**圖1 倉頡字典"假"的倉頡碼**
http://input.foruto.com/cjdict/45234.php

![image](https://user-images.githubusercontent.com/61800471/108679497-993cb900-7527-11eb-87d7-78d53d051013.png)
圖2 Apple內置倉頡"假"的倉頡碼

![image](https://user-images.githubusercontent.com/61800471/108679644-d30dbf80-7527-11eb-8c28-37735a37d31c.png)圖3 鼠鬚管倉頡輸入法輸入”人口卜水“時出現的字

![image](https://user-images.githubusercontent.com/61800471/108679794-018b9a80-7528-11eb-9db8-a1e350665d5d.png)
圖4 鼠鬚管倉頡輸入法輸入”人口尸水“時出現的”假“字

請問證據夠充分了嗎？

**Comment by pk197197** [comment]
![image](https://user-images.githubusercontent.com/61800471/108680079-62b36e00-7528-11eb-9509-b29157126df7.png)
圖5 yahoo！奇摩輸入法輸入“人口卜水“時出現的“假“字

![image](https://user-images.githubusercontent.com/61800471/108680217-8aa2d180-7528-11eb-9912-5f3ecf1637d3.png)
圖6 yahoo！奇摩輸入法輸入“人口尸水“時沒有出現假字

**Comment by LEOYoon-Tsaw** [comment]
iOS倉頡人口尸水、人口卜水皆可，可以加上人口卜水

**Comment by LEOYoon-Tsaw** [comment]
加上了

**Comment by lotem** [comment]
​不行啊，我們的方案是倉頡五代。不應該加三代的取碼。
