### ISSUE TITLE
ubuntu下用fcitx-rime设置字号？

### ISSUE THREAD

**Issue by yeqibin** [rime/home#73]
新建了一个weasel.custom.yaml
patch:
  "style/font_point": 18
重新部署后不起作用啊。

**Comment by osfans** [comment]
那是给小狼毫用的，肯定不起作用啦

**Comment by yeqibin** [comment]
不好意思，才知道linux下叫中州韵。把fcitx-sogou卸载后通过fcitx全局设置即可。

**Comment by mhohai** [comment]
@yeqibin 自觉关闭issue :8ball:
