### ISSUE TITLE
Linux上ibus-rime无法在chrome,Vscode上切换中文输入法

### ISSUE THREAD

**Issue by IammyselfYBX** [rime/home#730]
我安装chrome和Vscode以后发现无发使用中文输入法,找了一下说明文档https://github.com/rime/home/wiki/CustomizationGuide#%E5%9C%A8%E7%89%B9%E5%AE%9A%E7%A8%8B%E5%BA%8F%E8%A3%8F%E9%97%9C%E9%96%89%E4%B8%AD%E6%96%87%E8%BC%B8%E5%85%A5
不知道是不是这个问题

**Comment by IammyselfYBX** [comment]
目前只有Chrome和Vscode有这样的问题,其他程序都可以

**Comment by lotem** [comment]
需要調試iBus。
ibus-rime與應用程序沒有發生直接聯繫。

**Comment by IammyselfYBX** [comment]
你好，那想问一下调试```ibus-setup```中的选项那个是控制与应用程序交互的

**Comment by lotem** [comment]
> 你好，那想问一下调试`ibus-setup`中的选项那个是控制与应用程序交互的

據我所知沒有這樣的選項。

應該是兼容性問題，或者是沒有設置好iBus所需的環境變量。也可以添加其他ibus引擎驗證是不是iBus無法使用。
