### ISSUE TITLE
ibus-rime配色问题

### ISSUE THREAD

**Issue by IammyselfYBX** [rime/home#731]
根据https://github.com/rime/home/wiki/CustomizationGuide#%E4%B8%80%E4%BE%8B%E5%AE%9A%E8%A3%BD%E5%B0%8F%E7%8B%BC%E6%AF%AB%E9%85%8D%E8%89%B2%E6%96%B9%E6%A1%88在~/.config/ibus/rime中创建了weasel.custom.yaml文件并且执行 ```ibus-daemon -drx```之后没有任何效果，我看了一下luna_pinyin_simp.custom.yaml中想引入symbols.custom.yaml中的符号是```import_preset: symbols.custom```这句，想问一下是不是引入weasel.custom.yaml也需要添加一些应用呢？

**Comment by lotem** [comment]
小狼毫和ibus-rime是不同的軟件。
