### ISSUE TITLE
小狼毫和ibus-rime是不同的軟件。

### ISSUE THREAD

**Issue by IammyselfYBX** [rime/home#732]
小狼毫和ibus-rime是不同的軟件。

_Originally posted by @lotem in https://github.com/rime/home/issues/731#issuecomment-787000475_
那咱们的wiki该怎么该才能让小狼毫适用于ibus-rime呢

**Comment by lotem** [comment]
wiki不能讓。

除非刪掉所有小狼毫專有的內容，比如關於界面風格的設置等，之保留所有平臺都支持的部分，就能適用了。

**Comment by IammyselfYBX** [comment]
那就意味着ibus用户需要自己探索对吗？

**Comment by lotem** [comment]
不太明白你的疑問是什麼。
如果Wiki上寫明是小狼毫的配置項，那麼該功能及其配置只有小狼毫支持。

**Comment by IammyselfYBX** [comment]
对不起
我在https://github.com/rime/ibus-rime/wiki上买看到使用手册，就找到https://github.com/rime/home/wiki，发现里面的设置不起作用

**Comment by IammyselfYBX** [comment]
但是如果我想像小狼毫那样修改我的ibus-rime就没有说明wiki了对吗？

**Comment by lotem** [comment]
Wiki裏面沒有說明只適用於某一個平臺/輸入法前端項目的條目，屬於跨平臺的功能，可以在支持Rime輸入法的任意平臺上使用。
如果Wiki上寫明是小狼毫的配置項，那麼該功能及其配置只有小狼毫支持。
