### ISSUE TITLE
如何為Rime鎖定ABC鍵盤佈局

### ISSUE THREAD

**Issue by li-jingyun** [rime/home#734]
因為工作原因經常需要切換使用德語和英語鍵盤，但是用RIME時希望能一直鎖定英語的ABC鍵盤佈局而不是自動繼承德文鍵盤佈局。因為本身不會編程，我試了一下在squirrel.yaml文件和自定義文件裡添加了一行 us_keyboard_layout: true 但是也沒有用。請問有什麼好的解決方法嗎？

我用的是洋蔥版注音輸入法。

謝謝！！

**Comment by lotem** [comment]
洋蔥版注音輸入法不是Rime團隊發佈的軟件，我對他不太瞭解，請向該軟件的開發者諮詢。

**Comment by tsaihsing3** [comment]
不知道是不是这这今年的版本更新了，现在的 ´squirrel.yaml´下有一个配置
´keyboard_layout: default´ 亲测就是跟随系统设置(Mac的键盘设置同时选择 保持abc布局),可以锁住布局
