### ISSUE TITLE
Once input, but double output problem in telegram

### ISSUE THREAD

**Issue by laraws** [rime/home#736]
For example, when I input "nice" use rime, the output is "nicenice" in the Telegram. Please fix it, thanks.

![image](https://user-images.githubusercontent.com/40230381/109588286-72900b00-7b43-11eb-80a0-fb70d2f086e7.png)

![image](https://user-images.githubusercontent.com/40230381/109588373-96535100-7b43-11eb-9402-bdc96bcfc01f.png)

**Comment by lotem** [comment]
Ask Telegram to fix it.

See also
https://github.com/rime/squirrel/issues?q=is%3Aissue+telegram
https://github.com/rime/weasel/issues?q=is%3Aissue+telegram
