### ISSUE TITLE
請問怎樣使用其他粵語碼表？

### ISSUE THREAD

**Issue by adrianmak** [rime/home#74]
網絡上有多種粵語碼表，RIME跟來的粵語碼表與我平常使用的粵語拼音有少少差異。

請問怎樣可以代替原有的粵語碼表？

**Comment by ziloeng** [comment]
我的做法是新建一個schema.yaml文件，碼表共用原來的粵拼碼表。

1、把jyutping.schema.yaml另存一份，將文件名和文件內容schema_id:后的jyutping改成自己的方案名。
我的改成這樣：
schema:
  schema_id: yvtping
  name: "粵拼YP"

2、另外speller:  algebra:部分根據你的方案使用拼寫運算。
我的就添加這幾行：
    - "xform/yu/v/"
    - "xform/j/y/"
    - "derive/^yv/yu/"

xform --改寫〔不保留原形〕
derive --衍生〔保留原形〕
abbrev --簡拼〔出字優先級較上兩組更低〕
fuzz --畧拼〔此種簡拼僅組詞，不出單字〕
xlit --變換〔適合大量一對一變換〕
erase --刪除

3、之後translator也要改一下prism，指定拼寫運算棱鏡文件名。
translator:
#  dictionary: jyutping
  dictionary: &dict
    jyutping
  prism: yvtping

4、最後修改default.yaml：
schema_list:添加
  - schema: yvtping

5、重新部署，按選單選擇新添加的方案就可以了。

**Comment by Kahaani** [comment]
补充楼上的回答：brise中恰好有个例子，可以作为参考。

原有的码表采用了语言学会的粤拼方案：
https://github.com/rime/brise/blob/master/supplement/jyutping.dict.yaml
https://github.com/rime/brise/blob/master/supplement/jyutping.schema.yaml

新增的方案重用了原来的码表，在配置文件把粤拼转换成耶鲁方案：
https://github.com/rime/brise/blob/master/supplement/yale.schema.yaml
