### ISSUE TITLE
Squirrel上部分字符显示不正常

### ISSUE THREAD

**Issue by hammerfunctor** [rime/home#741]
如图：
<img width="79" alt="image" src="https://user-images.githubusercontent.com/65394269/110275885-eed79200-800c-11eb-998c-d05b417ae4a6.png">
`luna_pinyin`和`plum`原生配置的字体没有改动过。

感谢！

**Comment by LEOYoon-Tsaw** [comment]
字體問題，你可以加多幾個字體
