### ISSUE TITLE
最新版本bug，如果候选词由emoj，文本框的高度会不停的浮动

### ISSUE THREAD

**Issue by Vergegung** [rime/home#745]
型版本更新之后，字符框会随着emoj候选词的出现，而不停的改变，之前的版本就不会出现，希望能修复，非常感谢。

**Comment by lotem** [comment]
哪款輸入法軟件的哪個版本？

**Comment by Vergegung** [comment]
> 哪款輸入法軟件的哪個版本？

macos，鼠须管，最新的0.15.2

**Comment by lotem** [comment]
同 https://github.com/rime/squirrel/issues/543
