### ISSUE TITLE
添加辅助码之后的候选字排序似乎有 bug？

### ISSUE THREAD

**Issue by BettyJJ** [rime/home#750]
我构造了一个最简例子来展示这个疑似 bug，schema 和码表见 https://gist.github.com/BettyJJ/7a837441b80f485082102ef5ea2af7d7
示例码表中只包含读 tai 的字，给每个字拼音后面加上了辅助码，比如“太”成为 `tai;dd`

输入 tai，翻一两页，会看到很多生僻字排序很靠前

如果把码表中从分号开始的辅助码部分全都去掉，只保留全拼
重新部署后再输入 tai，翻一两页，可以看到前面都是常见字

因为是最简例子，所以没加任何拼写运算（也试过加各种拼写运算，对这个效果没影响）
码表中没有词频，是 `use_preset_vocabulary:	true` 导入了预设的 essay.txt，而 essay.txt 文件我没改过，点开看了，里面的词频都是正常的

我还试验过把所有字的辅助码都写成一样，比如都写成 `tai;pp`，这时输入 tai 就发现排序正常，跟只保留全拼效果一样

所以，看起来似乎是辅助码本身的码影响了排序
我还试过把一个辅助码是 dd 的字改成 zd，它在候选字里的顺序就从很前面跑到后面去了……

这是个 bug？还是什么隐藏机制？还是我哪里没配置对？
应如何解决？

**Comment by lotem** [comment]
​示例的方案代碼沒有定義拼寫運算規則。以編碼術的話語講，是沒有定義什麼是「主碼」。

因此沒有輸入完整編碼的時候，所有的候選字都是根據未完成的那部分編碼預測出來的，這類結果排序按照編碼的字典順序排列。
