### ISSUE TITLE
希望小狼毫可以针对五笔输入进行优化

### ISSUE THREAD

**Issue by baileichao** [rime/home#761]
希望小狼毫可以增加五笔输入时的设置支持，例如添加用户自造词的快捷键，重复上次输入内容的快捷键（其它输入是按z键），切换生僻字和常用字的快捷键（其它输入法用的是ctrl+m键），希望可以增加这些设置的界面，这样可以直接进行比较直观的设置，而不是通过在源文件设置。

**Comment by LEOYoon-Tsaw** [comment]
配置介面沒人做的

**Comment by lotem** [comment]
​其他輸入法都具備這些功能的話，我等再做一遍的意義是什麼呢？

**Comment by baileichao** [comment]
> ​其他輸入法都具備這些功能的話，我等再做一遍的意義是什麼呢？

小狼毫没有这些功能，作为五笔输入时用起来不顺手，而其它输入法有这个功能，为什么不借鉴一下把小狼毫的功能再丰富一下呢？

**Comment by lotem** [comment]
因爲要花工夫做，卻沒有解決新的問題。
其他輸入法已經有了，爲何不用呢？重複勞動的價值何在？

**Comment by baileichao** [comment]
> 因爲要花工夫做，卻沒有解決新的問題。
> 其他輸入法已經有了，爲何不用呢？重複勞動的價值何在？

别人的东西好，你另外做了一个类似的，没有别人的好，不能学习一下别人的，完善自己的？让自己的变得比别人的更好？行吧，理解不同，再讨论也没有什么意义。

**Comment by baileichao** [comment]
> 因爲要花工夫做，卻沒有解決新的問題。
> 其他輸入法已經有了，爲何不用呢？重複勞動的價值何在？

别人的东西好，你另外做了一个类似的，没有别人的好，不能学习一下别人的，完善自己的？让自己的变得比别人的更好？而且话说你是用五笔输入法的么？不是的话，你不理解我这建议很正常。行吧，理解不同，再讨论也没有什么意义。

**Comment by LEOYoon-Tsaw** [comment]
如果你覺得很有意義，歡迎你來做

**Comment by Ace-Who** [comment]
这位用户压根儿不了解 Rime 的基本功能，讨论确实没意义。
