### ISSUE TITLE
No such file or directory: "/usr/share/rime-data"

### ISSUE THREAD

**Issue by hongyi-zhao** [rime/home#772]
On Ubuntu 20.04, I compiled and installed the git master version of [librime](https://github.com/rime/librime) but failed to depoly it with the following error:

```
$ cat /tmp/rime.fcitx-rime.ERROR
Log file created at: 2021/04/21 13:13:47
Running on machine: apollo-Nuvo-8108GC-Series
Log line format: [IWEF]mmdd hh:mm:ss.uuuuuu threadid file:line] msg
E0421 13:13:47.180413  4620 deployment_tasks.cc:62] Error reading file information: boost::filesystem::canonical: No such file or directory: "/usr/share/rime-data"
```
Then I created a directory based on the "ERROR" log reported above, and rime can be successfully deployed:

`$ sudo mkdir /usr/share/rime-data`

But there is still nothing under the created directory:

```
$ ls -la /usr/share/rime-data
total 16
drwxr-xr-x   2 root root  4096 Apr 21 13:20 .
drwxr-xr-x 340 root root 12288 Apr 21 13:20 ..
```
I am confused, if rime deploy doesn't need this directory at all, why it can't be successfully deployed without this directory.

Regards,
HY

**Comment by lotem** [comment]
How do you define "success"?

To install dependencies automatically, use `sudo apt install fcitx-rime`

**Comment by hongyi-zhao** [comment]
> How do you define "success"?

IMHO, if I compile rime from scratch, it shouldn't bother other stuff installed from the distro's repo. But apparently, I'm wrong there due to that rime in itself depends on fcitx. 

> To install dependencies automatically, use sudo apt install fcitx-rime

Thanks. It seems that the following packages will be installed by the `sudo apt install fcitx-rime` command:
```
$ apt-file search -x ^/usr/share/rime-data | awk '{print $1}' |sort -u
librime-data:
librime-data-array30:
librime-data-bopomofo:
librime-data-cangjie5:
librime-data-combo-pinyin:
librime-data-double-pinyin:
librime-data-emoji:
librime-data-ipa-xsampa:
librime-data-jyutping:
librime-data-luna-pinyin:
librime-data-pinyin-simp:
librime-data-quick5:
librime-data-sampheng:
librime-data-scj6:
librime-data-soutzoe:
librime-data-stenotype:
librime-data-stroke:
librime-data-terra-pinyin:
librime-data-wubi:
librime-data-wugniu:
librime-data-zyenpheng:
```
Finally, the following files will be created:

```
$ ls -l /usr/share/rime-data 
total 9464
-rw-r--r-- 1 root root    5676 Dec 19  2019 bopomofo_express.schema.yaml
-rw-r--r-- 1 root root    5820 Dec 19  2019 bopomofo.schema.yaml
-rw-r--r-- 1 root root    5696 Dec 19  2019 bopomofo_tw.schema.yaml
drwxr-xr-x 2 root root    4096 Apr 29 13:20 build
-rw-r--r-- 1 root root  789090 Dec 19  2019 cangjie5.dict.yaml
-rw-r--r-- 1 root root    2532 Dec 19  2019 cangjie5_express.schema.yaml
-rw-r--r-- 1 root root    2429 Dec 19  2019 cangjie5.schema.yaml
-rw-r--r-- 1 root root    4863 Dec 19  2019 default.yaml
-rw-r--r-- 1 root root 3804188 Dec 19  2019 essay.txt
-rw-r--r-- 1 root root  890087 Dec 19  2019 luna_pinyin.dict.yaml
-rw-r--r-- 1 root root    2185 Dec 19  2019 luna_pinyin_fluency.schema.yaml
-rw-r--r-- 1 root root    2207 Dec 19  2019 luna_pinyin.schema.yaml
-rw-r--r-- 1 root root    1938 Dec 19  2019 luna_pinyin_simp.schema.yaml
-rw-r--r-- 1 root root    1849 Dec 19  2019 luna_pinyin_tw.schema.yaml
-rw-r--r-- 1 root root    1680 Dec 19  2019 luna_quanpin.schema.yaml
-rw-r--r-- 1 root root 2287038 Dec 19  2019 stroke.dict.yaml
-rw-r--r-- 1 root root    1529 Dec 19  2019 stroke.schema.yaml
-rw-r--r-- 1 root root   28975 Dec 19  2019 symbols.yaml
-rw-r--r-- 1 root root 1798690 Dec 19  2019 terra_pinyin.dict.yaml
-rw-r--r-- 1 root root    4361 Dec 19  2019 terra_pinyin.schema.yaml

```

**Comment by lotem** [comment]
No. Rime doesn't depend on fcitx.
librime itself is a library that implements input method logic. Users don't directly use libraries. The issue description didn't convey what you attempted to achieve by compiling librime yourself.
It is the data packages that are required for a typical user journey, and maybe a missing part of your expected success scenario.

**Comment by hongyi-zhao** [comment]
> It is the data packages that are required for a typical user journey, and maybe a missing part of your expected success scenario.

Thanks a lot for your clarification. What's the relationship between the data packages you mentioned above and the librime itself. BTW, can the data packages be generated by [plum](https://github.com/rime/plum)?

**Comment by lotem** [comment]
Your usage is okay.
For more details read the doc:
https://github.com/rime/home/wiki/Configuration#%E4%BD%8D%E7%BD%AE%E5%8F%8A%E7%B5%84%E7%B9%94%E6%96%B9%E5%BC%8F

**Comment by hongyi-zhao** [comment]
Based on the notes [here](https://github.com/rime/home/wiki/UserData), it seems that for fcitx-rime, the following location is preferred: `~/.config/fcitx/rime`, instead of the one I reported here, i.e., `$HOME/.local/share/fcitx5/rime`. Furthermore, If I remember correct, the former is a suggested user date path in the long run defined by the [XDG_Base_Directory specifications](https://wiki.archlinux.org/index.php/XDG_Base_Directory).
