### ISSUE TITLE
增加default.custom.yaml后 /输入symbols 的功能出不来

### ISSUE THREAD

**Issue by iheaing** [rime/home#773]
我在home对应目录里新增了 symbols.custom.yaml 文件，默认的 “朙月拼音” 下是正常的，能用 / 输入各种 symbols。

但我新建了default.custom.yaml 后，/ 输入 symbols 功能失效了，请教怎么办？

看了很多次官网文章和网上各种 howto 都没解决，请帮忙，感谢。

我的 default.custom.yaml 内容：
````
patch:
  "menu/page_size": 9

  schema_list:
    - schema: wubi86
    - schema: wubi_pinyin

**Comment by xaengceilbiths** [comment]
用旧版symbols.yaml会有这种问题。
需要加入recognizer/patterns/punct: '^/([0-9]0?|[A-Za-z]+)$'

**Comment by iheaing** [comment]
`
config_version: '1.4.1'

patch:
  punctuator/import_preset: symbols
  recognizer/patterns/punct: '^/([0-9]0?|[A-Za-z]+)$'`

symbols.yaml 是1.4.1 已经有这一行的啦。

**Comment by iheaing** [comment]
已解决。

把 ~/.config/ibus/rime/下的文件还原到默认的，只添加 symbols.custom.yaml 与 default.custom.yaml 即可。

问题是因为我把 https://github.com/junxxx/rime_wubi_pinyin 这个全一股脑地覆盖啦 .config/ibus/rime/
