### ISSUE TITLE
结构输入法 --- 发现了一个网站，不知道跟咱们是什么关系

### ISSUE THREAD

**Issue by boboIqiqi** [rime/home#78]
今天更新了一下腾讯的应用宝，然后就提示

> 结构输入法(同文) 有更新,请下载

我还以为是我们的输入法上线了，结果想找，却没找到。网上一搜，找到这个网站：
http://www.jiegoushurufa.icoc.cc/

感觉他们商业化做得挺好的，只是不知道跟我们是什么关系，里面还引用到@osfans 老大的输入法apk.

**Comment by jakwings** [comment]
只要沒違反源代碼的版權協議，怎麼樣都沒所謂吧。

* brise（東風破）是 GPLv3，非必需組件。
* librime（Rime引擎）是 3-clause BSD 還是 GPLv3？
* Trime（同文，必須用到 librime）是 Apache License 2.0，假如 librime 是 GPLv3，那就很有問題。

GPLv3 允許商業用途，但不允許不公開衍生作品的源代碼。

**Comment by jakwings** [comment]
以乎沒人注意到：librime 的主頁寫着 BSD 協議，而 Squirrel 的主頁寫着 librime 是 GPLv3。到底哪個對？

/cc @lotem

**Comment by twz915** [comment]
@jakwings librime 是输入法的内核（核心），squirrel 是使用此内核在 macOS 上的实现，属于不同的东西。

**Comment by eagleoflqj** [comment]
网站已经🈚️了
