### ISSUE TITLE
请问下我怎么设置z键为重复上次录入，以及其他键作为临时拼音的按键呢

### ISSUE THREAD

**Issue by NewChenJie** [rime/home#781]

**Comment by baileichao** [comment]
以五笔输入法为例，在wubi86.schema.yaml文件里面的engine下面的translators下面写入代码：
`  - history_translator@history`
然后在下面的path下面写入代码：
`history: #按Z键重复上次输入
  input: z
  size: 1 #重复前几次上屏，1就是1
  initial_quality: 10000 #重复上屏的字的权重`

但是这个时候你输入z键，并不是重复上次输入，因为z键依然是被临时拼音功能占用，将reverse_lookup下面的prefix:"z"中的改为其它引导键，例如zz。
重新部署，这样，z键就变成了重复上次输入，而接连输入两个z，就变成了临时拼音。

**Comment by NewChenJie** [comment]
感谢。
