### ISSUE TITLE
小狼毫在系统更新后出现明显的用户词典丢失现象

### ISSUE THREAD

**Issue by francis707** [rime/home#788]
我在5月4日更新了Windows 10系统20H2和其他一些系统补丁，之后出现了很明显的个人词典丢失的现象：
- 一些经常输入的很基本的词语也不再排在第一个候选项了，有的很常用的词语甚至要翻到第二页第三页才能找到。
- 用户文件夹出现了一个`luna_pinyin_simp.userdb.old`文件夹
  - 这个文件夹的修改日期显示的就是5月4日我更新系统的那段时间
  - 里面有个`lost`文件夹，修改日期显示的也是我更新系统的那段时间
- 我右键单击任务栏小狼毫图标，选择“用户资料同步”后，在用户文件夹出现了一个sync文件夹
  - 里面的`luna_pinyin_simp.userdb.txt` 到5/7才820多行，到今天(5/8)为止，也才1000多行，30多kb，而我安装小狼毫是在1月末
 
我的小狼毫安装路径：
- 程序文件夹：E盘（非系统盘）
- 用户文件夹：E盘（非系统盘）

好不容易积累了一段时间的用户词典，现在连输入常用的词语都要看一会甚至要翻页才能找到这个词语，真的有点打击积极性

请问如果出现这种情况有没有什么办法恢复，以及有什么办法能预防吗？

**Comment by lotem** [comment]
數據庫文件損壞了，且嘗試自動恢復失敗後，會重命名爲`*.old`。
google/leveldb 數據庫據說十分健壯，且有較強的數據恢復能力。文件損壞不常見。

假如是系統升級時的不穩定情況比如極短時間內反覆啓動服務導致當時無法正確讀取，可以在關閉輸入法算法服務後用`.old`備份數據庫替換新生成的數據庫，再次嘗試讓leveldb自動修復。
