### ISSUE TITLE
自定义短语的“候选位置”字段不生效

### ISSUE THREAD

**Issue by luochen1990** [rime/home#789]
当映射值是符号时，它总是被放在候选词的第一个，而不论 “候选位置” 字段的值。

示例配置 （custom_phase.txt) :

```
π	pi	9
```

期望效果:  输入 `pi` 后，第九个候选词为 `π`
实际效果:  输入 `pi` 后，第一个候选词为 `π`

**Comment by lotem** [comment]
不支持設置「候選位置」唷。
碼表第三列用來給重碼的候選字賦予權重，從大到小排序。

**Comment by luochen1990** [comment]
@lotem 谢谢回复, 那是我理解有偏差了, 不过还想再请教一下:

1. 这个 "权重" 要设置成多少比较合适呢?   这个值的语义是什么, 取值范围是 0~1 的小数, 还是自然数呢?
2. 有没有提供固定候选词位置的方式呢?
