### ISSUE TITLE
小狼毫可以通过命令行部署吗？- 附请教正确的调试流程

### ISSUE THREAD

**Issue by boboIqiqi** [rime/home#79]
小狼毫有没有命令行模式，这样可以方便调试。

比如，我用gVim 编辑完成源文件，可以直接在命令模式敲
`:!rime_deploy.bat`
然后就布署了。

主要是这样：

``` bat
:: rime_deploy.bat
copy weasel.yaml %appdata%\rime
copy weasel.custom.yaml %appdata%\rime
copy wubi86_double_key.schema.yaml %appdata%\rime

rem 希望有一个命令可以直接部署
pause
```

就是我希望每次修改的部署前，都将weasel.yaml覆盖回厂一下。这样就保证我之前的修改的错误不会累积。

下面我的理解：

> 重新布署，并没有生成中间文件来保存合并结果，而是直接在weasel.yaml上进行合并。这样，如果进行错误的修改，后面的补丁中没有覆盖掉，就会出现问题。所以，如果要生成一个可移植的weasel.custom.yaml。可以事先保存一份出厂的weasel.yaml，每次覆盖，再重新布署
> 而且还会出现这样的情况，比如，你前面某次修改对了，正确的设置已经添加到weasel.yaml中了。但是，你后来的custom.yaml中删除该设置，发现也能正常工作。但是，此时的状态，依赖于修改后的weasel.yaml。如果恢复出厂，就不行了

我说的有没有问题？
@xiaoqun2016  有请xiaoqun老师移步

**Comment by boboIqiqi** [comment]
再问一个小问题，ascii_mode: 0
也可以写作 ascii_mode: false
所有的表示布尔值的0/1 
都可以用true/false代替吗？

**Comment by xiaoqun2016** [comment]
可以使用安装文件夹下的weaseldeployer.exe  
具体是这样：  
部署 weaseldeployer /deploy
同步 weaseldeployer /sync
用户词典管理 weaseldeployer /dict

可以这样调试

**Comment by boboIqiqi** [comment]
@xiaoqun2016 
还有这个：
WeaselServer.exe /restart
如果没有托盘图标时可以用
还有别的吗？你怎么知道的呀

**Comment by xiaoqun2016** [comment]
开始菜单的程序文件夹里面有这些快捷方式。其它的我也不懂了。   
ascii_mode可以用true/false吗？

**Comment by lotem** [comment]
`WeaselDeployer.exe /deploy` 正解。

`ascii_mode` 哪裏有這個選項？是這裏嘛？
https://github.com/rime/weasel/blob/develop/output/data/weasel.yaml#L6
