### ISSUE TITLE
使用Control+space切换中英文，状态栏的输入法指示器会变成一个「X」(已禁用输入法)，而不是「A」

### ISSUE THREAD

**Issue by ziloeng** [rime/home#803]
使用Control+space切换中英文，状态栏的输入法指示器会变成一个「X」(已禁用输入法)；
再按一下Control+space，变成「中」；
再按一下Control+space，变成「X」；
......
鼠标点击「中」，是会变成「A」的，但再按Control+space，又会进入「X」「中」「X」「中」循环。

**Comment by lotem** [comment]
`​Control+space`是Windows系統啓用/禁用輸入法的快捷鍵。

**Comment by ziloeng** [comment]
但搜狗输入法用​Control+space可以实现「中」「英」切换，不会变成禁用输入法。
小狼毫是否可以参考下？

**Comment by lotem** [comment]
​暫時沒有實現。在其他工單裏有記錄。

**Comment by lotem** [comment]
另外，系統默認的行爲可能比切換輸入法內部的轉換狀態更有用。不同用家的看法不一致。

因此以往的討論沒有得出需要把啓用/禁用輸入法做成和狀態開關聯動的的結論。

**Comment by lotem** [comment]
​如果確實需要達到所述的效果，可以這樣設置：
1. 在Windows的高級輸入法設置裏關閉Control+space的快捷鍵；
2. 定義Rime快捷鍵：
```yaml
# 輸入方案.custom.yaml
patch:
  key_binder/bindings/+:
    - { when: always, accept: Control+space, toggle: ascii_mode }

**Comment by gdtv** [comment]
> ​如果確實需要達到所述的效果，可以這樣設置：
> 
>     1. 在Windows的高級輸入法設置裏關閉Control+space的快捷鍵；
> 
>     2. 定義Rime快捷鍵：
> 
> 
> ```yaml
> # 輸入方案.custom.yaml
> patch:
>   key_binder/bindings/+:
>     - { when: always, accept: Control+space, toggle: ascii_mode }
> ```



> 这个问题我刚刚解决了，这里的关键在于下面截图中的设置： 不是不勾选； 不是 Ctrl + 空格； 不是左 alt + Shift； 只有 Ctrl + Shift 才能正常切换。
> 
> ⬇️⬇️
> 
> ![微信截图_20220509222718](https://user-images.githubusercontent.com/7327187/167432258-66958e99-e76b-4f88-91ee-4d4286a95223.png)


谢谢大家，我的系统是windows11，输入法版本是0.16，按这两个方法（两个都要改）解决了。
有一个要注意的地方，修改后，重新部署小狼毫后，需要关闭原先打开的文字编辑软件，再打开才行。我原本用EmEditor测试，没有重启EmEditor，所以一直（好像有两三年时间）没有成功。
但还是有点问题，就是这样改了之后，其他输入法里不能按ctrl+空格切换中英文了。
