### ISSUE TITLE
英文版？？

### ISSUE THREAD

**Issue by KuroiRaku** [rime/home#812]
有可能製作英文版嗎？我覺得這個Engine很好！ 

我倒是可以幫忙翻譯

**Comment by LEOYoon-Tsaw** [comment]
甚麼英文版？現在支持英文。

**Comment by LEOYoon-Tsaw** [comment]
支持的吧。至少鼠鬚管是可以的，小狼毫不知道。

**Comment by KuroiRaku** [comment]
小狼毫目前沒英文版，好奇Rime 的開發者會不會做一個英文版。

**Comment by lotem** [comment]
​目前主要支持輸入中文。
英文跟中文的關係比較遠，基本不適用這套輸入框架，因此似乎沒有必要特意提供英文界面。

**Comment by KuroiRaku** [comment]
不是這麽説的，我認識到很多不會普通話的，可是會閩南語，廣東話，客家話等等。我認識的印度朋友，我外婆等等就是這類人。

如果他們不習慣漢子的話，可能還會做一個羅馬字的系統。

除此之外，這個軟件也很好用。我想很多外國人都會想著爲自己的語言創造自己的輸入法和字典。

**Comment by lotem** [comment]
對這部分使用者而言，輸入中文的障礙主要是中文讀寫能力吧。
本品界面文字絕少，本地化即使有幫助，也十分有限。
而且這類需求沒有統一的解決辦法，只能針對細分人羣的需要一一定製本地化的界面。
甚至常見軟件裏比較大衆的本地化語言如法文、英文等，本品的使用者中，母語是這些語言的屬於絕對少數。因此大多使用者用不到。
如果有相對集中的本地化需求，還得靠使用者社羣自己拾柴。項目組不能主力搞翻譯，成字幕組了。

**Comment by KuroiRaku** [comment]
都是看不懂漢字的人 ：）如果有英文的話，肯定能幫到他們。

而且這個軟件也非常有用。如果加了英文版，外國人也肯定開始利用的。

**Comment by KuroiRaku** [comment]
而且，少數也不代表他們不重要。。。如果能幫到就盡量幫，這個不是華人的傳統文化嗎？

**Comment by Ace-Who** [comment]
问题已经回答了。确实有需求的，使用者社群自发实现、自力更生，是最有效率的。这种需求的的实际情况，对于非当事人，多出于想象，基于想象的生产缺乏效率。
