### ISSUE TITLE
考虑到大陆访问 GitHub 不稳定，是否有计划在 Gitee 上传一份本项目的克隆

### ISSUE THREAD

**Issue by functoreality** [rime/home#815]
最近给新用户推荐了本项目的 wiki 作为入门资料，但得到的反馈是 GitHub 访问受限。鉴于 Rime 大陆用户较多，且 Gitee 访问不会受限，个人认为提供本项目的 Gitee 版本能够帮助新用户入门。

**Comment by lotem** [comment]
我做了一份鏡像 https://gitee.com/lotem/rime-home
