### ISSUE TITLE
86五笔 如何设置 第五键 自动上屏 首选词

### ISSUE THREAD

**Issue by gclintj** [rime/home#824]
默认设置是输完一个四键词，第五键输入的内容接在后面，而不上屏。
如何设置为输入第五键时，先把前面四键的首选结果上屏，并保留第五键的输入有效，可以继续输入？

**Comment by nb5p** [comment]
https://github.com/rime/squirrel/issues/174

**Comment by gclintj** [comment]
解决了，原来我的主要问题是，应该把配置文件放在Rime下而非build下，以及配置文件开头要加 `patch:` .

具体解决：
```
speller:
    max_code_length: 4 # 形碼最大碼長，超過則頂字上屛
```

https://github.com/LEOYoon-Tsaw/Rime_collections/blob/master/Rime_description.md#%E4%B8%80speller

**Comment by Ace-Who** [comment]
将 `speller/max_code_length` 设置为 `4`。
