### ISSUE TITLE
 小白求助，怎么把繁体输入法包含“強”的词汇全部替换为“强”？

### ISSUE THREAD

**Issue by ChexMauDu** [rime/home#825]
Rime的繁体输入法里默认“強”作为“强”的繁体，理由我大概能理解：《说文》里把“弘”当成“強”的声符，可惜这是错的——汉代以前的流行写法就是“强”。所以我现在想一次性把所有繁体输入中包含“強”的词汇中的“強”全部替换成“强”，有大佬知道可以怎么办吗？

**Comment by Ace-Who** [comment]
用文本编辑器打开码表，搜索、替换。

**Comment by LEOYoon-Tsaw** [comment]
用opencc

**Comment by bosconb** [comment]
Rime用OpenCC繁简转换，我记得作者说过OpenCC遵循的标准不是字源或者《说文解字》，对标的是学术上符合考据的传统字形。

事实上楼主的理解并不恰当。汉字部件「口」和「厶」在一直都是互通的，比如：「强」与「強」，「船」与「舩」，「员」与「贠」，「或」与「㦯」。从历代字形材料来看，「强」与「強」及更早的「彊」等，在过去的两千多年里一直是并存的。

[历代强字的拓本文字](http://coe21.zinbun.kyoto-u.ac.jp/djvuchar?query=%E5%BC%BA)

建国后，多选一将「強」留作异体，「强」作为正字，是出于字模印刷与简并构字的考虑，论正统的话，甲骨文、金文、楚简中的「彊」更古典工整。

**Comment by groverlynn** [comment]
opencc選擇香港繁體（zh-hk）

**Comment by groverlynn** [comment]
參考這裏https://tieba.baidu.com/p/1909252328?red_tag=1965747518，自定義一個簡到繁轉換。鑑於「强」其實是香港俗字，可以把「強」->「强」定義成繁到港的轉換

**Comment by Ace-Who** [comment]
这个需求只需修改码表，简繁转换是绕了两个弯子。因为所谓「Rime 的繁体输入法」，官方的繁体输入方案，本身就不是通过简繁转换过滤器实现的，而是码表本身就是繁体。

**Comment by LEOYoon-Tsaw** [comment]
> 这个需求只需修改码表，简繁转换是绕了两个弯子。因为所谓「Rime 的繁体输入法」，官方的繁体输入方案，本身就不是通过简繁转换过滤器实现的，而是码表本身就是繁体。

改碼表不行，essay裏的也得改。還是OpenCC方便。

**Comment by lotem** [comment]
孰正孰異，​每個人有特別的看法。
向大家提供的現成品，不能把所有異體字都組成詞，總得選取一個標準。RIME預設詞庫採取的標準是「[開放中文轉換](https://github.com/BYVoid/OpenCC)」。
不可避免，個性化的用字習慣要求完全個性化的詞庫。預設詞庫有預設的用字標準，因此不適用。

**Comment by Ace-Who** [comment]
> 
> 
> > 这个需求只需修改码表，简繁转换是绕了两个弯子。因为所谓「Rime 的繁体输入法」，官方的繁体输入方案，本身就不是通过简繁转换过滤器实现的，而是码表本身就是繁体。
> 
> 改碼表不行，essay裏的也得改。還是OpenCC方便。

这倒是。
