### ISSUE TITLE
无法在朙月拼音内输入“抬”

### ISSUE THREAD

**Issue by ImBearChild** [rime/home#831]
如题。在朙月拼音内只能输入“擡杠”而非“抬杠”或“抬槓”。鉴于“抬”是一个常用字，无法输入会造成不便。

维基百科将“擡”列为异体字，且无论香港繁体抑或台湾繁体，在维基百科均无“擡杠”，只有“抬槓”

[维基百科简繁转换一对多列表](https://zh.wikipedia.org/wiki/%E7%B0%A1%E7%B9%81%E8%BD%89%E6%8F%9B%E4%B8%80%E5%B0%8D%E5%A4%9A%E5%88%97%E8%A1%A8) 有如下内容：
抬⇄抬（擡-康熙）

同时[汉典](https://www.zdic.net/hans/%E6%8A%AC)也将“抬”作为现代简繁通行的字形，而把“擡”作为异体字。

**Comment by lotem** [comment]
上游數據源 OpenCC 已作出修改：
https://github.com/BYVoid/OpenCC/commit/eea8b785c9b2ed9f0cf220a0a40fa6df3f231496#diff-36c1b9078c643ef9b4206597a19b23acc85e25261a12dced63f5226c6bc0dceb

應同步修改到 rime-essay 等倉庫。

**Comment by Shinolr** [comment]
可以使用[rime-essay-simp](https://github.com/rime/rime-essay-simp)代替essay.txt

**Comment by gaochenyi** [comment]
我也遇到了这个问题，请问 Squirrel 0.15.2 应该如何打补丁呢？

**Comment by ImBearChild** [comment]
> 我也遇到了这个问题，请问 Squirrel 0.15.2 应该如何打补丁呢？

我目前的规避方案是在用户的词库里单独自定义一个“抬”字。

**Comment by lotem** [comment]
​更新 https://github.com/rime/rime-essay , https://github.com/rime/rime-luna-pinyin , https://github.com/rime/rime-terra-pinyin

**Comment by lotem** [comment]
已修正
