### ISSUE TITLE
小狼毫怎样外挂英语词库？

### ISSUE THREAD

**Issue by baileichao** [rime/home#842]
想请教一下，想打英语单词，现在有单词表，怎样把它挂接到输入法里面，我用的是五笔86版，想临时可能打英语，怎样外挂或者内置这个英语词库，并且在想用的时候，通过什么快捷键可以直接输出英语单词。

**Comment by roxine9** [comment]
Rime英文输入补靪（适用于所有输入方案）https://tieba.baidu.com/p/3679492448?red_tag=2241627200#
1o7Jd2NC 提取碼:8p57
我用了这个，可以英文输出

**Comment by iDvel** [comment]
我用的这个方案的方法 https://github.com/tumuyan/rime-pinyin-simp 这个已经有了几千个单词表
也可以参考一下我的 https://github.com/iDvel/rime-settings
就是将这个英文方案嵌入到自己的拼音或五笔方案中。
还有一个 easy_en 方案 https://github.com/BlindingDark/rime-easy-en
