### ISSUE TITLE
请问如何在MAC上设定自定义的自适应皮肤

### ISSUE THREAD

**Issue by TomatoFryEggs** [rime/home#844]
使用native后是输入法自带的样，请问如何替换成自定义样式。

**Comment by LEOYoon-Tsaw** [comment]
"style/color_scheme": solarized-light
  "style/color_scheme_dark": solarized-dark
如此分別設

**Comment by TomatoFryEggs** [comment]
> "style/color_scheme": solarized-light
> "style/color_scheme_dark": solarized-dark
> 如此分別設

感谢！
