### ISSUE TITLE
fcitx5+rime emoji cannot display

### ISSUE THREAD

**Issue by ytingone** [rime/home#861]
Enviroment: Debian11

`Noto Sans CJK` & `Noto Color Emoji` both installed.
`.config/fcitx5/conf/classicui.conf` set fonts to `Noto Sans CJK SC`

`librime-data-emoji` installed
![Screenshot_2021-08-19_15-55-13](https://user-images.githubusercontent.com/7035143/130030391-326b5210-4bc9-426b-9770-fb286c6b05d9.png)

**Comment by lotem** [comment]
不懂。楼主可以去fcitx打听打听。
