### ISSUE TITLE
候選框位置和實際輸入位置相隔太遠

### ISSUE THREAD

**Issue by desertstsung** [rime/home#862]
出現問題：中文候選框位置隨實際輸入位置變化，但是候選框和輸入位置相隔太遠。
類似問題：[#123(Open)](https://github.com/rime/home/issues/123) [#62(Open)](https://github.com/rime/home/issues/62)

OS：ArchLinux
內核：5.13.12-zen1-1-zen
桌面：GNOME 40.4.0
熒幕分辨率：2560*1600
縮放：200%（100%同樣出現問題）
顯示伺服器：Wayland幾乎所有應用都會出現問題；Xorg在Firefox91.0.1會出現，在其他GNOME應用時正常（如gnome-terminal和gedit等）
ibus：1.5.25
ibus-rime：ibus-rime-1.5.0-1

複現：
```zsh
yes | doas pacman -Rcns ibus{,-rime}
doas rm -rf /usr/share/ibus/
rm -rf ~/.config/ibus/
yes | doas pacman -Sc
yes | doas pacman -S ibus{,-rime}
reboot
```

截圖：
當顯示伺服器爲Wayland，縮放爲100%時，問題截圖：![Wayland-100%](https://user-images.githubusercontent.com/42174739/130386666-4c740d5c-89b0-4cf8-be56-d4b28fe77836.png)
當顯示伺服器爲Wayland，縮放爲200%時，問題截圖：![Wayland-200%-1](https://user-images.githubusercontent.com/42174739/130387189-4bce7983-5e8f-471a-ad53-2b19b383943d.png)![Wayland-200%-2](https://user-images.githubusercontent.com/42174739/130387195-70336364-d452-49e5-bc25-ff08059e69c5.png)
當顯示伺服器爲Xorg時，Firefox91.0.1界面截圖：![Xorg-200%](https://user-images.githubusercontent.com/42174739/130387288-4aa38496-4817-417a-9bd6-9ba0f494951c.png)

**Comment by desertstsung** [comment]
定位到了是ibus框架的问题，因为ibus-libpinyin也会有同样的问题

**Comment by ID2233** [comment]
你这个问题有解决吗？我的 ubuntu24 只有在使用 chrome 输入时会出现类似的问题，离的很远。ibus 是 1.5.29-2。
截图：

![Image](https://github.com/user-attachments/assets/4664f9b9-94fd-45a5-92b2-77bb95183783)
