### ISSUE TITLE
RIME Hangul/Hanja IME

### ISSUE THREAD

**Issue by zgw3kszo** [rime/home#864]
I've been trying to make an IME using RIME that can type Hangul and Hanja so that Korean Mixed Script is easier to write. The problem is that I would like the IME to input Hangul by default and not use the Space key as an entry key so that it functions like a normal Korean keyboard. That is to say, when I type, I want a list of Hanja to appear, but I only want to use the Enter/Return key and or number keys to select the Hanja to replace the Hangul. If those are not pressed, I'd like it to type Hangul only. I have some code that a friend made that allows for Hangul typing, but it has Hangul on the candidates list, which is not what I want. I've attached a video of how I want it to type and also the existing concept files I have. There is an almost perfect IME using the FCTIX framework on Linux but it is stuck in Linux and cannot be used anywhere else. I would like to make the same thing using RIME so that everyone can use it.

How the IME should work: https://www.youtube.com/watch?v=QIxKsXa0MnQ

[hanja.dict.yaml.txt](https://github.com/rime/home/files/7035886/hanja.dict.yaml.txt)
[hanja.schema.yaml.txt](https://github.com/rime/home/files/7035887/hanja.schema.yaml.txt)

**Comment by lotem** [comment]
```yaml
punctuator:
  use_space: true
  half_shape:
    ' ': ' '
```

that's how to make space commit space character.
`punctuator` must come before `selector` in `engine/processors`.

hangul must be the top candidate. what you've described makes the ime feature incomplete.
you didn't provide any means for user to select the Hangul, consider the user is typing:
`<hanja1><hangul2><hanja3>`
they select `<hanja1>` by pressing return key or number key, then there is no way to select `<hangul2>` before they can move forward to select the next hanja.
the only workaround would be pressing space after the hangul and BackSpace to delete the extra space.
a simple fix would be making the hangul the first candidate, so that Return key would commit the hangul.
the aforementionned space key setting also requires the hangul to be the top candidate so that it's committed by default before committing a space character.

**Comment by zgw3kszo** [comment]
Is there any way to forego having Hangul be a candidate at all? For example could I type 국 and not have to select anything or hit space to finish the character? In Korean IME's you enter enough characters to make a valid block and then upon the next letter press that would not fit in the block, the current one is finished and a new one is made. I would like it to work like that. Is that possible?

**Comment by zgw3kszo** [comment]
You can see how the line shows which block is being worked on. Typing this all the user is doing is pressing letter keys. There is no use of the Spacebar or Enter/Return to finalise the entry

https://user-images.githubusercontent.com/76275696/130548137-53d62557-393b-43a1-86c5-ea065e6ef4b0.mov

**Comment by lotem** [comment]
> Is there any way to forego having Hangul be a candidate at all? For example could I type 국 and not have to select anything or hit space to finish the character? In Korean IME's you enter enough characters to make a valid block and then upon the next letter press that would not fit in the block, the current one is finished and a new one is made. I would like it to work like that. Is that possible?

Yes. Rime well implement that feature. It's often adopted by shape-based Chinese IMEs.
But that way the left composing region is always the last syllable and as a result you may only convert the last syllable to hanja. That's exactly what every existing Korean IME can do.

Did you mention that you wished to use Rime to make Korean Mixed Script easier to write? The desired behaviour you described, in contrast, seem to be just working exactly like the existing Korean IMEs. Why do you need to RIME?

**Comment by zgw3kszo** [comment]
I'd like it to work like an existing Korean IME when inputting Hangul. But whilst it does that I would like there to be a constant candidate window looking to replace any Hangul with applicable Hanja, so if the user wants they can use the Enter/Return key or the numbers to select it. Currently for Korean IMEs it is incedibly bothersome to input Hanja. On Windows you must go through every Hangul block and select a Hanja from a list that isn't even sorted by use. E.g. to write 大韓民國 you would type 대 then select 大, 한 then select 韓, 민 then select 民, and 국 then select 國, and so on for every word you want Hanja for. On Mac this is a bit better as it allows you to do whole words. So you could type 대한민국 and then hit Alt+Return and a Hanja candidate list will be brought up that allows you to select 大韓民國 via Return for the first candidate, number keys, or you can use the arrows to select and then hit Return. This is okay but on Mac it only works in some programs, many it doesn't work at all. In Linux however, you can FCTIX which functions exactly how I want to make the RIME IME. So I'm looking to make a RIME Korean IME that functions like a normal Korean IME but has a constant Hanja candidate list to allow the user to input them if desired. Unlike Windows you wouldn't have to convert every block individually, and unlike Mac, because it is RIME, it would work everywhere on the computer and allow you to input the Hanja for any word you want at any time without pressing any extra keys.

**Comment by zgw3kszo** [comment]
In that first video I sent you can see how the FCTIX IME functions (https://www.youtube.com/watch?v=QIxKsXa0MnQ). It inputs Hangul like a standard Korean IME but when prompted via the Return key or numbers keys by the user it replaces the Hangul with Hanja.

**Comment by lotem** [comment]
> In that first video I sent you can see how the FCTIX IME functions (https://www.youtube.com/watch?v=QIxKsXa0MnQ). It inputs Hangul like a standard Korean IME but when prompted via the Return key or numbers keys by the user it replaces the Hangul with Hanja.

No, it isn't like the PC Korean IME.
Fcitx buffers all input (signified by underline) so that they can show hanja phrase candidates corresponding to the buffered input. Buffered input isn't finished - that's why the hangul syllables can be replaced with hanja.

You need to choose between the two conflicting features:
commit a hangul syllable automatically as you type,
or buffer input over multiple syllables for phrase level input.

With Rime you can achieve the same typing behaviour as in Fcitx IME.
Both give you hanguls as the default result, and hanja words as alterntives.
The only a difference is in how these results are displayed. What's the big deal?

**Comment by zgw3kszo** [comment]
Sorry for the miscommunication and confusion. I would want it to buffer input over multiple syllables for phrase level input like FCTIX. Would buffer input over multiple syllables for phrase level input make you select Hangul from the candidate list to input Hangul only? Or would it work like FCTIX and simply retain what is typed instead of replace the relevant Hangul with Hanja.

**Comment by zgw3kszo** [comment]
Or would programming it to buffer input over multiple syllables require there to be Hangul listed in the candidate list?

**Comment by zgw3kszo** [comment]
Also, how would code the IME to function like that?

**Comment by lotem** [comment]
Use two translators configured with separate dictionaries for Hangul and Hanja.
One given higher `initial_quality` for composing Hangul, the other for looking up Hanja word candidates.

Needs changes to the program to
  - discard partial match Hangul candidates, take only the first fullly match candidate;
  - hide the Hangul candidate from the list of candidates.

**Comment by zgw3kszo** [comment]
Changes to the program meaning changes to RIME itself, right?

**Comment by lotem** [comment]
You may fork the code and make changes, or implement its speical logic in a Rime plugin.

I don't anticipate such changes to happen in librime unless the feature meets broader needs than serving this single use case.

**Comment by zgw3kszo** [comment]
I sent you an email asking some questions about this, did you get it?

**Comment by lotem** [comment]
Oh, you did. I missed it.
I'm not interested in this topic, and will not follow up.
