### ISSUE TITLE
rime输入法，每次启动win7系统桌面都跳：停止工作！怎么办？

### ISSUE THREAD

**Issue by lylx12345** [rime/home#875]
我用rime输入法的五笔，
rime输入法，每次启动win7系统到桌面，都跳一个出错框，怎么办？

小狼毫算法服務

摘要
**已停止工作**

日期
‎2021-‎09-‎05 下午 10:22

状态
已发送报告

描述
错误的应用程序路径:	C:\Program Files (x86)\Rime\weasel-0.14.3\WeaselServer.exe

问题签名
问题事件名称:	BEX
应用程序名:	WeaselServer.exe
应用程序版本:	0.14.3.0
应用程序时间戳:	5d0e4f2f
故障模块名称:	StackHash_0a9e
故障模块版本:	0.0.0.0
故障模块时间戳:	00000000
异常偏移:	00000000
异常代码:	c0000005
异常数据:	00000008
OS 版本:	6.1.7601.2.1.0.256.1
区域设置 ID:	2052
其他信息 1:	0a9e
其他信息 2:	0a9e372d3b4ad19135b953a78882e789
其他信息 3:	0a9e
其他信息 4:	0a9e372d3b4ad19135b953a78882e789

---------------------------
要过一段时间（十分钟以上）重启输入法的服务就正常可以输入了，

**Comment by eagleoflqj** [comment]
小狼毫已不再支持Win 7
