### ISSUE TITLE
使用倉頡輸入法時如何不顯示詞組

### ISSUE THREAD

**Issue by HongTao628** [rime/home#88]
我只用倉頡打字，不打詞，每次輸入幾個字母後總有很多詞組作為備選很礙事，如何關閉此功能，謝謝。

**Comment by lotem** [comment]
刪除以下兩處代碼：
`cangjie5.dict.yaml` 文件頭部分 `use_preset_vocabulary: true` 這一句用來導入詞組並爲詞組編碼。
再者，方案文件中
https://github.com/rime/brise/blob/master/preset/cangjie5.schema.yaml#L64
`translator/enable_encoder: true` 開啓了自動造詞。

**Comment by 307587** [comment]
每次更新小狼毫就會覆蓋這兩份檔案，設定也隨之消失，想保留就要每次更新前人手備份，更新後又要人手編輯該行而不可整份檔案取代，免得連更新的內容也蓋掉（如更新了碼表），極爲不便，有無在更新小狼毫時自動保留這設定的方法？

**Comment by lotem** [comment]
> 有無在更新小狼毫時自動保留這設定的方法？

另寫一個方案文件
https://github.com/lotem/rime-sancang/blob/master/sancang_simp.schema.yaml#L55
和詞典文件
https://github.com/lotem/rime-sancang/blob/master/sancang_simp.dict.yaml#L14
以上配置供參考

**Comment by 307587** [comment]
…不太懂具體怎改，有無只改custom.yaml的簡單方法？

**Comment by lotem** [comment]
別挖墳吶……

要參考，可以參考原版

https://github.com/rime/rime-cangjie/blob/master/cangjie5_express.schema.yaml
