### ISSUE TITLE
Linux下与squirrel.custom.yaml 或 weasal.custom.yaml 相同功能的文件的文件名是什么？

### ISSUE THREAD

**Issue by meoow** [rime/home#883]
OS：Arch Linux
IM: fcitx5-rime

在 $HOME/.local/share/fcitx5/rime/ 路径下与mac下 squirrel.custom.yaml 或 windows下 weasal.custom.yaml 这两个文件相同功能的linux下的文件应该叫什么名字？
我试了rime.custom.yaml没有效果。

**Comment by lotem** [comment]
​那些是用來配置macOS和Windows上的輸入法前端程序的。fcitx-rime的前端應該就是fcitx，程序實現不一樣，沒有對應的。
