### ISSUE TITLE
Rime中文输入回车功能不一致

### ISSUE THREAD

**Issue by HiSDR** [rime/home#884]
中文输入（简体或繁体）时字母区的回车与数字区的回车功能不一致。
例如：
> 输入qq单击字母区回车，会直接输入qq两个字母。   
  
> 输入qq单击数字区回车，则会出现两种情况
1.在备忘录，提醒事项这些app中，qq字符会与候选字一同消失
2.在网址输入框，Alfred输入框中，qq字符会消失，候选字不会消失
- [ 此时单击空格默认直接输入候选字1对应的内容] 
- [ 此时单击任意候选字对应的数字则输入对应的候选字] 

- [ 此时继续输入字符则消失的qq字符会重新出现] 然后循环     “例如：”  后出现的情况。

**Comment by lotem** [comment]
受個人經歷所限，程序不支持數字鍵盤。
可以嘗試通過`key_binder`配置把數字鍵盤上的按鍵一一映射到主鍵盤區的對應按鍵。

**Comment by HiSDR** [comment]
> 受個人經歷所限，程序不支持數字鍵盤。
> 可以嘗試通過`key_binder`配置把數字鍵盤上的按鍵一一映射到主鍵盤區的對應按鍵。

正在研究，修改它参数，逻辑是否与其他个性配置补丁相同？例如：
patch 定義了一組「補靪」，以源文件中的設定爲基礎，寫入新的設定項、或以新的設定值取代現有設定項的值。
