### ISSUE TITLE
Rime中文状态下输入英文字符无法被识别被保存

### ISSUE THREAD

**Issue by HiSDR** [rime/home#885]
中文输入（简体或繁体）时，按住Shift+字母，快捷输入大写字母时无法被某些浏览器插件识别，导致提示保存成功但并未保存。
例如：
1. Chrome的插件，Video Speed Controller，在设置快捷键功能的时候。
2. 将默认的恢复默认速度为1的快捷键R修改为S。
3. 中文输入（简体或繁体）时，按住Shift+S输入后，保存，提示保存成功但并未保存。
4. 中文输入（简体或繁体）时，输入数字后，保存，提示保存成功有效。
5. 中文输入（简体或繁体）时，单击CapsLock，输入对应字母保存，提示保存成功有效。

**Comment by Ace-Who** [comment]
不应当在中文状态下进行这些操作。

**Comment by HiSDR** [comment]
> 不应当在中文状态下进行这些操作。

个人愚见：我认为中文状态下快捷输入英文字符应与英文状态下输入的字符保持一致且被其他应用识别保持一致。这样比较符合逻辑不是么？

**Comment by lotem** [comment]
​有沒有提交/上屏？`Shift+S`並不是一個常規意義上的組合鍵，而是切換到上檔/下檔字符。
如果文字還留在輸入法的輸入緩衝區，那很可能應用程序讀不到。

**Comment by HiSDR** [comment]
> ​有沒有提交/上屏？`Shift+S`並不是一個常規意義上的組合鍵，而是切換到上檔/下檔字符。
> 如果文字還留在輸入法的輸入緩衝區，那很可能應用程序讀不到。

我想您没有理解我的意思，我在精准的描述一边我的问题。
RIME中文（简繁）状态下
1. 直接输入f（候选字为中文），回车，默认输出小写f，提交/上屏后（有没有这一步，该Chrome插件快捷键修改框都可以读到），点击该插件的保存，此次操作失效，该f字符无法被保存。
2. 直接输入Shift+F（无候选字框）默认输出大写F，提交/上屏后（有没有这一步，该Chrome插件快捷键修改框都可以读到），点击该插件的保存，此次操作失效，该f字符无法被保存。
3. 单击Shift，将输入法切换为中文状态的英文输入（Rime为默认配置，无任何修改），无论输入f还是F（Shift+F）（无候选字框），无论是否提交/上屏该Chrome插件快捷键修改框都可以读到），点击该插件的保存，此次操作成功。
4. 单击Caps Lock，将输入法切换为中文状态的英文大写输入（Rime为默认配置，无任何修改），输入F（无候选字框），无论是否提交/上屏该Chrome插件快捷键修改框都可以读到），点击该插件的保存，此次操作成功。

- [ 综上所诉：中文状态下快捷输入英文字母与中文状态下切换到英文（shift或capslock），输出同一字符，对于某些app产生效果不同，这是我的问题。
- 当然它不是不能被解决，但我每次修改需要切换为英文，而不是在中文状态下快捷输入英文]

**Comment by lotem** [comment]
請分清按鍵和按鍵產生的文字是不同的。
如果应用要讀取按鍵（從你的描述推測是這樣），則不應使用輸入法。
应用需要捕捉到由鍵盤發出的按鍵消息而不是顯示了一樣的字在介面上。

**Comment by HiSDR** [comment]
我试了试苹果自带的输入法也是同样的问题，只要中文输入是快捷输入英文就不识别。应该是这个应用的逻辑不支持。
