### ISSUE TITLE
如何只让回车键代替空格键上屏, 空格键作为默认功能

### ISSUE THREAD

**Issue by hicaicai** [rime/home#888]
找了很久,试过了很多,但似乎没效果
用这个也没效果
fluid_editor
还有
punctuator/use_space: true
也不行
咋整滴

**Comment by hicaicai** [comment]
就是打一个空格出来，我用fluid_editor这个空格还是能上屏，只不过下面多了个下划线。

**Comment by lotem** [comment]
空格鍵的默認功能是在有候選詞時選擇當前高亮的候選，無候選詞時輸入法不做轉換，即由系統解釋爲空白字符。

不使用空格鍵選字在中文輸入法中比較少見，配置方法如：
https://github.com/rime/home/issues/864#issuecomment-904277336
