### ISSUE TITLE
在中文环境只能打出英文

### ISSUE THREAD

**Issue by TianSalt** [rime/home#892]
有时，在中文环境下无法输入中文，仍和在英文状态下一样。

**Comment by Humwq** [comment]
应该禁用了相关的服务。之前我用ASUS GPU TweakII进行游戏优化 就会禁用输入法的服务 导致切换了输入法不能打中文 
重启系统后 就好了  
不要使用一些优化

**Comment by Python-37** [comment]
檢查`小狼毫算法服務`是否在運行

**Comment by TianSalt** [comment]
https://github.com/rockbenben/rime-WeaselServer
