### ISSUE TITLE
在字典中引用多個文件

### ISSUE THREAD

**Issue by DaengGWokFook** [rime/home#90]
最簡單的例子：大陸普通話和臺灣國語發音幾乎相同，相同發音的字詞用共同的字典，個別發音有差異的字和用語分開用字典，有效地減少重碼和異地發音或用語之混淆。以上想法能實現嗎？

**Comment by lotem** [comment]
能。

**Comment by DaengGWokFook** [comment]
目前最新版小狼毫支持以上想法嗎？

**Comment by lotem** [comment]
支持用 `import_tables:` 加載其它外部碼表
https://github.com/LEOYoon-Tsaw/Rime_collections/blob/master/Rime_description.md#配置
https://github.com/rime-aca/dictionaries#增加自己的詞庫
