### ISSUE TITLE
拼音输入时词库联想的问题！

### ISSUE THREAD

**Issue by TCMobi** [rime/home#904]
请问佛振大人以及各位高手朋友，小狼毫是否有词库长词联想的方案呢？例如：
我想打“羌笛何须怨杨柳”时（词库有这个词！），输入:qiang di he xu，候选词中怎么才能显示这个完整的词呢？
现在只能打出完整的拼音或完整词的首字母才可以显示出来。
请各位朋友们帮助，小狼毫是我用过最简洁好用的输入法，这个问题如果能解决了，那这个输入框架真是太完美了！
请各位大神的帮忙！

**Comment by TCMobi** [comment]
[TCM.schema.txt](https://github.com/rime/home/files/7370738/TCM.schema.txt)

**Comment by TCMobi** [comment]
> 我也没招了，可能要你打一次，它才会提前
可能我的描述不够准确，比如：
我想输入“床前明月光”，词库码表种有这个词，当我拼写“chuang qian ming"的时候，候选词中能否列出”床前明月光“这个词可以选择。不用全部打完“chuang qian ming yue guang"这样的。不知道您可以理解吗？
有位朋友说，小狼毫的翻译器，有提示配匹后续条目的功能，不知道怎么开启，是哪条设置，您方便能根据https://github.com/rime/rime-luna-pinyin 这个朙月拼音的配置文件帮忙改下吗，真心的感谢您！

**Comment by TCMobi** [comment]
> > > enable_completion: true 这个你的方案用不上，换成spelling_hints: 9 试试
> > 
> > 
> > 非常感谢您的回复，我尝试了下，当输入qiang di he xu时，候选词中并没有提示“羌笛何须怨杨柳”这个词，而是每个候选词后面添加了拼音，还请您再帮忙看下，感谢您！
> 
> 我也没招了，可能要你打一次，它才会提前

可能我的描述不够准确，比如：
我想输入“床前明月光”，词库码表种有这个词，当我拼写“chuang qian ming"的时候，候选词中能否列出”床前明月光“这个词可以选择。不用全部打完“chuang qian ming yue guang"这样的。不知道您可以理解吗？
有位朋友说，小狼毫的翻译器，有提示配匹后续条目的功能，不知道怎么开启，是哪条设置，您方便能根据https://github.com/rime/rime-luna-pinyin 这个朙月拼音的配置文件帮忙改下吗，真心的感谢您！

**Comment by KeqiZeng** [comment]
> 

请问这个问题您最后是怎么解决的呢？

**Comment by KeqiZeng** [comment]
> > > > enable_completion: true 这个你的方案用不上，换成spelling_hints: 9 试试
> > > 
> > > 
> > > 非常感谢您的回复，我尝试了下，当输入qiang di he xu时，候选词中并没有提示“羌笛何须怨杨柳”这个词，而是每个候选词后面添加了拼音，还请您再帮忙看下，感谢您！
> > 
> > 
> > 我也没招了，可能要你打一次，它才会提前
> 
> 可能我的描述不够准确，比如： 我想输入“床前明月光”，词库码表种有这个词，当我拼写“chuang qian ming"的时候，候选词中能否列出”床前明月光“这个词可以选择。不用全部打完“chuang qian ming yue guang"这样的。不知道您可以理解吗？ 有位朋友说，小狼毫的翻译器，有提示配匹后续条目的功能，不知道怎么开启，是哪条设置，您方便能根据https://github.com/rime/rime-luna-pinyin 这个朙月拼音的配置文件帮忙改下吗，真心的感谢您！

请问这个问题您最后是怎么解决的呢？

**Comment by lotem** [comment]
没有做这个选项。目前还不能通过配置打开。

**Comment by zeng-y-l** [comment]
这一功能目前有了吗？我觉得很有用。

如果手动加上“chuang qian ming -> 床前明月光”的词，非常麻烦，而且我觉得不能保证仅在句末生效。

**Comment by siuze** [comment]
> 这一功能目前有了吗？我觉得很有用。
> 
> 如果手动加上“chuang qian ming -> 床前明月光”的词，非常麻烦，而且我觉得不能保证仅在句末生效。

如果你用的是windows小狼毫，可以试试我修改后的这个[librime](https://github.com/rime/home/files/14391843/rime.zip)，实现了打出四个音节及以上时候的长词联想。   
先退出小狼毫算法服务来解除文件占用，然后打开小狼毫的程序文件夹，替换掉原本的rime.dll文件，再开启小狼毫算法服务、重新部署。应该就可以了。    

原版官方的rime.dll文件记得备份，防止出了问题又要重装软件。  
如果是macos的话可以去[releases](https://github.com/siuze/librime/releases)找一找对应的编译版本

**Comment by eagleoflqj** [comment]
已支持长词联想

**Comment by zhengpd** [comment]
> 已支持长词联想

@eagleoflqj 哪个版本可以用？要加什么配置项吗？

**Comment by ksqsf** [comment]
@zhengpd 在 librime 1.11 引入。通过 `script_translator` 组件的 `enable_completion` 选项开关。
