### ISSUE TITLE
自定義增廣字庫

### ISSUE THREAD

**Issue by DaengGWokFook** [rime/home#91]
爲了輸入方便輸入，我想修改倉頡方案預設的常用與增廣字庫轉換，將部分增廣字庫裏的方言字變成常用字，還有部分方言字取代的常用字變爲增廣字。

**Comment by lotem** [comment]
字符集開關是根據 Unicode 內碼所處區塊做過濾的。
要自定義字符集，那麼就得寫一個詞典，包含這個字符集裏的字。從效率上來講，多查一個詞典做字符集過濾，不如直接做一個限定字符集的詞典效率高。
所以推薦做法是：分別做大字符集和限定字符集的方案，相互切換。

現有的這個限定字符集的選項，之所以做成選項，是因爲根據文字內碼做過濾不需要額外的數據字典，比分別做兩個詞典成本要低得多。

**Comment by camxcube** [comment]
我现在是用香港常用的仓颉输入法。

其实现在有其中一个增广字符"㗎"为香港日常用字，我想把它调整为常用字，可是试过特意将此字另外加入到cangjie5.dict.yaml，也没能成功打出这个字来，请问有办法解决吗？

现在为了不想重码那么严重，每次都要挺频繁的打开增广字符，真的挺烦的。

**Comment by hyaray** [comment]
如果用户可以自定义几个字符集（或其他概念），比如常用字，生僻字，内置词组，自定义词组等几类。
然后用switches 可以指定当前生效是哪几个字符集，这样就不需要用字典来判断了？这个不好实现吗？
