### ISSUE TITLE
建议增加英文单词的自动编码功能

### ISSUE THREAD

**Issue by iDvel** [rime/home#912]
例如中文的：
```
你好	ni hao
```
不用写后面的注音
```
你好
```
也可以打出来。 

---

像我的英文词库里都是这样的：
```
hello	hello
world	world
Database	Database
Java	Java
```
如果只写一个，需要特殊化处理的再自己注音，是不是就很方便了，看起来也很直观。

**Comment by lotem** [comment]
​主題中的需求沒有標準化的實現，取決於英文單詞如何編碼。
例如用原文字符串做編碼表，用對應的小寫形式做編碼表，還可以拆分爲單個字母做音節式編碼。
無論採用哪種編碼策略，都可以容易地用腳本程序做一次預處理生成Rime碼表，所以不必在標準不統一的局面下搞內置的自動編碼程序。
