### ISSUE TITLE
[BUG] Linux VScode终端 输入一次,打印两次.

### ISSUE THREAD

**Issue by spaceack** [rime/home#914]
![Peek 2021-11-02 15-53](https://user-images.githubusercontent.com/23256191/139807369-935cea35-983c-4f90-81f5-a5d2e890340d.gif)
系统环境 ubuntu20.04 

如图, 只有在VScode终端下有这个问题, 输入单个字符没问题. 两个及两个字符以上, 简体和繁体字都会打印两次. 
在系统自带终端及其它输入环境使用均正常.

但使用其它输入法在VScode终端没问题.

不知到问题出在哪里?要如何排查?

**Comment by Python-37** [comment]
我更倾向于是VSCode 终端自己的问题，VSCode 终端出问题不是第一次了。

**Comment by WayneTian-42** [comment]
我也遇到了这个问题，请问怎么解决呢

**Comment by ydyvip** [comment]
换了fcitx5也还是一样，有没有人知道怎么解决

**Comment by GZGavinZhao** [comment]
VS Code 1.65.2 c722ca6c7eed3d7987c0d5c3df5c45f6b15e77d1 x64版本搭配nodejs v16.14.0无问题，用的是ibus-rime。

操作系统为Solus 4.3。

**Comment by lotem** [comment]
那就需要vscode修復這個問題了。輸入法沒轍。
