### ISSUE TITLE
當mac更新到mac版本12.0.1無法使用rime

### ISSUE THREAD

**Issue by na0930** [rime/home#916]
打擾了大家
請問安裝後在輸入方式並未顯示鼠鬚管輸入法
且重新安裝也無法
不知道是否是新版本系統上有不支援的地方
右上角的切換輸入法沒有，cmd+space切換也沒有，重新打開輸入方式裡面鼠鬚管的標籤就消失了
只能等新版本出現嗎？

**Comment by LEOYoon-Tsaw** [comment]
已有thread討論：https://github.com/rime/squirrel/issues/590

**Comment by Dreamer57** [comment]
在键盘设置里先把鼠须管移除，然后再添加进来。
