### ISSUE TITLE
如何改变并击判定时间

### ISSUE THREAD

**Issue by longhjues** [rime/home#920]
我想要实现一款并击输入中文，单击输入英文的输入法。在输入英文够慢时，可以实现单字上屏，但是很多时候输入英文并没有实际的 **完全** 抬起，即被并击捕获了。

是否能够配置并击输入时长，比如从第一个按键开始算起的0.2s内，超过哪怕还有按键没有松开也算已经并击结束。

**Comment by lotem** [comment]
鼠鬚管就是用時間窗口實現的，因爲沒有從系統收到按鍵擡起的事件。

這兩種輸入方式從按鍵序列無法嚴格區分。
連續擊鍵只須保證按下的順序正確，而擡起的時間序列是任意的。速度一快，必然會有同時處於按下狀態的按鍵，或落入並擊時間窗口內的連續按下動作，從而與並擊混淆。

**Comment by longhjues** [comment]
根据其他issue的描述，鼠鬚管是按照最后一个按下的键开始算时间。
为了能不影响“单击”输入英文，希望配置从第一个按键开始计时的并击时长。
另外如果考虑实现的话，最好能做成通用的，不依赖于具体特定实现的。

**Comment by lotem** [comment]
我覺得你還不理解問題的實質。
建議你實際記錄並觀察並擊和快速連擊的按鍵序列，看看能否從數據上區分。

鼠鬚管並不處理按鍵鬆開的事件，因爲系統沒給。因此和你擔心的按鍵是否及時抬起沒有關係。
快速連擊也同樣不看何時抬鍵，兩者都只看觸發事件。

問題的關鍵在於快速連擊允許後鍵落下遠遠早於前鍵彈起的最短時間，即連擊觸發的間隔小於完成並擊的最短時間。而兩鍵觸發行程大部分重疊，形如並擊。

**Comment by lotem** [comment]
具體實例，鼠鬚管默認設置的並擊時間是0.1秒。熟練使用者實際按下所有並擊按鍵的時間都遠小於0.1秒，從而不會發生識別成兩次並擊的情況。而在並擊模式下連擊字母鍵，非常容易識別爲並擊，說明盲打熟練者會在0.1秒內擊出兩鍵以上。
無論設什麼時長，你要保證連擊中的每兩個按鍵間隔大於此數值，同時保證並擊中所有按鍵按下的時間小於此數值，這不是矛盾嗎？能在快速連擊兩鍵的間隔時間內絕對完成一次並擊？那只能慢慢敲才能保證。

**Comment by longhjues** [comment]
以下是我的理解，以鼠鬚管并击间隔0.1s计：
![image](https://user-images.githubusercontent.com/28733238/143152880-c3cf3a98-609d-4783-9a34-172a444af038.png)

并击会将键入重新排序，因此即使分析出某段属于连击也会导致无法上屏。
我估计0.1s的并击间隔时间应该是足够应付绝大多数情况了，仅有少数频繁且简短的英文（如if）会识别成并击，从数据上区分下估计也能成功（以第一个按键计时，避免后续按键也加入并击）。

经过一翻锻炼，应该可以降低并击时长，压缩判定时间以大于绝大多数连击间隔。

我使用的是windows下的小狼毫，所以无法实际体验0.1秒的情况（未找到对应设置）。并且小狼毫是以松开来计算并击的，请问能够配置吗？另外期望能做到从输入法角度配置并击时长和计算方式，以期可以方便跨平台和分享。
