### ISSUE TITLE
rime_candidate_copy 内存泄漏

### ISSUE THREAD

**Issue by jimmy54** [rime/home#94]
//candidate
    RimeCandidateListIterator ite;
    bool res = RimeCandidateListBegin(sessionId, &ite);
    if (res == false) {
        return nil;
    }
    
    NSMutableArray *candidates = [NSMutableArray new];
    
    NSString *s = nil;
    while (RimeCandidateListNext(&ite)) {
        

        s = [NSString stringWithUTF8String:ite.candidate.text];
        [candidates addObject:s];
    }
    
    RimeCandidateListEnd(&ite);

使用下面函数，会导致内存泄漏。具体在.rime_candidate_copy函数

static void rime_candidate_copy(RimeCandidate* dest, const an<Candidate>& src) {
  dest->text = new char[src->text().length() + 1];（传出值后这里没有释放）
  std::strcpy(dest->text, src->text().c_str());
  string comment(src->comment());
  if (!comment.empty()) {
    dest->comment = new char[comment.length() + 1];
    std::strcpy(dest->comment, comment.c_str());
  }
  else {
    dest->comment = nullptr;
  }
  dest->reserved = nullptr;
}

[图片](http://i1.piimg.com/567571/6cddb1a1557081e8.png)

**Comment by lotem** [comment]
謝謝。已修復。

**Comment by jimmy54** [comment]
速度很快阿

**Comment by jimmy54** [comment]
经测试，泄漏解决了。
