### ISSUE TITLE
请问rime有基于web的界面吗？

### ISSUE THREAD

**Issue by zjiekai** [rime/home#95]
苦于找不到运行在本机的基于web的中文输入法，但是又找不到什么讨论中文输入法的论坛。特来宝地求教。

**Comment by lotem** [comment]
Google Input Tools (Chrome extension)

**Comment by zjiekai** [comment]
谢谢推荐~
google input tools好像还是开源的?
我主要是想后端运行在本地，用google input tools实在慢得有点痛苦

**Comment by lotem** [comment]
Chrome 擴展就是在本地運行的。

**Comment by zjiekai** [comment]
这样啊，难道是性能有问题？原来chrome插件还可以是c++写的啊。
