### ISSUE TITLE
求助 ！双拼怎么把i定义成z呢

### ISSUE THREAD

**Issue by icydgx** [rime/home#96]
下面是我的配置  
  - erase/^xx$/             # 碼表中有幾個拼音不明的字，編碼成xx了，消滅他
    - derive/^([jqxy])u$/$1v/ # ju jv都是可以的
    - xform/^([aoe].*)$/U$1/  # 添上固定的零聲母U
    - xform/^zh/E/           # 替換聲母鍵，用大寫以防與原有的字母混淆
    - xform/^ch/A/
    - xform/^sh|uo$/O/
    - xform/^z/i/                 #    输入 iu ia is 等出不来字
    - xform/ei$/Y/            # 替換韻母鍵
    - xform/v$/Y/
    - xform/ian$/B/
    - xform/[iu]ang$/L/
    - xform/iu$/W/
    - xform/er$/U/
    - xform/ang$/P/
    - xform/in$/M/
    - xform/ua$/F/
    - xform/uan$/G/
    - xform/i?ong$/H/
    - xform/[iu]a$/F/
    - xform/en$/N/
    - xform/eng$/R/
    - xform/an$/S/
    - xform/iao$/Q/
    - xform/ao$/C/
    - xform/ing$|uai$/D/
    - xform/ai$/T/
    - xform/ie$/X/
    - xform/ou$/K/
    - xform/un$/J/
    - xform/ui$/V/
    - xform/[uv]e$/Z/
    - xlit/QWERTYUOPASDFGHJKLZXCVBNM/qwertyuopasdfghjklzxcvbnm/  # 最後把雙拼碼全部變小寫

**Comment by lotem** [comment]
输入 `iu ia is` 等出不来字，因爲這些音節最終被變換爲 `w f b`

**Comment by icydgx** [comment]
解决了 。谢谢
