### ISSUE TITLE
Rime文件夹下更改custom文件部署无效

### ISSUE THREAD

**Issue by debeetle** [rime/home#961]
macbook air m1
用户Rime文件夹下更改custom部署无效，必须到Library/Input Methods/Squirrel.app/Contents/SharedSupport下直接更改原文件，甚至此时有时custom也无效，部署后同步到Rime文件夹下会有几率生效

**Comment by lotem** [comment]
沒聽說過這個事。我自己天天用的好使着呢，只是沒有macbook air。如果送我一臺，可以幫你測試測試。

**Comment by mokapsing** [comment]
从来没遇到过 不如把你的custom文件贴上来看看
