### ISSUE TITLE
ui为繁体不能改简体

### ISSUE THREAD

**Issue by 233lol** [rime/home#972]
ui只有繁体没有简体，虽然使用没有影响但是强迫症不能与系统统一风格

**Comment by Un1Gfn** [comment]
你需要將哪裡改變為簡體，請擷圖擧例

**Comment by 233lol** [comment]
<img width="126" alt="Snipaste_2021-12-31_11-34-11" src="https://user-images.githubusercontent.com/18070600/147801748-78b44560-ee5e-40e0-93f6-0c02c8eeac25.png">
<img width="356" alt="Snipaste_2021-12-31_11-34-35" src="https://user-images.githubusercontent.com/18070600/147801753-ae8a24b0-6457-42d6-8642-b7ef3d930639.png">

**Comment by Un1Gfn** [comment]
```
git clone --recursive https://github.com/rime/weasel.git
fgrep -nr --binary-files=text "勾選" weasel/
fgrep -nr --binary-files=text "$(iconv -f utf8 -t cp936 <<<勾選)" weasel/
fgrep -nr --binary-files=text "$(iconv -f utf8 -t big5 <<<勾選)" weasel/
# 無有效結果
```

@lotem 上圖UI中的字串來自哪裡?

**Comment by lotem** [comment]
> ```
> git clone --recursive https://github.com/rime/weasel.git
> fgrep -nr --binary-files=text "勾選" weasel/
> fgrep -nr --binary-files=text "$(iconv -f utf8 -t cp936 <<<勾選)" weasel/
> fgrep -nr --binary-files=text "$(iconv -f utf8 -t big5 <<<勾選)" weasel/
> # 無有效結果
> ```
> 
> @lotem 上圖UI中的字串來自哪裡?
> 

VC资源文件

**Comment by Un1Gfn** [comment]
[rc](https://docs.microsoft.com/en-us/cpp/windows/resource-files-visual-studio)

```
git clone --recursive https://github.com/rime/weasel.git
find weasel/ -name "*.rc" -exec iconv -f utf16le -t utf8 {} -o {}.utf8 \;
find weasel/ -name "*.rc.utf8" -exec fgrep -Hn --binary-files=text {} \
  -e 輸入法設定 \
  -e 退出算法服務 \
  -e 方案選單設定 \
  -e 請勾選所需的輸入方案 \
  -e 獲取更多輸入方案 \
  \;
```

```
weasel/WeaselTSF/WeaselTSF.rc.utf8:56:        MENUITEM "輸入法設定 (&S)",                  ID_WEASELTRAY_SETTINGS
weasel/WeaselTSF/WeaselTSF.rc.utf8:68:        MENUITEM "退出算法服務 (&Q)",                     ID_WEASELTRAY_QUIT
weasel/WeaselServer/WeaselServer.rc.utf8:132:        MENUITEM "輸入法設定 (&S)",                  ID_WEASELTRAY_SETTINGS
weasel/WeaselDeployer/WeaselDeployer.rc.utf8:33:CAPTION "【小狼毫】方案選單設定"
weasel/WeaselDeployer/WeaselDeployer.rc.utf8:36:    LTEXT           "請勾選所需的輸入方案：",IDC_STATIC,7,7,89,8
weasel/WeaselDeployer/WeaselDeployer.rc.utf8:41:    PUSHBUTTON      "獲取更多輸入方案...",IDC_GET_SCHEMATA,7,169,90,14
```

@233lol \
應該是寫死的\
嘗試改掉那些字串然用VC做一遍?

**Comment by eagleoflqj** [comment]
应该已经支持了
