### ISSUE TITLE
小狼毫在某些软件窗口中无法输入中文，显示「已禁用输入法」

### ISSUE THREAD

**Issue by isPoto** [rime/home#973]
小狼毫在一些软件窗口中无法输入中文，比如 Quicker 搜索框。只能输入英文，状态栏的 rime 图标变成叉叉样，显示「已禁用输入法」。

在其他 issue 中看到有设置为按管理员身份执行和每次遇到已禁用输入法，敲 Ctrl + Space 解除禁用。

我按此操作，即使设为管理员身份执行，仍然会遇到「已禁用输入法」问题。

Ctrl + Space 能成功解除，但随之带来一个问题，就是我次次都会遇到「已禁用输入法」，次次都要敲 Ctrl + Space 解除禁用。

能否有一劳永逸的方法可以彻底解决「已禁用输入法」这个问题。

---

能否换成多多输入法那种架构。小鹤音形基于多多输入法，体验非常好，即使在安装在 Sandboxie Plus 等沙箱隔离的软件，都能正常输入中文，也从来没有 rime 这种已禁用输入法的现象。

**Comment by Chzy2018** [comment]
同意，在Windows的edge浏览器中，查找或者搜索框中均无法正常调出输入法，系统显示已禁用输入法。

本想来反映这个问题，看到楼上已给出解决方案（用ctrl+space可调出输入法），但每次都这样依然很麻烦。

想请问何时能够解决这个问题，或者是否有更完美的方法解决

**Comment by wanglongbiao** [comment]
我在 win10 上也有这样的问题，切换到英文输入时，显示'已禁用输入法'

**Comment by cangzhouyuhe** [comment]
+1
我也是在启动之后过几小时就不断被禁用，或者输入框会闪烁。

**Comment by JourneyFlower** [comment]
+1         在Edge浏览器时，输入法会显示圆形白底黑色的叉叉，ctrl+space 可以好，但是不知道是什么时候会禁用，我试着重新使用 ctrl+space 快捷键立马就会禁用，再用快捷键就好，是不是哪里有冲突。

**Comment by iTomxy** [comment]
这个敲代码时很好用，之前 0.9 和 0.14 是 Ctrl + Space 禁用/解禁，今天升级 0.15 之后 ctrl + space 无效了，在 `%APPDATA%\Rime\build\default.yaml` 也没看到 ctrl + space，所以 0.15 禁用/解禁的组合键是什么呢？这个可以在哪里查？

**Comment by JourneyFlower** [comment]
> 这个敲代码时很好用，之前 0.9 和 0.14 是 Ctrl + Space 禁用/解禁，今天升级 0.15 之后 ctrl + space 无效了，在 `%APPDATA%\Rime\build\default.yaml` 也没看到 ctrl + space，所以 0.15 禁用/解禁的组合键是什么呢？这个可以在哪里查？

![image_338](https://github.com/rime/home/assets/40282177/fff40c5d-fb63-49ab-9bd4-eab8d52539ba)

是不是这里呀

**Comment by JourneyFlower** [comment]
> 这个敲代码时很好用，之前 0.9 和 0.14 是 Ctrl + Space 禁用/解禁，今天升级 0.15 之后 ctrl + space 无效了，在 `%APPDATA%\Rime\build\default.yaml` 也没看到 ctrl + space，所以 0.15 禁用/解禁的组合键是什么呢？这个可以在哪里查？

![image_339](https://github.com/rime/home/assets/40282177/f2cc1c9e-d94c-4a99-bd3f-fafc1393046b)
是不是这里呀

**Comment by iTomxy** [comment]
@JourneyFlower 对，我个刚在 [#803](https://github.com/rime/home/issues/803) 也看到了，在 Setting -> Language -> Keyboard -> Input language hot keys，但是这个是已经启用的：
![1686220290053](https://github.com/rime/home/assets/44149820/f2027f19-5a6f-4779-acc0-50bacab29aaa)
就今天下午升级之前还用着，升级 0.15.0（会重启一次电脑）之后就不行了，现在 ctrl + grave 呼出小狼毫菜单跟 vs code 呼出命令行冲突了，之前在 vs code 禁用输入法就不会冲突。

**Comment by JourneyFlower** [comment]
> @JourneyFlower 对，我个刚在 [#803](https://github.com/rime/home/issues/803) 也看到了，在 Setting -> Language -> Keyboard -> Input language hot keys，但是这个是已经启用的： ![1686220290053](https://user-images.githubusercontent.com/44149820/244355979-f2027f19-5a6f-4779-acc0-50bacab29aaa.jpg) 就今天下午升级之前还用着，升级 0.15.0（会重启一次电脑）之后就不行了，现在 ctrl + grave 呼出小狼毫菜单跟 vs code 呼出命令行冲突了，之前在 vs code 禁用输入法就不会冲突。

那有没有可能是vscode的问题，把vscode关闭了再看看 ctrl+space快捷键对输入法生效不

**Comment by iTomxy** [comment]
@JourneyFlower 不行，关了 vscode 在桌面试，无效，打开 notepad 打字也无效

**Comment by JourneyFlower** [comment]
> @iTomxy

像这种情况，如果是我的话，我会先退出算法服务
![image_341](https://github.com/rime/home/assets/40282177/d8f2c149-6c2b-4815-9213-70a4295ae9c7)
然后以管理员权限重新运行算法服务
![image_342](https://github.com/rime/home/assets/40282177/8c051017-e4f3-4353-b74b-7037f05c06b4)
再然后在cmd窗口执行   taskkill /f /im explorer.exe & start explorer.exe  命令重启资源管理器
![image_343](https://github.com/rime/home/assets/40282177/5196b86f-12a1-4110-b9f5-f4d44914dd34)
像上面这些步骤都试过仍然不行的话，我会回退到上一个版本的输入法软件，就没别的办法了

**Comment by JourneyFlower** [comment]
> @iTomxy 
强啊，原来是快捷键冲突。PowerToys我也在用，如果你没装 Snipaste 这款软件的话，建议你可以把powertoys取色快捷键设置为Alt+1，超方便。

**Comment by jingouwangzi** [comment]
也有这个问题，先试试修改一下powertoys的快捷键

**Comment by Cierra-Runis** [comment]
可以看看这个 <https://blog.bling.moe/post/2/#%e8%ae%be%e7%bd%ae%e5%bf%ab%e6%8d%b7%e9%94%ae>

**Comment by neederhow** [comment]
+1 ，每次打开notepad++都禁用，还以为是notepad++的问题

**Comment by fxliang** [comment]
notepad++未复现问题

**Comment by AlbertWang2018** [comment]
> +1 ，每次打开 notepad++ 都禁用，还以为是 notepad++ 的问题

一样的问题，一直没解决，每次按 ctrl+space 切换状态，电脑上目前就只发现这一个软件是这样子

**Comment by neederhow** [comment]
> +1 ，每次打开notepad++都禁用，还以为是notepad++的问题

Windows 10 家庭中文版 22h2 (19045.4291)
notepad++ v8.1.5 64bit
小狼毫 0.15.0.0

还有什么信息需要提供吗

**Comment by neederhow** [comment]
> windows 10 ltsc 64bit notepad++ 8.6.5 64bit 小狼毫nightly
> 
> 目前未复现故障，或者晚些時候我试试其他电脑看看情况

我明天到公司把双方都升级一下看看

**Comment by wordpure** [comment]
> 小狼毫在一些软件窗口中无法输入中文，比如 Quicker 搜索框。只能输入英文，状态栏的 rime 图标变成叉叉样，显示「已禁用输入法」。

Quicker 搜索框出现这个问题，大概率是因为开启了搜索设置里的关闭输入法状态，改成「不控制」就好了。

![图片](https://github.com/rime/home/assets/68013962/1857cf00-e335-4e04-aedd-281d40c702d0)

不过出现这个问题的根本原因，是 Rime 对「输入法/非输入法切换」这一系统功能的 [处理逻辑](https://rime.im/release/weasel/#0-12-0-2018-11-12) 与其他输入法不太一样，其他输入法只是切换到英文状态，Rime 是真的在应用程序里把自己禁用了……

![图片](https://github.com/rime/home/assets/68013962/659796f7-1668-497e-bbed-1647905701c0)

希望作者大大能考虑一下 [#1498](https://github.com/rime/home/issues/1498) 的建议，把「输入法/非输入法切换」的处理逻辑改成「中英文状态切换」。或者，提供一个设置项，允许用户在「输入法/非输入法切换」和「中英文状态切换」之间进行选择。

**Comment by ricolxwz** [comment]
> 可以看看这个 https://blog.bling.moe/post/2/#%e8%ae%be%e7%bd%ae%e5%bf%ab%e6%8d%b7%e9%94%ae

已修改注册表, 问题仍然存在

**Comment by shuxuejia** [comment]
> 同意，在Windows的edge浏览器中，查找或者搜索框中均无法正常调出输入法，系统显示已禁用输入法。
> 
> 本想来反映这个问题，看到楼上已给出解决方案（用ctrl+space可调出输入法），但每次都这样依然很麻烦。
> 
> 想请问何时能够解决这个问题，或者是否有更完美的方法解决

+1

**Comment by Yizhouuu** [comment]
重装系统后，未安装 powertoys，在使用 Vivaldi 时同样会遇到在输入框里禁用输入法的情况，应该跟 powertoys 关系不大

**Comment by cangzhouyuhe** [comment]
建议更新到最新版本0.16.1，更新之后我再也没碰到过被禁用的情况。

**Comment by Yizhouuu** [comment]
> 建议更新到最新版本0.16.1，更新之后我再也没碰到过被禁用的情况。

我就是 0.16.1，还是会遇到这个情况😂目前看起来还是会遇到，就是可能比之前要少，还没经过充分测试

**Comment by cloudusa** [comment]
在vscode和Firefox都频繁出现此问题，vscode和小狼毫均为最新版本，Windows 11

**Comment by 9563067** [comment]
问题居然这么严重吗😥，我刚想入rime

**Comment by Yizhouuu** [comment]
> 问题居然这么严重吗😥，我刚想入rime
@9563067 
我个人用下来，遇到这问题的软件很少，就算遇到了，ctrl + space 就好了，感觉不太用担心这个问题

**Comment by yrljroli** [comment]
> 问题居然这么严重吗😥，我刚想入rime

新版本此项可设定、且默认为与其他输入法相同逻辑。已不再是问题。参[0.16.2](https://github.com/rime/weasel/releases/tag/0.16.2)。

建议<ruby>关闭<rt>close</rt></ruby>此<ruby>问题<rt>issue</rt></ruby>。
