### ISSUE TITLE
Linux 下 weasel.custom.yaml/squirrel.custom.yaml 的對應物是什麼？

### ISSUE THREAD

**Issue by Axure** [rime/home#98]
rime.custom.yaml？似乎沒用。。

還有 defalut.custom.yaml 和這個有什麼區別？爲什麼有的設置只能在某一個中做？

**Comment by lotem** [comment]
顧名思義，`weasel.yaml` 就是小狼毫（Weasel）的專有配置。
其中配置的許多前端功能 ibus-rime 並沒有對應的實現。界面樣式由 IBus 控制。
這一系列輸入法都使用跨平臺的 librime 輸入法算法庫，其中（與平臺和用戶介面無關的）共通功能的配置寫在 `default.yaml`。
