### ISSUE TITLE
想把简繁切换快捷键设置为control+shift+f 但是无效果

### ISSUE THREAD

**Issue by helee9199** [rime/home#981]
control+shift+数子 不太好按 习惯了control+shift+f  但是设置完以后没效果

**Comment by helee9199** [comment]
- {accept: "Control+Shift+F", toggle: simplification, when: always}    # 繁简体切换
f试过大写和小写 都没效果

**Comment by Python-37** [comment]
我之前也遇到过，只能改用别的键位

**Comment by lotem** [comment]
> ```
> - {accept: "Control+Shift+F", toggle: simplification, when: always}    # 繁简体切换
> ```
> 
> 
>     
>   
> 
> f试过大写和小写 都没效果

無法重現問題。我用這行代碼測試能行。
