### ISSUE TITLE
rkrd 㗎, 口架 候選字

### ISSUE THREAD

**Issue by JW9506** [rime/home#987]
rkrd出現
![image](https://user-images.githubusercontent.com/34848995/147859719-a9effe29-d8d6-46fb-9cee-daa9c9d7e32b.png)

How can I fix this?

**Comment by LEOYoon-Tsaw** [comment]
此乃擴展A區之字也，而尔在通用，換至增廣即可

**Comment by JW9506** [comment]
> 此乃擴展A區之字也，而尔在通用，換至增廣即可

本來已經在cangjie5.schema.yaml 把增廣設為第0項, 原來還要在輸入法裡面再設置一下
