### ISSUE TITLE
gnome下ibus-rime的托盘图标不能正常显示

### ISSUE THREAD

**Issue by bruce-lcf** [rime/home#99]
archlinux gnome3，ibus-rime的托盘图标显示是一个纯色的方块。

尝试更改/usr/share/ibus-rime/icons里的图片格式，也无法生效。

不知道应该改哪里？

**Comment by mhohai** [comment]
@bruce-lcf 你用的版本是不是太低了

**Comment by bruce-lcf** [comment]
@mhohai pacman装的官方包，版本应该是最新的吧

**Comment by mhohai** [comment]
@bruce-lcf 我编译安装的1.2，图标瞬间好了，之前从升级Ubuntu14.04也是白块。。。

**Comment by bruce-lcf** [comment]
@mhohai 我也解决了，原来那玩意根本就不是图标，只是一个字符而已，可能是我系统字体不支持显示这个特殊字符吧，导致了它成了一个白块，我去ibus目录下改一下xml文件，把字符改成其他能正常显示的就好了。。

**Comment by mhohai** [comment]
@bruce-lcf 是的，Ubuntu 12.04是支持字符的。。。
这个关闭吧

**Comment by osfans** [comment]
嗯，只是字體的問題。

**Comment by mhohai** [comment]
@osfans 是系统不支持将文字作为图标的吧。

**Comment by osfans** [comment]
archlinux的gnome3版本比ubuntu12.04要新。

**Comment by mhohai** [comment]
@osfans 之前12.04是支持的，后来14.04就不支持了，所以说新版本是不支持的。
升级下rime后，问题解决了。
