### ISSUE TITLE
方案选单处的笑脸

### ISSUE THREAD

**Issue by dalton-chiou** [rime/home#990]
刚注意到，在鼠须管中用control+grave调出方案选单，会在当前位置出现一个三个标点组成的老式smiley。比如我输入“示例”，然后调出选单，如图：

![屏幕快照 2022-01-12 03 27 54](https://user-images.githubusercontent.com/34107144/149010292-1fc42fe9-f44a-4968-9650-7396449f62c1.png)

不妨碍使用，只是好奇，这是本来的设计，还是我哪里弄的不对？
我的标点用的是默认的；没有启用key_binder。

**Comment by lotem** [comment]
没有设置`switcher/caption`，所以随意显示一个字符串以免输入为空与部分软件不兼容。这个选项需要设置一个YAML字符串，不能用字符串列表。

**Comment by dalton-chiou** [comment]
我把[方案选单]加上引号， 就正常显示了。谢谢。
不过程序自带的default.yaml就是没引号的。

**Comment by lotem** [comment]
`[ ]`在YAML里面用来定义列表。

**Comment by dalton-chiou** [comment]
是我糊涂了。乱改符号所至。
