### ISSUE TITLE
Bug？電腦重新啟動後打唔了粵拼

### ISSUE THREAD

**Issue by weeliyen** [rime/home#995]
我嘅OS係macOS Catalina，本身係冇粵拼嘅。
之前我安裝 https://rime.im/ 同埋 https://github.com/rime/rime-cantonese/releases 後可以打粵拼。
不過電腦重新啟動後就打唔了喇。試過重新安裝https://github.com/rime/rime-cantonese/releases又可以。
不過電腦重新啟動後又唔可以喇。點解？
而家我暫時在用Chrome上嘅插件。。

**Comment by lotem** [comment]
無法實地診斷。不清楚具體情況。
