### ISSUE TITLE
使用xlit後，不能造詞

### ISSUE THREAD

**Issue by trivisionary** [rime/home#999]
系統：Win10 21H1
小狼毫版本：0.14.3

我用的是colemak鍵盤，使用拼寫運算的xlit功能把按鍵映射過（如附圖），讓倉頡輸入法的按鍵保持在原來的位置上。

輸入法日常使用上都正常，只有造詞功能失效。

有趣的是，只要我把schema.yaml中改按鍵的部份刪掉，造詞功能又回復正常。

![Q-1](https://user-images.githubusercontent.com/57785571/149617799-d22e1842-5a81-40c4-9dd8-f848e0d81662.jpg)

**Comment by lotem** [comment]
不能這樣用。
拼寫運算在編譯時執行，算出固定的輸入碼與字典碼的映射表。後加的編碼當時並不存在。

倉頡字母與拉丁字母對應，不與按鍵的位置對應。你的改動重新定義了倉頡字母對應的拉丁字母，修改碼表是恰當的。

**Comment by trivisionary** [comment]
我明白了，感謝解惑！

後來我使用了下面連結內的碼表轉換腳表，修改了一下讓它能產出對應Colemak鍵盤佈局的碼表，之後問題就解決了。
[https://github.com/Verf/wubi-norman](url)
